Repository patternfly/patternfly-react, pull requests merged in 2018-11, with the labels that each got.

#848 refactor(Radio/Checkbox): replace checked with isChecked in API
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/ControlledCheckbox.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.test.js
  packages/patternfly-4/react-core/src/components/Radio/examples/ControlledRadio.js
Labels: PF4, chore :house:

#876 feat(condensed horizontal nav): updates condensed nav to match Core horizontal & vertical nav
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Avatar/__snapshots__/Avatar.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/NavList.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavList.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/demos/PageLayout/PageLayoutDemo.docs.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNavCondensed.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutVerticalNavCondensed.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.test.js
  packages/patternfly-4/react-core/src/layouts/Page/__mocks__/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:

#880 fix(typescript): Export LoginBox and make PageSection props optional
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageSection.d.ts
Labels: PF4, bug :bug:

#883 fix(overlay): add anchor tag to filter overlay
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNavCondensed.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutVerticalNavCondensed.js
Labels: PF4

#878 fix(modal transition): Reduce translate3d (right offset) positioning for right-side-modal-pf to 25%
  packages/patternfly-3/patternfly-react/less/modeless-overlay.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss
Labels: bug :bug:

#870 fix(BadgedResource): Use css over inlined style for bg color
  packages/patternfly-3/patternfly-react-extensions/less/badged-resource.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_badged-resource.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/ResourceTypes.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/__snapshots__/BadgedResource.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/index.js
Labels: bug :bug:, extension

#863 feat(LoginPage): introduce the login page component
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.docs.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.js
  packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBox.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginBox/examples/SimpleLoginBox.js
  packages/patternfly-4/react-core/src/components/LoginBox/index.d.ts
  packages/patternfly-4/react-core/src/components/LoginBox/index.js
  packages/patternfly-4/react-core/src/components/LoginPage/Login.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/Login.js
  packages/patternfly-4/react-core/src/components/LoginPage/Login.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBox.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBox.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBox.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxBody.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxBody.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxBody.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxFooter.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxFooter.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxFooter.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxHeader.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginBoxHeader.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginFooter.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginFooter.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginHeader.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginHeader.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginHeaderBrand.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginHeaderBrand.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.docs.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/Login.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginBox.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginBoxBody.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginBoxFooter.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
  packages/patternfly-4/react-core/src/components/LoginPage/examples/pf_logo_color.svg
  packages/patternfly-4/react-core/src/components/LoginPage/index.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-core/src/layouts/Login/Login.docs.js
  packages/patternfly-4/react-core/src/layouts/Login/__snapshots__/Login.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Login/examples/SimpleLoginLayout.js
  packages/patternfly-4/react-core/src/layouts/Login/examples/common/getContainerProps.js
  packages/patternfly-4/react-core/src/layouts/Login/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Login/index.js
  packages/patternfly-4/react-core/src/layouts/index.js
Labels: Hacktoberfest :jack_o_lantern:, PF4, css approved, enhancement :rocket:, ux approved

#877 fix(FilterSidePanel/VerticalTabs): Adjust top and bottom spacing of f…
  packages/patternfly-3/patternfly-react-extensions/less/filter-side-panel.less
  packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_filter-side-panel.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanel.stories.js
Labels: bug :bug:, extension

#893 feat(DropdownToggle - noCaret option): Adds the noCaret option
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
Labels: PF4

#900 fix(dropdown props): fix typescript typings
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
Labels: PF4, bug :bug:

#882 update contributing guidelines
  CONTRIBUTING.md
Labels: documentation :memo:

#902 fix(charts): address typescript issues
  packages/patternfly-4/react-charts/src/components/AreaChart/examples/common/getContainerProps.js
  packages/patternfly-4/react-charts/src/components/AreaChart/examples/common/getContainerPropsDark.js
  packages/patternfly-4/react-charts/src/components/BarChart/examples/common/getContainerProps.js
  packages/patternfly-4/react-charts/src/components/Chart/Chart.d.ts
  packages/patternfly-4/react-charts/src/components/ChartArea/ChartArea.d.ts
  packages/patternfly-4/react-charts/src/components/ChartBar/ChartBar.d.ts
  packages/patternfly-4/react-charts/src/components/ChartContainer/ChartContainer.d.ts
  packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.d.ts
  packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.d.ts
  packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.d.ts
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.d.ts
  packages/patternfly-4/react-charts/src/components/ChartLine/ChartLine.d.ts
  packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.d.ts
  packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.d.ts
  packages/patternfly-4/react-charts/src/components/ChartTooltip/ChartTooltip.d.ts
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.d.ts
  packages/patternfly-4/react-charts/src/components/LineChart/examples/common/getContainerProps.js
  packages/patternfly-4/react-charts/src/components/StackChart/examples/common/getContainerProps.js
Labels: PF4

#904 feat(a11y): add accessibility checks for pf4
  packages/patternfly-4/react-docs/src/pages/index.js
  yarn.lock
Labels: PF4, accessibility

#891 feat(styled-system): adds styled system to pf4 as its own package
  packages/patternfly-4/react-docs/build/copyDocs.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
  packages/patternfly-4/react-docs/src/components/section/section.js
  packages/patternfly-4/react-docs/src/components/section/section.styles.js
  packages/patternfly-4/react-styled-system/.babelrc
  packages/patternfly-4/react-styled-system/.npmignore
  packages/patternfly-4/react-styled-system/README.md
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styled-system/scripts/copyTS.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledBox.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledBox.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledFlex.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledFlex.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledSystem.docs.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledSystem.test.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledText.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledText.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/__snapshots__/StyledSystem.test.js.snap
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/BorderStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/BoxShadowStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/ColorStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/FlexStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/FontSizeStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/OverrideTheme.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/PositionStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/ResponsiveStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/SpaceStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/TypographyStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/examples/WidthStyles.js
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/index.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/index.js
  packages/patternfly-4/react-styled-system/src/components/index.d.ts
  packages/patternfly-4/react-styled-system/src/components/index.js
  packages/patternfly-4/react-styled-system/src/index.d.ts
  packages/patternfly-4/react-styled-system/src/index.js
  yarn.lock
Labels: PF4

#607 feat(DesktopViewer): introduce DesktopViewer component
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_expand-collapse.scss
  packages/patternfly-3/react-console/README.md
  packages/patternfly-3/react-console/less/console.less
  packages/patternfly-3/react-console/less/desktop-viewer.less
  packages/patternfly-3/react-console/less/variables.less
  packages/patternfly-3/react-console/package.json
  packages/patternfly-3/react-console/sass/_desktop-viewer.scss
  packages/patternfly-3/react-console/sass/_variables.scss
  packages/patternfly-3/react-console/sass/_vnc-console.scss
  packages/patternfly-3/react-console/sass/console.scss
  packages/patternfly-3/react-console/src/DesktopViewer/ConnectWithRemoteViewer.js
  packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.js
  packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.stories.js
  packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.test.js
  packages/patternfly-3/react-console/src/DesktopViewer/ManualConnection.js
  packages/patternfly-3/react-console/src/DesktopViewer/MoreInformationDefaultContent.js
  packages/patternfly-3/react-console/src/DesktopViewer/MoreInformationInstallVariant.js
  packages/patternfly-3/react-console/src/DesktopViewer/__snapshots__/DesktopViewer.test.js.snap
  packages/patternfly-3/react-console/src/DesktopViewer/consoleDetailPropType.js
  packages/patternfly-3/react-console/src/DesktopViewer/index.js
  packages/patternfly-3/react-console/src/DesktopViewer/vvFileGenerator.js
  packages/patternfly-3/react-console/src/common/constants.js
  packages/patternfly-3/react-console/src/index.js
  yarn.lock
Labels: css approved, enhancement :rocket:, review, ux approved

#910 fix(CatalogTileView): Fix to prevent category size updates after unmount
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
Labels: bug :bug:, extension

#874 feat(LoginForm): Added the PF4 LoginForm Component
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.docs.js
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
  packages/patternfly-4/react-core/src/components/LoginPage/index.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/index.js
Labels: PF4, css approved, ux approved

#895 fix(PF4 AboutModal and Modal): added a class to the body when the Mod…
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.js
Labels: PF4, bug :bug:

#911 fix(LoginPage): small fixes.
  packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardInput.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardRememberMe.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSettings.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSignUp.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginLanguagePicker.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginFooterLinks.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageHeader.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageWithTranslation.js
Labels: bug :bug:

#918 fix(styled-system): check if global variables are defined before use
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.js
Labels: PF4

#907 Updating reference link to PatternFly Storybook
  packages/patternfly-3/patternfly-react/README.md
Labels: documentation :memo:

#899 feat(pf4-table): Introduce new package @patternfly/react-table for table implementation
  packages/patternfly-4/react-table/.babelrc
  packages/patternfly-4/react-table/.npmignore
  packages/patternfly-4/react-table/README.md
  packages/patternfly-4/react-table/build/copyStyles.js
  packages/patternfly-4/react-table/build/snapshot-serializer.js
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-table/scripts/copyTS.js
  packages/patternfly-4/react-table/src/index.js
  yarn.lock
Labels: PF4

#916 fix(subcomponents): Make all subcomponents available from base component
  packages/patternfly-3/patternfly-react/src/components/Button/Button.js
  packages/patternfly-3/patternfly-react/src/components/Cards/Card.js
  packages/patternfly-3/patternfly-react/src/components/Chart/Chart.js
  packages/patternfly-3/patternfly-react/src/components/Dropdown/Dropdown.js
  packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNav.js
  packages/patternfly-3/patternfly-react/src/components/InlineEdit/InlineEdit.js
  packages/patternfly-3/patternfly-react/src/components/Label/DisposableLabel.js
  packages/patternfly-3/patternfly-react/src/components/Label/Label.js
  packages/patternfly-3/patternfly-react/src/components/Label/index.js
  packages/patternfly-3/patternfly-react/src/components/ListGroup/ListGroup.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.js
  packages/patternfly-3/patternfly-react/src/components/Nav/Nav.js
  packages/patternfly-3/patternfly-react/src/components/Pagination/Pagination.js
  packages/patternfly-3/patternfly-react/src/components/SessionTimeout/SessionTimeout.js
  packages/patternfly-3/patternfly-react/src/components/Tabs/Tabs.js
  packages/patternfly-3/patternfly-react/src/components/ToastNotification/TimedToastNotification.js
  packages/patternfly-3/patternfly-react/src/components/ToastNotification/ToastNotification.js
  packages/patternfly-3/patternfly-react/src/components/TreeView/TreeView.js
  packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.js
Labels: bug :bug:

#761 feat(component): introduce the pf4 switch component
  packages/patternfly-4/react-core/src/components/Switch/Switch.d.ts
  packages/patternfly-4/react-core/src/components/Switch/Switch.docs.js
  packages/patternfly-4/react-core/src/components/Switch/Switch.js
  packages/patternfly-4/react-core/src/components/Switch/Switch.test.js
  packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap
  packages/patternfly-4/react-core/src/components/Switch/examples/DisabledSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/NoLabelSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/SimpleSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/UncontrolledSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/index.d.ts
  packages/patternfly-4/react-core/src/components/Switch/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
Labels: PF4, css review, enhancement :rocket:, ux review

#922 feat(HintBlock): Add the HintBlock component
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react/package.json
  packages/patternfly-3/patternfly-react/src/components/HintBlock/HintBlock.js
  packages/patternfly-3/patternfly-react/src/components/HintBlock/HintBlock.stories.js
  packages/patternfly-3/patternfly-react/src/components/HintBlock/HintBlock.test.js
  packages/patternfly-3/patternfly-react/src/components/HintBlock/__snapshots__/HintBlock.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/HintBlock/index.js
  packages/patternfly-3/patternfly-react/src/index.js
  packages/patternfly-3/react-console/package.json
Labels: enhancement :rocket:

#920 chore(pf-core): update core for PF4
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, chore :house:

#938 Fix sub-component references in react-console DesktopViewer
  packages/patternfly-3/react-console/src/DesktopViewer/ManualConnection.js
Labels: bug :bug:

#936 fix(LoginPage): Improve inputs validation
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
Labels: bug :bug:

#935 Fix Dropdown typescript issue
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
Labels: PF4, bug :bug:

#909 refactor(SerialConsole,VncConsole): Unify use of Toolbar
  packages/patternfly-3/react-console/less/console-selector.less
  packages/patternfly-3/react-console/less/serial-console.less
  packages/patternfly-3/react-console/less/vnc-console.less
  packages/patternfly-3/react-console/sass/_console-selector.scss
  packages/patternfly-3/react-console/sass/_serial-console.scss
  packages/patternfly-3/react-console/sass/_vnc-console.scss
  packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
  packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.js
  packages/patternfly-3/react-console/src/SerialConsole/__snapshots__/SerialConsole.test.js.snap
  packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
  packages/patternfly-3/react-console/src/VncConsole/__snapshots__/VncConsole.test.js.snap
Labels: chore :house:

#944 fix(LoginPage): improve submit button UX
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSubmitButton.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
Labels: bug :bug:

#941 feat(PF4 Page): Allow passing of custom ref for condensed header
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/TextArea/__snapshots__/TextArea.test.js.snap
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.docs.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.test.js
  packages/patternfly-4/react-core/src/components/TextInput/__snapshots__/TextInput.test.js.snap
  packages/patternfly-4/react-core/src/components/TextInput/examples/AltTextInput.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4

#948 fix(less): convert less variables from scss in treeview - #943
  packages/patternfly-3/patternfly-react/less/treeview.less
Labels: bug :bug:

#942 fix(LoginPage): improve form's error style and behavior
  packages/patternfly-3/patternfly-react/less/login-page.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginFormError.js
Labels: bug :bug:

#807 Rdp console
  packages/patternfly-3/react-console/less/desktop-viewer.less
  packages/patternfly-3/react-console/sass/_desktop-viewer.scss
  packages/patternfly-3/react-console/src/DesktopViewer/ConnectWithRemoteViewer.js
  packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.js
  packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.stories.js
  packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.test.js
  packages/patternfly-3/react-console/src/DesktopViewer/ManualConnection.js
  packages/patternfly-3/react-console/src/DesktopViewer/MoreInformationDefaultRDPContent.js
  packages/patternfly-3/react-console/src/DesktopViewer/__snapshots__/DesktopViewer.test.js.snap
  packages/patternfly-3/react-console/src/DesktopViewer/consoleDescriptorGenerator.js
  packages/patternfly-3/react-console/src/DesktopViewer/vvFileGenerator.js
  packages/patternfly-3/react-console/src/common/constants.js
  packages/patternfly-3/react-console/src/common/helpers.js
Labels: enhancement :rocket:

#906 introduce preselectedType for AccessConsoles component
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.stories.js
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.test.js
  packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
Labels: bug :bug:, ux approved

#754 feat(Popover): Add PF4 Popover
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts
  packages/patternfly-4/react-core/src/components/Popover/Popover.docs.txt
  packages/patternfly-4/react-core/src/components/Popover/Popover.js
  packages/patternfly-4/react-core/src/components/Popover/Popover.test.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverArrow.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverArrow.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverBody.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverBody.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverContent.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverContent.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverDialog.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverDialog.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.js
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.js.snap
  packages/patternfly-4/react-core/src/components/Popover/examples/HeadlessPopover.txt
  packages/patternfly-4/react-core/src/components/Popover/examples/SimplePopover.txt
  packages/patternfly-4/react-core/src/components/Popover/index.d.ts
  packages/patternfly-4/react-core/src/components/Popover/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
Labels: PF4, css approved, enhancement :rocket:, ux review

#931 chore(generator): Update generator to match new docs structure
  scripts/generators/patternfly-4-component/templates/component/examples/Simple{{componentName}}.js
  scripts/generators/patternfly-4-component/templates/component/{{componentName}}.docs.js
Labels: PF4, chore :house:

#951 docs(Contribution Guide): update Contribution Guide demo hosting step
  CONTRIBUTING.md
  packages/patternfly-3/patternfly-react/CONTRIBUTING.md
  packages/patternfly-4/react-core/CONTRIBUTING.md
Labels: documentation :memo:

#949 documentation(PF4 - alt form example): remove the alt form example
  packages/patternfly-4/react-core/src/components/Form/Form.docs.js
  packages/patternfly-4/react-core/src/components/Form/examples/AlternativeForm.js
Labels: PF4

#952 fix(LoginPage): Add submit error callback handling
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.stories.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
Labels: bug :bug:

#872 feat(breadcrumb): adds PF4 breadcrumb, breadcrumbItem, breadcrumbTitle components
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.docs.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.test.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.test.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.test.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbHeading.test.js.snap
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbItem.test.js.snap
  packages/patternfly-4/react-core/src/components/Breadcrumb/examples/HeadingBreadcrumbs.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/examples/SimpleBreadcrumbs.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/examples/WithoutLinkBreadcrumbs.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/index.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
Labels: PF4, api review, css approved, ux approved

#964 fix(DesktopViewer): Fix reference to constants in dist
  packages/patternfly-3/react-console/src/DesktopViewer/ConnectWithRemoteViewer.js
Labels: bug :bug:

#828 fix(Slider): Call onSlide on slide event
  packages/patternfly-3/patternfly-react/src/components/Slider/Slider.js
  packages/patternfly-3/patternfly-react/src/components/Slider/Slider.stories.js
  packages/patternfly-3/patternfly-react/src/components/Slider/__snapshots__/Slider.test.js.snap
Labels: bug :bug:

#971 Icon alignment
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.styles.js
  packages/react-icons/src/__snapshots__/createIcon.test.js.snap
  packages/react-icons/src/createIcon.js
Labels: PF4, bug :bug:

#958 fix(CatalogTile): Fix to correctly position fading out of description text
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
Labels: bug :bug:, extension

#972 chore(core): update core to .83
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/NavList.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavList.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/demos/PageLayout/PageLayoutDemo.docs.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNavCondensed.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutVerticalNavCondensed.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.test.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.test.js
  packages/patternfly-4/react-core/src/layouts/Page/__mocks__/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, chore :house:

#950 feat(Progress): use max parameter to scale value of progress bar
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
Labels: PF4, enhancement :rocket:

#954 fix(Dropdown): Apply `pf-m-plain` modifier to dropdown toggle element instead of wrapper
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/KebabToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
Labels: PF4, bug :bug:

#977 fix(CatalogTileView): Support tiles without categories.
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewNoCategoriesExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
Labels: bug :bug:, extension

#985 fix(extensions): Create local helpers to lessen dependencies
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react-extensions/src/common/helpers.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategoryItem.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridColumnHeader.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
Labels: bug :bug:

#980 fix(LoadingState): Add LoadingState component to exports (#881)
  packages/patternfly-3/patternfly-react/src/index.js
Labels: bug :bug:

#983 fix(packageJson) : Updated package.json to fix prod issue when import…
  packages/patternfly-4/react-core/package.json
Labels: PF4, bug :bug:

#988 fix(LoginPage): typos
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.js
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap
Labels: PF4, bug :bug:
