Repository patternfly/patternfly-react, pull requests merged in 2018-09, with the labels that each got.

#593 fix(stylesheet): restore css export
  packages/patternfly-4/react-styles/src/index.d.ts
Labels: review

#597 fix(docs): fix broken link in readme
  README.md
Labels: documentation, review

#599 Force react-core release for missing modal typings
  packages/patternfly-4/react-core/src/components/Modal/Backdrop.d.ts
  packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
Labels: review

#592 feat(vertical tabs): add vertical-tabs component
  packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
  packages/patternfly-3/patternfly-react-extensions/less/variables.less
  packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabsTab.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/_mocks_/mockVerticalTabsExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/index.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: review, ux approved

#595 Fix #431 : Add href paths to VerticalNav menuItems
  packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNav.js
  packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
  packages/patternfly-3/patternfly-react/src/components/VerticalNav/__mocks__/mockNavItems.js
Labels: review

#594 feat(table-grid): add Table Grid component
  packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
  packages/patternfly-3/patternfly-react-extensions/less/table-grid.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_table-grid.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridBody.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridColumnHeader.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/__snapshots__/TableGrid.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockItems.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockTableGridExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/index.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: review, ux approved

#608 fix(exports): add exports for ApplicationLauncher, InlineEdit, SessionTimeout
  packages/patternfly-3/patternfly-react/src/index.js
Labels: review

#590 feat(patternfly-4/react-core/): added Select Component
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Select/Select.docs.js
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/Select.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOption.js
  packages/patternfly-4/react-core/src/components/Select/SelectOptionGroup.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOptionGroup.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/examples/SelectInput.js
  packages/patternfly-4/react-core/src/components/Select/examples/SelectInputDisabled.js
  packages/patternfly-4/react-core/src/components/Select/examples/SelectInputGrouped.js
  packages/patternfly-4/react-core/src/components/Select/index.d.ts
  packages/patternfly-4/react-core/src/components/Select/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
Labels: PF4, review

#612 docs(Dropdown): fix component imports in Dropdown examples
  packages/patternfly-4/react-core/src/components/Dropdown/examples/DirectionUpDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/KebabDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/PositionRightDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/SimpleDropdown.js
Labels: review

#611 feat(vertical-tabs): add sub-tab support, with restricted mode
  package.json
  packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabsTab.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/_mocks_/mockVerticalTabsExample.js
Labels: css approved, review, ux approved

#614 feat(catalog-tile): add CatalogTile component
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
  packages/patternfly-3/patternfly-react-extensions/less/variables.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTileBadge.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__images__/nginx.png
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/index.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: css approved, review, ux approved

#615 feat(pf4-avatar): introduce avatar component
  package.json
  packages/patternfly-4/react-core/build/snapshot-serializer.js
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.d.ts
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.docs.js
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.js
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.test.js
  packages/patternfly-4/react-core/src/components/Avatar/__snapshots__/Avatar.test.js.snap
  packages/patternfly-4/react-core/src/components/Avatar/examples/SimpleAvatar.js
  packages/patternfly-4/react-core/src/components/Avatar/index.js
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardBody.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxBody.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.js
  packages/patternfly-4/react-core/src/components/TextArea/__snapshots__/TextArea.test.js.snap
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.js
  packages/patternfly-4/react-core/src/components/TextInput/__snapshots__/TextInput.test.js.snap
  packages/patternfly-4/react-core/src/components/Title/__snapshots__/Title.test.js.snap
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-docs/src/assets/img_avatar.png
  packages/patternfly-4/react-styles/src/build/jest/snapshot-serializer/cssUtils.js
  packages/patternfly-4/react-styles/src/build/jest/snapshot-serializer/serializer.js
  packages/patternfly-4/react-tokens/package.json
  yarn.lock
Labels: PF4, review

#619 chore(variable update): updated variable for react-docs navigation st…
  packages/patternfly-4/react-docs/src/components/navigation/navigation.styles.js
Labels: PF4, review

#620 fix(catalog-tile): allow icons to be used in the tile image area
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTileBadge.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap
Labels: review, ux approved

#617 feat(catalog-tile-view): add CatalogTileView component
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/less/variables.less
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/index.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: css approved, review, ux approved

#629 chore(tests): fix test warnings in vertical tabs component
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
Labels: review

#624 feat(modeless-overlay): add the ModelessOverlay component
  packages/patternfly-3/patternfly-react/less/modeless-overlay.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-3/patternfly-react/src/components/Modal/Modal.stories.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.test.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModlessOverlay.stories.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__mocks__/mockModelessManager.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__snapshots__/ModelessOverlay.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/index.js
  packages/patternfly-3/patternfly-react/src/index.js
Labels: review, ux approved

#631 fix(card): Fix card background color (#630)
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.js.snap
Labels: bug, review

#633 feat(pf4-brand): introduce brand component
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.js
  packages/patternfly-4/react-core/src/components/Avatar/examples/SimpleAvatar.js
  packages/patternfly-4/react-core/src/components/Avatar/examples/img_avatar.png
  packages/patternfly-4/react-core/src/components/Brand/Brand.d.ts
  packages/patternfly-4/react-core/src/components/Brand/Brand.docs.js
  packages/patternfly-4/react-core/src/components/Brand/Brand.js
  packages/patternfly-4/react-core/src/components/Brand/Brand.test.js
  packages/patternfly-4/react-core/src/components/Brand/__snapshots__/Brand.test.js.snap
  packages/patternfly-4/react-core/src/components/Brand/examples/SimpleBrand.js
  packages/patternfly-4/react-core/src/components/Brand/examples/pf_logo.svg
  packages/patternfly-4/react-core/src/components/Brand/index.js
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-tokens/package.json
  yarn.lock
Labels: PF4, review

#634 fix(@patternfly/react-docs): use emotion to load in global pf core st…
  packages/patternfly-4/react-docs/.gitignore
  packages/patternfly-4/react-docs/.npmignore
  packages/patternfly-4/react-docs/build/copyDocs.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/gatsby-ssr.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/layouts/example.js
  packages/patternfly-4/react-docs/src/layouts/index.js
  yarn.lock
Labels: PF4, review

#616 Docs update
  CONTRIBUTING.md
  GETTING-STARTED.md
  README.md
  packages/README.md
  packages/patternfly-3/README.md
  packages/patternfly-3/patternfly-react/CONTRIBUTING.md
  packages/patternfly-3/patternfly-react/README.md
  packages/patternfly-4/README.md
  packages/patternfly-4/react-core/CONTRIBUTING.md
  packages/patternfly-4/react-core/README.md
  packages/patternfly-4/react-docs/README.md
Labels: review

#640 fix(catalog tile): remove the default tooltip for description text
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap
Labels: review

#636 feat(catalog item header): add CatalogItemHeader component
  packages/patternfly-3/patternfly-react-extensions/less/catalog-item.less
  packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-item.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/__images__/nginx.png
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/__snapshots__/CatalogItemHeader.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/index.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: extension, review, ux approved

#643 chore(update jest): update jest and jest-cli to jest 23
  package.json
  packages/patternfly-3/patternfly-react/src/components/Alert/Alert.test.js
  packages/patternfly-3/patternfly-react/src/components/Alert/__snapshots__/helpers.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNav.test.js
  packages/patternfly-3/patternfly-react/src/components/Masthead/__snapshots__/Masthead.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNav.test.js
  packages/patternfly-3/patternfly-react/src/components/Wizard/__snapshots__/Wizard.test.js.snap
  packages/patternfly-3/react-console/src/SerialConsole/__snapshots__/SerialConsole.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  yarn.lock
Labels: review

#641 chore(pf4): force version of @patternfly/patternfly-next across packages
  packages/patternfly-4/package.json
  packages/patternfly-4/verifyCoreVersions.js
Labels: PF4, review

#647 feat(Properties Side Panel): adds the PropertiesSidePanel component
  packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
  packages/patternfly-3/patternfly-react-extensions/less/properties-side-panel.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_properties-side-panel.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertiesSIdePanel.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertiesSidePanel.js
  packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertyItem.js
  packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertySidePanel.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/__snapshots__/PropertiesSIdePanel.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/index.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: enhancement, extension, review, ux review

#650 feat(modal): add class to allow Modal dialog to be placed on the right side
  packages/patternfly-3/patternfly-react/less/modeless-overlay.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss
  packages/patternfly-3/patternfly-react/src/components/Modal/Modal.stories.js
  packages/patternfly-3/patternfly-react/src/components/Modal/__mocks__/mockModalManager.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.js
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__snapshots__/ModelessOverlay.test.js.snap
Labels: review

#649 fix(@patternfly/react-docs): fixes the path to the font files
  packages/patternfly-4/react-docs/build/copyDocs.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/layouts/example.js
  packages/patternfly-4/react-docs/src/layouts/index.js
Labels: PF4, review

#657 feat(table-grid): add Row and Cell selection support to TableGrid
  packages/patternfly-3/patternfly-react-extensions/less/table-grid.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_table-grid.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridCol.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/__snapshots__/TableGrid.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockTableGridExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/index.js
Labels: enhancement, extension, review, ux approved

#653 fix(surge): add surge pr support to travis
  .public/index.html
  .travis.yml
  .travis/deploy_pr.sh
  package.json
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/package.json
Labels: review

#662 docs(PF4 badge): update doc to show read/unread styles appropriately
  packages/patternfly-4/react-core/src/components/Badge/examples/ReadBadge.js
  packages/patternfly-4/react-core/src/components/Badge/examples/UnreadBadge.js
Labels: PF4, review

#666 fix(examples and docs): adding react-live…
  packages/patternfly-4/react-core/src/components/Button/examples/LinkButton.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/DirectionUpDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/KebabDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/PositionRightDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/SimpleDropdown.js
  packages/patternfly-4/react-docs/.env.development
  packages/patternfly-4/react-docs/.env.production
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-docs/src/layouts/index.js
  yarn.lock
Labels: review

#651 chore(update storybook): update storybook packages to 3.4.11
  packages/patternfly-3/package.json
  storybook/webpack.config.js
  yarn.lock
Labels: review

#664 fix(VerticalTabs): set tab text to wrap when necessary
  packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabsTab.js
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/_mocks_/mockVerticalTabsExample.js
Labels: review

#659 feat(TableGrid): add Checkbox select support to TableGrid
  packages/patternfly-3/patternfly-react-extensions/less/table-grid.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_table-grid.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/__snapshots__/TableGrid.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockTableGridExample.js
Labels: css approved, enhancement, extension, review, ux approved

#674 fix(commit): add private config to hidden packages
  packages/patternfly-3/package.json
  packages/patternfly-4/package.json
Labels: review

#675 fix(README): add README text for the patternfly-3 package
  packages/patternfly-3/README.md
Labels: review

#679 fix(README): update test command
  packages/patternfly-3/patternfly-react/README.md
Labels: review
