Repository patternfly/patternfly-react, pull requests merged in 2018-02, with the labels that each got.

#225 fix(pagination): Allow drop down for page size selector
  src/components/Pagination/Paginate.test.js
  src/components/Pagination/Pagination.stories.js
  src/components/Pagination/PaginationRow.js
  src/components/Pagination/__mocks__/mockPaginationRow.js
  src/components/Pagination/__snapshots__/Paginate.test.js.snap
Labels: review

#228 Issue #159 fix(constants file): Rename all constants file to {Component_Name}Con…
  CONTRIBUTING.md
  src/components/Alert/Alert.js
  src/components/Alert/Alert.stories.js
  src/components/Alert/Alert.test.js
  src/components/Alert/AlertConstants.js
  src/components/Alert/helpers.js
  src/components/Alert/helpers.test.js
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Button/ButtonConstants.js
  src/components/Button/DropdownButton.js
  src/components/Button/SplitButton.js
  src/components/Chart/AreaChart.js
  src/components/Chart/BarChart.js
  src/components/Chart/ChartConstants.js
  src/components/Chart/DonutChart.js
  src/components/Chart/GroupedBarChart.js
  src/components/Chart/LineChart.js
  src/components/Chart/PieChart.js
  src/components/Chart/SingleAreaChart.js
  src/components/Chart/SingleLineChart.js
  src/components/Chart/SparklineChart.js
  src/components/Chart/StackedBarChart.js
  src/components/Pagination/PaginationConstants.js
  src/components/Pagination/PaginationRow.js
  src/components/Pagination/Paginator.js
  src/components/Pagination/index.js
  src/components/Table/TableCell.js
  src/components/Table/TableConstants.js
  src/components/Table/TableHeading.js
  src/components/Table/index.js
  src/components/VerticalNav/VerticalNav.js
  src/components/VerticalNav/VerticalNavConstants.js
  src/components/VerticalNav/VerticalNavItem.js
  src/components/VerticalNav/VerticalNavItemHelper.js
  src/components/VerticalNav/VerticalNavMasthead.js
  src/components/VerticalNav/VerticalNavSecondaryItem.js
  src/components/VerticalNav/VerticalNavTertiaryItem.js
Labels: review

#195 docs(CONTRIBUTING.md): Clarify contribution process
  CONTRIBUTING.md
Labels: review

#231 chore(ToastNotification) update storybook, increase test coverage
  src/components/ToastNotification/ToastNotification.stories.js
  src/components/ToastNotification/ToastNotification.test.js
  src/components/ToastNotification/__snapshots__/ToastNotification.test.js.snap
Labels: chore, review

#238 chore(dev): adds openurl support to dev start
  package-lock.json
  package.json
  storybook/openBrowser.js
Labels: chore, review

#199 feat(infoTip): Add Infotip component
  src/common/helpers.js
  src/components/InfoTip/InfoTip.js
  src/components/InfoTip/InfoTip.stories.js
  src/components/InfoTip/InfoTip.test.js
  src/components/InfoTip/InfoTipMenu.js
  src/components/InfoTip/InfoTipMenuFooter.js
  src/components/InfoTip/InfoTipMenuItemIcon.js
  src/components/InfoTip/InfoTipToggle.js
  src/components/InfoTip/__snapshots__/InfoTip.test.js.snap
  src/components/InfoTip/index.js
Labels: css approved, review, ux approved

#246 fix(infotip): adds some eslint fixes for infotip
  src/components/InfoTip/InfoTip.js
  src/components/InfoTip/InfoTip.stories.js
  src/components/InfoTip/InfoTip.test.js
  src/components/InfoTip/InfoTipMenu.js
  src/components/InfoTip/InfoTipMenuFooter.js
  src/components/InfoTip/InfoTipMenuItemIcon.js
  src/components/InfoTip/InfoTipToggle.js
  src/components/InfoTip/__snapshots__/InfoTip.test.js.snap
Labels: review

#245 fix(Wizard): Allow numbers as step identifiers
  src/components/Wizard/WizardSidebarGroup.js
  src/components/Wizard/WizardSidebarGroupItem.js
  src/components/Wizard/WizardStep.js
  src/components/Wizard/WizardSubStep.js
  src/components/Wizard/__mocks__/mockWizardItems.js
  src/components/Wizard/__snapshots__/Wizard.test.js.snap
Labels: review

#248 fix(wizard): fix wizard contents default props
  src/components/Wizard/WizardContents.js
Labels: review

#242 fix(ToastNotificationList): ensures timeout on dismissal and not onhover
  src/components/ToastNotification/ToastNotification.stories.js
  src/components/ToastNotification/ToastNotification.test.js
  src/components/ToastNotification/ToastNotificationList.js
  src/components/ToastNotification/__snapshots__/ToastNotification.test.js.snap
Labels: bug, review

#249 fix(Button): Allow bsStyle success
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Button/ButtonConstants.js
  src/components/Button/__snapshots__/DropdownButton.test.js.snap
  src/components/Button/__snapshots__/SplitButton.test.js.snap
Labels: review

#251 feat(VerticalNavItem): Add support for custom className on a nav item
  src/components/VerticalNav/VerticalNav.test.js
  src/components/VerticalNav/VerticalNavConstants.js
  src/components/VerticalNav/VerticalNavItemHelper.js
  src/components/VerticalNav/__mocks__/basicExample.js
  src/components/VerticalNav/__snapshots__/VerticalNav.test.js.snap
Labels: review

#255 fix(index.js): Fix broken export of controlled helper
  src/index.js
Labels: review

#211 feat: Utilization bar
  less/patternfly-react.less
  less/utilization-bar.less
  sass/patternfly-react/_patternfly-react.scss
  sass/patternfly-react/_utilization-bar.scss
  src/components/UtilizationBar/UtilizationBar.js
  src/components/UtilizationBar/UtilizationBar.stories.js
  src/components/UtilizationBar/UtilizationBar.test.js
  src/components/UtilizationBar/__snapshots__/UtilizationBar.test.js.snap
  src/components/UtilizationBar/helpers.js
  src/components/UtilizationBar/index.js
  src/index.js
Labels: enhancement, p2
