Repository patternfly/patternfly-react, pull requests merged in 2018-10, with the labels that each got.

#626 feat(pf4-nav): add nav component
  package.json
  packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
  packages/patternfly-4/react-core/src/components/Brand/index.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/index.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/index.d.ts
  packages/patternfly-4/react-core/src/components/List/index.d.ts
  packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
  packages/patternfly-4/react-core/src/components/Nav/Nav.docs.js
  packages/patternfly-4/react-core/src/components/Nav/Nav.js
  packages/patternfly-4/react-core/src/components/Nav/Nav.test.js
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.js
  packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavItem.js
  packages/patternfly-4/react-core/src/components/Nav/NavList.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavList.js
  packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
  packages/patternfly-4/react-core/src/components/Nav/NavVariants.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavVariants.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/examples/NavDefaultList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavGroupedList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavHorizontalList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavMixedList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavTertiaryList.js
  packages/patternfly-4/react-core/src/components/Nav/index.d.ts
  packages/patternfly-4/react-core/src/components/Nav/index.js
  packages/patternfly-4/react-core/src/components/Radio/index.d.ts
  packages/patternfly-4/react-core/src/components/Select/index.d.ts
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.d.ts
  packages/patternfly-4/react-core/src/components/TextArea/index.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/index.d.ts
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  yarn.lock
Labels: PF4, review

#686 docs(toolbar): correct titles and aria lables for toolbar
  packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbar.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbarSection.js
Labels: PF4

#693 build(lerna): adds lerna-changelog and removes lerna-semantic-release
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .travis/after_success.sh
  CONTRIBUTING.md
  lerna.json
  package.json
  yarn.lock
Labels: chore :house:, review

#697 feat(pf-next update): Update location of styles for patternfly next
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/AlertAction.js
  packages/patternfly-4/react-core/src/components/Alert/AlertBody.js
  packages/patternfly-4/react-core/src/components/Alert/AlertIcon.js
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
  packages/patternfly-4/react-core/src/components/Badge/Badge.js
  packages/patternfly-4/react-core/src/components/Button/Button.js
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/Card.js
  packages/patternfly-4/react-core/src/components/Card/CardBody.js
  packages/patternfly-4/react-core/src/components/Card/CardFooter.js
  packages/patternfly-4/react-core/src/components/Card/CardHeader.js
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/Item.js
  packages/patternfly-4/react-core/src/components/Dropdown/Separator.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-core/src/components/List/List.js
  packages/patternfly-4/react-core/src/components/Modal/Backdrop.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/Nav/Nav.js
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.js
  packages/patternfly-4/react-core/src/components/Nav/NavItem.js
  packages/patternfly-4/react-core/src/components/Nav/NavList.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.js
  packages/patternfly-4/react-core/src/components/Title/Title.js
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.js
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.js
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.js
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js
  packages/patternfly-4/react-core/src/layouts/Grid/gridUtils.js
  packages/patternfly-4/react-core/src/layouts/Level/Level.js
  packages/patternfly-4/react-core/src/layouts/Split/Split.js
  packages/patternfly-4/react-core/src/layouts/Split/SplitItem.js
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.js
  packages/patternfly-4/react-core/src/layouts/Stack/StackItem.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.js
  packages/patternfly-4/react-tokens/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:, review

#696 fix(pf-4): checkboxProps to be consistent with Checkbox.propTypes
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
Labels: PF4

#700 fix(deploy): add surge deployment for merged pr's
  .travis.yml
  .travis/deploy_pr.sh
Labels: chore :house:, review

#695 fix(patternfly-4/react-core): add missing comments to component props
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Badge/Badge.js
  packages/patternfly-4/react-core/src/components/Card/Card.js
  packages/patternfly-4/react-core/src/components/Card/CardBody.js
  packages/patternfly-4/react-core/src/components/Card/CardFooter.js
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Title/Title.js
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.js
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.js
  packages/patternfly-4/react-core/src/layouts/Gallery/GalleryItem.js
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.docs.js
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.js
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js
  packages/patternfly-4/react-core/src/layouts/Grid/examples/GridOverrides.js
  packages/patternfly-4/react-core/src/layouts/Grid/examples/GridPlayground.js
  packages/patternfly-4/react-core/src/layouts/Level/Level.js
  packages/patternfly-4/react-core/src/layouts/Level/LevelItem.js
  packages/patternfly-4/react-core/src/layouts/Split/Split.js
  packages/patternfly-4/react-core/src/layouts/Split/SplitItem.js
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.js
  packages/patternfly-4/react-core/src/layouts/Stack/StackItem.js
Labels: PF4, documentation :memo:, review

#698 chore(lerna-changelog): set the next version attribute appropriately
  lerna.json
Labels: chore :house:, review

#706 fix(Enzyme-adapter): Updated to enzyme-adapter-react-16.3
  package.json
  test.env.js
Labels: review

#707 fix(release): move docs builds into common location and update release
  .travis/deploy_pr.sh
  .travis/release.sh
Labels: review

#694 feat(Live Examples): allow users to tab past editors
  packages/patternfly-4/react-docs/.env.development
  packages/patternfly-4/react-docs/.env.production
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
Labels: PF4, documentation :memo:, review

#654 feat(pf-icons): add all PF icons and update font awesome pckg
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/react-icons/build/generateIcons.js
  packages/react-icons/build/icons.js
  packages/react-icons/build/pfIcons.js
  packages/react-icons/build/templates/iconFile.hbs
  packages/react-icons/package.json
  packages/react-icons/src/createIcon.js
  yarn.lock
Labels: chore :house:, extension, review

#711 chore(react-core, react-docs): added ability to add demos to react-docs.
  packages/patternfly-4/react-core/.babelrc
  packages/patternfly-4/react-core/src/demos/README.md
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/src/components/navigation/navigation.js
  packages/patternfly-4/react-docs/src/layouts/index.js
Labels: Hacktoberfest, review

#712 feat(a11y): add basic a11y checks with react-axe
  packages/patternfly-3/patternfly-react/package.json
  storybook/config.js
  yarn.lock
Labels: accessibility, review

#709 fix(CatalogTile): Fix to show only the iconImg if given, not both the image and icon.
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
Labels: bug :bug:, review

#648 feat(pf4-progress): introduce new component progress with it's variants
  packages/patternfly-4/react-core/src/components/Progress/Progress.d.ts
  packages/patternfly-4/react-core/src/components/Progress/Progress.docs.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/examples/LargeProgress.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressFailure.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressFailureWithoutMeasure.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressInside.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressInsideSuccess.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressOutside.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressOutsideFailure.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressSuccess.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressWithDynamicDescription.js
  packages/patternfly-4/react-core/src/components/Progress/examples/ProgressWithoutMeasure.js
  packages/patternfly-4/react-core/src/components/Progress/examples/SimpleProgress.js
  packages/patternfly-4/react-core/src/components/Progress/examples/SmallProgress.js
  packages/patternfly-4/react-core/src/components/Progress/index.d.ts
  packages/patternfly-4/react-core/src/components/Progress/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
Labels: PF4, review

#713 fix(Alert): Use the correct css class name for screen readers
  packages/patternfly-4/react-core/package.json
Labels: PF4

#671 feat(AboutModal): Add PF4 AboutModal Component
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.docs.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxLogo.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxLogo.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxLogo.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxBrand.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHero.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxLogo.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalContainer.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/examples/SimpleAboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/examples/pf_logo.svg
  packages/patternfly-4/react-core/src/components/AboutModal/examples/pf_mini_logo_white.svg
  packages/patternfly-4/react-core/src/components/AboutModal/examples/pfbg_992.jpg
  packages/patternfly-4/react-core/src/components/AboutModal/index.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/index.js
  packages/patternfly-4/react-core/src/components/Backdrop/Backdrop.d.ts
  packages/patternfly-4/react-core/src/components/Backdrop/Backdrop.js
  packages/patternfly-4/react-core/src/components/Backdrop/Backdrop.test.js
  packages/patternfly-4/react-core/src/components/Backdrop/__snapshots__/Backdrop.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
  packages/patternfly-4/react-core/src/components/Modal/index.d.ts
  packages/patternfly-4/react-core/src/components/Modal/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
Labels: PF4, enhancement :rocket:, review

#722 fix(test): Update the snapshot for progress bar com…
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
Labels: Hacktoberfest :jack_o_lantern:, PF4, bug :bug:

#701 docs(Allowing each example to configure if it should display a live e…
  packages/patternfly-4/react-core/src/layouts/Grid/examples/GridPlayground.js
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
Labels: Hacktoberfest :jack_o_lantern:, PF4, review

#705 fix(Pagination) - buttons are clickable when disabled
  packages/patternfly-3/patternfly-react/less/pagination.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_pagination.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
Labels: review

#661 test(components): Add tests to Filter and Sort selectors
  packages/patternfly-3/patternfly-react/src/components/Filter/Filter.test.js
  packages/patternfly-3/patternfly-react/src/components/Sort/Sort.test.js
  packages/patternfly-3/patternfly-react/src/components/Sort/SortTypeSelector.js
Labels: bug :bug:

#710 fix(backgroundImage): import images to override css paths
  packages/patternfly-4/react-core/build/copyStyles.js
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.docs.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.test.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
  packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/index.d.ts
  packages/patternfly-4/react-core/src/components/BackgroundImage/index.js
  packages/patternfly-4/react-styles/src/StyleSheet.js
  packages/patternfly-4/react-tokens/package.json
  yarn.lock
Labels: PF4, review

#725 fix(CatalogTileView): Fix to not render hidden tiles in catalog tile view categories
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/less/variables.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
Labels: bug :bug:, extension

#714 feat(Page layout): Adds the page layout to PF4
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.docs.js
  packages/patternfly-4/react-core/src/layouts/Gallery/examples/GalleryWithGutters.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/Page.docs.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.test.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.js
  packages/patternfly-4/react-core/src/layouts/Page/PageSection.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageSection.js
  packages/patternfly-4/react-core/src/layouts/Page/PageSidebar.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageSidebar.js
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/examples/HorizontalPage.js
  packages/patternfly-4/react-core/src/layouts/Page/examples/VerticalPage.js
  packages/patternfly-4/react-core/src/layouts/Page/examples/common/getContainerProps.js
  packages/patternfly-4/react-core/src/layouts/Page/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/index.js
  packages/patternfly-4/react-core/src/layouts/index.d.ts
  packages/patternfly-4/react-core/src/layouts/index.js
Labels: Hacktoberfest :jack_o_lantern:, PF4, review

#727 fix(Alert): [TS] action type is string while it should've been node
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
Labels: PF4, bug :bug:

#721 fix(react-docs: oneoftype support):
  packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
Labels: Hacktoberfest :jack_o_lantern:, PF4, bug :bug:

#730 fix(CatalogTileView): Fix to render non-tile children of a category
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
Labels: bug :bug:, extension

#734 fix(table-grid): use package import rather than relative path in TableGrid
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
Labels: bug :bug:, extension

#735 docs(README.md): Update docs about running the site locally
  packages/patternfly-4/react-core/README.md
  packages/patternfly-4/react-docs/README.md
Labels: documentation :memo:

#737 feat(LoginBox): introduce the pf4 loginbox component
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.d.ts
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.docs.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.test.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxBody.d.ts
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxBody.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxBody.test.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxFooter.d.ts
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxFooter.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxFooter.test.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.js
  packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.test.js
  packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBox.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBoxBody.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBoxFooter.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginBox/examples/SimpleLoginBox.js
  packages/patternfly-4/react-core/src/components/LoginBox/index.d.ts
  packages/patternfly-4/react-core/src/components/LoginBox/index.js
  packages/patternfly-4/react-core/src/components/index.js
Labels: Hacktoberfest :jack_o_lantern:, PF4

#733 feat(text component): adds the text component to PF4
  packages/patternfly-4/react-core/src/components/AboutModal/examples/SimpleAboutModal.js
  packages/patternfly-4/react-core/src/components/Text/Text.d.ts
  packages/patternfly-4/react-core/src/components/Text/Text.docs.js
  packages/patternfly-4/react-core/src/components/Text/Text.js
  packages/patternfly-4/react-core/src/components/Text/Text.test.js
  packages/patternfly-4/react-core/src/components/Text/TextContent.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextContent.js
  packages/patternfly-4/react-core/src/components/Text/TextList.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextList.js
  packages/patternfly-4/react-core/src/components/Text/TextListItem.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextListItem.js
  packages/patternfly-4/react-core/src/components/Text/__snapshots__/Text.test.js.snap
  packages/patternfly-4/react-core/src/components/Text/examples/BodyText.js
  packages/patternfly-4/react-core/src/components/Text/examples/DataList.js
  packages/patternfly-4/react-core/src/components/Text/examples/Headings.js
  packages/patternfly-4/react-core/src/components/Text/examples/OrderedList.js
  packages/patternfly-4/react-core/src/components/Text/examples/UnorderedList.js
  packages/patternfly-4/react-core/src/components/Text/index.d.ts
  packages/patternfly-4/react-core/src/components/Text/index.js
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-styles/src/StyleSheet.js
  packages/patternfly-4/react-styles/src/__snapshots__/StyleSheet.test.js.snap
Labels: Hacktoberfest :jack_o_lantern:, PF4

#742 docs(README): Update link for PF4-React documentation page
  packages/patternfly-4/react-core/README.md
  packages/patternfly-4/react-tokens/README.md
  packages/react-icons/README.md
Labels: PF4, documentation :memo:

#748 fix(BackgroundImage): remove children from props
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
Labels: PF4

#746 PF4: Login layout
  packages/patternfly-4/react-core/src/layouts/Login/Login.d.ts
  packages/patternfly-4/react-core/src/layouts/Login/Login.docs.js
  packages/patternfly-4/react-core/src/layouts/Login/Login.js
  packages/patternfly-4/react-core/src/layouts/Login/Login.test.js
  packages/patternfly-4/react-core/src/layouts/Login/LoginFooter.d.ts
  packages/patternfly-4/react-core/src/layouts/Login/LoginFooter.js
  packages/patternfly-4/react-core/src/layouts/Login/LoginHeader.d.ts
  packages/patternfly-4/react-core/src/layouts/Login/LoginHeader.js
  packages/patternfly-4/react-core/src/layouts/Login/LoginHeaderBrand.d.ts
  packages/patternfly-4/react-core/src/layouts/Login/LoginHeaderBrand.js
  packages/patternfly-4/react-core/src/layouts/Login/__snapshots__/Login.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Login/examples/SimpleLoginLayout.js
  packages/patternfly-4/react-core/src/layouts/Login/examples/common/getContainerProps.js
  packages/patternfly-4/react-core/src/layouts/Login/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Login/index.js
  packages/patternfly-4/react-core/src/layouts/index.d.ts
  packages/patternfly-4/react-core/src/layouts/index.js
Labels: PF4

#751 Fix broken image paths for patternfly-4 docs hosted by surge
  .travis/release.sh
Labels: chore :house:

#749 feat(page layout demos): Add PF4 page layout demos
  packages/patternfly-4/react-core/.babelrc
  packages/patternfly-4/react-core/.npmignore
  packages/patternfly-4/react-core/src/demos/PageLayout/PageLayoutDemo.docs.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/img_avatar.png
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/l_pf-reverse-164x11.png
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.styles.js
  packages/patternfly-4/react-docs/src/layouts/index.js
  yarn.lock
Labels: PF4

#717 feat(checkBox): updated PF4 checkBox component according to PF-next
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.docs.js
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.js
  packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
  packages/patternfly-4/react-core/src/components/Checkbox/examples/ControlledCheckbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/CustomLabelCheckbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/DisabledCheckbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/UncontrolledCheckbox.js
Labels: PF4, enhancement :rocket:

#613 feat(ExpandCollapse): introduce ExpandCollapse component
  packages/patternfly-3/patternfly-react/less/expand-collapse.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_expand-collapse.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.stories.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.test.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/__snapshots__/ExpandCollapse.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/constants.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/index.js
  packages/patternfly-3/patternfly-react/src/index.js
Labels: css approved, enhancement :rocket:, review, ux approved

#763 feat(CatalogTile): Use a link for tiles with href or onClick props
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap
Labels: enhancement :rocket:, extension

#764 fix(CatalogTile): Style update for tile with focus
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
Labels: bug :bug:, extension

#758 Show Masthead title
  packages/patternfly-3/patternfly-react/src/components/HorizontalNav/__snapshots__/HorizontalNav.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/Masthead/Masthead.js
Labels: bug :bug:

#667 feat(formComponent): add Form, FormGroup, ActionGroup PF4 components
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.d.ts
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.js
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.test.js
  packages/patternfly-4/react-core/src/components/Form/Form.d.ts
  packages/patternfly-4/react-core/src/components/Form/Form.docs.js
  packages/patternfly-4/react-core/src/components/Form/Form.js
  packages/patternfly-4/react-core/src/components/Form/Form.test.js
  packages/patternfly-4/react-core/src/components/Form/FormContext.js
  packages/patternfly-4/react-core/src/components/Form/FormGroup.d.ts
  packages/patternfly-4/react-core/src/components/Form/FormGroup.js
  packages/patternfly-4/react-core/src/components/Form/FormGroup.test.js
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/Form.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/examples/AlternativeForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/InvalidForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/VariousLabelsForm.js
  packages/patternfly-4/react-core/src/components/Form/index.d.ts
  packages/patternfly-4/react-core/src/components/Form/index.js
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.js
  packages/patternfly-4/react-core/src/internal/htmlConstants.js
Labels: PF4, enhancement :rocket:, review

#780 fix(react-docs): Fix live mode toggling
  packages/patternfly-4/react-docs/README.md
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
Labels: PF4, bug :bug:

#790 fix(Progress): Correct small progress size
  packages/patternfly-4/react-core/src/components/Progress/Progress.d.ts
Labels: PF4, bug :bug:

#798 fix(react-core): add missing component to index type definitions
  packages/patternfly-4/react-core/src/components/index.d.ts
Labels: PF4

#776 fix(ModelessOverlay): Fix for animation on open in Firefox browser
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.js
Labels: bug :bug:

#756 feat(radioComponent): updated according to PF-next demo
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
  packages/patternfly-4/react-core/src/components/Radio/Radio.docs.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.test.js
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
  packages/patternfly-4/react-core/src/components/Radio/examples/ControlledRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/CustomLabelRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/DisabledRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/UncontrolledRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/common/getContainerProps.js
Labels: PF4, enhancement :rocket:

#792 fix(Form): Do not add any class if action modifier is missing
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.js
Labels: PF4, bug :bug:

#800 fix(typescript definitions): fix ts defs for checkbox, BackgroundImage, and Form
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
  packages/patternfly-4/react-core/src/components/BackgroundImage/index.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
  packages/patternfly-4/react-core/src/components/Form/FormGroup.d.ts
Labels: bug :bug:

#794 Fix typo in story file name
  packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.stories.js
Labels: chore :house:

#804 fix(CatalogTile): Fix to not allow the description text to overflow the tile
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__images__/OpenShift.svg
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
Labels: bug :bug:, extension

#806 fix(ts-definitions): fix type definitions for radio
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
Labels: PF4, bug :bug:

#808 fix(CatalogItemHeader): Make subtitle optional
  packages/patternfly-3/patternfly-react-extensions/less/catalog-item.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-item.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/__snapshots__/CatalogItemHeader.test.js.snap
Labels: bug :bug:, extension

#810 fix(CatalogTile): Catalog Tiles can shrink
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
Labels: bug :bug:, extension

#812 chore(pf4): update core
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Backdrop/__snapshots__/Backdrop.test.js.snap
  packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
  packages/patternfly-4/react-tokens/package.json
  yarn.lock
Labels: PF4

#805 docs(formComponent): changes radios in examples to radio component
  packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js
Labels: PF4, documentation :memo:

#814 chore(pf4): update core for react-icons
  packages/patternfly-4/verifyCoreVersions.js
  packages/react-icons/package.json
  yarn.lock
Labels: PF4

#815 feat(PF4-Dropdown): Enhance keyboard interaction for a11y
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  yarn.lock
Labels: PF4

#823 fix(formComponent): removes Children props checking
  packages/patternfly-4/react-core/src/components/Form/FormGroup.js
Labels: PF4

#822 feat(Labeled progress): allow consumers to pass additional label for progressbar
  packages/patternfly-4/react-core/src/components/Progress/Progress.docs.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/examples/LabeledProgress.js
Labels: PF4, enhancement :rocket:

#826 fix(ExpandCollapse): Fix to export ALIGN_LEFT and ALIGN_CENTER constants
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.stories.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.test.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/constants.js
Labels: bug :bug:

#703 chore(generators): Update package generator to new build script styles
  scripts/generators/package/.babelrc.hbs
  scripts/generators/package/.npmignore.hbs
  scripts/generators/package/index.js
  scripts/generators/package/package.json.hbs
Labels: review

#731 docs(custom-icon): describe how to add custom icons
  packages/react-icons/README.md
Labels: documentation :memo:

#833 fix(Select/TextInput): fix components typescript interfaces
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts
Labels: PF4, bug :bug:

#788 refactor(patternfly-4/react-core): Updated the Dropdown component to …
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/Item.js
  packages/patternfly-4/react-core/src/components/Dropdown/KebabToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/Separator.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownItem.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/BasicDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/DirectionUpDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/KebabDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/PositionRightDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/SimpleDropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/index.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/index.js
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: Hacktoberfest :jack_o_lantern:, PF4

#606 feat(ConsoleSelector): introduce ConsoleSelector component
  packages/patternfly-3/react-console/less/console-selector.less
  packages/patternfly-3/react-console/less/console.less
  packages/patternfly-3/react-console/less/vnc-console.less
  packages/patternfly-3/react-console/package.json
  packages/patternfly-3/react-console/sass/_console-selector.scss
  packages/patternfly-3/react-console/sass/_vnc-console.scss
  packages/patternfly-3/react-console/sass/console.scss
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.stories.js
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.test.js
  packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
  packages/patternfly-3/react-console/src/AccessConsoles/index.js
  packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.stories.js
  packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
  packages/patternfly-3/react-console/src/VncConsole/__snapshots__/VncConsole.test.js.snap
  packages/patternfly-3/react-console/src/common/constants.js
  packages/patternfly-3/react-console/src/index.js
Labels: enhancement :rocket:, review

#832 chore(patternfly-4/react-core): Added a Wrapper component that will g…
  packages/patternfly-4/react-core/src/internal/GenerateId/GenerateId.js
  packages/patternfly-4/react-core/src/internal/GenerateId/GenerateId.test.js
  packages/patternfly-4/react-core/src/internal/GenerateId/__snapshots__/GenerateId.test.js.snap
Labels: Hacktoberfest :jack_o_lantern:, PF4

#830 refactor: Use the same mechanism for autogenerated component id
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/internal/util.js
  packages/patternfly-4/react-core/src/internal/util.test.js
Labels: PF4, chore :house:

#843 feat(page layout): adds the condensed header feature to the page header
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/demos/PageLayout/PageLayoutDemo.docs.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutCondensedHeader.js
  packages/patternfly-4/react-core/src/internal/util.js
  packages/patternfly-4/react-core/src/internal/util.test.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/Page.js
  packages/patternfly-4/react-core/src/layouts/Page/Page.test.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.d.ts
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.js
  packages/patternfly-4/react-core/src/layouts/Page/PageHeader.test.js
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:

#841 fix(patternfly-4/react-core): Make the id prop for Dropdown optional …
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
Labels: Hacktoberfest :jack_o_lantern:, PF4, bug :bug:

#842 feat(helpers): Add exported helpers object containing all helper functions
  packages/patternfly-3/patternfly-react/src/common/helpers.js
Labels: enhancement :rocket:

#835 fix(CatalogTileView): Behave correctly when CatalogTile components are wrapped
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
Labels: bug :bug:, extension

#850 fix(CatalogTile): Fade end of description text rather than truncate
  packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
Labels: bug :bug:, extension

#853 feat(Extensions): Import patternfly-react components individually
  packages/patternfly-3/.babelrc.js
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategory.js
  packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategoryItem.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridColumnHeader.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
  packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
Labels: enhancement :rocket:, extension

#854 Nav item update to handle onClick
  packages/patternfly-4/react-core/src/components/Nav/Nav.js
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavItem.js
  packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
Labels: PF4

#861 fix(PF4 - Progress): update styles usage
  packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
Labels: PF4

#858 fix(Progress): import progress style object
  packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
Labels: PF4, bug :bug:

#829 feat(BadgedResource): Add BadgedResource component to patternfly-react-extensions
  packages/patternfly-3/patternfly-react-extensions/less/badged-resource.less
  packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_badged-resource.scss
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.stories.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.test.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/ResourceTypes.js
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/__snapshots__/BadgedResource.test.js.snap
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/index.js
  packages/patternfly-3/patternfly-react-extensions/src/index.js
Labels: enhancement :rocket:, extension, ux approved
