Repository patternfly/patternfly-react, pull requests merged in 2018-06, with the labels that each got.

#372 feat(bullet-chart): add Bullet Chart component
  packages/core/package.json
  packages/core/src/components/Chart/BulletChart/BulletChart.js
  packages/core/src/components/Chart/BulletChart/BulletChart.test.js
  packages/core/src/components/Chart/BulletChart/BulletChartAxis.js
  packages/core/src/components/Chart/BulletChart/BulletChartAxisTic.js
  packages/core/src/components/Chart/BulletChart/BulletChartLegend.js
  packages/core/src/components/Chart/BulletChart/BulletChartLegendItem.js
  packages/core/src/components/Chart/BulletChart/BulletChartRange.js
  packages/core/src/components/Chart/BulletChart/BulletChartThreshold.js
  packages/core/src/components/Chart/BulletChart/BulletChartTitle.js
  packages/core/src/components/Chart/BulletChart/BulletChartValue.js
  packages/core/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap
  packages/core/src/components/Chart/BulletChart/index.js
  packages/core/src/components/Chart/Chart.stories.js
  packages/core/src/components/Chart/Stories/BulletChartStory.js
  packages/core/src/components/Chart/Stories/index.js
  packages/core/src/components/Chart/index.js
  yarn.lock
Labels: ux approved

#374 feat(TypeAheadSelect): Add TypeAheadSelect component with storybook and tests
  packages/core/less/patternfly-react.less
  packages/core/less/type-ahead-select.less
  packages/core/package.json
  packages/core/sass/patternfly-react/_patternfly-react.scss
  packages/core/sass/patternfly-react/_type-ahead-select.scss
  packages/core/src/components/TypeaheadSelect/AsyncTypeAheadSelect.js
  packages/core/src/components/TypeaheadSelect/AsyncTypeAheadSelect.test.js
  packages/core/src/components/TypeaheadSelect/GithubMenuItem.js
  packages/core/src/components/TypeaheadSelect/TypeAheadSelect.js
  packages/core/src/components/TypeaheadSelect/TypeAheadSelect.stories.js
  packages/core/src/components/TypeaheadSelect/TypeAheadSelect.test.js
  packages/core/src/components/TypeaheadSelect/__snapshots__/AsyncTypeAheadSelect.test.js.snap
  packages/core/src/components/TypeaheadSelect/__snapshots__/TypeAheadSelect.test.js.snap
  packages/core/src/components/TypeaheadSelect/index.js
  packages/core/src/components/TypeaheadSelect/mock.js
  yarn.lock
Labels: css approved, ux approved

#319 feat(ApplicationLauncher): Add Application Launcher Component
  packages/core/package.json
  packages/core/src/components/ApplicationLauncher/ApplicationLauncher.js
  packages/core/src/components/ApplicationLauncher/ApplicationLauncher.stories.js
  packages/core/src/components/ApplicationLauncher/ApplicationLauncher.test.js
  packages/core/src/components/ApplicationLauncher/ApplicationLauncherItem.js
  packages/core/src/components/ApplicationLauncher/ApplicationLauncherToggle.js
  packages/core/src/components/ApplicationLauncher/Stories/NavApplicationLauncherStory.js
  packages/core/src/components/ApplicationLauncher/Stories/WrapperNavApplicationLauncherStory.js
  packages/core/src/components/ApplicationLauncher/Stories/index.js
  packages/core/src/components/ApplicationLauncher/Wrappers/ApplicationLauncherWrapper.js
  packages/core/src/components/ApplicationLauncher/Wrappers/StatefulApplicationLauncherWrapper.js
  packages/core/src/components/ApplicationLauncher/Wrappers/Wrappers.test.js
  packages/core/src/components/ApplicationLauncher/Wrappers/__snapshots__/Wrappers.test.js.snap
  packages/core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/core/src/components/ApplicationLauncher/index.js
  yarn.lock
Labels: css approved, ux approved

#330 feat(VerticalNav): Add Divider as a Secondary Item
  packages/patternfly-react/less/patternfly-react.less
  packages/patternfly-react/less/verticalnavdivider.less
  packages/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-react/sass/patternfly-react/_verticalnavdivider.scss
  packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
  packages/patternfly-react/src/components/VerticalNav/VerticalNavDividerItem.js
  packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
  packages/patternfly-react/src/components/VerticalNav/VerticalNavSecondaryItem.js
  packages/patternfly-react/src/components/VerticalNav/__mocks__/basicExample.js
  packages/patternfly-react/src/components/VerticalNav/__mocks__/mockNavItems.js
  packages/patternfly-react/src/components/VerticalNav/index.js
Labels: css approved, ux approved

#363 feat(MessageDialog): introduces MessageDialog component
  packages/patternfly-react/package.json
  packages/patternfly-react/src/components/MessageDialog/MessageDialog.js
  packages/patternfly-react/src/components/MessageDialog/MessageDialog.stories.js
  packages/patternfly-react/src/components/MessageDialog/MessageDialog.test.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogDeleteConfirmation.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogError.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogInfo.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogNondestructiveAction.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogQuestion.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogSuccess.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogToggleableOptions.js
  packages/patternfly-react/src/components/MessageDialog/Stories/MessageDialogWarning.js
  packages/patternfly-react/src/components/MessageDialog/Stories/lorem.js
  packages/patternfly-react/src/components/MessageDialog/index.js
  packages/patternfly-react/src/index.js
  packages/react-console/package.json
  yarn.lock
Labels: ux approved

#414 feat(MastHead) Add Horizontal Navigation MastHead
  packages/patternfly-react/less/masthead.less
  packages/patternfly-react/less/patternfly-react.less
  packages/patternfly-react/sass/patternfly-react/_masthead.scss
  packages/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-react/src/components/Masthead/Masthead.js
  packages/patternfly-react/src/components/Masthead/Masthead.stories.js
  packages/patternfly-react/src/components/Masthead/MastheadDropdown.js
  packages/patternfly-react/src/components/Masthead/__snapshots__/Masthead.test.js.snap
  storybook/img/brand.svg
Labels: enhancement, ux approved

#425 fix(react-core/typings): relax typings for button. Correct typings for title
  packages/react-core/src/components/Button/Button.d.ts
  packages/react-core/src/components/Title/Title.d.ts
  packages/react-core/src/typeUtils.d.ts
  tsconfig.json
Labels: PF4

#424 chore(generator): Generators
  .eslintignore
  CONTRIBUTING.md
  package.json
  packages/react-docs/src/pages/components/title.js
  plopfile.js
  scripts/generators/actionTypes.js
  scripts/generators/helpers.js
  scripts/generators/package/index.js
  scripts/generators/package/package.json.hbs
  scripts/generators/patternfly-4-component/index.js
  scripts/generators/patternfly-4-component/templates/component/index.js
  scripts/generators/patternfly-4-component/templates/component/{{componentName}}.js
  scripts/generators/patternfly-4-component/templates/component/{{componentName}}.test.js
  scripts/generators/patternfly-4-component/templates/docs.hbs
  yarn.lock
Labels: PF4
