Repository patternfly/patternfly-react, pull requests merged in 2018-04, with the labels that each got.

#269 Docs(storybook): update to storybook 3.4
  package-lock.json
  package.json
  src/components/Alert/Alert.stories.js
  src/components/Badge/Badge.stories.js
  src/components/Breadcrumb/Breadcrumb.stories.js
  src/components/Button/Button.stories.js
  src/components/Chart/Chart.stories.js
  src/components/Chart/Stories/AreaChartStory.js
  src/components/Chart/Stories/BarChartStory.js
  src/components/Chart/Stories/DonutChartStory.js
  src/components/Chart/Stories/LineChartStory.js
  src/components/Chart/Stories/PieChartStory.js
  src/components/Chart/Stories/index.js
  src/components/DropdownKebab/DropdownKebab.stories.js
  src/components/EmptyState/EmptyState.stories.js
  src/components/FieldLevelHelp/FieldLevelHelp.stories.js
  src/components/Form/Form.stories.js
  src/components/Grid/Grid.stories.js
  src/components/Icon/Icon.stories.js
  src/components/InfoTip/InfoTip.stories.js
  src/components/Label/Label.stories.js
  src/components/ListGroup/ListGroup.stories.js
  src/components/ListView/ListView.stories.js
  src/components/MenuItem/MenuItem.stories.js
  src/components/Pagination/Pagination.stories.js
  src/components/Popover/Popover.stories.js
  src/components/ProgressBar/ProgressBar.stories.js
  src/components/Sort/Sort.stories.js
  src/components/Spinner/Spinner.stories.js
  src/components/Switch/Switch.stories.js
  src/components/Table/Stories/BootstrapTableStory.js
  src/components/Table/Stories/ClientPaginationTableStory.js
  src/components/Table/Stories/ClientSortableTableStory.js
  src/components/Table/Stories/PatternflyTableStory.js
  src/components/Table/Stories/ServerPaginationTableStory.js
  src/components/Table/Stories/index.js
  src/components/Table/Table.stories.js
  src/components/Tabs/Tabs.stories.js
  src/components/ToastNotification/ToastNotification.stories.js
  src/components/Tooltip/Tooltip.stories.js
  src/components/UtilizationBar/UtilizationBar.stories.js
  storybook/addons.js
  storybook/webpack.config.js
Labels: chore, review

#293 chore(dependencies): Update non-breaking deps
  package-lock.json
  package.json
  src/components/AboutModal/__snapshots__/AboutModal.test.js.snap
  src/components/Cards/__snapshots__/Cards.test.js.snap
  src/components/Form/__snapshots__/Form.test.js.snap
  src/components/ListView/__snapshots__/ListView.test.js.snap
  src/components/Table/__snapshots__/Table.test.js.snap
Labels: chore

#262 feat(NotificationDrawer): Notification, NotificationDrawer
  less/notificationdrawer.less
  less/patternfly-react.less
  sass/patternfly-react/_notificationdrawer.scss
  sass/patternfly-react/_patternfly-react.scss
  src/components/Notification/Notification.js
  src/components/Notification/Notification.test.js
  src/components/Notification/NotificationContent.js
  src/components/Notification/NotificationDrawer/NotificationDrawer.js
  src/components/Notification/NotificationDrawer/NotificationDrawer.test.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerAccordion.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerDropDown.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanel.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelAction.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelActionLink.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelBody.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelCollapse.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelCounter.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelHeading.js
  src/components/Notification/NotificationDrawer/NotificationDrawerAccordion/NotificationDrawerPanelTitle.js
  src/components/Notification/NotificationDrawer/NotificationDrawerTitle.js
  src/components/Notification/NotificationDrawer/NotificationDrawerToggle.js
  src/components/Notification/NotificationDrawer/__snapshots__/NotificationDrawer.test.js.snap
  src/components/Notification/NotificationDrawer/index.js
  src/components/Notification/NotificationDrawerStory.stories.js
  src/components/Notification/NotificationInfo.js
  src/components/Notification/NotificationInfoLeft.js
  src/components/Notification/NotificationInfoRight.js
  src/components/Notification/NotificationMessage.js
  src/components/Notification/Stories/StatefulNotificationDrawerStory.js
  src/components/Notification/Stories/WrapperNotificationDrawerStory.js
  src/components/Notification/Stories/basicNotificationDrawerStory.js
  src/components/Notification/Stories/index.js
  src/components/Notification/Wrappers/Icon.consts.js
  src/components/Notification/Wrappers/NotificationDrawerPanelWrapper.js
  src/components/Notification/Wrappers/NotificationDrawerWrapper.js
  src/components/Notification/Wrappers/StatefulNotificationDrawerWrapper.js
  src/components/Notification/Wrappers/StatefulToggleNotificationDrawerWrapper.js
  src/components/Notification/Wrappers/Wrappers.test.js
  src/components/Notification/Wrappers/__snapshots__/Wrappers.test.js.snap
  src/components/Notification/Wrappers/index.js
  src/components/Notification/__snapshots__/Notification.test.js.snap
  src/components/Notification/index.js
  src/index.js
Labels: css approved, review, structural pattern, ux approved

#280 feat(Slider): Add Slider component, storybook and tests
  package-lock.json
  package.json
  src/components/Slider/BootstrapSlider.js
  src/components/Slider/Boundaries.js
  src/components/Slider/DropdownMenu.js
  src/components/Slider/Slider.js
  src/components/Slider/Slider.stories.js
  src/components/Slider/Slider.test.js
  src/components/Slider/__mocks__/bootstrap-slider-without-jquery.js
  src/components/Slider/__snapshots__/Slider.test.js.snap
  src/components/Slider/index.js
  src/index.js
Labels: ux approved

#268 feat(WizardPattern): Add WizardPattern and StatefulWizardPattern components
  package.json
  src/common/controlled.js
  src/common/helpers.js
  src/components/Wizard/Patterns/StatefulWizardPattern.js
  src/components/Wizard/Patterns/WizardPattern.js
  src/components/Wizard/Patterns/WizardPatternBody.js
  src/components/Wizard/Patterns/WizardPatternConstants.js
  src/components/Wizard/Stories/LoadingWizardExample.js
  src/components/Wizard/Stories/LoadingWizardExampleStory.js
  src/components/Wizard/Stories/WizardExample.js
  src/components/Wizard/Stories/WizardExampleStory.js
  src/components/Wizard/Stories/WizardPatternExample.js
  src/components/Wizard/Stories/WizardPatternExampleStory.js
  src/components/Wizard/Stories/index.js
  src/components/Wizard/Stories/mockWizardBase.js
  src/components/Wizard/Stories/mockWizardDeployContents.js
  src/components/Wizard/Stories/mockWizardItems.js
  src/components/Wizard/Stories/mockWizardRenderers.js
  src/components/Wizard/Stories/mockWizardReviewStepsManager.js
  src/components/Wizard/Wizard.js
  src/components/Wizard/Wizard.stories.js
  src/components/Wizard/Wizard.test.js
  src/components/Wizard/WizardBody.js
  src/components/Wizard/WizardFooter.js
  src/components/Wizard/WizardHeader.js
  src/components/Wizard/__mocks__/mockEmbeddedWizardManager.js
  src/components/Wizard/__mocks__/mockLoadingWizardManager.js
  src/components/Wizard/__mocks__/mockModalWizardManager.js
  src/components/Wizard/__snapshots__/Wizard.test.js.snap
  src/components/Wizard/index.js
  src/index.js
  yarn.lock
Labels: review, structural pattern

#315 chore(package.json): Make git-hooks a dev dependency
  package.json
Labels: review
