Repository patternfly/patternfly-react, pull requests merged in 2019-05, with the labels that each got.

#1876 fix(ClipboardCopy): update imports and clean up
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.d.ts
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.js
Labels: PF4, bug :bug:

#1847 docs(wizard): remember the last step on close
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
Labels: PF4, documentation :memo:

#1904 docs(Wizard): update the description for the startAtStep prop
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
Labels: PF4, documentation :memo:

#1924 fix (dropitems): Updates to drop down item and skip to content api
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.d.ts
  packages/patternfly-4/react-core/src/components/SkipToContent/SkipToContent.tsx
Labels: PF4, bug :bug:

#1868 fix(React Icons documentation): fix link in Icons documentation
  packages/react-icons/README.md
Labels: PF4, documentation :memo:

#1757 fix(popover): Enable highlighting and selecting text in popover.
  packages/patternfly-4/react-core/src/components/Tooltip/styles.js
Labels: PF4, enhancement :rocket:

#1923 fix(BackgroundImage): fixed background image spacing issue
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.md
  packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
  packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.md
Labels: PF4, bug :bug:

#1667 fix(Dropdown): Send event when clicking on dropdown toggle
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
Labels: PF4

#1899 fix(types): Update @types/victory, victory, victory-core, and hoist-non-react-statics packages to latest
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.d.ts
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.js.snap
  yarn.lock
Labels: PF4, bug :bug:

#1912 Typescript integration test
  .travis.yml
  package.json
  packages/patternfly-4/react-core/CONTRIBUTING.md
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Avatar/index.ts
  packages/patternfly-4/react-core/src/components/Button/Button.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardToggle.tsx
  packages/patternfly-4/react-core/src/components/Wizard/index.ts
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-core/tslint.json
  packages/patternfly-4/react-integration/README.md
  packages/patternfly-4/react-integration/cypress/fixtures/example.json
  packages/patternfly-4/react-integration/cypress/integration/navigation.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tabdemo.spec.ts
  packages/patternfly-4/react-integration/cypress/plugins/index.js
  packages/patternfly-4/react-integration/cypress/support/commands.js
  packages/patternfly-4/react-integration/cypress/support/index.js
  packages/patternfly-4/react-integration/cypress/tsconfig.json
  packages/patternfly-4/react-integration/demo-app-ts/package.json
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/assets/images/imgAvatar.svg
  packages/patternfly-4/react-integration/demo-app-ts/src/assets/images/imgBrand.png
  packages/patternfly-4/react-integration/demo-app-ts/src/components/AppHeader/AppHeader.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/AppSidebar/AppSidebar.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/AppToolbar/AppToolbar.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AvatarDemo/AvatarDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TitleDemo/TitleDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TooltipDemo/TooltipDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/index.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/logo.svg
  packages/patternfly-4/react-integration/demo-app-ts/tsconfig.json
  packages/patternfly-4/react-integration/package.json
  packages/patternfly-4/react-integration/scripts/server.js
  packages/patternfly-4/react-integration/tsconfig.json
  packages/patternfly-4/react-integration/tslint.json
  packages/patternfly-4/react-integration/webpack.config.js
  yarn.lock
Labels: PF4, infrastructure

#1948 Update README.md
  packages/patternfly-4/react-integration/README.md
Labels: PF4, doc review, documentation :memo:

#1911 fix(DualList): Distinguish between default hidden to filter hidden
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListItem.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
Labels: PF3

#1896 feat(Label): Convert Label to TypeScript
  packages/patternfly-4/react-core/src/components/Label/Label.d.ts
  packages/patternfly-4/react-core/src/components/Label/Label.js
  packages/patternfly-4/react-core/src/components/Label/Label.test.tsx
  packages/patternfly-4/react-core/src/components/Label/Label.tsx
  packages/patternfly-4/react-core/src/components/Label/__snapshots__/Label.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Label/index.d.ts
  packages/patternfly-4/react-core/src/components/Label/index.js
  packages/patternfly-4/react-core/src/components/Label/index.ts
  packages/patternfly-4/react-integration/cypress/integration/label.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, enhancement :rocket:

#1928 feat(Paginator): Add disableNext,disablePrev Props
  packages/patternfly-3/patternfly-react/src/components/Pagination/PaginationRow.js
  packages/patternfly-3/patternfly-react/src/components/Pagination/PaginationRowBack.js
  packages/patternfly-3/patternfly-react/src/components/Pagination/PaginationRowForward.js
  packages/patternfly-3/patternfly-react/src/components/Pagination/Paginator.js
Labels: PF3

#1813 add support for spice connectivity using JS based client
  packages/patternfly-3/react-console/package.json
  packages/patternfly-3/react-console/src/SpiceConsole/SpiceActions.js
  packages/patternfly-3/react-console/src/SpiceConsole/SpiceActions.test.js
  packages/patternfly-3/react-console/src/SpiceConsole/SpiceConsole.js
  packages/patternfly-3/react-console/src/SpiceConsole/SpiceConsole.stories.js
  packages/patternfly-3/react-console/src/SpiceConsole/__snapshots__/SpiceActions.test.js.snap
  packages/patternfly-3/react-console/src/SpiceConsole/index.js
  packages/patternfly-3/react-console/src/index.js
  yarn.lock
Labels: PF3

#1974 feat(LoginPage): support multiple alerts
  packages/patternfly-3/patternfly-react/less/login-page.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/SocialLoginPage.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageAlerts.js
Labels: PF3

#1930 fix(DualList): The component shouldn't count, toggle or filter hidden items.
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
Labels: PF3

#1901 fix(DualList): add callbacks to Controlled Dual List methods
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualListControlled.js
Labels: PF3

#1907 feat(Text): Convert Text to TypeScript
  packages/patternfly-4/react-core/src/components/Text/Text.d.ts
  packages/patternfly-4/react-core/src/components/Text/Text.js
  packages/patternfly-4/react-core/src/components/Text/Text.md
  packages/patternfly-4/react-core/src/components/Text/Text.test.js
  packages/patternfly-4/react-core/src/components/Text/Text.tsx
  packages/patternfly-4/react-core/src/components/Text/TextContent.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextContent.tsx
  packages/patternfly-4/react-core/src/components/Text/TextList.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextList.js
  packages/patternfly-4/react-core/src/components/Text/TextList.tsx
  packages/patternfly-4/react-core/src/components/Text/TextListItem.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextListItem.js
  packages/patternfly-4/react-core/src/components/Text/TextListItem.tsx
  packages/patternfly-4/react-core/src/components/Text/__snapshots__/Text.test.js.snap
  packages/patternfly-4/react-core/src/components/Text/index.d.ts
  packages/patternfly-4/react-core/src/components/Text/index.js
  packages/patternfly-4/react-core/src/components/Text/index.ts
  packages/patternfly-4/react-integration/cypress/integration/text.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextDemo/TextDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#1929 fix(Checkbox): Set checked value correctly
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.md
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
Labels: PF4, bug :bug:

#1918 feat(brand): Converted brand component to typescript
  packages/patternfly-4/react-core/src/components/Brand/Brand.d.ts
  packages/patternfly-4/react-core/src/components/Brand/Brand.js
  packages/patternfly-4/react-core/src/components/Brand/Brand.md
  packages/patternfly-4/react-core/src/components/Brand/Brand.test.tsx
  packages/patternfly-4/react-core/src/components/Brand/Brand.tsx
  packages/patternfly-4/react-core/src/components/Brand/__snapshots__/Brand.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Brand/index.d.ts
  packages/patternfly-4/react-core/src/components/Brand/index.js
  packages/patternfly-4/react-core/src/components/Brand/index.ts
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-4/react-integration/cypress/integration/brand.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/BrandDemo/BrandDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/BrandDemo/images/pfLogo.svg
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#1978 feat(alert): convert alert to TS
  .travis.yml
  package.json
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/Alert.md
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
  packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.tsx
  packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.d.ts
  packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.js
  packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.tsx
  packages/patternfly-4/react-core/src/components/Alert/AlertBody.js
  packages/patternfly-4/react-core/src/components/Alert/AlertIcon.tsx
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Alert/index.d.ts
  packages/patternfly-4/react-core/src/components/Alert/index.js
  packages/patternfly-4/react-core/src/components/Alert/index.ts
  packages/patternfly-4/react-core/src/components/Title/Title.tsx
  packages/patternfly-4/react-core/src/declarations.d.ts
  packages/patternfly-4/react-docs/src/components/componentDocs/propsTable.js
  packages/patternfly-4/react-docs/src/templates/mdxTemplate.js
  packages/patternfly-4/react-integration/cypress/integration/alert.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
Labels: PF4, TypeScript, chore :house:

#1942 feat(Modal): Convert Modal component to typescript
  packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.md
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.test.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.test.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.test.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.test.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBox.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxBody.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxFooter.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/index.d.ts
  packages/patternfly-4/react-core/src/components/Modal/index.js
  packages/patternfly-4/react-core/src/components/Modal/index.ts
  packages/patternfly-4/react-core/src/declarations.d.ts
  packages/patternfly-4/react-integration/cypress/integration/modal.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#1945 feat(Radio): Convert radio to TypeScript
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.md
  packages/patternfly-4/react-core/src/components/Radio/Radio.test.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
  packages/patternfly-4/react-core/src/components/Radio/index.d.ts
  packages/patternfly-4/react-core/src/components/Radio/index.js
  packages/patternfly-4/react-core/src/components/Radio/index.ts
  packages/patternfly-4/react-integration/cypress/integration/radio.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/RadioDemo/RadioDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2025 fix(Dropdown): handle on enter focusing when options are disabled
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
Labels: PF4

#2001 React-wooden-tree major version update and update the example accordingly
  packages/patternfly-3/patternfly-react-wooden-tree/package.json
  packages/patternfly-3/patternfly-react-wooden-tree/src/components/TreeView/TreeViewExample.js
  packages/patternfly-3/patternfly-react-wooden-tree/src/components/TreeView/index.js
  yarn.lock
Labels: PF3

#1946 feat(List): Convert list to TypeScript
  packages/patternfly-4/react-core/src/components/List/List.d.ts
  packages/patternfly-4/react-core/src/components/List/List.js
  packages/patternfly-4/react-core/src/components/List/List.md
  packages/patternfly-4/react-core/src/components/List/List.test.js
  packages/patternfly-4/react-core/src/components/List/List.tsx
  packages/patternfly-4/react-core/src/components/List/ListItem.d.ts
  packages/patternfly-4/react-core/src/components/List/ListItem.js
  packages/patternfly-4/react-core/src/components/List/ListItem.tsx
  packages/patternfly-4/react-core/src/components/List/__snapshots__/List.test.js.snap
  packages/patternfly-4/react-core/src/components/List/index.d.ts
  packages/patternfly-4/react-core/src/components/List/index.js
  packages/patternfly-4/react-core/src/components/List/index.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.test.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/list.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ListDemo/ListDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#1885 feat(card): Converted card component to typescript
  packages/patternfly-4/react-core/src/components/Card/Card.d.ts
  packages/patternfly-4/react-core/src/components/Card/Card.js
  packages/patternfly-4/react-core/src/components/Card/Card.md
  packages/patternfly-4/react-core/src/components/Card/Card.test.tsx
  packages/patternfly-4/react-core/src/components/Card/Card.tsx
  packages/patternfly-4/react-core/src/components/Card/CardBody.d.ts
  packages/patternfly-4/react-core/src/components/Card/CardBody.js
  packages/patternfly-4/react-core/src/components/Card/CardBody.test.tsx
  packages/patternfly-4/react-core/src/components/Card/CardBody.tsx
  packages/patternfly-4/react-core/src/components/Card/CardFooter.d.ts
  packages/patternfly-4/react-core/src/components/Card/CardFooter.js
  packages/patternfly-4/react-core/src/components/Card/CardFooter.test.tsx
  packages/patternfly-4/react-core/src/components/Card/CardFooter.tsx
  packages/patternfly-4/react-core/src/components/Card/CardHeader.d.ts
  packages/patternfly-4/react-core/src/components/Card/CardHeader.js
  packages/patternfly-4/react-core/src/components/Card/CardHeader.test.tsx
  packages/patternfly-4/react-core/src/components/Card/CardHeader.tsx
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardBody.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardFooter.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Card/index.d.ts
  packages/patternfly-4/react-core/src/components/Card/index.js
  packages/patternfly-4/react-core/src/components/Card/index.ts
  packages/patternfly-4/react-integration/cypress/integration/card.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#1723 feat(Breadcrumb): Convert Breadcrumb jsx file to tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.md
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.test.tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.test.tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.test.tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbHeading.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbItem.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Breadcrumb/index.d.ts
  packages/patternfly-4/react-core/src/components/Breadcrumb/index.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/index.ts
  packages/patternfly-4/react-core/src/components/Page/Page.test.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-integration/README.md
  packages/patternfly-4/react-integration/cypress/integration/breadcrumb.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/BreadcrumbDemo/BreadcrumbDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#1993 fix(wizard): wizards props extends div element props
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
Labels: PF4, bug :bug:

#1933 feat(form): Converted form component to typescript
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.d.ts
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.test.tsx
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.tsx
  packages/patternfly-4/react-core/src/components/Form/Form.d.ts
  packages/patternfly-4/react-core/src/components/Form/Form.md
  packages/patternfly-4/react-core/src/components/Form/Form.test.tsx
  packages/patternfly-4/react-core/src/components/Form/Form.tsx
  packages/patternfly-4/react-core/src/components/Form/FormContext.tsx
  packages/patternfly-4/react-core/src/components/Form/FormGroup.d.ts
  packages/patternfly-4/react-core/src/components/Form/FormGroup.test.tsx
  packages/patternfly-4/react-core/src/components/Form/FormGroup.tsx
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.d.ts
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.js
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.test.tsx
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.tsx
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormHelperText.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Form/index.d.ts
  packages/patternfly-4/react-core/src/components/Form/index.js
  packages/patternfly-4/react-core/src/components/Form/index.ts
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/form.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2042 fix(Select): account for direct JSX children
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
Labels: PF4

#1968 feat(ts): convert aboutmodal to TS
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.md
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBox.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxBrand.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.test.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBox.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxBrand.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHero.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalContainer.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AboutModal/index.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/index.js
  packages/patternfly-4/react-core/src/components/AboutModal/index.ts
  packages/patternfly-4/react-integration/cypress/integration/aboutmodal.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AboutModal/AboutModalDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AboutModal/brandImg.svg
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2027 fix(alert): add interactive alert integration test
  packages/patternfly-4/react-core/src/components/Alert/Alert.md
  packages/patternfly-4/react-integration/cypress/integration/alert.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
Labels: PF4, chore :house:, integration tests

#2049 feat(Checkbox): Add checkbox demo with tests
  packages/patternfly-4/react-integration/cypress/integration/checkbox.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CheckboxDemo/CheckboxDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, chore :house:, integration tests

#2005 feat(Nav): Convert Nav component to typescript, add Demos
  packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
  packages/patternfly-4/react-core/src/components/Nav/Nav.js
  packages/patternfly-4/react-core/src/components/Nav/Nav.md
  packages/patternfly-4/react-core/src/components/Nav/Nav.test.tsx
  packages/patternfly-4/react-core/src/components/Nav/Nav.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.js
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavItem.js
  packages/patternfly-4/react-core/src/components/Nav/NavItem.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavItemSeparator.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavItemSeparator.js
  packages/patternfly-4/react-core/src/components/Nav/NavItemSeparator.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavList.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavList.js
  packages/patternfly-4/react-core/src/components/Nav/NavList.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
  packages/patternfly-4/react-core/src/components/Nav/NavVariants.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavVariants.js
  packages/patternfly-4/react-core/src/components/Nav/NavVariants.tsx
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Nav/index.d.ts
  packages/patternfly-4/react-core/src/components/Nav/index.js
  packages/patternfly-4/react-core/src/components/Nav/index.ts
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutManualNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
  packages/patternfly-4/react-integration/cypress/integration/nav.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
Labels: PF4, TypeScript, chore :house:

#1973 feat(page): add fill and no-fill modifiers to page sections
  packages/patternfly-4/react-core/src/components/Page/Page.md
  packages/patternfly-4/react-core/src/components/Page/PageSection.d.ts
  packages/patternfly-4/react-core/src/components/Page/PageSection.js
  packages/patternfly-4/react-core/src/components/Page/PageSection.test.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageSection.test.js.snap
Labels: PF4, css review, enhancement :rocket:

#2060 Tabs: fix scrollable tabs
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
Labels: PF4, bug :bug:

#2071 PF4 Nav: make horizontal nav scrollable
  packages/patternfly-4/react-core/src/components/Nav/Nav.md
  packages/patternfly-4/react-core/src/components/Nav/Nav.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavList.tsx
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Page/PageHeader.js
Labels: PF4, enhancement :rocket:

#2032 Convert Popover to Typescript
  packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts
  packages/patternfly-4/react-core/src/components/Popover/Popover.md
  packages/patternfly-4/react-core/src/components/Popover/Popover.test.tsx
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx.txt
  packages/patternfly-4/react-core/src/components/Popover/PopoverArrow.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverArrow.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverBody.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverBody.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverBody.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverContent.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverContent.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverDialog.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverFooter.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverFooter.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.tsx
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Popover/index.d.ts
  packages/patternfly-4/react-core/src/components/Popover/index.js
  packages/patternfly-4/react-core/src/components/Popover/index.ts
  packages/patternfly-4/react-core/src/components/Tooltip/styles.tsx
  packages/patternfly-4/react-integration/cypress/integration/popover.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
Labels: PF4, TypeScript, chore :house:

#2097 fix(index.js): [PF3] Export BreadcrumbSwitcher from patternfly-react index
  packages/patternfly-3/patternfly-react/src/index.js
Labels: PF3, chore :house:

#2107 fix(Select): update SelectProps interface, clean up demos
  packages/patternfly-4/react-core/src/components/Popover/Popover.md
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.md
  packages/patternfly-4/react-core/src/demos/ToolbarDemo.md
Labels: PF4

#2113 fix(popover): make PopoverPosition an enum
  packages/patternfly-4/react-core/src/components/Popover/Popover.md
  packages/patternfly-4/react-core/src/components/Popover/Popover.test.tsx
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
Labels: PF4

#2002 feat(OptionsMenu): Options Menu Component Typescript Conversion
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.md
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.test.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItemGroup.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItemGroup.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItemGroup.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuSeparator.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuSeparator.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuSeparator.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-core/src/components/OptionsMenu/index.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/index.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/index.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/optionsMenuConstants.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/optionsMenuConstants.js
  packages/patternfly-4/react-docs/src/components/componentDocs/live-edit.scss
  packages/patternfly-4/react-integration/cypress/integration/optionsmenu.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/OptionsMenuDemo/OptionsMenuDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript

#1875 feat(component): Add Time Picker component
  packages/patternfly-3/patternfly-react/less/date-time-picker.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_date-time-picker.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateTimePicker.stories.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/PickTimeClock.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/PickTimeClock.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/PickTimeTable.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/PickTimeTable.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/TimeConstants.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/TimeInput.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/TimeInput.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/__snapshots__/PickTimeClock.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/__snapshots__/PickTimeTable.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeComponents/__snapshots__/TimeInput.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeHelpers.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeHelpers.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimePicker.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimePicker.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__snapshots__/TimePicker.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/index.js
Labels: PF3, enhancement :rocket:, ux approved

#1905 Classification banner component
  packages/patternfly-3/patternfly-react/less/classification-banner.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_classification-banner.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-3/patternfly-react/src/components/ClassificationBanner/ClassificationBanner.js
  packages/patternfly-3/patternfly-react/src/components/ClassificationBanner/ClassificationBanner.stories.js
  packages/patternfly-3/patternfly-react/src/components/ClassificationBanner/ClassificationBanner.test.js
  packages/patternfly-3/patternfly-react/src/components/ClassificationBanner/__snapshots__/ClassificationBanner.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/ClassificationBanner/index.js
  packages/patternfly-3/patternfly-react/src/index.js
Labels: PF3, css approved
