Repository patternfly/patternfly-react, pull requests merged in 2019-02, with the labels that each got.

#1304 Update react to pf-next 167
  package-lock.json
  package.json
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/build/copyStyles.js
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/DataList/DataList.js
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
  packages/patternfly-4/react-core/src/components/DataList/DataListCell.js
  packages/patternfly-4/react-core/src/components/DataList/DataListCheck.js
  packages/patternfly-4/react-core/src/components/DataList/DataListContent.js
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.js
  packages/patternfly-4/react-core/src/components/DataList/DataListToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/LoginFooterItem.js
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginFooterItem.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainBody.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainFooter.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxBody.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxFooter.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
  packages/patternfly-4/react-core/src/components/Text/__snapshots__/Text.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.js
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-table/src/components/Table/ExpandableRowContent.js
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.js
  packages/patternfly-4/react-table/src/components/Table/SelectColumn.js
  packages/patternfly-4/react-table/src/components/Table/SortColumn.d.ts
  packages/patternfly-4/react-table/src/components/Table/SortColumn.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: enhancement :rocket:

#1281 Fix react-table not expose index.d.ts issue
  packages/patternfly-4/react-table/src/components/index.d.ts
  packages/patternfly-4/react-table/src/index.d.ts
Labels: PF4, bug :bug:

#1307 refactor(AboutModal): Upgrade core to 1.0.175 and Refactor AboutModal
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.test.js
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHero.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalContainer.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/examples/SimpleAboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/examples/pfbg_992.jpg
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:

#1314 fix(Table): Use direct imports for styles
  packages/patternfly-4/react-table/src/components/Table/ExpandableRowContent.js
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.js
  packages/patternfly-4/react-table/src/components/Table/SortColumn.js
  packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
Labels: PF4, bug :bug:

#1244 fix(PF4): tooltip/popover - include tippy css
  package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts
  packages/patternfly-4/react-core/src/components/Popover/Popover.js
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.js.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
  packages/patternfly-4/react-core/src/components/Tooltip/styles.js
  packages/patternfly-4/react-integration/README.md
  packages/patternfly-4/react-integration/demo-app-ts/package.json
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/package-lock.json
  yarn.lock
Labels: PF4, bug :bug:

#1276 chore(react-styled-system, react-table): Replace SFC syntax with FunctionComponent
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledBox.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledFlex.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledText.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.d.ts
  packages/patternfly-4/react-table/src/components/Table/Body.d.ts
  packages/patternfly-4/react-table/src/components/Table/Header.d.ts
  packages/patternfly-4/react-table/src/components/Table/SortColumn.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
Labels: PF4, enhancement :rocket:

#1205 feat(Tooltip): Add optional delay prop to Tooltip
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
Labels: PF4, enhancement :rocket:

#1320 fix(Alert): Fix index.d.ts file
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js
  packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.js
  packages/patternfly-4/react-core/src/components/Alert/index.d.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, bug :bug:

#1322 chore(prerelease): move all pf4 packages to prerelease channel
  .public/index.html
  package-lock.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-integration/package.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styles/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
Labels: PF4

#1232 fix(utils): export common utility functions and constants in react-core
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.js
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.js
  packages/patternfly-4/react-core/src/components/Button/Button.js
  packages/patternfly-4/react-core/src/components/Card/Card.js
  packages/patternfly-4/react-core/src/components/Card/CardBody.js
  packages/patternfly-4/react-core/src/components/Card/CardFooter.js
  packages/patternfly-4/react-core/src/components/Card/CardHeader.js
  packages/patternfly-4/react-core/src/components/Chip/Chip.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/Item.js
  packages/patternfly-4/react-core/src/components/Dropdown/Separator.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Form/FormGroup.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.js
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.js
  packages/patternfly-4/react-core/src/components/Page/Page.js
  packages/patternfly-4/react-core/src/components/Popover/Popover.js
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx.txt
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/components/Switch/Switch.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
  packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.d.ts
  packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.js
  packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.test.js
  packages/patternfly-4/react-core/src/helpers/GenerateId/__snapshots__/GenerateId.test.js.snap
  packages/patternfly-4/react-core/src/helpers/componentShape.js
  packages/patternfly-4/react-core/src/helpers/constants.ts
  packages/patternfly-4/react-core/src/helpers/htmlConstants.ts
  packages/patternfly-4/react-core/src/helpers/index.ts
  packages/patternfly-4/react-core/src/helpers/safeHTMLElement.js
  packages/patternfly-4/react-core/src/helpers/util.test.js
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-core/src/index.ts
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.js
  packages/patternfly-4/react-core/src/layouts/Split/Split.js
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.js
Labels: PF4, enhancement :rocket:

#1328 fix(Radio): Use pf-c-radio class in Radio
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
Labels: PF4, bug :bug:

#1316 fix(Nav): do not render the examples page
  packages/patternfly-4/react-core/src/components/Nav/examples/NavDefaultList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavGroupedList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavHorizontalList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavMixedList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavTertiaryList.js
Labels: PF4, bug :bug:

#1341 fix(types): popover, tooltip, and helper types fixes
  packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.d.ts
Labels: PF4, bug :bug:

#1326 fix(Alert): Make Alert title required
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.js
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
Labels: PF4, enhancement :rocket:

#1252 fix: Add consistent aria labels for <nav> elements
  packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.js
  packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
  packages/patternfly-4/react-core/src/components/Nav/Nav.js
  packages/patternfly-4/react-core/src/components/Nav/Nav.test.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/examples/NavDefaultList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavGroupedList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavHorizontalList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavMixedList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavTertiaryList.js
  packages/patternfly-4/react-core/src/components/Page/PageHeader.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageHeader.test.js.snap
Labels: PF4, accessibility, bug :bug:

#1298 fix(Alert): Make Alert consistent with core
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/examples/DangerAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/InfoAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/SuccessAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/WarningAlert.js
Labels: PF4, accessibility, bug :bug:

#1324 fix(Table): allow colspan to be set in props for each cell
  packages/patternfly-4/react-table/README.md
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/BodyCell.js
  packages/patternfly-4/react-table/src/components/Table/HeaderCell.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/examples/SimpleTable.js
  packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
Labels: PF4, enhancement :rocket:

#1331 fix(ListViewItem) - initExpanded being passed to children
  packages/patternfly-3/patternfly-react/src/components/ListView/ListViewItem.js
Labels: bug :bug:

#1345 fix(nav): Allow nav to expand by prop change
  packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
Labels: PF4, bug :bug:

#1354 chore: Upgrade to PatternFly core 1.0.184
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxBody.test.js.snap
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, chore :house:

#1282 fix(Table): Allow mixins of object, strings and numbers as row cell
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.js
Labels: PF4, bug :bug:

#1313 fix(Table): Update table styles based on new styling from pf-next v 175
  packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js
  packages/patternfly-4/react-table/src/components/Table/CollapseColumn.js
  packages/patternfly-4/react-table/src/components/Table/SortColumn.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/examples/CollapsibleTable.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.test.js
Labels: PF4, bug :bug:, css review

#1245 feat(chipGroup): Add Chip Group component to pf4
  packages/patternfly-4/react-core/src/components/Chip/Chip.docs.js
  packages/patternfly-4/react-core/src/components/Chip/examples/SimpleChip.js
  packages/patternfly-4/react-core/src/components/Chip/index.d.ts
  packages/patternfly-4/react-core/src/components/Chip/index.js
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.js
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.test.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipButton.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipButton.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.docs.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.test.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.js
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/Chip.test.js.snap
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/ChipGroup/examples/BadgeChip.js
  packages/patternfly-4/react-core/src/components/ChipGroup/examples/MultiSelectChipGroup.js
  packages/patternfly-4/react-core/src/components/ChipGroup/examples/ToolbarChipGroup.js
  packages/patternfly-4/react-core/src/components/ChipGroup/index.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/index.js
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-core/src/tsconfig.dts.json
  packages/patternfly-4/react-core/tsconfig.json
  tsconfig.json
Labels: PF4, css review, ux review

#1319 fix(Login): update component to match pf4 design changes
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.d.ts
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.js
  packages/patternfly-4/react-core/src/components/Form/FormHelperText.test.js
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormHelperText.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/index.d.ts
  packages/patternfly-4/react-core/src/components/Form/index.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooter.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooter.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterBandItem.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterBandItem.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterBandItem.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainFooterBandItem.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainFooterLinksItem.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
  packages/patternfly-4/react-core/src/components/LoginPage/index.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/index.js
Labels: PF4, css review, enhancement :rocket:, ux review

#1279 fix(LoginPage): Remove Language Selector from LoginPage
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.test.js
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
Labels: PF4, bug :bug:

#1359 refactor(ApplicationLauncher): Refactor so it no longer uses Dropdown
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.d.ts
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherMenu.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/Toggle.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/applicationLauncherConstants.d.ts
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/applicationLauncherConstants.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/SimpleApplicationLauncher.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/TooltipApplicationLauncher.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/Item.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
Labels: PF4, enhancement :rocket:

#1380 fix(core): FormSelect onChange value type was missing
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.d.ts
Labels: PF4, bug :bug:

#1330 fix(tokens): Use only light theme variables
  packages/patternfly-4/react-tokens/build/generateTokens.js
Labels: PF4, bug :bug:

#1382 refactor(Dropdown and ApplicationLauncher): Refactor keyHandler usage
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherMenu.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/helpers/constants.ts
  packages/patternfly-4/react-core/src/helpers/util.test.js
  packages/patternfly-4/react-core/src/helpers/util.ts
Labels: PF4, enhancement :rocket:

#1388 Faster CI
  .circleci/clean_cache.sh
  .circleci/config.yml
  .circleci/release.sh
  .circleci/upload_preview.sh
  .travis.yml
  .travis/after_success.sh
  .travis/before_install.sh
  .travis/deploy_pr.sh
  .travis/release.sh
  lerna.json
  now.json
  package.json
  packages/patternfly-3/package.json
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react/package.json
  packages/patternfly-3/react-console/package.json
  packages/patternfly-4/package.json
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styles/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: infrastructure

#1396 fix(build): fix lerna on master
  .circleci/config.yml
  .circleci/release.sh
  .travis.yml
Labels: bug :bug:, infrastructure

#1404 fix: additional boolean check in Grid layout
  package.json
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.js
Labels: PF4, bug :bug:

#1335 feat(Progress): add single line progress handling and example
  packages/patternfly-4/react-core/src/components/Progress/Progress.docs.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/examples/SingleLineProgress.js
Labels: PF4, css review, enhancement :rocket:

#1406 fix(Table): Pass calculated rows to body wrapper to eliminate re-renders
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
Labels: PF4, bug :bug:

#1373 fix(login): Add union types for backgroundImgSrc
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
Labels: PF4, bug :bug:

#1405 chore(clean build): Remove some unused dependencies
  package.json
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-charts/scripts/copyTS.js
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/scripts/copyTS.js
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styled-system/scripts/copyTS.js
  packages/patternfly-4/react-styles/package.json
  packages/patternfly-4/react-styles/scripts/copyTS.js
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-table/scripts/copyTS.js
  packages/react-icons/package.json
  packages/react-icons/scripts/copyTS.js
Labels: chore :house:, infrastructure

#1398 fix(Table): Fix grid breakpoints for table
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  yarn.lock
Labels: PF4, bug :bug:

#1415 build(flakes): fix some flaky build steps
  .circleci/config.yml
  .travis.yml
Labels: bug :bug:, infrastructure

#1410 refactor(datalist,table): use regular input checkbox
  packages/patternfly-4/react-core/src/components/DataList/DataListCheck.js
  packages/patternfly-4/react-table/src/components/Table/SelectColumn.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
Labels: PF4, enhancement :rocket:

#1312 Added browser tests after deploy
  .circleci/trigger_browser_tests.sh
  .travis.yml
  README.md
Labels: infrastructure

#1277 Single select
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Select/Select.docs.js
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/Select.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOption.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.test.js
  packages/patternfly-4/react-core/src/components/Select/SingleSelect.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/examples/SingleSelectInput.js
  packages/patternfly-4/react-core/src/components/Select/index.d.ts
  packages/patternfly-4/react-core/src/components/Select/index.js
  packages/patternfly-4/react-core/src/components/Select/selectConstants.js
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, accessibility, css review, enhancement :rocket:, ux review

#1309 PF4 Charts: Add ChartAxis for custom tic labels
  packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.d.ts
  packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.js
  packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.test.js
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.js.snap
  packages/patternfly-4/react-charts/src/components/ChartAxis/index.d.ts
  packages/patternfly-4/react-charts/src/components/ChartAxis/index.js
  packages/patternfly-4/react-charts/src/components/LineChart/examples/SimpleChart.js
  packages/patternfly-4/react-charts/src/components/index.d.ts
  packages/patternfly-4/react-charts/src/components/index.js
Labels: PF4, enhancement :rocket:, ux review

#1372 fix(modalbox): add the small modifier to modalbox
  packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
  packages/patternfly-4/react-core/src/components/Modal/Modal.docs.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/examples/SmallModal.js
  packages/patternfly-4/react-core/src/components/Modal/examples/WidthModal.js
Labels: PF4, enhancement :rocket:

#1419 fix(Table): Disable row click when clicked on select or button
  packages/patternfly-4/react-table/src/components/Table/Body.js
Labels: PF4, enhancement :rocket:

#1379 refactor(form): use form actions instead of toolbar
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.js
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js
Labels: PF4, css review, enhancement :rocket:

#1347 fix(DataList): Add aria-label and aria-labelledby improvements
  packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
  packages/patternfly-4/react-core/src/components/DataList/DataListCell.js
  packages/patternfly-4/react-core/src/components/DataList/DataListContent.js
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.js
  packages/patternfly-4/react-core/src/components/DataList/DataListToggle.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListToggle.js
  packages/patternfly-4/react-core/src/components/DataList/examples/ExpandableDataList.js
  packages/patternfly-4/react-core/src/components/DataList/examples/ModifiersDataList.js
Labels: PF4, accessibility

#1470 fix(Select): fix typescript def for SelectProps and SelectOptionProps
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
Labels: PF4, bug :bug:
