Repository patternfly/patternfly-react, pull requests merged in 2019-09, with the labels that each got.

#2802 appendTo prop
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
Labels: PF4, enhancement :rocket:

#2834 Fix(badges): Add badges back
  README.md
Labels: PF4, documentation :memo:

#2830 feat(Wizard): add support for in page rendering
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx
Labels: PF4, css review, enhancement :rocket:, ux approved

#2835 feat(Modal): add modifier to left align Modal footer
  packages/patternfly-4/react-core/src/components/Modal/Modal.md
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.tsx.snap
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
Labels: PF4, css review, enhancement :rocket:, ux review

#1873 feat(component): Add Date Picker component
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DateConstants.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DateInput.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DateInput.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/Day.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/Day.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DecadeView.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DecadeView.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DecadeViewHeader.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/DecadeViewTable.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/Header.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/Header.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/MonthView.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/MonthView.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/TodayButton.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/TodayButton.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/YearView.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/YearView.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/DateInput.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/Day.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/DecadeView.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/Header.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/MonthView.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/TodayButton.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/YearView.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/helpers.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/helpers.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateHelpers.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DatePicker.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DatePicker.stories.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimePicker.stories.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__tests__/DateHelpers.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__tests__/DatePicker.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__tests__/TimeHelpers.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__tests__/TimePicker.test.js
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/__tests__/__snapshots__/TimePicker.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/index.js
Labels: PF3, enhancement :rocket:

#2870 Modal optin text
  packages/patternfly-4/react-core/src/components/Modal/Modal.md
Labels: PF4, documentation :memo:

#2749 fix(switch): use defaultChecked instead of checked
  packages/patternfly-4/react-core/src/components/DataList/DataListCheck.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Switch/Switch.test.tsx
  packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
  packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.tsx.snap
Labels: Do Not Merge, PF4

#2820 feat(Select): add creatable and new features
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, ux approved

#2713 feat(accordion): add content and toggle container props
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.tsx
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContext.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx
Labels: PF4, css review

#2681 feat(tab): support JSX elements in Tab title
  packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
Labels: PF4, enhancement :rocket:

#2825 fix(HorizontalNavMenuItem): Allow HorizontalNavMenuItem's title to be a node
  packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNavMenuItem.js
Labels: PF3, bug :bug:

#2861 feat(DataToolbar): Add Data Toolbar component to experimental
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/index.ts
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-docs/gatsby-browser.js
Labels: css review, enhancement :rocket:, ux approved

#2887 Add line border to ChartArea and move sparkline
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeErrorMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeWarningMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimaryDotMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimarySegmentedMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletQualitativeRange.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartScatter/__snapshots__/ChartScatter.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md
  packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.scss
Labels: ux approved

#2891 Add stacked area chart example
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/chart-stack.scss
Labels: ux approved

#2685 chore(react-integration): add tables to demos and write unit tests
  packages/patternfly-4/react-integration/cypress/integration/tableactions.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablebreakpointmodifiers.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablecollapsible.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablecompact.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablecompactborderlessrows.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablecompactexpandable.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablecompoundexpandable.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablefirstcellasheader.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tableheaderswrappable.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tableselectable.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablesimple.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablesimpleactions.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablesortable.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tablewidthmodifiers.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableActionsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableBreakpointModifiersDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCollapsibleDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompactBorderlessRowsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompactDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompactExpandableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompoundExpandableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableFirstCellAsHeaderDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableHeadersWrappableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSelectableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleActionsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableForCompoundExpandableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableWidthModifiersDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/patternfly-4/react-integration/webpack.config.js
  packages/patternfly-4/react-table/src/components/Table/BodyWrapper.tsx
  packages/patternfly-4/react-table/src/components/Table/Table.tsx
  packages/patternfly-4/react-table/src/components/Table/base/body-row.tsx
  packages/patternfly-4/react-virtualized-extension/src/declarations.d.ts
  packages/patternfly-4/tsconfig.base.json
Labels: PF4, chore :house:

#2878 fix(chipGroup): Allow variable number of chips to be displayed
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.test.tsx
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.tsx
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: ux approved

#2882 fix(chipgroup): allow chipgroup toolbar item to handle single chip
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.tsx
Labels: PF4, bug :bug:

#2682 fix(LoginPage): Add attributes to the submit button
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSubmitButton.js
Labels: PF3

#2940 Broken link for donut chart tutorial
  packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
Labels: documentation :memo:

#2923 fix(copyclipboard): add prop for expanded by default
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
  packages/patternfly-4/react-integration/cypress/integration/clipboardcopyexpanded.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ClipboardCopyDemo/ClipboardCopyExpandedDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: enhancement :rocket:

#2683 fix(button): set the disable modifier when component is not button
  packages/patternfly-4/react-core/src/components/Button/Button.tsx
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: PF4, bug :bug:, css review

#2862 refactor(Modal): Simplify disabling of FocusTrap
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
Labels: PF4, css review

#2962 chore(charts): update chart tutorial paths
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
  packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md
Labels: PF4, chore :house:

#2967 fix(react-table): fix cell title warning
  packages/patternfly-4/react-table/src/components/Table/Table.tsx
Labels: PF4, enhancement :rocket:

#2796 area chart - horizontal indicator example
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
  packages/patternfly-4/react-charts/src/components/ChartTheme/ChartTheme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/threshold-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.test.tsx
  packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.tsx
  packages/patternfly-4/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartThreshold/index.ts
  packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts
  packages/patternfly-4/react-charts/src/components/index.ts
Labels: PF4, documentation :memo:, ux review

#2842 fix(Dropdown split button): Add 3rd state to split button
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.test.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap
Labels: PF4, css review, enhancement :rocket:, ux approved

#2902 feat(Tab): Added two new props: mountOnEnter and unmountOnExit
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/tabdemo.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
Labels: PF4, enhancement :rocket:

#2943 Missing key prop warning for ChartPie based components
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/ChartArea/ChartArea.tsx
  packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.tsx
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/ChartBar.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBullet.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimaryDotMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimarySegmentedMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletQualitativeRange.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimaryDotMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimarySegmentedMeasure.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletQualitativeRange.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartContainer/ChartContainer.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.tsx
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.tsx
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegendWrapper.tsx
  packages/patternfly-4/react-charts/src/components/ChartLine/ChartLine.tsx
  packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartScatter/ChartScatter.tsx
  packages/patternfly-4/react-charts/src/components/ChartScatter/__snapshots__/ChartScatter.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.tsx
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartUtils/chart-helpers.ts
  packages/patternfly-4/react-charts/src/components/ChartUtils/index.ts
Labels: PF4, bug :bug:

#2984 fix(HorizontalNavMenuItem): Fix onItemClick PropType.
  packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNavMenuItem.js
Labels: bug :bug:

#2895 chore(deps): bump PF3 deps
  jest.config.js
  jest.env.js
  package.json
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react-wooden-tree/package.json
  packages/patternfly-3/patternfly-react/package.json
  packages/patternfly-3/patternfly-react/src/components/VerticalNav/__snapshots__/VerticalNav.test.js.snap
  packages/patternfly-3/react-console/package.json
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.tsx
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.tsx.snap
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-inline-edit-extension/package.json
  packages/patternfly-4/react-integration/demo-app-ts/package.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-topology/package.json
  packages/patternfly-4/react-virtualized-extension/package.json
  storybook/.babelrc
  storybook/babel.config.js
  storybook/openBrowser.js
  storybook/webpack.config.js
  test.env.js
  yarn.lock
Labels: chore :house:

#2979 docs(modal): change the cancel button variant to link
  packages/patternfly-4/react-core/src/components/Modal/Modal.md
Labels: bug :bug:, ux approved

#2993 fix(Select): Add props for hard coded strings
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, bug :bug:

#2983 feat(Button): add control variant to button
  packages/patternfly-4/react-core/src/components/Button/Button.md
  packages/patternfly-4/react-core/src/components/Button/Button.tsx
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.tsx
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.tsx.snap
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.md
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/InputGroupDemo/InputGroupDemo.tsx
Labels: css review

#2946 feat(Select): add max height property, update tests
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, enhancement :rocket:

#2985 feat(Flex): Added support for flex layout, tests, etc.
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/helpers/util.test.js
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-core/src/layouts/Flex/Flex.test.tsx
  packages/patternfly-4/react-core/src/layouts/Flex/Flex.tsx
  packages/patternfly-4/react-core/src/layouts/Flex/FlexItem.tsx
  packages/patternfly-4/react-core/src/layouts/Flex/FlexUtils.tsx
  packages/patternfly-4/react-core/src/layouts/Flex/__snapshots__/Flex.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Flex/examples/Flex.md
  packages/patternfly-4/react-core/src/layouts/Flex/examples/flex.scss
  packages/patternfly-4/react-core/src/layouts/Flex/index.ts
  packages/patternfly-4/react-core/src/layouts/index.d.ts
  packages/patternfly-4/react-core/src/layouts/index.js
  packages/patternfly-4/react-integration/cypress/integration/flex.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FlexDemo/FlexDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, css review, feature, ux approved

#2998 feat(Pagination): add compact variation flag
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.md
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
Labels: PF4, css review, enhancement :rocket:, ux review

#2957 feat(emptyState): Support primary and icon as div elements
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.md
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.tsx
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.tsx
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStatePrimary.tsx
  packages/patternfly-4/react-core/src/components/EmptyState/index.ts
Labels: PF4, css review, enhancement :rocket:, ux approved

#2981 fix(copytoclipboard): wrap content in pre tag
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx
Labels: css review

#3011 make dropdown/app launcher work better with router components
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.md
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherContent.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherIcon.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherItem.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherText.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/index.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
Labels: PF4, enhancement :rocket:

#2904 fix(Pagination): Styling discrepancy with HTML version
  packages/patternfly-4/react-core/src/components/Dropdown/index.ts
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/patternfly-4/react-core/src/components/Pagination/ToggleTemplate.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: css review, ux approved

#3012 fix(DataToolbar): add aria-haspopup to the toggle group
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
Labels: PF4, accessibility, bug :bug:

#2948 Overflowmenu
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenu.md
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenu.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenu.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuContext.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuControl.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuControl.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuDropdownItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuGroup.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuItem.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenuControl.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenuGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenuItem.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/index.ts
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-docs/.eslintrc.js
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-integration/cypress/integration/overflowmenu.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/OverflowMenuDemo/OverflowMenuDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, css review, enhancement :rocket:, ux approved

#2969 feat(DataToolbar): add Chip groups to DataToolbar
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/index.ts
  packages/patternfly-4/react-docs/gatsby-browser.js
Labels: accessibility, css review, enhancement :rocket:, ux approved

#3031 fix(Tabs): Fix the regression in the Tab class with the title prop
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: PF4, bug :bug:
