Repository patternfly/patternfly-react, pull requests merged in 2019-08, with the labels that each got.

#2635 fix(Topology): Fix paddings for topology control bar buttons
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/css/topology-controlbar-css.ts
Labels: PF4, ux approved

#2621 fix(Select): Prevent select from submitting forms
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/form.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: PF4, bug :bug:, css review

#2468 feat(switch): add aria-labelledby to input
  packages/patternfly-4/react-core/src/components/Switch/Switch.md
  packages/patternfly-4/react-core/src/components/Switch/Switch.test.js
  packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
  packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap
Labels: PF4, accessibility

#2639 fix(Pagination): Fix pagination to update page count
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
Labels: PF4

#2648 feat(Alert): Add the default alert variant
  packages/patternfly-4/react-core/src/components/Alert/Alert.md
  packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
  packages/patternfly-4/react-core/src/components/Alert/AlertIcon.tsx
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/alert.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
Labels: PF4, css review, enhancement :rocket:, ux approved

#2637 docs(extensions): add extension notes to Gatsby docs
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/InlineEdit.md
  packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.md
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/Virtualized.md
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md
Labels: PF4, documentation :memo:

#2664 refactor(Page): Change the defaultManagedSidebarOpen prop name for co…
  packages/patternfly-4/react-core/src/components/Page/Page.tsx
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageManagedSidebarClosedDemo.tsx
Labels: PF4

#2647 fix(select): disable focus trap on checkbox select with no children
  packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
Labels: PF4, bug :bug:

#2612 feat(Select): Adds the ability to pass in a user defined object
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/selectConstants.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/common/State.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, current sprint, enhancement :rocket:

#2663 fix(Checkbox): Updated ids so none repeat
  packages/patternfly-4/react-core/src/components/Checkbox/examples/Checkbox.md
Labels: PF4, bug :bug:

#1402 feat(VncConsole): More possibilities to customize component
  packages/patternfly-3/react-console/src/VncConsole/VncActions.js
  packages/patternfly-3/react-console/src/VncConsole/VncActions.test.js
  packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
  packages/patternfly-3/react-console/src/VncConsole/__snapshots__/VncActions.test.js.snap
Labels: PF3

#2586 feat(Pagination): add disabled flag for whole component
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.md
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/pagination.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#2634 fix(docs): Fix a11y issues in Documentation
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.md
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyToggle.tsx
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyToggle.test.tsx.snap
  packages/patternfly-4/react-core/src/components/DataList/DataList.md
Labels: accessibility

#2633 feat(drawer): Added the drawer component to experimental
  packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.md
  packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.tsx
  packages/patternfly-4/react-core/src/experimental/components/Drawer/DrawerPanelContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/Drawer/index.ts
  packages/patternfly-4/react-core/src/experimental/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-docs/.eslintrc.js
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-integration/cypress/integration/drawer.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, css review, current sprint

#2678 feat(Select): add disabled flag for component
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, enhancement :rocket:

#2628 feat(ExpandCollapse): Add onToggle callback
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.js
  packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.test.js
Labels: PF3, enhancement :rocket:

#2686 chore(Release Notes): update release notes for 2019.06
  RELEASE-NOTES.md
Labels: chore :house:

#2695 chore(dropdown): exclude checked from props, fix duplicate key error
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
Labels: PF4, TypeScript

#2690 fix(Dropdown): Spread props to Dropdown toggle to fix regression
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: PF4, accessibility, bug :bug:

#2670 fullscreen examples should have 100% height
  packages/patternfly-4/react-core/src/demos/PageLayout/PageLayout.md
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-docs/src/components/LinkPreview.js
  packages/patternfly-4/react-docs/src/components/componentDocs/liveEdit.js
  packages/patternfly-4/react-docs/src/components/mdx-renderer.js
  packages/patternfly-4/react-docs/src/styles/text.css
  packages/patternfly-4/react-docs/src/styles/workspace.css
  packages/patternfly-4/react-docs/src/templates/mdxTemplate.js
Labels: PF4, documentation :memo:

#2611 feat(Select): adds direction prop to Select
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/selectConstants.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#2645 fix(formselect): adds isRequired prop
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/__snapshots__/FormSelect.test.tsx.snap
Labels: PF4, accessibility

#2649 feat(Expandable): Support uncontrolled expandable
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.md
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.test.tsx
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
  packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/expandable.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ExpandableDemo/ExpandableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, enhancement :rocket:

#2755 Docs: target the container with more specificity
  packages/patternfly-4/react-docs/src/styles/workspace.css
Labels: PF4, documentation :memo:

#2659 fix(loginForm): adds autoFocus to username input
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
Labels: PF4, enhancement :rocket:

#2692 fix(emptyState): set the correct size modifier using the variant prop
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.tsx
  packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.tsx.snap
Labels: PF4, bug :bug:

#2701 feat(Icons - config): Publish configs as well with icons
  packages/react-icons/build/templates/iconFile.hbs
  packages/react-icons/build/templates/mainBarrelFile.hbs
Labels: PF4, enhancement :rocket:

#2794 Chart themeColor doc incorrect
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/ChartArea/ChartArea.tsx
  packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.tsx
  packages/patternfly-4/react-charts/src/components/ChartBar/ChartBar.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBullet.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeErrorMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeWarningMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimaryDotMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimarySegmentedMeasure.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletQualitativeRange.tsx
  packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx
  packages/patternfly-4/react-charts/src/components/ChartContainer/ChartContainer.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
  packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.tsx
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.tsx
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegendWrapper.tsx
  packages/patternfly-4/react-charts/src/components/ChartLine/ChartLine.tsx
  packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
  packages/patternfly-4/react-charts/src/components/ChartScatter/ChartScatter.tsx
  packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.tsx
  packages/patternfly-4/react-charts/src/components/ChartTooltip/ChartTooltip.tsx
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.tsx
Labels: PF4, documentation :memo:

#2774 fix(Modal): FocusTrap works with showClose being false
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
Labels: PF4, bug :bug:

#2625 feat(chart-stack): add monthly example
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
Labels: ux review

#2733 feat(PF4 - Drawer): Update drawer to expose all parts
  packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.md
  packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.tsx
  packages/patternfly-4/react-core/src/experimental/components/Drawer/DrawerContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/Drawer/index.ts
Labels: PF4, enhancement :rocket:

#2785 fix(ActionGroup): Remove unneeded Action import
  packages/patternfly-4/react-core/src/components/Form/ActionGroup.tsx
Labels: PF4
