Repository patternfly/patternfly-react, pull requests merged in 2019-11, with the labels that each got.

#3238 fix(optionmenu): remove the i element around selected item svg
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
Labels: PF4, enhancement :rocket:

#3249 build(package.json): Upgrade react-bootstrap to fix React deprecated lifecycle method warnings
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react/package.json
  packages/patternfly-3/patternfly-react/src/components/AboutModal/__snapshots__/AboutModal.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/DropdownKebab/__snapshots__/DropdownKebab.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/InfoTip/__snapshots__/InfoTip.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/Masthead/__snapshots__/Masthead.test.js.snap
  packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
  packages/patternfly-4/react-catalog-view-extension/package.json
  yarn.lock
Labels: PF3, infrastructure

#3222 chore(demo-app-ts): increase strict checks for react-integration
  packages/patternfly-4/react-integration/demo-app-ts/tsconfig.json
Labels: PF4, TypeScript, enhancement :rocket:

#3254 PF4: fix(README.md): provides URL location of workspace
  packages/patternfly-4/react-core/README.md
Labels: documentation :memo:

#3261 chore(repo): update github templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/patternfly-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: infrastructure

#3303 Properly import formatTime to DateTimePicker
  packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateTimePicker.js
Labels: bug :bug:

#3239 fix(wizard,aboutmodal): remove appendTo from props passed to div
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
Labels: PF4, bug :bug:

#3258 fix(flex): in breakpointMods set breakpoint as optional and add enums
  packages/patternfly-4/react-core/src/layouts/Flex/FlexUtils.tsx
  packages/patternfly-4/react-core/src/layouts/Flex/examples/Flex.md
  packages/patternfly-4/react-core/src/layouts/Flex/index.ts
Labels: PF4, bug :bug:

#3293 Update keyboard interaction for dropdown
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/patternfly-4/react-integration/cypress/integration/dropdown.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
Labels: accessibility

#3220 feat(form): Add validated variant to form inputs
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Form/FormGroup.test.tsx
  packages/patternfly-4/react-core/src/components/Form/FormGroup.tsx
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Form/examples/Form.md
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.test.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/__snapshots__/FormSelect.test.tsx.snap
  packages/patternfly-4/react-core/src/components/FormSelect/examples/FormSelect.md
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.test.js
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.tsx
  packages/patternfly-4/react-core/src/components/TextArea/__snapshots__/TextArea.test.js.snap
  packages/patternfly-4/react-core/src/components/TextArea/examples/TextArea.md
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.test.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.tsx
  packages/patternfly-4/react-core/src/components/TextInput/__snapshots__/TextInput.test.js.snap
  packages/patternfly-4/react-core/src/helpers/constants.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/__snapshots__/TableTextInput.test.js.snap
  packages/patternfly-4/react-integration/cypress/integration/form.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/formselect.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/textarea.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/textinputdemo.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormSelectDemo/FormSelectDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextInputDemo/TextInputDemo.tsx
Labels: css review

#3309 feat(Accordion): Add a prop to allow the box shadow to be removed
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
  packages/patternfly-4/react-core/src/components/Accordion/examples/Accordion.md
  packages/patternfly-4/react-integration/cypress/integration/accordion.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AccordionDemo/AccordionDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#3240 fix(button): support setting tab index unless not button and disabled
  packages/patternfly-4/react-core/src/components/Button/Button.test.tsx
  packages/patternfly-4/react-core/src/components/Button/Button.tsx
  packages/patternfly-4/react-integration/cypress/integration/button.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
Labels: PF4, bug :bug:

#3307 feat(Dropdown): add split button action variant
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItemIcon.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleAction.test.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleAction.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleAction.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/patternfly-4/react-core/src/components/Dropdown/index.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-integration/cypress/integration/dropdown.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
Labels: PF4, css review, ux approved

#3319 fix(DataToolbar): move and wrap chips in expandable content
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md
  packages/patternfly-4/react-integration/cypress/integration/datatoolbar.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx
Labels: css review

#3333 feat(Select): Add the ability to have custom content in the Select Menu
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/examples/Select.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, css review, enhancement :rocket:
