Repository patternfly/patternfly-react, pull requests merged in 2019-10, with the labels that each got.

#3054 fixed sentence case for component titles
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.md
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.md
  packages/patternfly-4/react-core/src/components/Nav/examples/Navigation.md
  packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.md
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/Topology.md
Labels: documentation :memo:

#3033 refactor(Tabs): move TabButton to new file
  packages/patternfly-4/react-core/src/components/Tabs/Tab.test.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
  packages/patternfly-4/react-core/src/components/Tabs/TabButton.test.tsx
  packages/patternfly-4/react-core/src/components/Tabs/TabButton.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tab.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/TabButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: PF4, chore :house:

#2684 fix(radio): group radio inputs in docs (axe-core)
  packages/patternfly-4/react-core/src/components/Radio/Radio.md
  packages/patternfly-4/react-core/src/components/Radio/Radio.test.tsx
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap
Labels: PF4, accessibility, css review

#3019 Charts: Move ChartThreshold to its own example
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
  packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
  packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/chart-threshold.scss
  packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md
Labels: PF4, documentation :memo:

#3063 docs(Spinner): Fix alert type in docs
  packages/patternfly-4/react-core/src/experimental/components/Spinner/Spinner.md
Labels: PF4, documentation :memo:

#3066 fix(Radio): pass checked either from isChecked or checked
  packages/patternfly-4/react-core/src/components/Radio/Radio.md
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap
Labels: PF4, bug :bug:

#3061 Charts: Tooltip examples
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
  packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
  packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/chart-tooltip.scss
  packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md
Labels: documentation :memo:

#3064 fix(Select): Allow custom components as select option
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
Labels: PF4, enhancement :rocket:

#2995 feat(Chip): Added OUIA compatibility to Chip component
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.test.tsx
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.tsx
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/Chip.test.tsx.snap
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: ouia

#3077 fix(button): component type should accept react-router Link
  packages/patternfly-4/react-core/src/components/Button/Button.tsx
Labels: PF4, enhancement :rocket:

#3030 SerialConsole: Use xterm v4
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/react-console/README.md
  packages/patternfly-3/react-console/package.json
  packages/patternfly-3/react-console/src/SerialConsole/XTerm.js
  storybook/sass/base.scss
  yarn.lock
Labels: PF3, breaking change :boom:

#3072 chore(charts): Use markdown links
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
  packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTheme/examples/ChartTheme.md
  packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
  packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
  packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/chart-tooltip.scss
  packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md
Labels: documentation :memo:

#3075 Properly use this.setState in components
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.tsx
  packages/patternfly-4/react-core/src/components/Page/Page.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
  packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx
Labels: bug :bug:

#3068 feat(Expandable): Allow for dynamic toggle text in uncontrolled version
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.md
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
  packages/patternfly-4/react-integration/cypress/integration/expandable.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ExpandableDemo/ExpandableDemo.tsx
Labels: PF4, enhancement :rocket:

#2996 Added OUIA compatibility to Select component
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: ouia

#3034 docs(button): add an example of a link button with anchor
  packages/patternfly-4/react-core/src/components/Button/Button.md
Labels: PF4, documentation :memo:

#3123 fix(Select): use props children if custom on filter used
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: bug :bug:

#3053 feat(tooltip): allow tooltip text to be left-aligned
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.md
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/TooltipContent.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
Labels: Hacktoberfest :jack_o_lantern:

#3107 fix(Dropdown/Application Launcher/Options Menu): Fix unit tests and options menu
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-core/src/helpers/util.test.js
Labels: PF4, bug :bug:

#3138 fix(Radio): Fix console error
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap
Labels: PF4, bug :bug:

#2935 fix(Cards): refactor sub-component references
  packages/patternfly-3/patternfly-react/src/components/Cards/Card.js
  packages/patternfly-3/patternfly-react/src/components/Cards/UtilizationTrendCard/UtilizationCard.test.js
  packages/patternfly-3/patternfly-react/src/components/Cards/index.js
Labels: PF3

#3149 fix(OUIA): Use consumer context if specified
  packages/patternfly-4/react-core/src/components/withOuia/withOuia.tsx
Labels: ouia

#3161 chore(emptyState): remove debug message from tests
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.tsx
Labels: chore :house:

#3178 surround ouia check with a try catch
  packages/patternfly-4/react-core/src/components/withOuia/ouia.ts
Labels: PF4, bug :bug:

#3140 fix(Select): add plain modifier to toggle button
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: PF4, bug :bug:, css review

#3125 feat(Divider): add divider component
  packages/patternfly-4/react-core/src/experimental/components/Divider/Divider.md
  packages/patternfly-4/react-core/src/experimental/components/Divider/Divider.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/Divider/Divider.tsx
  packages/patternfly-4/react-core/src/experimental/components/Divider/__snapshots__/Divider.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/Divider/index.ts
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-integration/cypress/integration/divider.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DividerDemo/DividerDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review

#3082 feat(BulkSelect demo): add bulk select demo with table and toolbar
  packages/patternfly-4/react-core/src/demos/BulkSelectTable.md
Labels: documentation :memo:, ux approved

#3144 fix(DataToolbar): implement changes to match PF-Core
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md
Labels: PF4, css review

#3160 Custom row wrapper example for table
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/RowWrapperForTableRowWrapperDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableActionsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableBreakpointModifiersDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCollapsibleDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompactBorderlessRowsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompactDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCompactExpandableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableRowWrapperDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleActionsDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableWidthModifiersDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.test.tsx
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.tsx
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/Table.test.tsx
  packages/patternfly-4/react-table/src/components/Table/Table.tsx
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.test.tsx
Labels: PF4, documentation :memo:

#3183 docs(Select): update prop description for selctions
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
Labels: PF4, documentation :memo:

#3180 feat(TextArea): Add a prop to allow limiting the resize orientation o…
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.test.js
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.tsx
  packages/patternfly-4/react-core/src/components/TextArea/__snapshots__/TextArea.test.js.snap
  packages/patternfly-4/react-core/src/components/TextArea/examples/TextArea.md
  packages/patternfly-4/react-integration/cypress/integration/textarea.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#2804 Add issue template
  .github/ISSUE_TEMPLATE/patternfly-issue-template.md
Labels: PF4, chore :house:

#3204 Bump @patternfly/patternfly versions to 2.40.2
  packages/patternfly-4/react-catalog-view-extension/package.json
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenu.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuControl.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuControl.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuDropdownItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuGroup.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuItem.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/OverflowMenuItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenuControl.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenuGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/OverflowMenu/__snapshots__/OverflowMenuItem.test.tsx.snap
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-inline-edit-extension/package.json
  packages/patternfly-4/react-integration/cypress/integration/overflowmenu.spec.ts
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styles/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/patternfly-4/react-topology/package.json
  packages/patternfly-4/react-virtualized-extension/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: css review

#3127 docs(Table Filter Demo)
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
Labels: PF4, ux approved

#3215 docs(Release Notes): Update release notes 2019.9
  RELEASE-NOTES.md
Labels: documentation :memo:
