Repository patternfly/patternfly-react, pull requests merged in 2019-07, with the labels that each got.

#2404 fix(grid): always remove size props from {...props}
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js
Labels: PF4, bug :bug:

#2399 feat(card): Add compact card variation
  packages/patternfly-4/react-core/src/components/Card/Card.md
  packages/patternfly-4/react-core/src/components/Card/Card.test.tsx
  packages/patternfly-4/react-core/src/components/Card/Card.tsx
  packages/patternfly-4/react-core/src/components/Card/CardHeader.tsx
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/card.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#2402 fix(tabs): tab container refs
  packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
Labels: PF4, bug :bug:

#2201 feat(Select): convert to Typescript
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelect.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.d.ts
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.test.tsx
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.tsx
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.test.tsx
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectGroup.test.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectGroup.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOption.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.test.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.tsx
  packages/patternfly-4/react-core/src/components/Select/SingleSelect.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectOption.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectOption.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/index.d.ts
  packages/patternfly-4/react-core/src/components/Select/index.js
  packages/patternfly-4/react-core/src/components/Select/index.ts
  packages/patternfly-4/react-core/src/components/Select/selectConstants.js
  packages/patternfly-4/react-core/src/components/Select/selectConstants.tsx
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2401 feat(OptionsMenu): Add disabled modifier to the toggle
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.md
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.test.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-integration/cypress/integration/optionsmenu.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/OptionsMenuDemo/OptionsMenuDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#2407 fix(BreadCrumbSwitcher): disable autocomplete
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSearchInput.js
Labels: PF3, bug :bug:

#2377 fix(incremental-build): also hash folder names
  scripts/hashDir.js
Labels: infrastructure

#2256 feat(Pagination): Pagination Component Typescript Conversion
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.d.ts
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.js
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.md
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.js
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/patternfly-4/react-core/src/components/Pagination/ToggleTemplate.js
  packages/patternfly-4/react-core/src/components/Pagination/ToggleTemplate.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
  packages/patternfly-4/react-core/src/components/Pagination/index.d.ts
  packages/patternfly-4/react-core/src/components/Pagination/index.js
  packages/patternfly-4/react-core/src/components/Pagination/index.tsx
  packages/patternfly-4/react-core/src/helpers/util.test.js
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-integration/cypress/integration/pagination.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript

#2406 fix(Modal): get modal container from state to set/unset aria-hidden
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
Labels: PF4, accessibility, bug :bug:

#2311 chore(Switch): convert Switch to TypeScript
  packages/patternfly-4/react-core/src/components/Switch/Switch.d.ts
  packages/patternfly-4/react-core/src/components/Switch/Switch.md
  packages/patternfly-4/react-core/src/components/Switch/Switch.test.js
  packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
  packages/patternfly-4/react-core/src/components/Switch/index.d.ts
  packages/patternfly-4/react-core/src/components/Switch/index.js
  packages/patternfly-4/react-core/src/components/Switch/index.ts
  packages/patternfly-4/react-integration/cypress/integration/switch.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SwitchDemo/SwitchDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2439 Update chart theme to use pf-core variables
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLabel/__snapshots__/ChartLabel.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTheme/styles/common-styles.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/styles/donut-styles.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/styles/donut-utilization-styles.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/axis-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/bullet-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-threshold-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-utilization-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
  packages/patternfly-4/react-tokens/src/generateTokens.js
Labels: PF4, enhancement :rocket:

#2456 fix(select): removed ariaLabel from grouped checkbox select
  packages/patternfly-4/react-core/src/components/Select/Select.md
Labels: PF4, accessibility

#2461 Remove invalid pf-core var
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
Labels: PF4

#2412 feat(Stack): Convert stack to typescript
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.d.ts
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.js
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.test.tsx
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.tsx
  packages/patternfly-4/react-core/src/layouts/Stack/StackItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Stack/StackItem.js
  packages/patternfly-4/react-core/src/layouts/Stack/StackItem.tsx
  packages/patternfly-4/react-core/src/layouts/Stack/__snapshots__/Stack.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Stack/examples/Stack.md
  packages/patternfly-4/react-core/src/layouts/Stack/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Stack/index.js
  packages/patternfly-4/react-core/src/layouts/Stack/index.ts
  packages/patternfly-4/react-integration/cypress/integration/stack.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/StackDemo/StackDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
Labels: PF4, TypeScript, chore :house:

#2427 feat(Bullseye): Convert bullseye to typescript
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalContainer.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.d.ts
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.js
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.test.tsx
  packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.tsx
  packages/patternfly-4/react-core/src/layouts/Bullseye/__snapshots__/Bullseye.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Bullseye/examples/Bullseye.md
  packages/patternfly-4/react-core/src/layouts/Bullseye/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Bullseye/index.js
  packages/patternfly-4/react-core/src/layouts/Bullseye/index.ts
  packages/patternfly-4/react-integration/cypress/integration/bullseye.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/BullseyeDemo/BullseyeDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2463 fix(charts): remove invalid pf-core var
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
Labels: PF4

#2432 feat(Gallery): Convert gallery to typescript
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.d.ts
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.js
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.test.tsx
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.tsx
  packages/patternfly-4/react-core/src/layouts/Gallery/GalleryItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Gallery/GalleryItem.js
  packages/patternfly-4/react-core/src/layouts/Gallery/GalleryItem.tsx
  packages/patternfly-4/react-core/src/layouts/Gallery/__snapshots__/Gallery.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Gallery/examples/Gallery.md
  packages/patternfly-4/react-core/src/layouts/Gallery/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Gallery/index.js
  packages/patternfly-4/react-core/src/layouts/Gallery/index.ts
  packages/patternfly-4/react-integration/cypress/integration/gallery.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/GalleryDemo/GalleryDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2304 feat(react-core): add ouia compatibility to Switch
  packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
  packages/patternfly-4/react-core/src/helpers/ouia.ts
Labels: PF4

#2450 feat(Level): Convert level to typescript
  packages/patternfly-4/react-core/src/layouts/Level/Level.d.ts
  packages/patternfly-4/react-core/src/layouts/Level/Level.js
  packages/patternfly-4/react-core/src/layouts/Level/Level.test.tsx
  packages/patternfly-4/react-core/src/layouts/Level/Level.tsx
  packages/patternfly-4/react-core/src/layouts/Level/LevelItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Level/LevelItem.js
  packages/patternfly-4/react-core/src/layouts/Level/LevelItem.tsx
  packages/patternfly-4/react-core/src/layouts/Level/__snapshots__/Level.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Level/examples/Level.md
  packages/patternfly-4/react-core/src/layouts/Level/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Level/index.js
  packages/patternfly-4/react-core/src/layouts/Level/index.tsx
  packages/patternfly-4/react-integration/cypress/integration/level.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/LevelDemo/LevelDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2251 feat(datalist): add hidden and visible breakpoints
  packages/patternfly-4/react-core/src/components/DataList/DataList.md
  packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.tsx
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
  packages/patternfly-4/react-styles/src/index.d.ts
  packages/patternfly-4/react-styles/src/index.js
  packages/patternfly-4/react-styles/src/utils.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.js
Labels: PF4, css review

#2466 feat(Split): Convert split to typescript
  packages/patternfly-4/react-core/src/layouts/Split/Split.d.ts
  packages/patternfly-4/react-core/src/layouts/Split/Split.js
  packages/patternfly-4/react-core/src/layouts/Split/Split.test.tsx
  packages/patternfly-4/react-core/src/layouts/Split/Split.tsx
  packages/patternfly-4/react-core/src/layouts/Split/SplitItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Split/SplitItem.js
  packages/patternfly-4/react-core/src/layouts/Split/SplitItem.tsx
  packages/patternfly-4/react-core/src/layouts/Split/__snapshots__/Split.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Split/examples/Split.md
  packages/patternfly-4/react-core/src/layouts/Split/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Split/index.js
  packages/patternfly-4/react-core/src/layouts/Split/index.ts
  packages/patternfly-4/react-integration/cypress/integration/split.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SplitDemo/SplitDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2471 fix(build): make pf3/pf4 build on windows
  package.json
  packages/patternfly-3/node-sass-patternfly-importer.js
  packages/patternfly-3/package.json
  packages/patternfly-3/patternfly-react-extensions/package.json
  packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions.scss
  packages/patternfly-3/patternfly-react/build/node-sass-tilde-importer.js
  packages/patternfly-3/patternfly-react/less/type-ahead-select.less
  packages/patternfly-3/patternfly-react/package.json
  packages/patternfly-3/patternfly-react/sass/patternfly-react.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_type-ahead-select.scss
  packages/patternfly-3/react-console/package.json
  packages/patternfly-4/package.json
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-inline-edit-extension/package.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styles/package.json
  packages/patternfly-4/react-styles/src/generateClasses.js
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-topology/package.json
  packages/patternfly-4/react-virtualized-extension/package.json
  packages/react-icons/package.json
  storybook/sass/base.scss
  storybook/webpack.config.js
  yarn.lock
Labels: infrastructure

#2475 feat(Toolbar): Convert toolbar to typescript
  packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.test.tsx
  packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.tsx
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.tsx
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.tsx
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.tsx
  packages/patternfly-4/react-core/src/layouts/Toolbar/__snapshots__/Toolbar.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Toolbar/examples/Toolbar.md
  packages/patternfly-4/react-core/src/layouts/Toolbar/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Toolbar/index.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/index.ts
  packages/patternfly-4/react-integration/cypress/integration/toolbar.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
Labels: PF4, TypeScript, chore :house:

#2457 fix(BreadCrumbSwitcher): Fix Autocomplete camelCase
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSearchInput.js
Labels: PF3

#2442 Chart: Add bottom-left legend position
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.tsx
  packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegendWrapper.tsx
  packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
  packages/patternfly-4/react-charts/src/components/ChartUtils/chart-legend.ts
Labels: PF4, enhancement :rocket:

#2443 feat(Grid): Convert grid to typescript
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.js
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.test.tsx
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.tsx
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.test.tsx
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.tsx
  packages/patternfly-4/react-core/src/layouts/Grid/__snapshots__/Grid.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Grid/__snapshots__/GridItem.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Grid/__snapshots__/GridItem.test.tsx.snap
  packages/patternfly-4/react-core/src/layouts/Grid/examples/Grid.md
  packages/patternfly-4/react-core/src/layouts/Grid/gridUtils.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/gridUtils.js
  packages/patternfly-4/react-core/src/layouts/Grid/index.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/index.js
  packages/patternfly-4/react-core/src/layouts/Grid/index.ts
  packages/patternfly-4/react-core/src/styles/sizes.d.ts
  packages/patternfly-4/react-core/src/styles/sizes.js
  packages/patternfly-4/react-core/src/styles/sizes.ts
  packages/patternfly-4/react-integration/cypress/integration/grid.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/GridDemo/GridDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2428 fix(aboutModal+modal): now trap focus in browser
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalContainer.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
Labels: PF4, accessibility, bug :bug:, enhancement :rocket:

#2493 feat(Tabs): Allow eventKey to accept a string
  packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/tabsstringeventkey.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsStringEventKeyDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, enhancement :rocket:

#2497 fix(charts): Adjust pf-core vars & add tooltip examples
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/blue-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/cyan-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/gold-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/gray-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/green-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/multi-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/orange-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/purple-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/blue-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/cyan-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/gold-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/gray-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/green-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/multi-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/orange-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/purple-color-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
Labels: PF4, bug :bug:

#2417 feat(Pagination): Let users enter numbers into the input field
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
  packages/patternfly-4/react-integration/cypress/integration/pagination.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
Labels: PF4, bug :bug:

#2455 fix(login page): removes ariaLabel from checkbox
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.test.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
  packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx
Labels: PF4, accessibility

#2500 Charts: provide an accessible title and description
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/chart-bar.scss
  packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
  packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.tsx
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/chart-line.scss
  packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
Labels: PF4, accessibility

#2419 feat(Select): add optional display via children to option
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.test.tsx
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
  packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectOption.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, enhancement :rocket:

#2499 feat(EmptyState): update EmptyStateBody to use <div> instead of <p>
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateBody.tsx
Labels: PF4, css review, enhancement :rocket:

#2510 chore(charts): tweak aria title for area chart
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
Labels: PF4, accessibility

#2512 feat(Tabs): Implement overflow styles for secondary tabs
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: PF4, css review, p1

#2530 chore(badges): temporarily disable problematic badges
  README.md
Labels: chore :house:, documentation :memo:

#2505 chore(deps): remove tippy-react dependency
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.test.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/styles.tsx
  packages/patternfly-4/react-core/src/helpers/PopoverBase/PopoverBase.d.ts
  packages/patternfly-4/react-core/src/helpers/PopoverBase/PopoverBase.js
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
  yarn.lock
Labels: PF4

#2527 fix(react-table): check empty array in areAllRowsSelected
  packages/patternfly-4/react-table/src/components/Table/Table.js
Labels: PF4, bug :bug:

#2518 feat(Select): update typeahead filtered list when children change
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
Labels: PF4, bug :bug:

#2363 feat(experimental): add POC for experimental button and badge
  packages/patternfly-4/react-core/src/experimental/components/Badge/Badge.md
  packages/patternfly-4/react-core/src/experimental/components/Badge/Badge.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/Badge/Badge.tsx
  packages/patternfly-4/react-core/src/experimental/components/Badge/__snapshots__/Badge.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/Badge/index.ts
  packages/patternfly-4/react-core/src/experimental/components/Button/Button.md
  packages/patternfly-4/react-core/src/experimental/components/Button/Button.tsx
  packages/patternfly-4/react-core/src/experimental/components/Button/index.ts
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-core/src/experimental/index.ts
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/src/templates/mdxTemplate.js
Labels: infrastructure

#2563 chore(react-docs): updated react-docs to use Red Hat font
  packages/patternfly-4/react-core/README.md
  packages/patternfly-4/react-docs/src/templates/sidebarLayout.js
Labels: PF4, chore :house:, css review

#2584 fix(charts): use vars to enable Red Hat fonts [ci skip]
  packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.tsx
  packages/patternfly-4/react-charts/src/components/ChartLabel/__snapshots__/ChartLabel.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartTheme/styles/common-styles.ts
  packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
  packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
Labels: PF4, css review

#2549 Bump @patternfly/patternfly to 2.23.0, add promotion script, add bumping script
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-inline-edit-extension/package.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-styles/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/patternfly-4/react-virtualized-extension/package.json
  packages/react-icons/package.json
  scripts/bumpCore.js
  scripts/promote.sh
  yarn.lock
Labels: chore :house:, infrastructure

#2375 fix(Donut Chart): Add fixed point notation into percentage donut charts
  packages/patternfly-3/patternfly-react/src/components/Chart/DonutChart.js
  packages/patternfly-3/patternfly-react/src/components/Chart/Stories/DonutChartStory.js
Labels: PF3, bug :bug:

#2478 Check if OUIA is set after mounting
  packages/patternfly-4/react-core/src/components/Switch/Switch.test.js
  packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
  packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/components/withOuia/index.ts
  packages/patternfly-4/react-core/src/components/withOuia/ouia.ts
  packages/patternfly-4/react-core/src/components/withOuia/withOuia.md
  packages/patternfly-4/react-core/src/components/withOuia/withOuia.tsx
  packages/patternfly-4/react-core/src/helpers/ouia.ts
  packages/patternfly-4/react-integration/cypress/integration/ouia.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/OuiaDemo/OuiaDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, chore :house:

#2539 feat(Tooltip): Added support for aria prop from Tippy library
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
Labels: PF4, accessibility

#2567 fix(form): replace radio with check
  packages/patternfly-4/react-core/src/components/Form/Form.md
Labels: PF4, accessibility

#2572 fix(select): select menu has consistent behavior on input field
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: PF4, bug :bug:, ux approved

#2547 fix(quarkster): add curl command after release
  .circleci/release.sh
Labels: chore :house:, infrastructure

#2558 fix(PF4: Pagination): When 0 or negative number is passed to Pagintion show 0 pages
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.md
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
Labels: PF4, ux approved

#2519 fix(page): skip to content should point to primary content container
  packages/patternfly-4/react-core/src/components/Page/Page.test.tsx
  packages/patternfly-4/react-core/src/components/Page/Page.tsx
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutManualNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
Labels: PF4, accessibility

#2517 fix(Dropdown): adds aria-label for icon only example
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
Labels: PF4, accessibility

#2434 feat(Select): add select custom filter callback
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
Labels: PF4, enhancement :rocket:

#2548 chore(incrementalBuild): invalidate all packages if yarn.lock changes
  scripts/hashDir.js
  scripts/incrementalBuild.js
Labels: chore :house:, infrastructure

#2120 feat(Modal): Allow custom header and footer
  packages/patternfly-4/react-core/src/components/Modal/Modal.md
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.test.tsx
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/modal.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
Labels: PF4, enhancement :rocket:

#2422 feat(accordion): add definition list use case
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.md
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.tsx
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContext.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx
  packages/patternfly-4/react-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Labels: PF4, accessibility, css review, enhancement :rocket:

#2601 docs(Pagination): add a demo of table integrated with pagination
  packages/patternfly-4/react-core/src/demos/PaginationTable.md
Labels: PF4, documentation :memo:

#2605 chore(doc): fix copy pasta typo
  packages/patternfly-4/react-core/src/layouts/Stack/StackItem.tsx
Labels: PF4, documentation :memo:

#2588 fix(select): add isPlain variation/prop to Select.tsx, snapshot tests, and integration
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: PF4, css review, enhancement :rocket:
