Repository patternfly/patternfly-react, pull requests merged in 2019-12, with the labels that each got.

#3262 fix(nav & pagelayout): removes basic nav example, switches to default variant, updates PF masthead logo
  .circleci/index.html
  packages/patternfly-4/react-core/src/components/Nav/NavGroup.tsx
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Nav/examples/Nav.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayout.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/imgBrand.png
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/imgBrand.svg
  packages/patternfly-4/react-integration/demo-app-ts/src/assets/images/imgBrand.png
  packages/patternfly-4/react-integration/demo-app-ts/src/assets/images/imgBrand.svg
  packages/patternfly-4/react-integration/demo-app-ts/src/components/AppHeader/AppHeader.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#3352 Add various table state demos
  packages/patternfly-4/react-core/src/demos/TableEmptyStatesDemo.md
Labels: documentation :memo:

#3182 feat(Pagination): automate pagination and overflow logic
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/patternfly-4/react-core/src/demos/PaginationTable.md
  packages/patternfly-4/react-integration/cypress/integration/pagination.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
Labels: PF4, css review, enhancement :rocket:, ux review

#3376 Popover - make text selectable
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
Labels: bug :bug:

#3370 Update tippy.js dependency
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/patternfly-4/react-core/src/helpers/PopoverBase/PopoverBase.js
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
  yarn.lock
Labels: chore :house:

#3375 docs(EmptyStateIcon): mark deprecated props
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.tsx
Labels: PF4, documentation :memo:

#3372 Update interpolation examples to use monotoneX
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartLegend/examples/ChartLegend.md
  packages/patternfly-4/react-charts/src/components/ChartScatter/examples/ChartScatter.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
  packages/patternfly-4/react-charts/src/components/ChartTheme/examples/ChartTheme.md
  packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
  packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
Labels: documentation :memo:

#3365 fix(table): rename visible/hiddenOn2Xl to visible/hiddenOn_2xl
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.ts
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.tsx
Labels: bug :bug:

#3345 PF3: add spacing between VncAction buttons in react-console
  packages/patternfly-3/react-console/sass/_vnc-console.scss
Labels: PF3

#3391 fix(Dropdown): Update component to use input rather than PF Checkbox
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap
Labels: bug :bug:, css review

#3386 build(workspace): upgrade gatsby and org theme
  .circleci/config.yml
  RELEASE-NOTES.md
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/pages/icons.js
  packages/patternfly-4/react-docs/src/pages/index.js
  packages/patternfly-4/react-docs/src/training.md
  yarn.lock
Labels: infrastructure

#3402 fix(Table): Fix the ActionColumn to allow a link in the actions menu
  packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx
  packages/patternfly-4/react-table/src/components/Table/Table.md
Labels: bug :bug:

#3363 feat(list): add the ordered variant
  packages/patternfly-4/react-core/src/components/List/List.test.js
  packages/patternfly-4/react-core/src/components/List/List.tsx
  packages/patternfly-4/react-core/src/components/List/examples/List.md
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.test.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.tsx
  packages/patternfly-4/react-integration/cypress/integration/list.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ListDemo/ListDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx
Labels: css review

#3371 Application launcher enhancements
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherItem.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/helpers/constants.ts
  packages/patternfly-4/react-core/src/helpers/util.test.js
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-integration/cypress/integration/applicationlauncher.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherFavoritesDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, css review, enhancement :rocket:, ux approved

#3387 doc(PageLayout): set breadcrumb, nav and title texts to sentence case
  packages/patternfly-4/react-core/src/components/Breadcrumb/examples/Breadcrumb.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayout.md
Labels: documentation :memo:

#3409 [PF3] Update CustomModalDialog to match changes to original react-bootstrap ModalDialog
  packages/patternfly-3/patternfly-react/src/components/Modal/InnerComponents/CustomModalDialog.js
Labels: PF3

#3404 feat(DataList): add selectable variant
  packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
  packages/patternfly-4/react-core/src/components/DataList/DataList.tsx
  packages/patternfly-4/react-core/src/components/DataList/DataListCheck.tsx
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
  packages/patternfly-4/react-core/src/components/DataList/examples/DataList.md
  packages/patternfly-4/react-integration/cypress/integration/datalist.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx
Labels: css review

#3428 chore(Release notes): update release notes for 2018.11
  RELEASE-NOTES.md
Labels: chore :house:
