Repository patternfly/patternfly-react, pull requests merged in 2019-01, with the labels that each got.

#1124 fix(BackgroundImage): remove old tokens
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
  packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.js
Labels: PF4, bug :bug:

#1117 Fix 1094: Updated to add support for generating d.ts files for ts, and tsx files.
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.d.ts
  packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
  packages/patternfly-4/react-core/src/components/Avatar/index.js
  packages/patternfly-4/react-core/src/components/Avatar/index.ts
  packages/patternfly-4/react-core/src/components/index.d.ts
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/index.d.ts
  packages/patternfly-4/react-core/src/tsconfig.dts.json
  yarn.lock
Labels: PF4

#1119 Fix #1118: Added tslint support to react-core
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.test.tsx
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.tsx
  packages/patternfly-4/react-core/tslint.json
  yarn.lock
Labels: PF4

#1110 docs(Select): Add an invalid select example
  packages/patternfly-4/react-core/src/components/Select/Select.docs.js
  packages/patternfly-4/react-core/src/components/Select/examples/SelectInputInvalid.js
Labels: PF4

#1103 feat(tooltip): add tooltip to PF4
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.docs.js
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.test.js
  packages/patternfly-4/react-core/src/components/Tooltip/TooltipArrow.js
  packages/patternfly-4/react-core/src/components/Tooltip/TooltipContent.js
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
  packages/patternfly-4/react-core/src/components/Tooltip/examples/SimpleTooltip.js
  packages/patternfly-4/react-core/src/components/Tooltip/examples/TooltipPositions.js
  packages/patternfly-4/react-core/src/components/Tooltip/index.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, css approved, enhancement :rocket:, ux review

#1127 Updated drop down with icon only example
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/IconDropdown.js
Labels: PF4, documentation :memo:

#1116 fix(Radio.d.ts): Made aria-label required
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
Labels: PF4

#1126 fix(dropdown): add focus trap option that allows close on click
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
Labels: PF4, bug :bug:

#1139 fix(AccessConsoles): fix propTypes checking for "null" child
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
Labels: bug :bug:

#1123 fix(VncConsole): disconnect VNC session when unmounting
  packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
Labels: bug :bug:

#1140 Feat 1130: Application Launcher
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.d.ts
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.docs.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.test.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/SimpleApplicationLauncher.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/TooltipApplicationLauncher.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/index.d.ts
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/index.js
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4

#1147 Fix for Avatar.d.ts file getting overwritten during build.
  packages/patternfly-4/react-core/package.json
Labels: PF4

#1137 fix(EmptyState): Use IconProps to define EmptyStateIconProps
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.d.ts
Labels: PF4, bug :bug:

#1151 Fix(dependencies): Fix react-tokens dependency and Tooltip typescript
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
  packages/patternfly-4/react-core/src/components/Avatar/index.ts
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardBody.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardFooter.test.js.snap
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Label/Label.js
  packages/patternfly-4/react-core/src/components/Label/__snapshots__/Label.test.js.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/tsconfig.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, bug :bug:, chore :house:

#1014 Dropdown interaction issues
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownItem.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.js
Labels: PF4, accessibility, bug :bug:

#1159 fix(docs): fix workspace previews
  packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
  packages/patternfly-4/react-core/src/components/Avatar/index.ts
Labels: PF4, documentation :memo:

#1152 fix(DropdownToggle): Listen for touch events on the document to close a Toggle on mobile
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
Labels: PF4, bug :bug:

#1162 Chore(update): Update core to 1.0.120
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, chore :house:

#1165 feat(Nav): add separator flag
  packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavItem.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
Labels: PF4

#1169 fix(dropdown): add span wrapper for dropdown toggle text
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
Labels: PF4, bug :bug:

#1173 PF4: Add missing attribute isPlain to Dropdown
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
Labels: PF4, bug :bug:

#1075 Dropdown arrow key support
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/Item.js
  packages/patternfly-4/react-core/src/components/Dropdown/Separator.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownItem.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.js
Labels: PF4, accessibility

#1186 fix(Button): make aria-label optional prop
  packages/patternfly-4/react-core/src/components/Button/Button.js
Labels: PF4, bug :bug:

#1143 chore(generator): update generator to support typescript files
  scripts/generators/patternfly-4-component/index.js
  scripts/generators/patternfly-4-component/templates/component/component.docs.js.hbs
  scripts/generators/patternfly-4-component/templates/component/component.test.tsx.hbs
  scripts/generators/patternfly-4-component/templates/component/component.tsx.hbs
  scripts/generators/patternfly-4-component/templates/component/example.js.hbs
  scripts/generators/patternfly-4-component/templates/component/index.ts.hbs
  scripts/generators/patternfly-4-component/templates/component/{{componentName}}.js
  tsconfig.json
Labels: chore :house:

#1171 fix(Login Page): fix settings visibility
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSettings.js
Labels: bug :bug:

#1178 fix(DualList): de-Select items after the transition between lists.
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.test.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
Labels: bug :bug:

#1190 fix(DualList): refactor helpers functions signatures
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
Labels: chore :house:

#1150 feat(umd modules): adds babel-transform-es2015-modules-umd
  packages/patternfly-4/react-core/package.json
Labels: chore :house:, enhancement :rocket:

#1180 Chip component
  packages/patternfly-4/react-core/src/components/Chip/Chip.d.ts
  packages/patternfly-4/react-core/src/components/Chip/Chip.docs.js
  packages/patternfly-4/react-core/src/components/Chip/Chip.js
  packages/patternfly-4/react-core/src/components/Chip/Chip.test.js
  packages/patternfly-4/react-core/src/components/Chip/ChipButton.d.ts
  packages/patternfly-4/react-core/src/components/Chip/ChipButton.js
  packages/patternfly-4/react-core/src/components/Chip/__snapshots__/Chip.test.js.snap
  packages/patternfly-4/react-core/src/components/Chip/examples/SimpleChip.js
  packages/patternfly-4/react-core/src/components/Chip/index.d.ts
  packages/patternfly-4/react-core/src/components/Chip/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4

#1193 fix(Dropdown): Pass down ref for dropdown item
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/demos/Toolbar/examples/ComplexToolbarDemo.js
  packages/patternfly-4/react-core/src/demos/Toolbar/examples/SimpleToolbarDemo.js
Labels: PF4, bug :bug:

#1187 build(lerna3): enhances build scripts to support lerna3
  lerna.json
  package.json
  packages/patternfly-4/verifyCoreVersions.js
  scripts/generators/package/index.js
  scripts/lernaHelpers.js
  storybook/webpack.config.js
  yarn.lock
Labels: chore :house:

#1198 fix(lerna3): ignore npmrc
  .travis/before_install.sh
  package.json
Labels: chore :house:

#821 feat(Table): introduce new component Table based on pf4 designs
  packages/patternfly-4/react-charts/.babelrc
  packages/patternfly-4/react-docs/build/copyDocs.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-table/.babelrc
  packages/patternfly-4/react-table/README.md
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-table/src/components/Table/ActionsColumn.js
  packages/patternfly-4/react-table/src/components/Table/Body.d.ts
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/BodyCell.js
  packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js
  packages/patternfly-4/react-table/src/components/Table/CollapseColumn.js
  packages/patternfly-4/react-table/src/components/Table/ExpandableRowContent.js
  packages/patternfly-4/react-table/src/components/Table/Header.d.ts
  packages/patternfly-4/react-table/src/components/Table/Header.js
  packages/patternfly-4/react-table/src/components/Table/HeaderCell.js
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.js
  packages/patternfly-4/react-table/src/components/Table/SelectColumn.js
  packages/patternfly-4/react-table/src/components/Table/SortColumn.d.ts
  packages/patternfly-4/react-table/src/components/Table/SortColumn.js
  packages/patternfly-4/react-table/src/components/Table/Table.api.test.js
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.docs.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.test.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/examples/ActionsTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/CellHeader.js
  packages/patternfly-4/react-table/src/components/Table/examples/CollapsibleTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/CompactTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/SelectableTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/SimpleTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/SortableTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/WidthTable.js
  packages/patternfly-4/react-table/src/components/Table/index.d.ts
  packages/patternfly-4/react-table/src/components/Table/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellWidth.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/headerCol.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js
  packages/patternfly-4/react-table/src/components/Table/utils/formatters.js
  packages/patternfly-4/react-table/src/components/Table/utils/formatters.test.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.test.js
  packages/patternfly-4/react-table/src/components/Table/utils/index.d.ts
  packages/patternfly-4/react-table/src/components/Table/utils/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
  packages/patternfly-4/react-table/src/components/index.js
  packages/patternfly-4/react-table/src/index.js
  packages/patternfly-4/react-table/src/test-helpers/MockedTableChanges.js
  packages/patternfly-4/react-table/src/test-helpers/data-sets.js
  yarn.lock
Labels: PF4, accessibility, enhancement :rocket:

#1192 docs(Button): update button docs to match core
  packages/patternfly-4/react-core/src/components/Button/Button.docs.js
  packages/patternfly-4/react-core/src/components/Button/examples/BlockButton.js
  packages/patternfly-4/react-core/src/components/Button/examples/ButtonVariants.js
  packages/patternfly-4/react-core/src/components/Button/examples/LinkButton.js
Labels: PF4, bug :bug:, css review

#1202 fix(lerna-changelog): update lerna changelog
  .travis/after_success.sh
  package.json
Labels: chore :house:

#1201 feat(Dropdown): handle keyboard navigation and styling for Link children
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
Labels: PF4, bug :bug:

#1203 fix(Dropdown): pass onClick to any dropdown item if present
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
Labels: PF4, bug :bug:

#1204 fix(lockfile): updates out of date yarn.lock
  .travis/after_success.sh
  yarn.lock
Labels: chore :house:

#1200 feat(Alert): Add optional Close button to Alert via onClose prop
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.js
  packages/patternfly-4/react-core/src/components/Alert/AlertBody.js
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/examples/DangerAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/InfoAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/SuccessAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/WarningAlert.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:

#1207 fix(DualList): fix hidden inputs
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.stories.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHiddenSelect.js
  packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
Labels: bug :bug:

#1179 Gatsby v2
  .public/index.html
  lerna.json
  package.json
  packages/patternfly-4/react-docs/.babelrc
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-docs/src/components/layouts/fullPage.js
  packages/patternfly-4/react-docs/src/components/layouts/index.js
  packages/patternfly-4/react-docs/src/components/navigation/navigation.js
  packages/patternfly-4/react-docs/src/components/navigation/navigationItem.js
  packages/patternfly-4/react-docs/src/components/page/page.js
  packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
  packages/patternfly-4/react-docs/src/html.js
  packages/patternfly-4/react-docs/src/layouts/example.js
  packages/patternfly-4/react-docs/src/layouts/index.css
  packages/patternfly-4/react-docs/src/pages/index.js
  packages/patternfly-4/react-docs/src/pages/styles/icons.js
  packages/patternfly-4/react-docs/src/pages/styles/tokens.js
  yarn.lock
Labels: PF4, documentation :memo:

#1211 fix(Dropdown): add onclick fix to custom items
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
Labels: PF4, bug :bug:

#1185 fix(Form): Update From Based on Audit
  packages/patternfly-4/react-core/src/components/Form/Form.docs.js
  packages/patternfly-4/react-core/src/components/Form/examples/InvalidForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js
  packages/patternfly-4/react-core/src/components/Form/examples/VariousLabelsForm.js
Labels: PF4, bug :bug:, css review

#1219 fix(DropdownMenu): Fixes dropdown menu when using items as children.
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
Labels: PF4, bug :bug:

#1222 fix(Dropdown): Do not focus Dropdown if menu is not opened
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
Labels: PF4, bug :bug:

#1223 fix(Slider): Update state when properties are updated.
  packages/patternfly-3/patternfly-react/src/components/Slider/Slider.js
Labels: bug :bug:

#1242 fix(ts): nav ts props
  packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
  packages/patternfly-4/react-integration/README.md
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/Nav.tsx
Labels: PF4, bug :bug:

#1145 fix(Page): improve a11y in sidebar and header
  packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts
  packages/patternfly-4/react-core/src/components/Page/PageHeader.js
  packages/patternfly-4/react-core/src/components/Page/PageSidebar.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Page/examples/VerticalPage.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
Labels: PF4, accessibility, bug :bug:, enhancement :rocket:

#1236 chore(readme): update contribution guide for non-patternfly component…
  CONTRIBUTING.md
Labels: chore :house:

#1259 refactor(Alert, EmptyState, Popover): Upgraded to Core version 1.0.137
  .gitignore
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.js.snap
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
  packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.js
  packages/patternfly-4/react-core/src/components/Alert/AlertAction.js
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.d.ts
  packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js
  packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.d.ts
  packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.js
  packages/patternfly-4/react-core/src/components/Alert/AlertBody.js
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/examples/DangerAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/InfoAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/SuccessAlert.js
  packages/patternfly-4/react-core/src/components/Alert/examples/WarningAlert.js
  packages/patternfly-4/react-core/src/components/Alert/index.d.ts
  packages/patternfly-4/react-core/src/components/Alert/index.js
  packages/patternfly-4/react-core/src/components/Badge/__snapshots__/Badge.test.js.snap
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.docs.js
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.js
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateAction.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateSecondaryActions.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateSecondaryActions.js
  packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
  packages/patternfly-4/react-core/src/components/EmptyState/examples/SimpleEmptyState.js
  packages/patternfly-4/react-core/src/components/EmptyState/index.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/index.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/components/Popover/Popover.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverFooter.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverFooter.js
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.js
  packages/patternfly-4/react-core/src/components/Popover/examples/AdvancedPopover.js
  packages/patternfly-4/react-core/src/components/Popover/examples/HeadlessPopover.js
  packages/patternfly-4/react-core/src/components/Popover/examples/SimplePopover.js
  packages/patternfly-4/react-core/src/layouts/Gallery/__snapshots__/Gallery.test.js.snap
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:

#1260 fix(BadgedResource): don't restrict resourceName to a string
  packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.js
Labels: bug :bug:, extension

#1262 fix(Chip): Replace check for length of chip text with refs
  packages/patternfly-4/react-core/src/components/Chip/Chip.d.ts
  packages/patternfly-4/react-core/src/components/Chip/Chip.js
Labels: PF4, bug :bug:

#1231 feat(FormSelect): rename Select components to FormSelect
  packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.docs.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.test.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOption.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOption.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOptionGroup.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOptionGroup.js
  packages/patternfly-4/react-core/src/components/FormSelect/__snapshots__/FormSelect.test.js.snap
  packages/patternfly-4/react-core/src/components/FormSelect/examples/FormSelectInput.js
  packages/patternfly-4/react-core/src/components/FormSelect/examples/FormSelectInputDisabled.js
  packages/patternfly-4/react-core/src/components/FormSelect/examples/FormSelectInputGrouped.js
  packages/patternfly-4/react-core/src/components/FormSelect/examples/FormSelectInputInvalid.js
  packages/patternfly-4/react-core/src/components/FormSelect/index.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/index.js
  packages/patternfly-4/react-core/src/components/Select/Select.docs.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOptionGroup.d.ts
  packages/patternfly-4/react-core/src/components/Select/examples/SelectInputInvalid.js
  packages/patternfly-4/react-core/src/components/Select/index.d.ts
  packages/patternfly-4/react-core/src/components/Select/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, enhancement :rocket:

#1272 fix(Table): Do not return value if table is not collapsed
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
Labels: PF4, bug :bug:

#1144 PF4: feat(Tabs) Add Tabs for PF4
  packages/patternfly-4/react-core/src/components/Tabs/Tab.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tab.js
  packages/patternfly-4/react-core/src/components/Tabs/Tab.test.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.docs.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.js
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tab.test.js.snap
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
  packages/patternfly-4/react-core/src/components/Tabs/examples/FilledTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/examples/ScrollButtonsTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/examples/SecondaryTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/examples/SimpleTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/index.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/index.js
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/internal/constants.js
  packages/patternfly-4/react-core/src/internal/util.js
  packages/patternfly-4/react-core/src/internal/util.test.js
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, css review, enhancement :rocket:, ux review

#1270 fix(Checkbox): Adjustments to examples
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.docs.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/ControlledCheckbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/CustomLabelCheckbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/DisabledCheckbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/examples/UncontrolledCheckbox.js
Labels: PF4, bug :bug:, css review

#1269 fix(Radio): Modify examples and aria-label/label
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
  packages/patternfly-4/react-core/src/components/Radio/Radio.docs.js
  packages/patternfly-4/react-core/src/components/Radio/Radio.js
  packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
  packages/patternfly-4/react-core/src/components/Radio/examples/ControlledRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/CustomLabelRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/DisabledRadio.js
  packages/patternfly-4/react-core/src/components/Radio/examples/UncontrolledRadio.js
Labels: PF4, accessibility, bug :bug:, css review

#1237 fix(Table): Use direct imports instead of spread
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/ExpandableRowContent.js
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.js
  packages/patternfly-4/react-table/src/components/Table/SelectColumn.js
  packages/patternfly-4/react-table/src/components/Table/SortColumn.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js
Labels: PF4, bug :bug:

#1280 fix(AboutModal): Use paragraph in heading
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap
Labels: PF4
