Repository patternfly/patternfly-react, pull requests merged in 2019-06, with the labels that each got.

#1879 feat(VictoryZoomContainer): Give examples of Victory Zoom component to allow zo…
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.tsx
  packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
  packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
Labels: PF4

#1914 feat(TextInput): Convert text input to TypeScript
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.md
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.test.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.tsx
  packages/patternfly-4/react-core/src/components/TextInput/index.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/index.js
  packages/patternfly-4/react-core/src/components/TextInput/index.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/__snapshots__/TableTextInput.test.js.snap
  packages/patternfly-4/react-integration/cypress/integration/textinputdemo.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextInputDemo/TextInputDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2013 feat(Select): add typeahead keyboard navigation
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.js
  packages/patternfly-4/react-core/src/components/Select/SingleSelect.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.js.snap
  packages/patternfly-4/react-core/src/helpers/util.ts
Labels: PF4

#2134 fix(NavItem): Maintain className passed to custom NavItems
  packages/patternfly-4/react-core/src/components/Nav/Nav.test.tsx
  packages/patternfly-4/react-core/src/components/Nav/NavItem.tsx
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap
Labels: PF4, bug :bug:

#2123 fix(issues): fix stalebot config to include issues
  .github/stale.yml
Labels: infrastructure

#2175 feat(PF4: Pagination): When empty array sent to pagination no per page should be visible
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
Labels: PF4, bug :bug:

#2193 fix(charts): align label vertically and add donutHeight/Width defaults
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
  packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/chart-donut-utilization.scss
Labels: p1

#2170 feat(Topology): Add @patternfly/react-topology package
  packages/patternfly-4/react-core/src/layouts/Stack/examples/stack.scss
  packages/patternfly-4/react-core/src/layouts/Toolbar/examples/toolbar.scss
  packages/patternfly-4/react-docs/.eslintrc.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/src/components/componentDocs/liveEdit.js
  packages/patternfly-4/react-topology/.babelrc
  packages/patternfly-4/react-topology/.npmignore
  packages/patternfly-4/react-topology/CHANGELOG.md
  packages/patternfly-4/react-topology/README.md
  packages/patternfly-4/react-topology/build/copyStyles.js
  packages/patternfly-4/react-topology/package.json
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.test.tsx
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/css/topology-controlbar-css.ts
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/index.ts
  packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.test.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyView/css/topology-view-css.ts
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ProjectToolbar.js
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/Topology.md
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ViewToolbar.js
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/topology-example.scss
  packages/patternfly-4/react-topology/src/components/TopologyView/index.ts
  packages/patternfly-4/react-topology/src/components/index.ts
  packages/patternfly-4/react-topology/src/index.ts
  packages/patternfly-4/react-topology/tsconfig.base.json
  packages/patternfly-4/react-topology/tsconfig.gen-dts.json
  packages/patternfly-4/react-topology/tsconfig.typecheck.json
Labels: PF4, enhancement :rocket:

#2122 feat(Card): Add support for images and actions
  packages/patternfly-4/react-core/src/components/Card/Card.md
  packages/patternfly-4/react-core/src/components/Card/CardActions.tsx
  packages/patternfly-4/react-core/src/components/Card/CardHead.tsx
  packages/patternfly-4/react-core/src/components/Card/examples/brandImg2.svg
  packages/patternfly-4/react-core/src/components/Card/examples/pfLogo.svg
  packages/patternfly-4/react-core/src/components/Card/index.ts
  packages/patternfly-4/react-docs/package.json
Labels: PF4, css review, enhancement :rocket:, ux approved

#2168 chore(TextArea): Convert TextArea to typescript
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.d.ts
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.js
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.md
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.test.js
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.tsx
  packages/patternfly-4/react-core/src/components/TextArea/__snapshots__/TextArea.test.js.snap
  packages/patternfly-4/react-core/src/components/TextArea/index.d.ts
  packages/patternfly-4/react-core/src/components/TextArea/index.js
  packages/patternfly-4/react-core/src/components/TextArea/index.ts
  packages/patternfly-4/react-integration/cypress/integration/textarea.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2217 fix(topology-view): Do not hard code margins on view components
  packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ProjectToolbar.js
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ViewToolbar.js
Labels: bug :bug:

#2126 feat(Alert): Add the inline alert modifier
  packages/patternfly-4/react-core/src/components/Alert/Alert.md
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
  packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
Labels: PF4, css review, enhancement :rocket:, ux approved

#2248 Table type adjustments
  packages/patternfly-4/react-table/README.md
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/index.d.ts
Labels: PF4, TypeScript

#2101 feat(PF4: Application launcher): Use dropdown components in App launcher
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.md
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.test.js
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherMenu.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherToggle.tsx
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/applicationLauncherConstants.tsx
Labels: PF4

#2218 fix(Alert): set the variant prop to info by default
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
  packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
Labels: PF4, bug :bug:

#2121 feat(Accordion): Accordion Component TypeScript Conversion
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.js
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.md
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.tsx
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.tsx
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx
  packages/patternfly-4/react-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Accordion/index.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/index.js
  packages/patternfly-4/react-core/src/components/Accordion/index.ts
  packages/patternfly-4/react-integration/cypress/integration/accordion.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AccordionDemo/AccordionDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2255 chore(virtual-scroll): use pf4 css grid layout for docs
  packages/patternfly-4/react-core/src/layouts/Grid/examples/grid.scss
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualGrid.example.css
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/Virtualized.md
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md
Labels: PF4, chore :house:, css :nail_care:

#2263 fix(ApplicationLauncher): Adjust cypress test
  packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts
  packages/patternfly-4/react-integration/cypress/integration/applicationlauncher.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
Labels: PF4, chore :house:

#2287 chore(build): Replace Travis with CircleCI
  .circleci/conditional_upload.sh
  .circleci/config.yml
  .circleci/copy-docs.sh
  .circleci/index.html
  .circleci/release.sh
  .circleci/upload-docs.sh
  .circleci/upload_preview.sh
  .gitignore
  .travis.yml
Labels: infrastructure

#2291 fix(virtual-grid): aria-label prop consistency
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
Labels: PF4, bug :bug:

#2284 fix(popover): reset pointer-events to capture default target bounds
  packages/patternfly-4/react-core/src/components/Popover/Popover.md
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/styles.tsx
Labels: enhancement :rocket:

#2138 pf3(docs): fix modal form story example to allow close
  packages/patternfly-3/patternfly-react/src/components/Form/Form.stories.js
  packages/patternfly-3/patternfly-react/src/components/Form/Stories/ModalForm.js
Labels: PF3

#2205 feat(Button): add icon property and wrapper css
  packages/patternfly-4/react-core/src/components/Button/Button.md
  packages/patternfly-4/react-core/src/components/Button/Button.test.tsx
  packages/patternfly-4/react-core/src/components/Button/Button.tsx
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.tsx.snap
Labels: PF4, css review, enhancement :rocket:

#2293 fix(Alert): remove the <p> from the Alert description
  packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
Labels: PF4, bug :bug:

#2204 feat(FormSelect): Convert form select to typescript
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.test.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOption.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOption.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOption.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOptionGroup.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOptionGroup.js
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOptionGroup.tsx
  packages/patternfly-4/react-core/src/components/FormSelect/__snapshots__/FormSelect.test.tsx.snap
  packages/patternfly-4/react-core/src/components/FormSelect/index.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/index.js
  packages/patternfly-4/react-core/src/components/FormSelect/index.ts
  packages/patternfly-4/react-integration/cypress/integration/formselect.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormSelectDemo/FormSelectDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:

#2208 PF4 - use context api in page component
  packages/patternfly-4/react-core/src/components/Page/Page.js
  packages/patternfly-4/react-core/src/components/Page/PageHeader.js
  packages/patternfly-4/react-core/src/components/Page/PageSidebar.js
Labels: PF4, bug :bug:

#2286 feat( topology-sidebar): Adds TopologySidebar to react-topology
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/css/topology-controlbar-css.ts
  packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.test.tsx
  packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.tsx
  packages/patternfly-4/react-topology/src/components/TopologySideBar/__snapshots__/TopologySideBar.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologySideBar/css/topology-side-bar-css.ts
  packages/patternfly-4/react-topology/src/components/TopologySideBar/index.ts
  packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.test.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ItemDetails.js
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/Topology.md
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ViewToolbar.js
  packages/patternfly-4/react-topology/src/components/index.ts
Labels: PF4, enhancement :rocket:

#2313 fix(virtual-scroll): add columnCount prop to VirtualTableBody
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualTableBody.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/Virtualized.md
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md
Labels: PF4, bug :bug:

#2308 fix(Alert): fix close button action
  packages/patternfly-4/react-core/src/components/Alert/Alert.md
Labels: PF4, bug :bug:

#2253 feat(Tabs): Convert tabs to typescript
  packages/patternfly-4/react-core/src/components/Tabs/Tab.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tab.js
  packages/patternfly-4/react-core/src/components/Tabs/Tab.test.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.js
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tab.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tabs/index.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/index.js
  packages/patternfly-4/react-core/src/components/Tabs/index.ts
Labels: PF4, TypeScript, chore :house:

#2326 feat(tippy): upgrade tippy deps and apply api changes
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.tsx
  packages/patternfly-4/react-core/src/components/Popover/Popover.md
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.tsx
  packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.md
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Tooltip/styles.tsx
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
  yarn.lock
Labels: PF4, enhancement :rocket:

#2330 fix(topology): Fix react-topology distribution JS
  packages/patternfly-4/react-topology/package.json
Labels: PF4, bug :bug:

#2348 fix(Tabs): Make variant prop optional
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
Labels: PF4, bug :bug:

#2340 fix(expandable): Add button type to the Expandable Component
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
  packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap
Labels: PF4, bug :bug:

#2352 fix(form): update text in form component
  packages/patternfly-4/react-core/src/components/Form/Form.md
Labels: PF4, bug :bug:, css review

#2351 fix(tabs): Remove comment from code
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
Labels: PF4, chore :house:

#2353 fix(Data list): Add DataListRow to imports
  packages/patternfly-4/react-core/src/components/DataList/DataList.md
Labels: PF4, bug :bug:

#2305 fix(Grid): Update grid layout to support new 2xl breakpoint
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.js
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js
  packages/patternfly-4/react-core/src/layouts/Grid/__snapshots__/GridItem.test.js.snap
  packages/patternfly-4/react-core/src/layouts/Grid/examples/Grid.md
  packages/patternfly-4/react-core/src/styles/sizes.d.ts
  packages/patternfly-4/react-core/src/styles/sizes.js
Labels: PF4, enhancement :rocket:

#2355 fix(dropdown): Automatically focus first dropdown item when DropdownMenu mounts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
Labels: PF4, bug :bug:

#2268 feat(Page): add page section main nav type variant
  packages/patternfly-4/react-core/src/components/Page/PageSection.test.tsx
  packages/patternfly-4/react-core/src/components/Page/PageSection.tsx
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageSection.test.tsx.snap
Labels: PF4, bug :bug:, css approved

#2292 fix(Radio): fix warning from undefined starting params
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
Labels: PF4, bug :bug:

#2373 fix(charts): adds sparkline example and interpolation to area examples
  packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
  packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
Labels: PF4, css review, enhancement :rocket:

#2376 fix(aboutmodal): change strapline element to paragraph
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.tsx
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.tsx.snap
Labels: PF4, css review, enhancement :rocket:

#2342 feat(Notification Badge): Adds the notification badge component
  packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.md
  packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.test.tsx
  packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.tsx
  packages/patternfly-4/react-core/src/components/NotificationBadge/__snapshots__/NotificationBadge.test.tsx.snap
  packages/patternfly-4/react-core/src/components/NotificationBadge/index.ts
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-integration/cypress/integration/notificationbadge.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/NotificationBadgeDemo/NotificationBadgeDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, css review, feature, ux approved

#2307 chore(Progress): Convert progress to TypeScript
  packages/patternfly-4/react-core/src/components/Progress/Progress.d.ts
  packages/patternfly-4/react-core/src/components/Progress/Progress.md
  packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.tsx
  packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressBar.tsx
  packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.tsx
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
  packages/patternfly-4/react-core/src/components/Progress/index.d.ts
  packages/patternfly-4/react-core/src/components/Progress/index.ts
  packages/patternfly-4/react-integration/cypress/integration/progress.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ProgressDemo/ProgressDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: PF4, TypeScript, chore :house:
