Repository patternfly/patternfly-react, pull requests merged in 2019-03, with the labels that each got.

#1108 feat(InputGroup): Add InputGroup to PF4
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.docs.js
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.js
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.test.js
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.js
  packages/patternfly-4/react-core/src/components/InputGroup/examples/SimpleInputGroups.js
  packages/patternfly-4/react-core/src/components/InputGroup/index.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, css review, enhancement :rocket:, ux review

#1278 fix(LoginPage): add an option to display errors only on top of the form
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.stories.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPageFixtures.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardInput.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginFormError.js
Labels: ux approved

#1385 feat(Icons): Add fa regular icons and update solid icons
  packages/react-icons/build/generateIcons.js
  packages/react-icons/build/icons.js
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, enhancement :rocket:

#1489 fix(inputgroup): fix typescript and examples
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/examples/SimpleInputGroups.js
Labels: PF4, bug :bug:

#1490 fix(navExpand): remove defaultExpand in favor of just using isExpanded
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
  packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
  packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js
Labels: bug :bug:

#1494 chore(inputgroup): add input group to react-integration
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.js
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.js
  packages/patternfly-4/react-core/src/components/InputGroup/examples/SimpleInputGroups.js
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, bug :bug:

#1499 chore(build): suppress travis bugs
  .circleci/release.sh
  .travis.yml
Labels: chore :house:

#1521 fix(typeUtils): export typeUtils and move them to helpers
  packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.d.ts
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
  packages/patternfly-4/react-core/src/components/Button/Button.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataList.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListCheck.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListContent.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.d.ts
  packages/patternfly-4/react-core/src/components/Form/FormGroup.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOption.d.ts
  packages/patternfly-4/react-core/src/components/FormSelect/FormSelectOptionGroup.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.d.ts
  packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
  packages/patternfly-4/react-core/src/components/List/List.d.ts
  packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
  packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
  packages/patternfly-4/react-core/src/components/Nav/NavList.d.ts
  packages/patternfly-4/react-core/src/components/Page/PageSection.d.ts
  packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts
  packages/patternfly-4/react-core/src/components/Progress/Progress.d.ts
  packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
  packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Switch/Switch.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.d.ts
  packages/patternfly-4/react-core/src/components/Text/Text.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextList.d.ts
  packages/patternfly-4/react-core/src/components/Text/TextListItem.d.ts
  packages/patternfly-4/react-core/src/components/TextArea/TextArea.d.ts
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts
  packages/patternfly-4/react-core/src/components/Title/Title.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/helpers/index.ts
  packages/patternfly-4/react-core/src/helpers/typeUtils.ts
  packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/gridUtils.d.ts
  packages/patternfly-4/react-core/src/layouts/Level/Level.d.ts
  packages/patternfly-4/react-core/src/layouts/Split/Split.d.ts
  packages/patternfly-4/react-core/src/layouts/Stack/Stack.d.ts
  packages/patternfly-4/react-core/src/styles/gutters.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
Labels: PF4, enhancement :rocket:

#1524 chore(circle): give circleci more time to build docs [ci skip]
  .circleci/config.yml
Labels: infrastructure

#1013 docs(LoadingState): Add state loading with delay to storybook
  packages/patternfly-3/patternfly-react/src/components/LoadingState/LoadingState.stories.js
  packages/patternfly-3/patternfly-react/src/components/LoadingState/Stories/LoadableState.js
Labels: documentation :memo:

#1441 feat(table): add customizable actions for each row
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/KebabToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/ActionsColumn.js
  packages/patternfly-4/react-table/src/components/Table/Table.api.test.js
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.docs.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.test.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/examples/ActionsTable.js
  packages/patternfly-4/react-table/src/components/Table/examples/SimpleActionsTable.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.test.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
  packages/patternfly-4/react-table/src/test-helpers/data-sets.js
Labels: PF4, enhancement :rocket:

#1297 feat(Pagination): Introduce new PF4 pagination component
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.js
  packages/patternfly-4/react-core/src/components/Pagination/OptionsMenu.js
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.docs.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
  packages/patternfly-4/react-core/src/components/Pagination/ToggleTemplate.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
  packages/patternfly-4/react-core/src/components/Pagination/examples/PaginationBottom.js
  packages/patternfly-4/react-core/src/components/Pagination/examples/PaginationTop.js
  packages/patternfly-4/react-core/src/components/Pagination/index.d.ts
  packages/patternfly-4/react-core/src/components/Pagination/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, css review, enhancement :rocket:, ux review

#1503 fix(Table): Expandable row should not prevent select all checkbox fro…
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.test.js
Labels: PF4, bug :bug:

#1508 feat(Icon): Openshift icon
  packages/react-icons/build/customIcons.js
  packages/react-icons/build/generateIcons.js
  packages/react-icons/build/icons.js
Labels: enhancement :rocket:

#1530 fix(core): fix pagination tests
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
  packages/patternfly-4/react-integration/.gitignore
  packages/patternfly-4/react-integration/package.json
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
Labels: bug :bug:

#1369 fix(TypeAheadSelect): Fix input height overflow issue without breaking IE11 compatibility
  packages/patternfly-3/patternfly-react/less/type-ahead-select.less
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_type-ahead-select.scss
Labels: bug :bug:

#1540 chore(TableDoc): Update Documentation for for using 'title' prop in table cells.
  packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
  packages/patternfly-4/react-table/src/components/Table/Table.js
Labels: PF4, enhancement :rocket:

#1510 feat(Dropdown): add support for disabled dropdown menus
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/examples/DisabledDropdown.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
Labels: PF4, enhancement :rocket:

#1423 fix(tabs): Move TabContent to its own component
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
Labels: PF4, css review, p1

#1543 fix(tabs): remove d.ts file from tabContent
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.js
Labels: PF4

#1255 fix(build): Support running the test suite under Windows
  .editorconfig
  .gitattributes
  package.json
  packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
  packages/patternfly-3/patternfly-react/src/components/Filter/__mocks__/mockFilterExample.js
  packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSocialColumns.js
  packages/patternfly-3/patternfly-react/src/components/Table/__mocks__/mockClientPaginationTable.js
  packages/patternfly-3/patternfly-react/src/components/Toolbar/__mocks__/mockToolbarExample.js
  packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
  packages/patternfly-3/patternfly-react/src/components/Wizard/Stories/WizardExample.js
  packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
  packages/patternfly-4/react-styles/src/build/util.js
  packages/patternfly-4/react-tokens/build/generateTokens.test.js
  packages/react-codemods/transforms/pf3-pf4.button.test.js
  packages/react-codemods/transforms/pf3-pf4.js
  packages/react-codemods/transforms/pf3-pf4.test.js
  yarn.lock
Labels: PF4, chore :house:

#1453 fix(Modal): accessibility enhancements and other small fixes
  packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
  packages/patternfly-4/react-core/src/components/Modal/Modal.docs.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBox.test.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBox.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/examples/NoHeader.js
Labels: PF4, accessibility, enhancement :rocket:

#1350 build(sass): Inline the CSS of imported files in patternfly-react.scss
  packages/patternfly-3/patternfly-react/build/node-sass-tilde-importer.js
  packages/patternfly-3/patternfly-react/package.json
  yarn.lock
Labels: PF3, enhancement :rocket:, infrastructure

#1555 fix(codemod): fix tests failing due to prettier
  packages/react-codemods/transforms/pf3-pf4.button.test.js
  packages/react-codemods/transforms/pf3-pf4.test.js
Labels: chore :house:

#1551 fix: PF4 Fix HelperText definition in LoginForm
  packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.d.ts
Labels: PF4, bug :bug:

#1553 fix(typeUtils): fix transformers test
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
Labels: PF4, bug :bug:

#1556 build(tests): add misc test build target to travis
  .travis.yml
  package.json
Labels: chore :house:, infrastructure

#1563 fix(Modal): remove backdropOpen class from body when Modal is removed
  packages/patternfly-4/react-core/src/components/Modal/Modal.js
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.js
Labels: PF4, bug :bug:

#1542 feat(Table): pass rowData and extraData to table callbacks
  packages/patternfly-4/react-table/src/components/Table/ActionsColumn.js
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/index.d.ts
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js
Labels: PF4, enhancement :rocket:

#1560 fix(Chip, NavItem): Fixed Typescript definition file errors
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.d.ts
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.js
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Nav.tsx
Labels: PF4, bug :bug:

#1445 chore(title): title fixes and upgrades
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.js
  packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
  packages/patternfly-4/react-core/src/components/EmptyState/examples/SimpleEmptyState.js
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts
  packages/patternfly-4/react-core/src/components/Popover/PopoverHeader.js
  packages/patternfly-4/react-core/src/components/Title/Title.d.ts
  packages/patternfly-4/react-core/src/components/Title/Title.js
  packages/patternfly-4/react-core/src/components/Title/Title.test.tsx
  packages/patternfly-4/react-core/src/components/Title/Title.tsx
  packages/patternfly-4/react-core/src/components/Title/__snapshots__/Title.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Title/examples/TitleSizes.js
  packages/patternfly-4/react-core/src/components/Title/index.d.ts
  packages/patternfly-4/react-core/src/components/Title/index.js
  packages/patternfly-4/react-core/src/components/Title/index.ts
  packages/patternfly-4/react-core/tslint.json
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/css-variables.js
  packages/patternfly-4/react-docs/src/components/docs/docs.js
  packages/patternfly-4/react-docs/src/components/docs/docs.styles.js
  packages/patternfly-4/react-docs/src/components/docs/index.js
  packages/patternfly-4/react-docs/src/components/example/example.js
  packages/patternfly-4/react-docs/src/components/example/liveDemo.js
  packages/patternfly-4/react-docs/src/components/layouts/index.js
  packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
  packages/patternfly-4/react-docs/src/components/propsTableTs/propsTableTs.js
  packages/patternfly-4/react-docs/src/components/section/section.js
  packages/patternfly-4/react-docs/src/pages/index.js
  packages/patternfly-4/react-docs/src/pages/styles/icons.js
  packages/patternfly-4/react-docs/src/pages/styles/tokens.js
  packages/patternfly-4/react-integration/demo-app-ts/src/App.css
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-styles/src/StyleSheet.d.ts
Labels: PF4, TypeScript, accessibility, enhancement :rocket:

#1079 fix(DataList): Add dropdown and button actions to DataList
  packages/patternfly-4/react-core/src/components/DataList/DataList.docs.js
  packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
  packages/patternfly-4/react-core/src/components/DataList/examples/ActionsDataList.js
Labels: PF4, bug :bug:, css review, ux review

#1539 feat(PF4): Wizard
  package.json
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.docs.js
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.test.tsx
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardBody.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNav.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardToggle.tsx
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Wizard/examples/SimpleWizard.js
  packages/patternfly-4/react-core/src/components/Wizard/examples/Steps/SampleFormOne.js
  packages/patternfly-4/react-core/src/components/Wizard/examples/Steps/SampleFormTwo.js
  packages/patternfly-4/react-core/src/components/Wizard/examples/ValidationWizard.js
  packages/patternfly-4/react-core/src/components/Wizard/index.ts
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/tslint.json
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/propsTableTs/propsTableTs.js
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/Wizard.tsx
  packages/patternfly-4/react-integration/package.json
  scripts/generators/patternfly-4-component/index.js
  scripts/generators/patternfly-4-component/templates/component/component.tsx.hbs
  yarn.lock
Labels: PF4, css review, enhancement :rocket:, ux review

#1590 Bump @patternfly/patternfly versions to 1.0.240
  packages/patternfly-4/react-charts/package.json
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-styled-system/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-tokens/package.json
  packages/react-icons/package.json
  yarn.lock
Labels: PF4, chore :house:

#1593 fix(Dropdown): fix d.ts file to make props optional
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
Labels: PF4, bug :bug:

#1585 fix(NavItem): fix type definition
  packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts
Labels: PF4, bug :bug:

#1570 feat(core): clean tsconfigs, add defaultProps to TS-docs
  .circleci/config.yml
  .travis.yml
  jest.config.js
  package.json
  packages/patternfly-3/patternfly-react-wooden-tree/package.json
  packages/patternfly-4/react-charts/src/typeUtils.d.ts
  packages/patternfly-4/react-core/package.json
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.test.tsx
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.tsx
  packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/Modal.test.js
  packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/Title/Title.test.tsx
  packages/patternfly-4/react-core/src/components/Title/Title.tsx
  packages/patternfly-4/react-core/src/components/Title/index.ts
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNav.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardToggle.tsx
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Wizard/examples/SimpleWizard.js
  packages/patternfly-4/react-core/src/declarations.d.ts
  packages/patternfly-4/react-core/src/helpers/typeUtils.ts
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-core/src/tsconfig.dts.json
  packages/patternfly-4/react-core/tsconfig.base.json
  packages/patternfly-4/react-core/tsconfig.gen-dts.json
  packages/patternfly-4/react-core/tsconfig.jest.json
  packages/patternfly-4/react-core/tsconfig.json
  packages/patternfly-4/react-core/tsconfig.typecheck.json
  packages/patternfly-4/react-core/typings/react-styles.d.ts
  packages/patternfly-4/react-docs/.gitignore
  packages/patternfly-4/react-docs/build/transformTsDocs.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-docs/src/components/componentDocs/propsHelper.js
  packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
  packages/patternfly-4/react-docs/src/components/propsTableTs/propsTableTs.js
  packages/react-icons/src/typeUtils.d.ts
  tsconfig.json
  yarn.lock
Labels: PF4, infrastructure

#1591 feat(Switch): Add icon and fix labels
  packages/patternfly-4/react-core/src/components/Switch/Switch.js
  packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap
  packages/patternfly-4/react-core/src/components/Switch/examples/DisabledSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/SimpleSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/UncontrolledSwitch.js
  packages/react-icons/src/createIcon.js
Labels: PF4, accessibility, bug :bug:, css review

#343 feat(ModalPattern): Add ModalPattern and StatefulModalPattern components
  packages/patternfly-3/patternfly-react/src/components/Modal/Modal.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Modal.stories.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Patterns/ModalPattern.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Patterns/StatefulModalPattern.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Stories/ModalExampleStory.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Stories/ModalPatternExample.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Stories/ModalPatternExampleStory.js
  packages/patternfly-3/patternfly-react/src/components/Modal/Stories/index.js
  packages/patternfly-3/patternfly-react/src/components/Modal/index.js
Labels: enhancement :rocket:

#1604 refactor(Switch): Aria label reflects the message when on
  packages/patternfly-4/react-core/src/components/Switch/Switch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/DisabledSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/NoLabelSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/SimpleSwitch.js
  packages/patternfly-4/react-core/src/components/Switch/examples/UncontrolledSwitch.js
Labels: PF4, accessibility, enhancement :rocket:

#1520 feat(Table): support custom components in expandable rows
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.test.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/examples/CollapsibleTable.js
  packages/patternfly-4/react-table/src/components/Table/index.d.ts
  packages/patternfly-4/react-table/src/components/Table/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
  packages/patternfly-4/react-table/src/components/Table/utils/index.d.ts
  packages/patternfly-4/react-table/src/components/Table/utils/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
  packages/patternfly-4/react-table/src/components/Table/utils/utils.js
  packages/patternfly-4/react-table/src/components/Table/utils/utils.test.js
  packages/patternfly-4/react-table/src/test-helpers/data-helpers.js
Labels: PF4, enhancement :rocket:

#1565 feat(Cloud icons): Add new cloud icons
  packages/react-icons/build/customIcons.js
Labels: enhancement :rocket:

#1614 fix (Wizard): remove console.log from save
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
Labels: PF4, bug :bug:

#1613 fix(DataList): remove shadow-box
  packages/patternfly-4/react-core/src/components/DataList/DataList.js
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
Labels: PF4, enhancement :rocket:

#1594 docs(Form): update horizontal form example to pf core
  packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
Labels: PF4, enhancement :rocket:

#1526 feat(ContextSelector): Add PF4 ContextSelector Component
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.d.ts
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.docs.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.test.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorItem.d.ts
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorItem.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorItem.test.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorMenuList.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorMenuList.test.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorToggle.js
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorToggle.test.js
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.js.snap
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelectorItem.test.js.snap
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelectorMenuList.test.js.snap
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelectorToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/ContextSelector/contextSelectorConstants.js
  packages/patternfly-4/react-core/src/components/ContextSelector/examples/SimpleContextSelector.js
  packages/patternfly-4/react-core/src/components/ContextSelector/index.d.ts
  packages/patternfly-4/react-core/src/components/ContextSelector/index.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.js
  packages/patternfly-4/react-core/src/components/TextInput/TextInput.test.js
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/helpers/constants.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, accessibility, css review, enhancement :rocket:, ux review

#1623 fix(Table): reverts unnecessary fix
  packages/patternfly-4/react-table/src/components/Table/Body.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
Labels: PF4

#1619 fix(ts-fixes): ts definition changes
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.d.ts
  packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorItem.d.ts
  packages/patternfly-4/react-table/src/components/Table/index.d.ts
  packages/patternfly-4/react-table/src/components/Table/utils/index.d.ts
Labels: PF4, bug :bug:

#1631 Fixed PF4 link in README
  packages/patternfly-4/react-core/README.md
Labels: documentation :memo:

#1627 fix(DataList): set width and isExpanded to optional in d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListCell.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListToggle.d.ts
Labels: PF4, bug :bug:

#1647 Fixes typo hove->hover
  packages/patternfly-4/react-core/src/components/Button/Button.js
Labels: PF4, documentation :memo:

#1632 Improved function typings for PF4 <Pagination> component
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts
Labels: PF4, enhancement :rocket:

#1643 feat(Icons): Paper plane alt icon
  packages/react-icons/build/customIcons.js
Labels: enhancement :rocket:

#1625 fix(util.ts): Improve cross-browser compatibility of `isElementInView` and `sideElementIsOutOfView`
  packages/patternfly-4/react-core/src/helpers/util.test.js
  packages/patternfly-4/react-core/src/helpers/util.ts
Labels: PF4, bug :bug:

#1109 feat(BreadcrumbSwitcher): creating a BreadcrumbSwitcher component
  packages/patternfly-3/patternfly-react/less/breadcrumbswitcher.less
  packages/patternfly-3/patternfly-react/less/patternfly-react.less
  packages/patternfly-3/patternfly-react/package.json
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_breadcrumbswitcher-popover.scss
  packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.fixtures.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.stories.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.test.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcherHelper.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/__snapshots__/BreadcrumbSwitcher.test.js.snap
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSearchInput.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSwitcherPopover.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSwitcherToggler.js
  packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/index.js
  yarn.lock
Labels: css approved, enhancement :rocket:, ux approved

#1645 fix(InlineEdit): remove flickering of dropdown in an example
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/examples/EditableTable.js
Labels: PF4

#1648 fix(tooltip): trigger tooltip by mouse click or other events
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
  packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.test.js
  packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
Labels: PF4, bug :bug:
