Repository patternfly/patternfly-react, pull requests merged in 2019-04, with the labels that each got.

#1660 fix(misc): small bug fixes
  packages/patternfly-4/react-charts/src/components/LineChart/examples/SimpleChart.js
  packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
  packages/patternfly-4/react-docs/src/components/css-variables.js
Labels: PF4, bug :bug:

#1642 fix(pagination): add "per page" suffix in options
  packages/patternfly-4/react-core/src/components/Pagination/OptionsMenu.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
Labels: PF4, bug :bug:, css review

#1413 feat(Tabs): Allow tabbing of content outside Tabs
  packages/patternfly-4/react-core/src/components/Tabs/Tab.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tab.js
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/TabContent.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.docs.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.js
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tab.test.js.snap
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
  packages/patternfly-4/react-core/src/components/Tabs/examples/AccessibleSecondaryTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/examples/AccessibleTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/examples/SeparateTabContent.js
  packages/patternfly-4/react-core/src/components/Tabs/index.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/index.js
  packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, css review, enhancement :rocket:

#1487 feat(Select): add checkbox select variant
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelect.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.d.ts
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.test.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.d.ts
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.js
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.test.js
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Select/Select.docs.js
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/Select.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.test.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectGroup.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectOption.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/examples/CheckboxSelectInput.js
  packages/patternfly-4/react-core/src/components/Select/examples/GroupedCheckboxSelectInput.js
  packages/patternfly-4/react-core/src/components/Select/index.d.ts
  packages/patternfly-4/react-core/src/components/Select/index.js
  packages/patternfly-4/react-core/src/components/Select/selectConstants.js
  packages/patternfly-4/react-docs/ts-docs/ts-output.json
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
Labels: PF4, accessibility, css review, ux review

#1690 fix(Tabs): Use TabsVariant.nav and fix a minor HTML issue
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
  packages/patternfly-4/react-core/src/components/Tabs/examples/AccessibleSecondaryTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/examples/AccessibleTabs.js
  packages/patternfly-4/react-core/src/components/Tabs/index.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/index.js
Labels: bug :bug:

#1664 fix(Table): fix type-o in ICell Interface transform (from transfrom)
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
Labels: PF4, breaking change :boom:

#1728 fix(ChipGroup): remove unused prop badgeText from d.ts file
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.d.ts
Labels: PF4, breaking change :boom:, bug :bug:

#1694 fix(pagination): remove size attr from type="number" input
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
Labels: PF4, css review, enhancement :rocket:

#1729 fix(emptyState): add small/large modifiers
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.js
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.md
  packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.js
  packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
  packages/patternfly-4/react-core/src/components/EmptyState/index.d.ts
  packages/patternfly-4/react-core/src/components/EmptyState/index.js
Labels: PF4, enhancement :rocket:

#1745 Updated to border prop for compact table.
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
Labels: PF4, enhancement :rocket:

#1663 fix(table): Add optional types for table column
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
Labels: PF4, enhancement :rocket:

#1755 refactor(DataList): Refactor DataList based on changes in core
  packages/patternfly-4/react-core/src/components/DataList/DataList.md
  packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
  packages/patternfly-4/react-core/src/components/DataList/DataListCell.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListCell.js
  packages/patternfly-4/react-core/src/components/DataList/DataListCheck.js
  packages/patternfly-4/react-core/src/components/DataList/DataListContent.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListContent.js
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.js
  packages/patternfly-4/react-core/src/components/DataList/DataListItemCells.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListItemCells.js
  packages/patternfly-4/react-core/src/components/DataList/DataListItemRow.d.ts
  packages/patternfly-4/react-core/src/components/DataList/DataListItemRow.js
  packages/patternfly-4/react-core/src/components/DataList/DataListToggle.js
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
  packages/patternfly-4/react-core/src/components/DataList/index.d.ts
  packages/patternfly-4/react-core/src/components/DataList/index.js
Labels: PF4, enhancement :rocket:

#1748 Updated collapsable table demo for issue #1678
  packages/patternfly-4/react-table/src/components/Table/Table.md
Labels: PF4, enhancement :rocket:

#1652 fix(select): remove the custom override on width
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
Labels: PF4, enhancement :rocket:

#1665 fix(Nav): change onSelect and onToggle arg types from positional to single obj
  packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
Labels: PF4, bug :bug:

#1788 fix(Tabs): Move TabContent outside of Tabs div
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
Labels: PF4, bug :bug:, css review, current sprint

#1793 fix(react-core): Fixes console error with perPageSuffix (Issue #1784)
  packages/patternfly-4/react-core/src/components/Pagination/OptionsMenu.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
Labels: PF4, current sprint

#1799 fix(Modal): Remove extra Bullseye from Modal
  packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
Labels: PF4, bug :bug:, css review

#1763 fix(demo-app-ts): update typescript demo application
  packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/Wizard.tsx
Labels: PF4, bug :bug:

#1659 fix(Table): Fix Table component accessibility issues
  packages/patternfly-4/react-table/src/components/Table/Table.md
Labels: PF4, accessibility, enhancement :rocket:

#1685 feat(Expandable): Add PF4 Expandable Component
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.md
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.test.tsx
  packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
  packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Expandable/index.ts
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, css review, enhancement :rocket:, ux review

#1700 fix(Table): Add ability to center-align header and cell text
  packages/patternfly-4/react-table/src/components/Table/BodyCell.js
  packages/patternfly-4/react-table/src/components/Table/HeaderCell.js
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/textCenter.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
Labels: PF4, enhancement :rocket:

#1639 feat(Chip): add read-only chip, add single chip examples
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.js
  packages/patternfly-4/react-core/src/components/ChipGroup/Chip.test.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.js
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.md
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/Chip.test.js.snap
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.js.snap
Labels: PF4, css review, enhancement :rocket:

#1538 feat(clipboardcopy): add clipboardcopy to PF4
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.d.ts
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md
  packages/patternfly-4/react-core/src/components/ClipboardCopy/CopyButton.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/CopyButton.test.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ExpandedContent.d.ts
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ExpandedContent.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ExpandedContent.test.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ToggleButton.d.ts
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ToggleButton.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ToggleButton.test.js
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/CopyButton.test.js.snap
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ExpandedContent.test.js.snap
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ToggleButton.test.js.snap
  packages/patternfly-4/react-core/src/components/ClipboardCopy/index.d.ts
  packages/patternfly-4/react-core/src/components/ClipboardCopy/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, accessibility, css review, enhancement :rocket:, ux review

#1812 feat(card): adds card is-hoverable modifier prop
  packages/patternfly-4/react-core/src/components/Card/Card.d.ts
  packages/patternfly-4/react-core/src/components/Card/Card.js
  packages/patternfly-4/react-core/src/components/Card/Card.md
  packages/patternfly-4/react-core/src/components/Card/Card.test.js
  packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.js.snap
Labels: PF4, css review, ux review

#1797 feat(aboutmodal): make productName optional
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.md
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.js
Labels: PF4, css review, ux approved

#1818 feat(padding): add pagesection no padding props
  packages/patternfly-4/react-core/src/components/Page/Page.md
  packages/patternfly-4/react-core/src/components/Page/PageSection.d.ts
  packages/patternfly-4/react-core/src/components/Page/PageSection.js
  packages/patternfly-4/react-core/src/components/Page/PageSection.test.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageSection.test.js.snap
Labels: PF4, css review

#1829 add bodyWrapper type def
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
Labels: PF4, bug :bug:

#1820 refactor(Button): Add a inline modifier to a link Button
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.js.snap
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/patternfly-4/react-core/src/components/Button/Button.d.ts
  packages/patternfly-4/react-core/src/components/Button/Button.js
  packages/patternfly-4/react-core/src/components/Button/Button.md
  packages/patternfly-4/react-core/src/components/Button/Button.test.js
  packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/Chip.test.js.snap
  packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.js.snap
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
  packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
  packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap
  packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.js.snap
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  packages/patternfly-4/react-inline-edit-extension/src/components/CancelButton/__snapshots__/CancelButton.test.js.snap
  packages/patternfly-4/react-inline-edit-extension/src/components/ConfirmButton/__snapshots__/ConfirmButton.test.js.snap
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/__snapshots__/ConfirmButtons.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
Labels: PF4, css review, enhancement :rocket:

#1749 fix(grid): add missing props in d.ts
  packages/patternfly-4/react-core/src/layouts/Grid/Grid.d.ts
Labels: PF4, bug :bug:

#1511 feat(accordion): Add accordion to pf
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.js
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.md.tmp
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.js
  packages/patternfly-4/react-core/src/components/Accordion/__snapshots__/Accordion.test.js.snap
  packages/patternfly-4/react-core/src/components/Accordion/index.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/index.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, css review, enhancement :rocket:, ux review

#1827 refactor(Select): add selected state to single select
  packages/patternfly-4/react-core/src/components/Select/SelectOption.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.test.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.js.snap
Labels: PF4, css review, enhancement :rocket:

#1786 feat(Wizard): support for full width and full height
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardBody.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNav.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardToggle.tsx
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Wizard/index.ts
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, enhancement :rocket:

#1762 Feat/checkbox ts2
  packages/patternfly-4/react-core/README.md
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.test.tsx
  packages/patternfly-4/react-core/src/components/Avatar/Avatar.tsx
  packages/patternfly-4/react-core/src/components/Avatar/index.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.tsx
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
  packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Checkbox/index.d.ts
  packages/patternfly-4/react-core/src/components/Checkbox/index.js
  packages/patternfly-4/react-core/src/components/Checkbox/index.ts
Labels: PF4, chore :house:

#1828 feat(Tab): Render Tab as <a> instead of <button> if it contains an href prop
  packages/patternfly-4/react-core/src/components/Tabs/Tab.d.ts
  packages/patternfly-4/react-core/src/components/Tabs/Tab.js
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
  packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.js
  packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
Labels: PF4, enhancement :rocket:

#1811 feat(BackgroundImage): update background image component
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.md
  packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
  packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.js
  packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.md
  packages/patternfly-4/react-docs/gatsby-node.js
Labels: PF4, css review

#1686 feat(Skip To Content): Added Skip To Content Component and Page breadcrumb styling
  packages/patternfly-4/react-core/src/components/Page/Page.d.ts
  packages/patternfly-4/react-core/src/components/Page/Page.js
  packages/patternfly-4/react-core/src/components/Page/Page.test.js
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
  packages/patternfly-4/react-core/src/components/SkipToContent/SkipToContent.md
  packages/patternfly-4/react-core/src/components/SkipToContent/SkipToContent.test.tsx
  packages/patternfly-4/react-core/src/components/SkipToContent/SkipToContent.tsx
  packages/patternfly-4/react-core/src/components/SkipToContent/__snapshots__/SkipToContent.test.tsx.snap
  packages/patternfly-4/react-core/src/components/SkipToContent/examples/SimpleSkipToContent.js
  packages/patternfly-4/react-core/src/components/SkipToContent/examples/SimpleSkipToContent.md
  packages/patternfly-4/react-core/src/components/SkipToContent/index.ts
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/demos/PageLayout/PageLayout.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutManualNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutManualNav.md
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
  packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.md
Labels: PF4, css review, enhancement :rocket:, rc.1, ux review

#1843 feat(DropdownToggle): Add splitButtonItems prop, DropdownToggleCheckbox and split-button dropdown examples
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.js
  packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.test.js
  packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
  packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.js.snap
  packages/patternfly-4/react-core/src/components/Dropdown/index.d.ts
  packages/patternfly-4/react-core/src/components/Dropdown/index.js
Labels: PF4, enhancement :rocket:

#1833 (Fixes #1455) RC.1 updates for Progress Bar.
  package.json
  packages/patternfly-4/react-core/src/components/Progress/Progress.js
  packages/patternfly-4/react-core/src/components/Progress/Progress.md
  packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
  packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
  packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
Labels: accessibility, current sprint, rc.1

#1754 PF4 Wizard: Controlled wizard (custom footer)
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
  packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardBody.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardContext.ts
  packages/patternfly-4/react-core/src/components/Wizard/WizardFooter.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNav.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/patternfly-4/react-core/src/components/Wizard/WizardToggle.tsx
  packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Wizard/examples/FinishedStep.js
  packages/patternfly-4/react-core/src/components/Wizard/examples/SampleForm.js
  packages/patternfly-4/react-core/src/components/Wizard/examples/SampleFormTwo.js
  packages/patternfly-4/react-core/src/components/Wizard/index.ts
  packages/patternfly-4/react-docs/plugins/gatsby-transformer-react-examples/CHANGELOG.md
  packages/patternfly-4/react-docs/src/templates/mdxTemplate.js
Labels: PF4, enhancement :rocket:

#1856 fix(Alert): Change title type from string to node
  packages/patternfly-4/react-core/src/components/Alert/Alert.js
Labels: PF4, bug :bug:

#1814 Feat(Options Menu): Add Options Menu Component
  packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.md
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.test.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItemGroup.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItemGroup.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuSeparator.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuSeparator.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
  packages/patternfly-4/react-core/src/components/OptionsMenu/index.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/index.js
  packages/patternfly-4/react-core/src/components/OptionsMenu/optionsMenuConstants.d.ts
  packages/patternfly-4/react-core/src/components/OptionsMenu/optionsMenuConstants.js
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.js
  packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.js
  packages/patternfly-4/react-core/src/components/Pagination/ToggleTemplate.js
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/helpers/util.ts
Labels: PF4, css review, enhancement :rocket:, ux approved

#1839 feat(Select): add typeahead variants (single and multi)
  packages/patternfly-4/react-core/src/components/Select/CheckboxSelectInput.js
  packages/patternfly-4/react-core/src/components/Select/GroupedCheckboxSelectInput.js
  packages/patternfly-4/react-core/src/components/Select/Select.d.ts
  packages/patternfly-4/react-core/src/components/Select/Select.js
  packages/patternfly-4/react-core/src/components/Select/Select.md
  packages/patternfly-4/react-core/src/components/Select/Select.test.js
  packages/patternfly-4/react-core/src/components/Select/SelectOption.js
  packages/patternfly-4/react-core/src/components/Select/SelectToggle.js
  packages/patternfly-4/react-core/src/components/Select/SingleSelect.js
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.js.snap
  packages/patternfly-4/react-core/src/components/Select/selectConstants.js
Labels: PF4, accessibility, css review, ux approved

#1852 feat(accordion): Introduce accordion
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.js
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.md
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.js
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.js
  packages/patternfly-4/react-core/src/components/Accordion/__snapshots__/Accordion.test.js.snap
  packages/patternfly-4/react-core/src/components/index.ts
Labels: PF4, accessibility, enhancement :rocket:

#1858 feat(Table): Add columnTransforms, classNames decorator, Visibility constants, and hidden/visible breakpoints example
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
Labels: PF4, enhancement :rocket:

#1860 Fixes demo to show single and multiple expand behavior
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.md
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.js
  packages/patternfly-4/react-core/src/components/index.ts
Labels: css review, rc.1, ux approved

#1859 feat(About modal): Added support for more user control over content
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.md
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.d.ts
  packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.js
  packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.js.snap
Labels: rc.1

#1851 feat(table): compound expansion
  packages/patternfly-4/react-table/src/components/Table/BodyCell.js
  packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js
  packages/patternfly-4/react-table/src/components/Table/Table.d.ts
  packages/patternfly-4/react-table/src/components/Table/Table.js
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/Table.test.js
  packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
  packages/patternfly-4/react-table/src/components/Table/demo/DemoSortableTable.js
  packages/patternfly-4/react-table/src/components/Table/index.js
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/compoundExpand.js
  packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
  packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
  packages/patternfly-4/react-table/src/components/Table/utils/utils.js
  packages/patternfly-4/react-table/src/components/Table/utils/utils.test.js
Labels: PF4, accessibility, css review, enhancement :rocket:, p1, rc.1, ux approved

#1870 fix(Accordion): Wrong import in definition file
  packages/patternfly-4/react-core/src/components/Accordion/Accordion.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.d.ts
  packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.d.ts
Labels: PF4, bug :bug:

#1880 fix(ApplicationLauncher): rename ariaHasPopup attribute to aria-h…
  packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.js
Labels: PF4, bug :bug:
