Repository patternfly/patternfly-react, pull requests merged in 2020-02, with the labels that each got.

#3635 fix(Catalog view extension): Many styles on examples stopped working
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogItemHeader/examples/catalogItemHeader.css
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/catalogTile.css
  packages/patternfly-4/react-catalog-view-extension/src/components/VerticalTabs/examples/verticalTab.css
Labels: PF4, bug :bug:

#3595 fix(Page & PageHeader): adds optional "role" prop
  packages/patternfly-4/react-core/src/components/Page/Page.tsx
  packages/patternfly-4/react-core/src/components/Page/PageHeader.tsx
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/page.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
Labels: accessibility

#3634 chore(github): fix broken link in issue template
  .github/ISSUE_TEMPLATE.md
Labels: chore :house:, infrastructure

#3652 docs(Demo): fixed the TextInput type in filter table demo
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
Labels: documentation :memo:

#3660 fix(Slider): Add limit for lowest possible value of slider
  packages/patternfly-3/patternfly-react/src/components/Slider/Slider.js
Labels: PF3, bug :bug:

#3712 chore(build): use machine instance
  .circleci/config.yml
  .eslintignore
  .eslintrc-md.json
  .gitignore
  package.json
  packages/patternfly-4/react-core/src/components/DataToolbar/examples/DataToolbar.md
  packages/patternfly-4/react-core/src/components/Drawer/examples/Drawer.md
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
  packages/patternfly-4/react-core/src/layouts/index.js
  packages/patternfly-4/react-core/src/layouts/index.ts
  packages/patternfly-4/react-docs/package.json
Labels: infrastructure

#3721 Chore - lint react topology
  package.json
  packages/patternfly-4/react-topology/build/copyStyles.js
  packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
  packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.test.tsx
  packages/patternfly-4/react-topology/src/components/TopologySideBar/__snapshots__/TopologySideBar.test.tsx.snap
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ProjectToolbar.js
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ViewToolbar.js
Labels: infrastructure

#3714 chore(react-catalog-view-extension): fix linting errors
  .eslintrc.json
  package.json
  packages/patternfly-4/react-catalog-view-extension/node-sass-patternfly-importer.js
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogItemHeader/CatalogItemHeader.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.test.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTileBadge.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
  packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategoryItem.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/PropertiesSidePanel/PropertyItem.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/VerticalTabs/VerticalTabsTab.tsx
  packages/patternfly-4/react-catalog-view-extension/src/helpers/util.test.js
  packages/patternfly-4/react-catalog-view-extension/src/helpers/util.ts
Labels: infrastructure

#3729 Table: support for truncated column headers
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/wrappable.ts
Labels: css review, enhancement :rocket:

#3715 chore(react-docs): resolved existing linting errors
  .eslintcache
  package.json
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-docs/gatsby-config.js
  packages/patternfly-4/react-docs/gatsby-node.js
  packages/patternfly-4/react-docs/src/pages/icons.js
  packages/patternfly-4/react-docs/src/pages/index.js
Labels: infrastructure

#3711 fix(Select): handle undefined default for checkbox select
  packages/patternfly-4/react-core/src/components/Select/Select.tsx
  packages/patternfly-4/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
Labels: PF4

#3710 feat(DataToolbar): update html structure to match core
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbar.test.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
  packages/patternfly-4/react-docs/package.json
Labels: PF4, css review

#3601 feat(Popover): add min-width override property
  packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
  packages/patternfly-4/react-core/src/components/Popover/__tests__/Popover.test.tsx
  packages/patternfly-4/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
Labels: css review

#3717 chore(lint-react-inline-edit-extension): resolve linting errors
  .eslintcache
  .eslintrc.json
  package.json
  packages/patternfly-4/react-inline-edit-extension/build/copyStyles.js
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableRowWrapper.d.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableRowWrapper.js
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableTableBody.d.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableTableBody.js
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/utils/formatters/inlineEditFormatterFactory.d.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.js
Labels: infrastructure

#3719 chore(react-styled-system): fixed linter errors
  package.json
  packages/patternfly-4/react-integration/cypress/integration/tableeditable.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.d.ts
  packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.js
Labels: infrastructure

#3723 Chore/lint react styles
  .eslintignore
  package.json
  packages/patternfly-4/react-styles/.eslintrc.json
  packages/patternfly-4/react-styles/scripts/copyStyles.js
  packages/patternfly-4/react-styles/src/StyleSheet.d.ts
  packages/patternfly-4/react-styles/src/StyleSheet.js
  packages/patternfly-4/react-styles/src/build/jest/snapshot-serializer/cssPropertyOverrides.js
  packages/patternfly-4/react-styles/src/build/jest/snapshot-serializer/cssUtils.js
  packages/patternfly-4/react-styles/src/build/jest/snapshot-serializer/reactUtils.js
  packages/patternfly-4/react-styles/src/build/jest/snapshot-serializer/serializer.js
  packages/patternfly-4/react-styles/src/build/jest/transform.js
  packages/patternfly-4/react-styles/src/build/loader/index.js
  packages/patternfly-4/react-styles/src/build/util.js
  packages/patternfly-4/react-styles/src/generateClasses.js
  packages/patternfly-4/react-styles/src/removeTS.js
  packages/patternfly-4/react-styles/src/server.js
  packages/patternfly-4/react-styles/src/utils.js
Labels: infrastructure

#3725 Chore/lint react tokens
  package.json
  packages/patternfly-4/react-tokens/src/generateTokens.js
  packages/patternfly-4/react-tokens/src/generateTokens.test.js
  packages/patternfly-4/react-tokens/src/templates/d.ts.js
  packages/patternfly-4/react-tokens/src/templates/esm.js
Labels: infrastructure

#3755 fix(beta): beta warning for datatoolbar, cleanup
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-docs/src/pages/icons.js
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx
  packages/patternfly-4/react-table/src/components/Table/Table.tsx
Labels: PF4

#3726 chore(react-virtualized-extension): resolved linter errors
  .circleci/config.yml
  package.json
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.test.tsx
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/accessibilityOverscanIndicesGetter.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/defaultOverscanIndicesGetter.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/utils/calculateSizeAndPositionDataAndUpdateScrollOffset.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/utils/createCallbackMemoizer.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/utils/requestAnimationTimeout.ts
  packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/utils/updateScrollIndexHelper.ts
  packages/patternfly-4/react-virtualized-extension/src/declarations.d.ts
Labels: infrastructure

#3761 Version fix 3759
  packages/patternfly-4/react-docs/package.json
  packages/patternfly-4/react-inline-edit-extension/package.json
  packages/patternfly-4/react-table/package.json
  packages/patternfly-4/react-topology/package.json
  packages/patternfly-4/react-virtualized-extension/package.json
  packages/react-icons/package.json
Labels: infrastructure

#3587 feat(card): add selectable and selected variation
  packages/patternfly-4/react-core/src/components/Card/Card.tsx
  packages/patternfly-4/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/patternfly-4/react-core/src/components/Card/examples/Card.md
  packages/patternfly-4/react-core/src/helpers/constants.ts
  packages/patternfly-4/react-integration/cypress/integration/card.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: css review

#3758 Remove width attr from BackgroundImage filter element
  packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.tsx
  packages/patternfly-4/react-core/src/components/BackgroundImage/__tests__/Generated/__snapshots__/BackgroundImage.test.tsx.snap
  packages/patternfly-4/react-core/src/components/BackgroundImage/__tests__/__snapshots__/BackgroundImage.test.tsx.snap
Labels: PF4

#3706 fix(switch): avoid switch id override by props
  packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
  packages/patternfly-4/react-integration/cypress/integration/switch.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SwitchDemo/SwitchDemo.tsx
Labels: bug :bug:

#3534 fix(pagination): calculate navigation input according to last page
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
Labels: css review

#3820 docs(select): fix panel checkbox labels
  packages/patternfly-4/react-core/src/components/Select/examples/Select.md
Labels: documentation :memo:

#3837 fix(readme): update readme to match new guidelines
  README.md
Labels: documentation :memo:

#3839 chore(inputgroup): update docs to be more readable
  packages/patternfly-4/react-core/src/components/InputGroup/examples/InputGroup.md
  packages/patternfly-4/react-core/src/layouts/Grid/examples/Grid.md
  yarn.lock
Labels: PF4, documentation :memo:, enhancement :rocket:
