Repository patternfly/patternfly-react, pull requests merged in 2020-09, with the labels that each got.

#4759 chore(release notes):Fixed release notes
  packages/react-docs/RELEASE-NOTES.md
Labels: chore :house:

#4778 header cell information tooltip/popover
  packages/react-core/src/components/Popover/index.ts
  packages/react-core/src/components/Tooltip/index.ts
  packages/react-integration/cypress/integration/tablesimple.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleDemo.tsx
  packages/react-table/src/components/Table/HeaderCellInfoWrapper.tsx
  packages/react-table/src/components/Table/base/header-row.tsx
  packages/react-table/src/components/Table/base/types.tsx
  packages/react-table/src/components/Table/examples/Table.md
Labels: css review

#4788 Add aria-labels to tooltip example checkboxes
  packages/react-core/src/components/Tooltip/examples/Tooltip.md
Labels: accessibility

#4789 Add href to nav examples
  packages/react-core/src/components/Nav/examples/Nav.md
Labels: accessibility

#4761 feat(Card): add ability to customize card title and support heading element
  packages/react-core/src/components/Card/CardTitle.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: accessibility

#4757 feat(Toolbar): add insets property
  packages/react-core/src/components/Toolbar/Toolbar.tsx
  packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-integration/cypress/integration/toolbar.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
Labels: css review, ux review

#4771 feat(Drawer): add bottom panel variation
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/examples/Drawer.md
  packages/react-integration/cypress/integration/drawer.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
Labels: css review, ux review

#4739 improvement(NotificationDrawer): Add x close button to notification drawer
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx
  packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
  packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
  packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts
  packages/react-integration/cypress/integration/notificationdrawergroups.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerBasicDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerGroupsDemo.tsx
Labels: css review, ux review

#4775 Add LabelGroup component
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/LabelGroup/LabelGroup.tsx
  packages/react-core/src/components/LabelGroup/__tests__/Generated/LabelGroup.test.tsx
  packages/react-core/src/components/LabelGroup/__tests__/Generated/__snapshots__/LabelGroup.test.tsx.snap
  packages/react-core/src/components/LabelGroup/__tests__/LabelGroup.test.tsx
  packages/react-core/src/components/LabelGroup/__tests__/__snapshots__/LabelGroup.test.tsx.snap
  packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
  packages/react-core/src/components/LabelGroup/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/label.spec.ts
  packages/react-integration/cypress/integration/labelgroup.spec.ts
  packages/react-integration/cypress/integration/labelgroupdefaultisopen.spec.ts
  packages/react-integration/cypress/integration/labelgroupvertical.spec.ts
  packages/react-integration/cypress/integration/labelgroupwithcategory.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupDefaultIsOpenDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupVerticalDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupWithCategoryDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4755 feat(Skeleton): add skeleton component, examples, tests
  packages/react-core/src/components/Skeleton/Skeleton.tsx
  packages/react-core/src/components/Skeleton/__tests__/Skeleton.test.tsx
  packages/react-core/src/components/Skeleton/__tests__/__snapshots__/Skeleton.test.tsx.snap
  packages/react-core/src/components/Skeleton/examples/Skeleton.md
  packages/react-core/src/components/Skeleton/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/skeleton.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/SkeletonDemo/SkeletonDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, enhancement :rocket:, ux approved

#4642 feat(Select): add support for favourites
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/SelectOption.tsx
  packages/react-core/src/components/Select/SelectToggle.tsx
  packages/react-core/src/components/Select/__tests__/Select.test.tsx
  packages/react-core/src/components/Select/__tests__/SelectOption.test.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/SelectOption.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-core/src/components/Select/selectConstants.tsx
  packages/react-core/src/helpers/util.ts
  packages/react-integration/cypress/integration/select.spec.ts
  packages/react-integration/cypress/integration/selectfavorites.spec.ts
  packages/react-integration/cypress/integration/tableeditable.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectFavoritesDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#4796 fix(tabs): conditionally render aria-controls when mountOnEnter
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-integration/cypress/integration/tabdemo.spec.ts
Labels: accessibility

#4855 feat(select): pass chip group props on typeaheadmulti variant
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: ux review

#4864 chore(Select): Clean up some typeahead behaviors
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectToggle.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/SelectToggle.test.tsx.snap
Labels: accessibility, ux review

#4837 feat(react-core-button): add isLoading and spinnerAriaValueText properties
  packages/react-core/src/components/Button/Button.tsx
  packages/react-core/src/components/Button/__tests__/Button.test.tsx
  packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/react-core/src/components/Button/examples/Button.md
  packages/react-integration/cypress/integration/button.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
Labels: css review, ux review

#4832 feat(react-core-tabs): add support for light scheme variant in Tabs && TabContent
  packages/react-core/src/components/Tabs/TabContent.tsx
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-integration/cypress/integration/tabdemo.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
Labels: css review

#4873 added chipGroupMain div, updated snapshots
  packages/react-core/src/components/ChipGroup/ChipGroup.tsx
  packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
Labels: css review

#4747 fix: Do not handle modified clicks on VerticalNav links
  packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
  packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
Labels: PF3

#4842 feat(Progress): added truncation
  packages/react-core/src/components/Modal/ModalBoxTitle.tsx
  packages/react-core/src/components/Progress/Progress.tsx
  packages/react-core/src/components/Progress/ProgressContainer.tsx
  packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/Progress.test.tsx.snap
  packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/ProgressContainer.test.tsx.snap
  packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap
  packages/react-core/src/components/Progress/examples/Progress.md
  packages/react-core/src/components/Tooltip/Tooltip.tsx
  packages/react-integration/cypress/integration/progress.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ProgressDemo/ProgressDemo.tsx
  packages/react-table/src/components/Table/BodyCell.tsx
  packages/react-table/src/components/Table/HeaderCell.tsx
  packages/react-table/src/components/Table/TableText.tsx
Labels: css review, ux review

#4772 feat(Select): Added support for Divider in Select
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-core/src/helpers/util.ts
  packages/react-integration/cypress/integration/select.spec.ts
  packages/react-integration/cypress/integration/selectfavorites.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: ux approved
