Repository patternfly/patternfly-react, pull requests merged in 2020-01, with the labels that each got.

#3444 fix(clipboardcopy): set type of copy and toggle buttons to 'button'
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
  packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyToggle.tsx
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyButton.test.tsx.snap
  packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyToggle.test.tsx.snap
Labels: css review

#3447 fix(DataList): properly assign selectable and selected classes
  packages/patternfly-4/react-core/src/components/DataList/DataList.tsx
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
  packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
Labels: PF4, bug :bug:

#3433 Page: add ability to customize screen reader label
  packages/patternfly-4/react-core/src/components/Page/Page.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
Labels: accessibility

#3455 feat(ChipGroup): add closable chip-group
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.test.tsx
  packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx
  packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/ChipGroup/examples/ChipGroup.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-integration/cypress/integration/chipgrouptoolbar.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupToolbarDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review

#3448 Use direct paths to react-icons in prod build
  packages/patternfly-4/react-core/.babelrc
  packages/patternfly-4/react-core/babel.config.js
  packages/patternfly-4/react-core/package.json
Labels: PF4, bug :bug:, infrastructure

#3474 Lint md code blocks 3469
  .circleci/config.yml
  .eslintignore
  .eslintrc_md.json
  package.json
  packages/patternfly-4/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/patternfly-4/react-core/src/experimental/components/Drawer/examples/Drawer.md
  packages/patternfly-4/react-styles/README.md
  packages/patternfly-4/react-table/README.md
  packages/patternfly-4/react-table/src/components/Table/Table.md
  packages/patternfly-4/react-tokens/README.md
  packages/patternfly-4/react-topology/README.md
  yarn.lock
Labels: infrastructure

#3477 add onFormatChange handler
  packages/patternfly-3/patternfly-react/src/components/Slider/Slider.js
  packages/patternfly-3/patternfly-react/src/components/Slider/Slider.stories.js
  packages/patternfly-3/patternfly-react/src/components/Slider/__snapshots__/Slider.test.js.snap
Labels: PF3, bug :bug:

#3472 fix(pagination): disable navigation input if page is equal to zero
  packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: bug :bug:, ux approved

#3422 fix(DataToolbar): add and remove some modifiers to match core
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
Labels: css review

#3493 fix(linting): eslint for *.md file fixes
  packages/patternfly-4/react-catalog-view-extension/README.md
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/CatalogTile.md
  yarn.lock
Labels: infrastructure

#3499 fix(PageHeader): removing redundant role="banner" attribute
  packages/patternfly-4/react-core/src/components/Page/PageHeader.tsx
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageHeader.test.tsx.snap
Labels: accessibility

#3485 Remove listing of icons while under construction
  .github/stale.yml
  packages/patternfly-4/react-docs/src/pages/icons.js
Labels: documentation :memo:

#3516 chore(Spinner, DataToolbar, Divider, OverflowMenu): Promote Spinner, DataToolbar, Divider and OverflowMenu from experimental
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbar.test.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarExpandableContent.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarFilter.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarItem.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarToggleGroup.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-core/src/components/DataToolbar/examples/DataToolbar.md
  packages/patternfly-4/react-core/src/components/DataToolbar/index.ts
  packages/patternfly-4/react-core/src/components/Divider/Divider.md
  packages/patternfly-4/react-core/src/components/Divider/Divider.test.tsx
  packages/patternfly-4/react-core/src/components/Divider/Divider.tsx
  packages/patternfly-4/react-core/src/components/Divider/__snapshots__/Divider.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Divider/index.ts
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenu.test.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenu.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuContent.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuContext.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuControl.test.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuControl.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuGroup.test.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuGroup.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuItem.test.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/OverflowMenuItem.tsx
  packages/patternfly-4/react-core/src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OverflowMenu/__snapshots__/OverflowMenuControl.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OverflowMenu/__snapshots__/OverflowMenuGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OverflowMenu/__snapshots__/OverflowMenuItem.test.tsx.snap
  packages/patternfly-4/react-core/src/components/OverflowMenu/examples/OverflowMenu.md
  packages/patternfly-4/react-core/src/components/OverflowMenu/index.ts
  packages/patternfly-4/react-core/src/components/Spinner/Spinner.test.tsx
  packages/patternfly-4/react-core/src/components/Spinner/Spinner.tsx
  packages/patternfly-4/react-core/src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Spinner/examples/Spinner.md
  packages/patternfly-4/react-core/src/components/Spinner/index.ts
  packages/patternfly-4/react-core/src/components/Tabs/TabButton.tsx
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
  packages/patternfly-4/react-core/src/demos/PaginationTable.md
  packages/patternfly-4/react-core/src/demos/TableEmptyStatesDemo.md
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DividerDemo/DividerDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/OverflowMenuDemo/OverflowMenuDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SpinnerDemo/SpinnerDemo.tsx
Labels: chore :house:

#3295 Coverage for Cypress tests
  .circleci/config.yml
  .circleci/copy-docs.sh
  package.json
  packages/patternfly-4/react-integration/.gitignore
  packages/patternfly-4/react-integration/cypress.json
  packages/patternfly-4/react-integration/cypress/integration/areachartcolor.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/areachartsparkline.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/areachartstacked.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/barchartcolorzoom.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/barchartpurple.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/barchartsimple.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/button.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/chipgroup.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/chipgroupdefaultisopen.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/datatoolbar.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donutbottomlegend.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donutcolorwithrightlegend.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donutrightlegend.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donutsmall.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donutsmallbottomlegend.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donutsmallrightlegend.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilization.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationgreenstaticright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationinvertedright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsimpleright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsimplerightgreen.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsmall.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsmallright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsmallstatic.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsmallstaticbottom.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationsmallstaticright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationstatic.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationstaticbottom.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationstaticinvertedright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/donututilizationstaticright.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/drawer.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/linechartcolor.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/linechartgreenzoom.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/linechartsimple.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/login-page.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/modal.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/nav.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/overflowmenu.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/pieblue.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/piecolor.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/pieorange.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/stackchartblue.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/stackchartgold.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/stackchartverticalcolor.spec.ts
  packages/patternfly-4/react-integration/cypress/integration/tableheaderswrappable.spec.ts
  packages/patternfly-4/react-integration/package.json
  packages/patternfly-4/react-integration/scripts/junit2html.js
  packages/patternfly-4/react-integration/webpack.config.js
  yarn.lock
Labels: infrastructure, integration tests

#3525 feat(pf4): Use absolute import paths for react core in pf4 packages.
  packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategory.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategoryItem.tsx
  packages/patternfly-4/react-catalog-view-extension/src/components/PropertiesSidePanel/PropertyItem.tsx
  packages/patternfly-4/react-core/src/components/Wizard/examples/SampleForm.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbar.js
  packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbarSection.js
  packages/patternfly-4/react-docs/src/pages/icons.js
  packages/patternfly-4/react-docs/src/pages/index.js
  packages/patternfly-4/react-inline-edit-extension/src/components/CancelButton/CancelButton.js
  packages/patternfly-4/react-inline-edit-extension/src/components/ConfirmButton/ConfirmButton.js
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/InlineEdit.api.test.js
  packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableTableBody.d.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.d.ts
  packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.js
  packages/patternfly-4/react-integration/demo-app-ts/src/common/State.ts
  packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx
  packages/patternfly-4/react-table/src/components/Table/CollapseColumn.tsx
  packages/patternfly-4/react-table/src/components/Table/RowWrapper.tsx
  packages/patternfly-4/react-table/src/components/Table/Table.tsx
  packages/patternfly-4/react-table/src/components/Table/utils/decorators/compoundExpand.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ItemDetails.js
  packages/patternfly-4/react-topology/src/components/TopologyView/examples/ProjectToolbar.js
Labels: infrastructure

#3580 chore(DataToolbar): Revert promotion of Datatoolbar from Experimental
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.test.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/index.ts
  packages/patternfly-4/react-core/src/experimental/components/index.ts
  packages/patternfly-4/react-core/src/helpers/util.ts
  packages/patternfly-4/react-docs/gatsby-browser.js
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx
Labels: chore :house:

#3531 feat(AlertGroup): Add alert group component
  packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
  packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
  packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Alert/examples/Alert.md
  packages/patternfly-4/react-core/src/components/AlertGroup/AlertGroup.test.tsx
  packages/patternfly-4/react-core/src/components/AlertGroup/AlertGroup.tsx
  packages/patternfly-4/react-core/src/components/AlertGroup/AlertGroupInline.tsx
  packages/patternfly-4/react-core/src/components/AlertGroup/__snapshots__/AlertGroup.test.tsx.snap
  packages/patternfly-4/react-core/src/components/AlertGroup/examples/AlertGroup.md
  packages/patternfly-4/react-core/src/components/AlertGroup/index.ts
  packages/patternfly-4/react-core/src/components/index.ts
  packages/patternfly-4/react-integration/cypress/integration/alertgroup.spec.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertGroupDemo/AlertGroupDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux approved

#3590 chore(Release notes): Update release notes for 2020.01
  RELEASE-NOTES.md
Labels: chore :house:

#3593 fix(a11y): fix a11y errors and enable a11y in CI
  .circleci/config.yml
  .circleci/copy-docs.sh
  .circleci/index.html
  .circleci/upload-docs.sh
  .circleci/upload-preview.js
  .gitignore
  package.json
  packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/examples/FilterSidePanel.md
  packages/patternfly-4/react-core/src/components/Card/examples/Card.md
  packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
  packages/patternfly-4/react-core/src/components/DataList/examples/DataList.md
  packages/patternfly-4/react-core/src/components/Form/examples/Form.md
  packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.tsx
  packages/patternfly-4/react-core/src/components/LoginPage/examples/LoginPage.md
  packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
  packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/patternfly-4/react-core/src/components/Popover/examples/Popover.md
  packages/patternfly-4/react-core/src/components/Select/examples/Select.md
  packages/patternfly-4/react-core/src/components/Tooltip/examples/Tooltip.md
  packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md
  packages/patternfly-4/react-docs/package.json
  yarn.lock
Labels: accessibility, infrastructure

#3612 Column functions are not always equal
  packages/patternfly-4/react-table/src/components/Table/base/columns-are-equal.ts
Labels: PF4, bug :bug:

#3623 Changed ouia variable name in localStorage in order to comply with spec
  packages/patternfly-4/react-core/src/components/withOuia/ouia.ts
Labels: infrastructure

#3621 feat(radio/check): add support for optional description
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.tsx
  packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
  packages/patternfly-4/react-core/src/components/Checkbox/examples/Checkbox.md
  packages/patternfly-4/react-core/src/components/Radio/Radio.test.tsx
  packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
  packages/patternfly-4/react-core/src/components/Radio/examples/Radio.md
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CheckboxDemo/CheckboxDemo.tsx
  packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/RadioDemo/RadioDemo.tsx
Labels: css review
