Repository patternfly/patternfly-react, pull requests merged in 2020-12, with the labels that each got.

#5193 feat(Drawer): add splitter feature
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/examples/Drawer.md
  packages/react-integration/cypress/integration/drawer.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
Labels: PF4, accessibility, css review, ux review

#5113 feat(descriptionList): add suport to auto fit
  packages/react-core/src/components/DescriptionList/DescriptionList.tsx
  packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
  packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap
  packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
  packages/react-integration/cypress/integration/descriptionlist.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListDemo.tsx
Labels: css review

#5211 Menu: Let consumer add SearchInput/TextInput
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuContent.tsx
  packages/react-core/src/components/Menu/MenuInput.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/index.ts
  packages/react-core/src/components/TextInput/TextInput.tsx
Labels: css review

#5128 (fix)TreeView: fix various bugs
  packages/react-core/src/components/TreeView/TreeView.tsx
  packages/react-core/src/components/TreeView/TreeViewList.tsx
  packages/react-core/src/components/TreeView/TreeViewListItem.tsx
  packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
  packages/react-core/src/components/TreeView/examples/TreeView.md
  packages/react-integration/cypress/integration/treeview.spec.ts
Labels: css review, ux review

#5207 feat(DualListSelector): add support for trees and checkboxes
  packages/react-core/src/components/DualListSelector/DualListSelector.tsx
  packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
  packages/react-core/src/components/DualListSelector/DualListSelectorTree.tsx
  packages/react-core/src/components/DualListSelector/DualListSelectorTreeItem.tsx
  packages/react-core/src/components/DualListSelector/__tests__/DualListSelector.test.tsx
  packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
  packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
  packages/react-core/src/components/DualListSelector/treeUtils.ts
  packages/react-core/src/components/TreeView/TreeView.tsx
  packages/react-core/src/components/TreeView/examples/TreeView.md
  packages/react-integration/cypress/integration/duallistselectortree.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelector/DualListSelectorTreeDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#5216 feat(TimePicker): Add basic time picker
  packages/react-core/src/components/TimePicker/TimeOption.tsx
  packages/react-core/src/components/TimePicker/TimePicker.tsx
  packages/react-core/src/components/TimePicker/TimePickerUtils.tsx
  packages/react-core/src/components/TimePicker/examples/TimePicker.md
  packages/react-core/src/components/TimePicker/index.ts
  packages/react-core/src/components/index.ts
Labels: css review, ux review
