Repository patternfly/patternfly-react, pull requests merged in 2020-11, with the labels that each got.

#5072 fix(Skeleton): Update skeleton examples
  packages/react-core/src/components/Skeleton/examples/Skeleton.md
Labels: accessibility

#5082 chore(card): add keyboard interaction a11y test, clean up docs
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: accessibility, integration tests

#5083 chore(form): add more tests around keyboard interactivity in forms
  packages/react-core/src/components/Divider/examples/Divider.md
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: accessibility, integration tests

#5044 Update disabled dropdown items
  packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
  packages/react-core/src/components/Dropdown/DropdownMenu.tsx
  packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
  packages/react-core/src/helpers/__tests__/util.test.js
  packages/react-core/src/helpers/util.ts
  packages/react-integration/cypress/integration/dropdown.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
Labels: accessibility, ux review

#5081 chore(modal): add/update test cypress tests for modal
  packages/react-integration/cypress/integration/modal.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
Labels: accessibility, integration tests

#5000 feat(demo): add sticky bottom pagination to the card demo
  packages/react-core/src/demos/Card/Card.md
  packages/react-core/src/demos/PrimaryDetail.md
Labels: css review, ux review

#5105 chore(Splitter): Remove Splitter component
  packages/react-core/src/components/Splitter/Splitter.tsx
  packages/react-core/src/components/Splitter/__tests__/Splitter.test.tsx
  packages/react-core/src/components/Splitter/__tests__/__snapshots__/Splitter.test.tsx.snap
  packages/react-core/src/components/Splitter/examples/Splitter.md
  packages/react-core/src/components/Splitter/examples/splitter.css
  packages/react-core/src/components/Splitter/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/demo-app-ts/src/components/demos/SplitterDemo/SplitterDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: chore :house:

#5098 feat(Toolbar): add flag to match page insets
  packages/react-core/src/components/Toolbar/Toolbar.tsx
  packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
Labels: css review

#5112 add action list
  packages/react-core/src/components/ActionList/ActionList.tsx
  packages/react-core/src/components/ActionList/ActionListGroup.tsx
  packages/react-core/src/components/ActionList/ActionListItem.tsx
  packages/react-core/src/components/ActionList/__tests__/ActionList.test.tsx
  packages/react-core/src/components/ActionList/__tests__/ActionListGroup.test.tsx
  packages/react-core/src/components/ActionList/__tests__/ActionListItem.test.tsx
  packages/react-core/src/components/ActionList/__tests__/__snapshots__/ActionList.test.tsx.snap
  packages/react-core/src/components/ActionList/__tests__/__snapshots__/ActionListGroup.test.tsx.snap
  packages/react-core/src/components/ActionList/__tests__/__snapshots__/ActionListItem.test.tsx.snap
  packages/react-core/src/components/ActionList/examples/ActionList.md
  packages/react-core/src/components/ActionList/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/actionlist.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/ActionListDemo/ActionListDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#5089 Feat/jump link
  packages/react-core/src/components/JumpLinks/JumpLinks.tsx
  packages/react-core/src/components/JumpLinks/JumpLinksItem.tsx
  packages/react-core/src/components/JumpLinks/examples/JumpLinks.md
  packages/react-core/src/components/JumpLinks/index.ts
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/JumpLinks.md
  packages/react-integration/cypress/integration/jumplinks.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/JumpLinksDemo/JumpLinksDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#5093 feat(Card): add expandable card, move tests
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/CardExpandableContent.tsx
  packages/react-core/src/components/Card/CardHeader.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/__tests__/CardExpandableContent.test.tsx
  packages/react-core/src/components/Card/__tests__/CardHeadMain.test.tsx
  packages/react-core/src/components/Card/__tests__/CardHeader.test.tsx
  packages/react-core/src/components/Card/__tests__/CardHeaderMain.test.tsx
  packages/react-core/src/components/Card/__tests__/Generated/__snapshots__/Card.test.tsx.snap
  packages/react-core/src/components/Card/__tests__/Generated/__snapshots__/CardHead.test.tsx.snap
  packages/react-core/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
  packages/react-core/src/components/Card/__tests__/__snapshots__/CardExpandableContent.test.tsx.snap
  packages/react-core/src/components/Card/__tests__/__snapshots__/CardHeadMain.test.tsx.snap
  packages/react-core/src/components/Card/__tests__/__snapshots__/CardHeader.test.tsx.snap
  packages/react-core/src/components/Card/__tests__/__snapshots__/CardHeaderMain.test.tsx.snap
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/components/Card/examples/pf-logo-small.svg
  packages/react-core/src/components/Card/index.ts
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: css review, ux review

#5115 feat(Touchspin): add touchspin component
  packages/react-core/src/components/Touchspin/Touchspin.tsx
  packages/react-core/src/components/Touchspin/__tests__/Touchspin.test.tsx
  packages/react-core/src/components/Touchspin/__tests__/__snapshots__/Touchspin.test.tsx.snap
  packages/react-core/src/components/Touchspin/examples/Touchspin.md
  packages/react-core/src/components/Touchspin/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/touchspin.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/TouchspinDemo/TouchspinDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#4847 feat(menu): introduces new menu component
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuContext.ts
  packages/react-core/src/components/Menu/MenuGroup.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/MenuItemAction.tsx
  packages/react-core/src/components/Menu/MenuList.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/index.ts
  packages/react-core/src/components/index.ts
Labels: accessibility, css review, ux review

#5120 feat(DualListSelector): add new component
  packages/react-core/src/components/DualListSelector/DualListSelector.tsx
  packages/react-core/src/components/DualListSelector/DualListSelectorListItem.tsx
  packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
  packages/react-core/src/components/DualListSelector/__tests__/DualListSelector.test.tsx
  packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
  packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
  packages/react-core/src/components/DualListSelector/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/duallistselectorbasic.spec.ts
  packages/react-integration/cypress/integration/duallistselectorwithactions.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelector/DualListSelectorBasicDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelector/DualListSelectorWithActionsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#5172 fix(form-demo): tidy form demo examples
  packages/react-core/src/components/Form/examples/Form.md
Labels: documentation :memo:, enhancement :rocket:

#5136 fix(OptionsMenu and AppLauncher): Make options menu and application launcher accessible in JAWS
  packages/react-core/src/components/Dropdown/DropdownMenu.tsx
Labels: accessibility
