Repository patternfly/patternfly-react, pull requests merged in 2020-06, with the labels that each got.

#4320 fix(table): update property name to avoid error
  packages/react-table/src/components/Table/utils/decorators/selectable.tsx
Labels: PF4

#4353 fix(OverflowMenu): fix accessibility issue on KebabToggle button
  packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx
Labels: accessibility

#4328 fix(Drawer): opening drawer can send focus to the drawer
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/examples/Drawer.md
  packages/react-integration/cypress/integration/drawer.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
Labels: accessibility

#4362 fix(NavExpandable): add style.modifiers.expandable
  packages/react-core/src/components/Nav/NavExpandable.tsx
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  packages/react-docs/gatsby-config.js
Labels: ux review

#4368 fix(breadcrumb): temp fix for spacing
  packages/react-core/src/components/Breadcrumb/Breadcrumb.tsx
  packages/react-core/src/components/Breadcrumb/BreadcrumbHeading.tsx
  packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx
  packages/react-core/src/components/Breadcrumb/__tests__/Generated/__snapshots__/BreadcrumbItem.test.tsx.snap
  packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
  packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/BreadcrumbItem.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-docs/gatsby-config.js
Labels: css review

#4405 fix(Form): Added .pf-c-form__group-control wrapper to .pf-c-form__actions
  packages/react-core/src/components/Form/ActionGroup.tsx
  packages/react-core/src/components/Form/__tests__/Generated/__snapshots__/ActionGroup.test.tsx.snap
  packages/react-core/src/components/Form/__tests__/__snapshots__/ActionGroup.test.tsx.snap
Labels: bug :bug:, css review

#4382 fix(Docs): Removed training.md since it is moved to patternfly-org repo
  packages/react-docs/gatsby-config.js
  packages/react-docs/src/training.md
Labels: infrastructure

#4410 feat(Divider): Add support for insets to the Divider
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-core/package.json
  packages/react-core/src/components/Divider/Divider.md
  packages/react-core/src/components/Divider/Divider.tsx
  packages/react-core/src/helpers/util.ts
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/dividerinsetdemo.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/DividerDemo/DividerInsetDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review, enhancement :rocket:

#4389 feat(react-virtualized-extension docs): add filterable demo, fix for filtering+scrolling
  packages/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
  packages/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.md
Labels: PF4

#4408 feat(Banner): add banner component
  packages/react-core/src/components/Banner/Banner.tsx
  packages/react-core/src/components/Banner/__tests__/Banner.test.tsx
  packages/react-core/src/components/Banner/__tests__/__snapshots__/Banner.test.tsx.snap
  packages/react-core/src/components/Banner/examples/Banner.md
  packages/react-core/src/components/Banner/index.ts
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/PageLayout/examples/BannerDemo.md
  packages/react-integration/cypress/integration/banner.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/BannerDemo/BannerDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4352 fix(OptionsMenu): fix accessibility issue in plain with text
  packages/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
  packages/react-core/src/components/OptionsMenu/__tests__/Generated/__snapshots__/OptionsMenuToggleWithText.test.tsx.snap
  packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
  packages/react-integration/cypress/integration/optionsmenu.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/OptionsMenuDemo/OptionsMenuDemo.tsx
Labels: accessibility

#4439 feat(Banner): add beta flag to docs
  packages/react-core/src/components/Banner/examples/Banner.md
Labels: PF4

#4444 chore(release notes): Release notes for 2020.08
  packages/react-docs/RELEASE-NOTES.md
Labels: chore :house:

#4424 fix(OptionsMenu): fix accessibility bug in plain with text disabled part
  packages/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
  packages/react-core/src/components/OptionsMenu/__tests__/Generated/__snapshots__/OptionsMenuToggleWithText.test.tsx.snap
  packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
Labels: accessibility
