Repository patternfly/patternfly-react, pull requests merged in 2020-08, with the labels that each got.

#4516 feat(NotificationBadge): add needs attention state and count
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeErrorMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeWarningMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimaryDotMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimarySegmentedMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletQualitativeRange.test.tsx.snap
  packages/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/react-charts/src/components/ChartCursorContainer/__snapshots__/ChartCursorContainer.test.tsx.snap
  packages/react-charts/src/components/ChartCursorTooltip/__snapshots__/ChartCursorFlyout.test.tsx.snap
  packages/react-charts/src/components/ChartCursorTooltip/__snapshots__/ChartCursorTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltipContent.test.tsx.snap
  packages/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/react-charts/src/components/ChartScatter/__snapshots__/ChartScatter.test.tsx.snap
  packages/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
  packages/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
  packages/react-core/package.json
  packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
  packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx
  packages/react-core/src/components/NotificationBadge/__tests__/NotificationBadge.test.tsx
  packages/react-core/src/components/NotificationBadge/__tests__/__snapshots__/NotificationBadge.test.tsx.snap
  packages/react-core/src/components/NotificationBadge/examples/NotificationBadge.md
  packages/react-core/src/components/NotificationBadge/examples/notificationBadge.css
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerList.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerListItem.test.tsx.snap
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/notificationbadge.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NotificationBadgeDemo/NotificationBadgeDemo.tsx
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review

#4586 feat(DescriptionList): add new DescriptionList component
  packages/react-core/src/components/DescriptionList/DescriptionList.tsx
  packages/react-core/src/components/DescriptionList/DescriptionListDescription.tsx
  packages/react-core/src/components/DescriptionList/DescriptionListGroup.tsx
  packages/react-core/src/components/DescriptionList/DescriptionListTerm.tsx
  packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
  packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap
  packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
  packages/react-core/src/components/DescriptionList/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/descriptionlist.spec.ts
  packages/react-integration/cypress/integration/descriptionlistbreakpoints.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListBreakpointsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4588 feat(SearchInput): add new SearchInput component
  packages/react-core/src/components/SearchInput/SearchInput.tsx
  packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
  packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
  packages/react-core/src/components/SearchInput/examples/SearchInput.md
  packages/react-core/src/components/SearchInput/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/searchinput.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4640 feat(NotificationDrawer): Add notification drawer demo
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-core/package.json
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-core/src/demos/NotificaitonDrawer/examples/NotificationDrawerDemo.md
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review, ux review

#4677 bump core version to 4.31.4
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-core/package.json
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: chore :house:

#4671 chore(docs): release note 2020.10
  packages/react-docs/RELEASE-NOTES.md
Labels: chore :house:

#4686 feat(Page): add width limit
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
Labels: css review, ux review

#4680 feat(Label): add no overflow prop
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/Label/__tests__/Label.test.tsx
  packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  packages/react-core/src/components/Label/examples/Label.md
  packages/react-integration/cypress/integration/label.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
Labels: css review

#4399 feat(alert,notificationdrawer): add support to truncate title
  packages/react-core/src/components/Alert/Alert.tsx
  packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
  packages/react-core/src/components/Alert/examples/Alert.md
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerGroup.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItemHeader.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroup.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
Labels: css review

#4678 feat(modal): add medium variant
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalBox.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-core/src/components/Modal/examples/Modal.md
  packages/react-integration/cypress/integration/modal.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
Labels: css review

#4701 feat(TreeView): add treeview, demos, tests
  packages/react-core/src/components/TreeView/TreeView.tsx
  packages/react-core/src/components/TreeView/TreeViewList.tsx
  packages/react-core/src/components/TreeView/TreeViewListItem.tsx
  packages/react-core/src/components/TreeView/TreeViewSearch.tsx
  packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx
  packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
  packages/react-core/src/components/TreeView/examples/TreeView.md
  packages/react-core/src/components/TreeView/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/treeview.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/TreeViewDemo/TreeViewDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4610 feat(Tile): add tile component
  packages/react-core/src/components/Tile/Tile.tsx
  packages/react-core/src/components/Tile/__tests__/Tile.test.tsx
  packages/react-core/src/components/Tile/__tests__/__snapshots__/Tile.test.tsx.snap
  packages/react-core/src/components/Tile/examples/Tile.md
  packages/react-core/src/components/Tile/index.ts
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/TileDemo.md
  packages/react-integration/cypress/integration/tile.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/TileDemo/TileDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#4702 feat(ToggleGroup): add new toggle group component
  packages/react-core/src/components/ToggleGroup/ToggleGroup.tsx
  packages/react-core/src/components/ToggleGroup/ToggleGroupContext.tsx
  packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
  packages/react-core/src/components/ToggleGroup/__tests__/ToggleGroup.test.tsx
  packages/react-core/src/components/ToggleGroup/__tests__/__snapshots__/ToggleGroup.test.tsx.snap
  packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
  packages/react-core/src/components/ToggleGroup/examples/toggleGroup.css
  packages/react-core/src/components/ToggleGroup/index.ts
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/FilterTableDemo.md
  packages/react-integration/cypress/integration/togglegroup.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/ToggleGroupDemo/ToggleGroupDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review
