Repository patternfly/patternfly-react, pull requests merged in 2020-07, with the labels that each got.

#4492 fix(examples): make the interactions in the demo more life-like
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
Labels: documentation :memo:, enhancement :rocket:

#4510 feat(Alert): Add alert timeout functionality
  packages/react-core/src/components/Alert/Alert.tsx
  packages/react-core/src/components/Alert/examples/Alert.md
  packages/react-integration/cypress/integration/alertcustomtimeout.spec.ts
  packages/react-integration/cypress/integration/alertdefaulttimeout.spec.ts
  packages/react-integration/cypress/integration/alerttimeoutclosebutton.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertCustomTimeoutDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDefaultTimeoutDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertTimeoutCloseButtonDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: ux review

#4488 feat(DataList): Add support for action containers in DataList
  packages/react-core/src/components/DataList/DataListAction.tsx
  packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
  packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
  packages/react-core/src/components/DataList/examples/DataList.md
  packages/react-integration/cypress/integration/datalist.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx
Labels: css review, enhancement :rocket:

#4508 fix(drawer): rename onMount to onExpand and add animation timeout
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/examples/Drawer.md
  packages/react-integration/cypress/integration/drawer.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
Labels: breaking change :boom:

#4503 fix(select): option with description on active display only value
  packages/react-core/src/components/Select/Select.tsx
Labels: css review

#4459 feat(Toolbar&OverflowMenu): update docs to use OverflowMenu components
  packages/react-core/src/components/OverflowMenu/examples/OverflowMenu.md
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-core/src/demos/BulkSelectTable.md
  packages/react-core/src/demos/CardView/examples/CardView.md
  packages/react-core/src/demos/MasterDetailDemo.md
  packages/react-core/src/demos/PaginationTable.md
  packages/react-core/src/demos/TableColumnManagementDemo.md
Labels: css review

#4554 feat(FormGroup, FormSelect, TextInput, TextArea): Add warning state
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-core/package.json
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-core/src/components/FormSelect/FormSelect.tsx
  packages/react-core/src/components/FormSelect/__tests__/FormSelect.test.tsx
  packages/react-core/src/components/FormSelect/__tests__/__snapshots__/FormSelect.test.tsx.snap
  packages/react-core/src/components/FormSelect/examples/FormSelect.md
  packages/react-core/src/components/TextArea/TextArea.tsx
  packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx
  packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
  packages/react-core/src/components/TextArea/examples/TextArea.md
  packages/react-core/src/components/TextInput/TextInput.tsx
  packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx
  packages/react-core/src/components/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  packages/react-core/src/helpers/constants.ts
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/cypress/integration/formselect.spec.ts
  packages/react-integration/cypress/integration/textarea.spec.ts
  packages/react-integration/cypress/integration/textinputdemo.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/FormSelectDemo/FormSelectDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TextInputDemo/TextInputDemo.tsx
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review, enhancement :rocket:, ux approved

#4559 feat(Table actions): allow custom properties for actions
  packages/react-table/src/components/Table/ActionsColumn.tsx
  packages/react-table/src/components/Table/examples/Table.md
Labels: enhancement :rocket:

#4550 feat(ChipGroup): changes TimesIcon to TimesCircleIcon
  packages/react-core/src/components/ChipGroup/ChipGroup.tsx
Labels: css review

#4512 fix(NavExpandable): converts nav expandable to button
  packages/react-core/src/components/Nav/NavExpandable.tsx
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
Labels: css review

#4466 fix(NotificationDrawer): fix accessibility issues and add accessibility test cases
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerGroup.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerListItem.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroup.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItem.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
  packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts
  packages/react-integration/cypress/integration/notificationdrawergroups.spec.ts
  packages/react-integration/cypress/integration/notificationdrawerlightweight.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerBasicDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerGroupsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerLightweightDemo.tsx
Labels: accessibility

#4596 feat(Button): add cta/large modifier
  packages/react-core/src/components/Button/Button.tsx
  packages/react-core/src/components/Button/__tests__/Button.test.tsx
  packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/react-core/src/components/Button/examples/Button.md
  packages/react-integration/cypress/integration/button.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
Labels: css review

#4595 feat(Hint): add hint components
  packages/react-core/src/components/Hint/Hint.tsx
  packages/react-core/src/components/Hint/HintBody.tsx
  packages/react-core/src/components/Hint/HintFooter.tsx
  packages/react-core/src/components/Hint/HintTitle.tsx
  packages/react-core/src/components/Hint/__tests__/Hint.test.tsx
  packages/react-core/src/components/Hint/__tests__/__snapshots__/Hint.test.tsx.snap
  packages/react-core/src/components/Hint/examples/Hint.md
  packages/react-core/src/components/Hint/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/hint.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/HintDemo/HintDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4425 feat(wiz): make wizard nav items more easily discoverable
  packages/react-catalog-view-extension/package.json
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardBody.tsx
  packages/react-core/src/components/Wizard/WizardNav.tsx
  packages/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/react-core/src/components/Wizard/WizardToggle.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/Wizard.test.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/WizardBody.test.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/WizardNav.test.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/WizardNavItem.test.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/WizardToggle.test.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardBody.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNav.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardToggle.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
  packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
  packages/react-core/src/components/Wizard/examples/FinishedStep.js
  packages/react-core/src/components/Wizard/examples/Wizard.md
  packages/react-integration/cypress/integration/wizard.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
Labels: PF4, accessibility, microcopy review

#4622 feat(Select): allow typeahead groups, fix few bugs around groups
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-core/src/helpers/util.ts
Labels: accessibility, ux review
