Repository patternfly/patternfly-react, pull requests merged in 2020-04, with the labels that each got.

#4017 fix(modal): default action alignment to left
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalBoxFooter.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-core/src/components/Modal/__tests__/Generated/Modal.test.tsx
  packages/react-core/src/components/Modal/__tests__/Generated/ModalContent.test.tsx
  packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/Modal.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/ModalBoxFooter.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxFooter.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
  packages/react-core/src/components/Modal/examples/Modal.md
  packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
Labels: PF4, breaking change :boom:

#4014 fix(gutter): fix type for gutter support
  packages/react-core/src/demos/CardView/examples/CardView.md
  packages/react-core/src/demos/PageLayout/examples/PageLayout.md
  packages/react-core/src/layouts/Gallery/Gallery.tsx
  packages/react-core/src/layouts/Gallery/__tests__/Gallery.test.tsx
  packages/react-core/src/layouts/Gallery/__tests__/Generated/Gallery.test.tsx
  packages/react-core/src/layouts/Gallery/__tests__/Generated/__snapshots__/Gallery.test.tsx.snap
  packages/react-core/src/layouts/Gallery/examples/Gallery.md
  packages/react-core/src/layouts/Grid/Grid.tsx
  packages/react-core/src/layouts/Grid/__tests__/Generated/Grid.test.tsx
  packages/react-core/src/layouts/Grid/__tests__/Generated/__snapshots__/Grid.test.tsx.snap
  packages/react-core/src/layouts/Grid/__tests__/Grid.test.tsx
  packages/react-core/src/layouts/Grid/examples/Grid.md
  packages/react-core/src/layouts/Level/Level.tsx
  packages/react-core/src/layouts/Level/__tests__/Generated/Level.test.tsx
  packages/react-core/src/layouts/Level/__tests__/Generated/__snapshots__/Level.test.tsx.snap
  packages/react-core/src/layouts/Level/__tests__/Level.test.tsx
  packages/react-core/src/layouts/Level/examples/Level.md
  packages/react-core/src/layouts/Split/Split.tsx
  packages/react-core/src/layouts/Split/__tests__/Generated/Split.test.tsx
  packages/react-core/src/layouts/Split/__tests__/Generated/__snapshots__/Split.test.tsx.snap
  packages/react-core/src/layouts/Split/__tests__/Split.test.tsx
  packages/react-core/src/layouts/Split/__tests__/__snapshots__/Split.test.tsx.snap
  packages/react-core/src/layouts/Split/examples/Split.md
  packages/react-core/src/layouts/Stack/Stack.tsx
  packages/react-core/src/layouts/Stack/__tests__/Generated/Stack.test.tsx
  packages/react-core/src/layouts/Stack/__tests__/Generated/__snapshots__/Stack.test.tsx.snap
  packages/react-core/src/layouts/Stack/__tests__/Stack.test.tsx
  packages/react-core/src/layouts/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
  packages/react-core/src/layouts/Stack/examples/Stack.md
  packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/GalleryDemo/GalleryDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LevelDemo/LevelDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SplitDemo/SplitDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/StackDemo/StackDemo.tsx
Labels: PF4, breaking change :boom:

#4030 fix(popover): update default popover header size
  packages/react-core/src/components/Popover/PopoverHeader.tsx
  packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverHeader.test.tsx.snap
  packages/react-integration/cypress/integration/popover.spec.ts
Labels: PF4, breaking change :boom:

#4031 fix(empty-state): add isFullHeight prop support
  packages/react-core/src/components/EmptyState/EmptyState.tsx
  packages/react-core/src/components/EmptyState/__tests__/EmptyState.test.tsx
  packages/react-core/src/components/EmptyState/__tests__/Generated/__snapshots__/EmptyState.test.tsx.snap
  packages/react-core/src/components/EmptyState/__tests__/__snapshots__/EmptyState.test.tsx.snap
  packages/react-core/src/components/EmptyState/examples/EmptyState.md
  packages/react-integration/cypress/integration/emptystate.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/EmptyStateDemo/EmptyStateDemo.tsx
Labels: PF4, css review, enhancement :rocket:

#4001 fix(examples): Fix ids to resolve site axe issues
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-core/src/components/Select/examples/Select.md
Labels: accessibility

#4026 feat(card): support flat variation
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: css review

#4056 fix(DataToolbar): fix filter context from updating unnecessarily
  packages/react-core/src/components/DataToolbar/DataToolbarFilter.tsx
  packages/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap
Labels: PF4

#4036 feat(Drawer): remove flag to add border, adjust flag for no border
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/examples/Drawer.md
Labels: css review

#4081 feat(title): supply defaults for title size property
  packages/react-core/src/components/Title/Title.tsx
  packages/react-core/src/components/Title/__tests__/Generated/Title.test.tsx
  packages/react-core/src/components/Title/__tests__/Generated/__snapshots__/Title.test.tsx.snap
  packages/react-core/src/components/Title/examples/Title.md
  packages/react-integration/cypress/integration/title.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TitleDemo/TitleDemo.tsx
Labels: PF4

#4065 chore(EmptyStateIcon): Remove unused props interface from EmptyStateIcon
  packages/react-core/src/components/EmptyState/EmptyStateIcon.tsx
Labels: breaking change :boom:

#4029 Remove promoted components from experimental index file
  packages/react-core/src/components/index.ts
  packages/react-core/src/experimental/components/Divider/index.ts
  packages/react-core/src/experimental/components/OverflowMenu/index.ts
  packages/react-core/src/experimental/components/Spinner/index.ts
  packages/react-core/src/experimental/components/index.ts
  packages/react-core/src/experimental/index.ts
Labels: breaking change :boom:

#4063 refactor(Wizard): Update string props to be React nodes.
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardFooterInternal.tsx
  packages/react-core/src/components/Wizard/WizardHeader.tsx
  packages/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap
Labels: breaking change :boom:

#4101 Release notes 2020.05
  packages/react-docs/RELEASE-NOTES.md
Labels: chore :house:

#4038 Feat(Dropdown): add image & plain text support
  packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
  packages/react-core/src/components/ApplicationLauncher/__tests__/Generated/__snapshots__/ApplicationLauncher.test.tsx.snap
  packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/react-core/src/components/Dropdown/DropdownToggle.tsx
  packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/react-core/src/components/Dropdown/__tests__/DropdownToggle.test.tsx
  packages/react-core/src/components/Dropdown/__tests__/Generated/__snapshots__/Dropdown.test.tsx.snap
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
  packages/react-core/src/components/Dropdown/dropdownConstants.tsx
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx
  packages/react-core/src/components/OptionsMenu/OptionsMenuToggle.tsx
  packages/react-core/src/components/OptionsMenu/__tests__/Generated/__snapshots__/OptionsMenu.test.tsx.snap
  packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap
  packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
Labels: breaking change :boom:

#4025 feat(form): support removing top spacer form from labels
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: css review

#4129 fix(nav): fix scrolling
  packages/react-core/src/components/Nav/Nav.tsx
  packages/react-core/src/components/Nav/NavList.tsx
  packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/Nav.test.tsx.snap
  packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavList.test.tsx.snap
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/helpers/util.ts
Labels: css review

#4034 fix(drawer): remove hidden when drawer is expanded
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/DrawerPanelContent.test.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
Labels: css review

#4157 Make tooltip examples keyboard accessible
  packages/react-core/src/components/Tooltip/examples/Tooltip.md
Labels: accessibility
