Repository patternfly/patternfly-react, pull requests merged in 2020-05, with the labels that each got.

#4137 feat(NotificationDrawer): Add new Notification Drawer Component
  packages/react-core/src/components/NotificationDrawer/NotificationDrawer.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerBody.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroupList.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerList.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemBody.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawer.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerBody.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerGroup.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerGroupList.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerHeader.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerList.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerListItem.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerListItemBody.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/NotificationDrawerListItemHeader.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawer.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerBody.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerGroup.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerGroupList.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerHeader.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerList.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerListItem.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerListItemBody.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerListItemHeader.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawer.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerBody.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerGroup.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerGroupList.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerHeader.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerList.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItem.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItemBody.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItemHeader.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawer.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerBody.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroup.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroupList.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerHeader.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerList.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItem.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItemBody.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItemHeader.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
  packages/react-core/src/components/NotificationDrawer/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts
  packages/react-integration/cypress/integration/notificationdrawergroups.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerBasicDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerGroupsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#4142 fix(wizard): remove old prop "isCompactNav"
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/Wizard.test.tsx
  packages/react-core/src/components/Wizard/examples/Wizard.md
Labels: PF4, breaking change :boom:

#4176 fix(experimental): remove experimental directory
  packages/react-core/src/components/index.ts
  packages/react-core/src/experimental/components/DataToolbar/index.ts
  packages/react-core/src/experimental/components/Drawer/index.ts
  packages/react-core/src/experimental/components/index.ts
  packages/react-core/src/experimental/index.ts
  packages/react-core/src/index.ts
Labels: PF4

#4185 feat(Select): Added placeholder text for inline filter
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/__tests__/Select.test.tsx
  packages/react-core/src/components/Select/examples/Select.md
Labels: PF4, enhancement :rocket:

#4140 chore(Wizard): make wizard inPage
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalBox.tsx
  packages/react-core/src/components/Modal/ModalBoxHeader.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-core/src/components/Modal/__tests__/Generated/ModalBoxHeader.test.tsx
  packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/Modal.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/ModalBoxHeader.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/ModalBoxHeader.test.tsx
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxHeader.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
  packages/react-core/src/components/Modal/examples/Modal.md
  packages/react-core/src/components/Modal/index.ts
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardHeader.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
  packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
  packages/react-core/src/components/Wizard/examples/Wizard.md
  packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
Labels: breaking change :boom:

#4154 chore(Divider): add vertical dividers and use Divider in DataToolbar
  packages/react-core/src/components/Divider/Divider.md
  packages/react-core/src/components/Divider/Divider.tsx
  packages/react-core/src/components/Divider/__tests__/Divider.test.tsx
  packages/react-core/src/components/Divider/__tests__/__snapshots__/Divider.test.tsx.snap
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-integration/cypress/integration/divider.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DividerDemo/DividerDemo.tsx
Labels: css review

#4200 docs(Empty State): Added xl empty state to demo app/tests
  packages/react-integration/cypress/integration/emptystate.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/EmptyStateDemo/EmptyStateDemo.tsx
Labels: PF4

#4133 feat(Drawer, DataList, Page): rename noPadding to hasNoPadding
  packages/react-core/src/components/DataList/DataListContent.tsx
  packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
  packages/react-core/src/components/DataList/__tests__/Generated/DataListContent.test.tsx
  packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
  packages/react-core/src/components/DataList/examples/DataList.md
  packages/react-core/src/components/Drawer/DrawerHead.tsx
  packages/react-core/src/components/Drawer/DrawerPanelBody.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/DrawerPanelContent.test.tsx
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/examples/Drawer.md
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/Generated/PageSection.test.tsx
  packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
  packages/react-core/src/components/Page/examples/Page.md
  packages/react-core/src/helpers/util.ts
  packages/react-integration/cypress/integration/page.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
Labels: breaking change :boom:

#4165 feat(Label): refactor for updated design and features
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/Label/__tests__/Generated/__snapshots__/Label.test.tsx.snap
  packages/react-core/src/components/Label/__tests__/Label.test.tsx
  packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  packages/react-core/src/components/Label/examples/Label.md
  packages/react-integration/cypress/integration/label.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
Labels: css review

#4115 feat(MasterDetailDemo): Add Master Detail Demo
  packages/react-core/src/demos/MasterDetailDemo.md
Labels: css review

#4202 fix(pagination): update to match core
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-core/package.json
  packages/react-core/src/components/Pagination/Navigation.tsx
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/demos/BulkSelectTable.md
  packages/react-core/src/demos/TableColumnManagementDemo.md
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-inline-edit-extension/package.json
  packages/react-integration/cypress/integration/pagination.spec.ts
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  packages/react-topology/package.json
  packages/react-virtualized-extension/package.json
  yarn.lock
Labels: css review

#4198 feat(Select): Add support for 0 and all badges
  packages/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
Labels: PF4, enhancement :rocket:, ux approved

#4228 Release notes 2020.06
  packages/react-docs/RELEASE-NOTES.md
Labels: chore :house:

#4146 Tabs updates
  packages/react-core/src/components/Tabs/Tab.tsx
  packages/react-core/src/components/Tabs/TabButton.tsx
  packages/react-core/src/components/Tabs/TabTitleIcon.tsx
  packages/react-core/src/components/Tabs/TabTitleText.tsx
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/__tests__/Tab.test.tsx
  packages/react-core/src/components/Tabs/__tests__/TabButton.test.tsx
  packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/TabButton.test.tsx.snap
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-core/src/components/Tabs/index.ts
  packages/react-core/src/helpers/util.ts
  packages/react-integration/cypress/integration/tabdemo.spec.ts
  packages/react-integration/cypress/integration/tabinsetdemo.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsInsetDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsStringEventKeyDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: breaking change :boom:, css review, ux review

#4247 feat(Form): added icon to form helper text
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/FormHelperText.tsx
  packages/react-core/src/components/Form/__tests__/FormHelperText.test.tsx
  packages/react-core/src/components/Form/__tests__/Generated/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormHelperText.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-core/src/components/LoginPage/LoginForm.tsx
  packages/react-core/src/components/LoginPage/__tests__/Generated/__snapshots__/LoginForm.test.tsx.snap
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
  packages/react-core/src/components/LoginPage/examples/LoginPage.md
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: breaking change :boom:, css review

#4195 feat(form): add support for form label icons
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
  packages/react-core/src/components/Form/__tests__/Generated/FormGroup.test.tsx
  packages/react-core/src/components/Form/__tests__/Generated/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: PF4, css review

#4248 fix(Progress): Update to match core and fix accessibility
  packages/react-core/src/components/Progress/Progress.tsx
  packages/react-core/src/components/Progress/ProgressBar.tsx
  packages/react-core/src/components/Progress/ProgressContainer.tsx
  packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/Progress.test.tsx.snap
  packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/ProgressContainer.test.tsx.snap
  packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap
Labels: accessibility

#4278 fix(charts): Use Victory's createContainer instead of allowZoom prop
  packages/react-charts/src/components/Chart/Chart.tsx
  packages/react-charts/src/components/ChartBar/examples/ChartBar.md
  packages/react-charts/src/components/ChartGroup/ChartGroup.tsx
  packages/react-integration/demo-app-ts/src/components/demos/BarChartDemo/ColorBarZoomDemo.tsx
Labels: breaking change :boom:

#4284 fix(Table): update imports to direct imports for react table
  packages/react-table/src/components/Table/EditColumn.tsx
  packages/react-table/src/components/Table/EditableTextCell.tsx
Labels: PF4, bug :bug:

#4280 fix(wiz): add missing label for wiz-in-modal
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap
  packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
Labels: PF4, enhancement :rocket:

#4290 fix(Pagination): Fix imports of tokens in pagination to direct imports
  packages/react-core/src/components/Pagination/Pagination.tsx
Labels: PF4, bug :bug:
