Repository patternfly/patternfly-react, pull requests merged in 2021-08, with the labels that each got.

#6053 feat(Form): add form group label info & docs(Form): add password strength demo
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/FormHelperText.tsx
  packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-core/src/components/TextInput/TextInput.tsx
  packages/react-core/src/demos/PasswordStrength.md
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: css approved, ux approved

#6095 fix(Select): first new item focused after view more clicked
  packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsole.test.tsx.snap
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/SelectOption.tsx
  packages/react-core/src/components/Select/__tests__/Generated/__snapshots__/SelectMenu.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/SelectOption.test.tsx.snap
Labels: accessibility

#6038 feat(Dropdown): Allow for tooltips on aria-disabled items
  packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
  packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
  packages/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
  packages/react-core/src/components/Dropdown/__tests__/InternalDropdownItem.test.tsx
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/InternalDropdownItem.test.tsx.snap
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
  packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
Labels: accessibility

#6130 feat(HelperText): update default icons for success/error
  packages/react-core/src/components/HelperText/HelperTextItem.tsx
  packages/react-core/src/components/HelperText/examples/HelperText.md
Labels: css review

#6149 feat(Navigation): add horizontal subnav variant
  packages/react-core/src/components/Nav/Nav.tsx
  packages/react-core/src/components/Nav/__tests__/Nav.test.tsx
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/components/Nav/examples/nav.css
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
  packages/react-core/src/demos/Nav.md
  packages/react-docs/src/generated/components/backdrop/react/with-spinner.png
  packages/react-docs/src/generated/components/navigation/react-demos/horizontal-nav-with-horizontal-subnav.png
  packages/react-docs/src/generated/components/navigation/react-demos/horizontal-subnav.png
  packages/react-docs/src/generated/components/navigation/react-demos/legacy-tertiary-nav.png
  packages/react-integration/cypress/integration/nav.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
Labels: css approved, ux approved

#6155 feat(Popover): support diagonal positions
  packages/react-core/src/components/Popover/Popover.tsx
  packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/Popover.test.tsx.snap
  packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  packages/react-core/src/components/Popover/examples/Popover.md
  packages/react-core/src/helpers/Popper/Popper.tsx
  packages/react-integration/cypress/integration/popover.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
Labels: ux review, css review

#6172 feat(TreeView): add guides + compact variants
  packages/react-core/src/components/TreeView/TreeView.tsx
  packages/react-core/src/components/TreeView/TreeViewListItem.tsx
  packages/react-core/src/components/TreeView/TreeViewRoot.tsx
  packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx
  packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
  packages/react-core/src/components/TreeView/examples/TreeView.md
  packages/react-integration/cypress/integration/treeview.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TreeViewDemo/TreeViewDemo.tsx
Labels: css review

#6141 feat(ContextSelector): Add plain variant
  packages/react-core/src/components/ContextSelector/ContextSelector.tsx
  packages/react-core/src/components/ContextSelector/ContextSelectorToggle.tsx
  packages/react-core/src/components/ContextSelector/__tests__/Generated/__snapshots__/ContextSelector.test.tsx.snap
  packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
  packages/react-core/src/components/ContextSelector/examples/ContextSelector.md
  packages/react-integration/demo-app-ts/src/components/demos/ContextSelectorDemo/ContextSelectorDemo.tsx
Labels: ux review, css review

#6178 feat(Search input): Added support for submit button
  packages/react-core/src/components/SearchInput/SearchInput.tsx
  packages/react-core/src/components/SearchInput/examples/SearchInput.md
Labels: ux review, css review

#6193 demos(Card): added horizontal split and details demos
  packages/react-core/src/demos/CardDemos.md
Labels: ux review, css review

#6175 feat(Menu): add app-launcher mockup
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/demos/ComposableMenu.md
  packages/react-core/src/demos/examples/pf-logo-small.svg
Labels: ux review, css approved

#6170 Masthead
  packages/react-core/src/components/ContextSelector/ContextSelector.tsx
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
  packages/react-core/src/components/Masthead/Masthead.tsx
  packages/react-core/src/components/Masthead/MastheadBrand.tsx
  packages/react-core/src/components/Masthead/MastheadContent.tsx
  packages/react-core/src/components/Masthead/MastheadMain.tsx
  packages/react-core/src/components/Masthead/MastheadToggle.tsx
  packages/react-core/src/components/Masthead/__tests__/Masthead.test.tsx
  packages/react-core/src/components/Masthead/__tests__/__snapshots__/Masthead.test.tsx.snap
  packages/react-core/src/components/Masthead/examples/Masthead.md
  packages/react-core/src/components/Masthead/examples/pf-logo-small.svg
  packages/react-core/src/components/Masthead/index.ts
  packages/react-core/src/components/Toolbar/Toolbar.tsx
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/Masthead.md
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: ux review, css approved
