Repository patternfly/patternfly-react, pull requests merged in 2021-02, with the labels that each got.

#5382 fix(Tooltip): only add aria when tooltip is visible/in the DOM
  packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
  packages/react-core/src/components/Tooltip/Tooltip.tsx
  packages/react-core/src/components/Tooltip/__tests__/Generated/__snapshots__/Tooltip.test.tsx.snap
  packages/react-core/src/components/Tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
  packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
Labels: accessibility

#5391 fix(wizard): add cancel button class
  packages/react-core/src/components/Wizard/WizardFooterInternal.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardFooterInternal.test.tsx.snap
Labels: css review

#5390 feat(spinner): add isSVG
  packages/react-core/src/components/Spinner/Spinner.tsx
  packages/react-core/src/components/Spinner/examples/Spinner.md
  packages/react-integration/cypress/integration/spinner.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SpinnerDemo/SpinnerDemo.tsx
Labels: css review

#5389 feat(card): add pf-m-display-lg and pf-m-rounded
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: css review, ux review

#5119 fix(datalist): use drag-over modifier instead of css style
  packages/react-core/src/components/DataList/DataList.tsx
  packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataList.test.tsx.snap
  packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
Labels: css review

#5427 fix(selectmenu): don't use focus trap when no tabbable children
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/SelectOption.tsx
  packages/react-core/src/components/Select/SelectToggle.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
Labels: accessibility

#5415 feat(Progress): Add warning when title and aria-label not present
  packages/react-core/src/components/Progress/Progress.tsx
  packages/react-core/src/components/Progress/ProgressBar.tsx
  packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/Progress.test.tsx.snap
  packages/react-core/src/components/Progress/__tests__/Progress.test.tsx
  packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap
  packages/react-core/src/components/Progress/examples/Progress.md
Labels: accessibility

#5314 Feat/jumplink subsection
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-core/src/components/JumpLinks/JumpLinks.tsx
  packages/react-core/src/components/JumpLinks/JumpLinksItem.tsx
  packages/react-core/src/components/JumpLinks/JumpLinksList.tsx
  packages/react-core/src/components/JumpLinks/examples/JumpLinks.md
  packages/react-core/src/components/JumpLinks/index.ts
  packages/react-core/src/components/Sidebar/Sidebar.tsx
  packages/react-core/src/components/Sidebar/SidebarContent.tsx
  packages/react-core/src/components/Sidebar/SidebarPanel.tsx
  packages/react-core/src/components/Sidebar/examples/Sidebar.md
  packages/react-core/src/components/Sidebar/index.ts
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/JumpLinks.md
  packages/react-table/package.json
Labels: css review, ux review

#5428 feat(FormSelect): added support for placeholder styled option
  packages/react-core/src/components/FormSelect/FormSelect.tsx
  packages/react-core/src/components/FormSelect/FormSelectOption.tsx
  packages/react-core/src/components/FormSelect/examples/FormSelect.md
  packages/react-integration/cypress/integration/formselect.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormSelectDemo/FormSelectDemo.tsx
Labels: css review, enhancement :rocket:, ux review

#5438 feat(Navigation): Added support for spreading props to the NaveExpand…
  packages/react-core/src/components/Nav/NavExpandable.tsx
  packages/react-integration/cypress/integration/nav.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
Labels: enhancement :rocket:

#5439 feat(TreeView): add keyboard interaction
  packages/react-core/src/components/TreeView/TreeView.tsx
  packages/react-core/src/components/TreeView/TreeViewListItem.tsx
  packages/react-core/src/components/TreeView/TreeViewRoot.tsx
  packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
  packages/react-core/src/components/TreeView/index.ts
  packages/react-integration/cypress/integration/treeview.spec.ts
Labels: accessibility, ux review

#5431 feat(Table): update column management demo to include label
  packages/react-table/src/demos/Table.md
Labels: css review

#5454 feat(SearchInput): add advanced search feature
  packages/react-core/src/components/SearchInput/SearchInput.tsx
  packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
  packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
  packages/react-core/src/components/SearchInput/examples/SearchInput.md
  packages/react-integration/cypress/integration/searchinput.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx
Labels: css review, ux review

#5453 feat(Slider): Added touch support
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-console/package.json
  packages/react-core/package.json
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: ux review

#5467 chore: Release notes 2021.02
  packages/react-docs/RELEASE-NOTES.md
Labels: chore :house:
