Repository patternfly/patternfly-react, pull requests merged in 2021-10, with the labels that each got.

#6378 Sidebar(docs): added tabindex to scrollable examples
  packages/react-core/src/components/Sidebar/examples/Sidebar.md
Labels: accessibility

#6307 docs(Card): add utilization card demos
  packages/react-core/src/demos/CardDemos.md
Labels: ux review, css review

#6342 feat(Tabs) Added support for expandable vertical tabs
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-integration/cypress/integration/tabexpandabledemo.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsExpandableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: ux review, css review, accessibility

#6392 fix(Wizard): Update aria-current on wizard steps
  packages/react-core/src/components/Wizard/WizardNavItem.tsx
Labels: accessibility

#6391 docs(Card): Added nested card demo
  packages/react-core/src/demos/CardDemos.md
Labels: ux review, css review
