Repository patternfly/patternfly-react, pull requests merged in 2021-07, with the labels that each got.

#5983 bug(DualListSelector): Fix button order
  packages/react-core/src/components/DualListSelector/DualListSelector.tsx
  packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
  packages/react-integration/cypress/integration/duallistselectorbasic.spec.ts
  packages/react-integration/cypress/integration/duallistselectortree.spec.ts
  packages/react-integration/cypress/integration/duallistselectorwithactions.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorBasicDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorTreeDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorWithActionsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: ux review

#5972 feat(misc): Keyboard handling helper
  packages/react-core/src/components/DualListSelector/DualListSelector.tsx
  packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/TreeView/TreeViewRoot.tsx
  packages/react-core/src/helpers/KeyboardHandler.tsx
  packages/react-core/src/helpers/index.ts
Labels: accessibility

#5946 feat(AlertGroup): Make dynamic alerts more accessible
  packages/react-core/src/components/Alert/examples/Alert.md
  packages/react-core/src/components/AlertGroup/AlertGroup.tsx
  packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx
  packages/react-core/src/components/AlertGroup/__tests__/Generated/__snapshots__/AlertGroupInline.test.tsx.snap
  packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
  packages/react-core/src/components/AlertGroup/examples/AlertGroup.md
Labels: accessibility

#5985 docs(Pagination): Export interfaces in md file so prop descriptions are documented
  packages/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/Pagination/examples/Pagination.md
Labels: accessibility

#5789 feat(menu): context menu flyout
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
  packages/react-core/src/components/Dropdown/Toggle.tsx
  packages/react-core/src/components/Menu/DrilldownMenu.tsx
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuContext.ts
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/MenuList.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/demos/ComposableMenu.md
  packages/react-core/src/demos/composable-menu.css
  packages/react-core/src/helpers/KeyboardHandler.tsx
  packages/react-core/src/helpers/Popper/Popper.tsx
  packages/react-virtualized-extension/src/components/Virtualized/examples/VirtualizedTable.md
  packages/react-virtualized-extension/src/components/Virtualized/examples/WindowScroller.md
Labels: css review, ux review

#6065 feat(Label): add editable label
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/Label/examples/Label.md
  packages/react-core/src/components/LabelGroup/LabelGroup.tsx
  packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
  packages/react-integration/cypress/integration/label.spec.ts
  packages/react-integration/cypress/integration/labelgroupeditable.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupEditableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css approved, ux approved

#6087 feat(Tabs): support page insets
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/examples/Tabs.md
Labels: css review

#6044 feat(LogViewer): Add dark theme
  packages/react-log-viewer/src/LogViewer/LogViewer.tsx
  packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
Labels: css review, ux review

#6078 feat(ExpandableSection): Added props to support disclosure variation
  packages/react-console/src/components/DesktopViewer/__tests__/__snapshots__/DesktopViewer.test.tsx.snap
  packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
  packages/react-integration/cypress/integration/expandablesection.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx
Labels: css review, ux review

#6085 feat(Accordion): Added support for bordered, display large …
  packages/react-core/src/components/Accordion/Accordion.tsx
  packages/react-core/src/components/Accordion/AccordionContent.tsx
  packages/react-core/src/components/Accordion/AccordionExpandedContentBody.tsx
  packages/react-core/src/components/Accordion/__tests__/Accordion.test.tsx
  packages/react-core/src/components/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  packages/react-core/src/components/Accordion/examples/Accordion.md
  packages/react-core/src/components/Accordion/index.ts
  packages/react-integration/cypress/integration/accordion.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/AccordionDemo/AccordionDemo.tsx
Labels: css review, ux review
