Repository patternfly/patternfly-react, pull requests merged in 2021-11, with the labels that each got.

#6557 docs(Modal): Added example of modal with form
  packages/react-core/src/components/Modal/examples/Modal.md
Labels: ux review, css review, accessibility

#6564 feat(Navigation): Added example for third level nested expansion
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/components/Nav/examples/nav.css
Labels: ux review, css review

#6554 feat(contextselector): added support for context selector items as links
  packages/react-core/src/components/ContextSelector/ContextSelectorItem.tsx
  packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
  packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelectorMenuList.test.tsx.snap
  packages/react-core/src/components/ContextSelector/examples/ContextSelector.md
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/demos/ComposableMenu.md
Labels: accessibility

#6538 feat(ComposableTable): add sticky columns and nested headers
  packages/react-table/src/components/TableComposable/InnerScrollContainer.tsx
  packages/react-table/src/components/TableComposable/OuterScrollContainer.tsx
  packages/react-table/src/components/TableComposable/TableComposable.tsx
  packages/react-table/src/components/TableComposable/Th.tsx
  packages/react-table/src/components/TableComposable/Thead.tsx
  packages/react-table/src/components/TableComposable/Tr.tsx
  packages/react-table/src/components/TableComposable/examples/ComposableTable.md
  packages/react-table/src/components/TableComposable/index.ts
Labels: ux review, css approved

#6556 feat(Pagination): Added indeterminate count
  packages/react-core/src/components/Pagination/Navigation.tsx
  packages/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/OptionsToggle.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/Pagination/examples/Pagination.md
Labels: ux review, css review

#6581 Add text input group demo
  packages/react-core/src/demos/TextInputGroupDemo.md
Labels: ux review, css review

#6545 feat(CalendarMonth): Added DateTimePicker demo
  packages/react-core/src/demos/DateTimePicker.md
Labels: ux review

#6570 feat(panel): added panel component
  packages/react-core/src/components/Panel/Panel.tsx
  packages/react-core/src/components/Panel/PanelFooter.tsx
  packages/react-core/src/components/Panel/PanelHeader.tsx
  packages/react-core/src/components/Panel/PanelMain.tsx
  packages/react-core/src/components/Panel/PanelMainBody.tsx
  packages/react-core/src/components/Panel/__tests__/Panel.test.tsx
  packages/react-core/src/components/Panel/__tests__/__snapshots__/Panel.test.tsx.snap
  packages/react-core/src/components/Panel/examples/Panel.md
  packages/react-core/src/components/Panel/index.ts
  packages/react-core/src/components/index.ts
Labels: css review, accessibility

#6565 feat(card): added hoverable/selectable/selected-raised variant
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
  packages/react-core/src/components/Card/examples/Card.md
Labels: ux review, css review

#6562 Page nav flyout bug
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/__tests__/Menu.test.tsx
  packages/react-core/src/components/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
  packages/react-core/src/components/Nav/NavItem.tsx
  packages/react-core/src/components/Nav/__tests__/Generated/NavItem.test.tsx
  packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavItem.test.tsx.snap
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/demos/Nav.md
  packages/react-docs/src/generated/components/navigation/react-demos/flyout-nav.png
Labels: css review
