Repository patternfly/patternfly-react, pull requests merged in 2021-12, with the labels that each got.

#6612 fix(Slider): Input resizing
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-core/src/components/Slider/examples/Slider.md
  packages/react-integration/cypress/integration/slider.spec.ts
Labels: css review

#6645 chore(Tabs): added nested Tabs demo
  packages/react-core/src/demos/Tabs.md
  packages/react-core/src/demos/Tabs/NestedTabsDemo.js
Labels: ux review, css review

#6651 feat(Dropdown): add toggle variants
  packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
  packages/react-core/src/components/Dropdown/DropdownToggle.tsx
  packages/react-core/src/components/Dropdown/Toggle.tsx
  packages/react-core/src/components/Dropdown/__tests__/DropdownToggle.test.tsx
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/DropdownToggle.test.tsx.snap
  packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Toggle.test.tsx.snap
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
Labels: ux review, css review

#6660 fix(popover): forwarded focus to close button with VoiceOver click
  packages/react-core/src/components/Popover/Popover.tsx
  packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/Popover.test.tsx.snap
  packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
Labels: accessibility

#6627 feat(MenuToggle): add plain with text variant
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx
  packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
Labels: ux review, css review

#6661 docs(TextInputGroup): add auto-complete search demo
  packages/react-core/src/demos/TextInputGroupDemo.md
  packages/react-core/src/demos/examples/TextInputGroup/AttributeValueFiltering.js
  packages/react-core/src/demos/examples/TextInputGroup/AutoCompleteSearch.js
Labels: ux review, css review

#6664 feat(Popover): add composable header and alert variants
  packages/react-core/src/components/Popover/Popover.tsx
  packages/react-core/src/components/Popover/PopoverBody.tsx
  packages/react-core/src/components/Popover/PopoverFooter.tsx
  packages/react-core/src/components/Popover/PopoverHeader.tsx
  packages/react-core/src/components/Popover/PopoverHeaderIcon.tsx
  packages/react-core/src/components/Popover/PopoverHeaderText.tsx
  packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverHeader.test.tsx.snap
  packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  packages/react-core/src/components/Popover/examples/Popover.md
  packages/react-core/src/demos/BackToTop.md
Labels: ux review, css review
