Repository patternfly/patternfly-react, pull requests merged in 2021-06, with the labels that each got.

#5807 docs(Menu): add drilldown composable menu demo back
  packages/react-core/src/demos/ComposableMenu.md
Labels: css review, ux review

#5827 fix(Table): change checkbox behavior in tree table examples
  packages/react-table/src/components/Table/examples/Table.md
Labels: accessibility

#5824 feat(Menu): filter tree demo
  packages/react-core/src/components/TreeView/TreeViewListItem.tsx
  packages/react-core/src/components/TreeView/TreeViewRoot.tsx
  packages/react-core/src/demos/ComposableMenu.md
Labels: css review, ux review

#5842 feat(Wizard): allow for expandable nav items
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardNavItem.tsx
  packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
  packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
  packages/react-core/src/components/Wizard/examples/Wizard.md
  packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
Labels: css review, ux review

#5887 feat(Card): Added support to remove offset from actions
  packages/react-core/src/components/Card/CardActions.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/images/pfLogo.svg
Labels: css review

#5885 feat(DescriptionList): add responsive layout breakpoint property
  packages/react-core/src/components/DescriptionList/DescriptionList.tsx
  packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
  packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap
  packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
  packages/react-integration/cypress/integration/descriptionlistbreakpoints.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListBreakpointsDemo.tsx
Labels: css review

#5907 docs(Card): add horizontal card grid demo
  packages/react-core/src/demos/Card/Card.md
  packages/react-core/src/demos/CardDemos.md
Labels: css review, ux review

#5870 fix(breadcrumb): moved divider outside of header element
  packages/react-core/src/components/Breadcrumb/BreadcrumbHeading.tsx
Labels: css review

#5917 feat(Text): Added support for visited link styling
  packages/react-core/src/components/Text/Text.tsx
  packages/react-core/src/components/Text/TextContent.tsx
  packages/react-core/src/components/Text/examples/Text.md
  packages/react-integration/cypress/integration/text.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TextDemo/TextDemo.tsx
Labels: css review

#5892 feat(split): added prop to allow children to wrap
  packages/react-core/src/layouts/Split/Split.tsx
  packages/react-core/src/layouts/Split/__tests__/Split.test.tsx
  packages/react-core/src/layouts/Split/__tests__/__snapshots__/Split.test.tsx.snap
  packages/react-core/src/layouts/Split/examples/Split.md
  packages/react-integration/cypress/integration/split.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SplitDemo/SplitDemo.tsx
Labels: css review

#5903 feat(HelperText): add helper text component
  packages/react-core/src/components/HelperText/HelperText.tsx
  packages/react-core/src/components/HelperText/HelperTextItem.tsx
  packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
  packages/react-core/src/components/HelperText/__tests__/__snapshots__/HelperText.test.tsx.snap
  packages/react-core/src/components/HelperText/examples/HelperText.md
  packages/react-core/src/components/HelperText/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/helpertext.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/HelperText/HelperTextDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#5921 feat(Table): add draggable table rows demo
  packages/react-table/src/components/Table/DraggableCell.tsx
  packages/react-table/src/components/Table/DraggableRowWrapper.tsx
  packages/react-table/src/components/Table/TableTypes.ts
  packages/react-table/src/components/Table/examples/Table.md
  packages/react-table/src/components/Table/index.ts
  packages/react-table/src/components/Table/utils/decorators/draggable.tsx
  packages/react-table/src/components/TableComposable/Td.tsx
  yarn.lock
Labels: css review, ux review
