Repository patternfly/patternfly-react, pull requests merged in 2021-05, with the labels that each got.

#5727 feat(ToolbarItem): add widths on breakpoints
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
  packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-integration/cypress/integration/toolbar.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
Labels: css review

#5688 fix(Accordion): set button type, update prop extension
  packages/react-core/src/components/Accordion/AccordionToggle.tsx
  packages/react-core/src/components/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
Labels: css review

#5735 feat(Gallery): add min/max widths at breakpoints
  packages/react-core/src/layouts/Gallery/Gallery.tsx
  packages/react-core/src/layouts/Gallery/__tests__/Gallery.test.tsx
  packages/react-core/src/layouts/Gallery/__tests__/__snapshots__/Gallery.test.tsx.snap
  packages/react-core/src/layouts/Gallery/examples/Gallery.md
  packages/react-integration/cypress/integration/gallery.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/GalleryDemo/GalleryDemo.tsx
Labels: css review

#5723 feat(Card): add isToggleRightAligned prop
  packages/react-core/src/components/Card/CardHeader.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: css review, ux review

#5657 Feat/log viewer [WIP]
  .circleci/config.yml
  packages/react-docs/patternfly-docs.source.js
  packages/react-log-viewer/package.json
  packages/react-log-viewer/src/LogViewer/LogViewer.tsx
  packages/react-log-viewer/src/LogViewer/LogViewerContext.tsx
  packages/react-log-viewer/src/LogViewer/LogViewerCustomControl.tsx
  packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx
  packages/react-log-viewer/src/LogViewer/LogViewerToolbar.tsx
  packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
  packages/react-log-viewer/src/LogViewer/examples/bigTestData.js
  packages/react-log-viewer/src/LogViewer/examples/realTestData.js
  packages/react-log-viewer/src/LogViewer/index.ts
  packages/react-log-viewer/src/LogViewer/utils/constants.ts
  packages/react-log-viewer/src/LogViewer/utils/utils.tsx
  packages/react-log-viewer/src/index.ts
  packages/react-log-viewer/src/react-window/VariableSizeList.tsx
  packages/react-log-viewer/src/react-window/areEqual.ts
  packages/react-log-viewer/src/react-window/createListComponent.ts
  packages/react-log-viewer/src/react-window/domHelpers.ts
  packages/react-log-viewer/src/react-window/index.ts
  packages/react-log-viewer/src/react-window/shallowDiffers.ts
  packages/react-log-viewer/src/react-window/timer.ts
  packages/react-log-viewer/tsconfig.cjs.json
  packages/react-log-viewer/tsconfig.json
  packages/tsconfig.base.json
  packages/tsconfig.cjs.json
  packages/tsconfig.json
  yarn.lock
Labels: ux review

#5722 feat(MenuToggle): add menu toggle / Add composable menu POCs
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx
  packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
  packages/react-core/src/components/MenuToggle/index.ts
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/ComposableMenu.md
  packages/react-core/src/helpers/index.ts
  packages/react-integration/cypress/integration/menutoggle.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuToggleDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, ux review

#5736 feat(Select): Added footer and view more options
  packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsole.test.tsx.snap
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/SelectOption.tsx
  packages/react-core/src/components/Select/SelectToggle.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/SelectOption.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/SelectToggle.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-integration/cypress/integration/select.spec.ts
  packages/react-integration/cypress/integration/selectviewmore.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#5796 feat(list): added icons, plain, bordered
  packages/react-core/src/components/List/List.tsx
  packages/react-core/src/components/List/ListItem.tsx
  packages/react-core/src/components/List/__tests__/Generated/__snapshots__/ListItem.test.tsx.snap
  packages/react-core/src/components/List/__tests__/List.test.tsx
  packages/react-core/src/components/List/__tests__/__snapshots__/List.test.tsx.snap
  packages/react-core/src/components/List/examples/List.md
  packages/react-integration/cypress/integration/list.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ListDemo/ListDemo.tsx
Labels: css review, ux review

#5740 core(Slider): showBoundaries should be independent from showTicks
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/SliderStep.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-core/src/components/Slider/examples/Slider.md
Labels: ux review

#5808 feat(Button): add danger modifier to link/secondary buttons
  packages/react-core/src/components/Button/Button.tsx
  packages/react-core/src/components/Button/__tests__/Button.test.tsx
  packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/react-core/src/components/Button/examples/Button.md
  packages/react-integration/cypress/integration/button.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
Labels: ux review

#5791 feat(Menu): add footer, add view more demo
  packages/react-core/src/components/Menu/MenuFooter.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/index.ts
  packages/react-integration/cypress/integration/menu.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
Labels: accessibility, css review, ux review

#5793 feat(select): allow filtering in single variant
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/SelectMenu.tsx
  packages/react-core/src/components/Select/SelectToggle.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-integration/cypress/integration/selectfiltering.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/FilteringSelectDemo.tsx
Labels: ux review

#5274 feat(grid+flex): add ability to specify order
  packages/react-core/src/helpers/util.ts
  packages/react-core/src/layouts/Flex/Flex.tsx
  packages/react-core/src/layouts/Flex/FlexItem.tsx
  packages/react-core/src/layouts/Flex/examples/Flex.md
  packages/react-core/src/layouts/Grid/Grid.tsx
  packages/react-core/src/layouts/Grid/GridItem.tsx
  packages/react-core/src/layouts/Grid/examples/Grid.md
Labels: css review
