Repository patternfly/patternfly-react, pull requests merged in 2021-04, with the labels that each got.

#5608 fix(treeview): add classname
  packages/react-core/src/components/TreeView/TreeView.tsx
  packages/react-core/src/components/TreeView/TreeViewRoot.tsx
Labels: bug :bug:

#5623 fix(Wizard): disable back button on first step for keyboard users
  packages/react-core/src/components/Wizard/WizardFooterInternal.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardFooterInternal.test.tsx.snap
Labels: accessibility

#5605 fix(card): add empty state to card demo
  packages/react-core/src/demos/Card/Card.md
Labels: css review, ux review

#5589 Nav: add missing pf-c-nav__list class to grouped nav items wrapper
  packages/react-core/src/components/Nav/NavGroup.tsx
  packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavGroup.test.tsx.snap
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
Labels: css review

#5654 feat(TableText): allow passing tooltipProps
  packages/react-core/src/components/Tooltip/examples/Tooltip.md
  packages/react-integration/cypress/integration/tablecomposable.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx
  packages/react-table/src/components/Table/TableText.tsx
Labels: ux review

#5632 feat(Card): add full-height and plain variation
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: css review, ux review

#5629 feat(ClipboardCopy): add inline variant
  packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
  packages/react-core/src/components/ClipboardCopy/ClipboardCopyAction.tsx
  packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
  packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md
  packages/react-core/src/components/ClipboardCopy/index.ts
  packages/react-integration/cypress/integration/clipboardcopy.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ClipboardCopyDemo/ClipboardCopyDemo.tsx
Labels: ux review

#5677 feat(Select): Added optional item count
  packages/react-core/src/components/Select/SelectOption.tsx
  packages/react-core/src/components/Select/__tests__/SelectOption.test.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/SelectOption.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-integration/cypress/integration/select.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
Labels: css review, ux review

#5643 feat(ExpandableSection): add detached variant, update tests
  packages/react-console/src/components/DesktopViewer/__tests__/__snapshots__/DesktopViewer.test.tsx.snap
  packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
  packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/Generated/__snapshots__/ExpandableSection.test.tsx.snap
  packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
  packages/react-core/src/components/ExpandableSection/index.ts
  packages/react-integration/cypress/integration/expandablesection.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx
Labels: css review, ux review

#5671 docs(Card): move card view to demos section
  package.json
  packages/react-core/src/demos/Card/Card.md
  packages/react-docs/src/generated/components/backdrop/react/with-spinner.png
  packages/react-docs/src/generated/components/login-page/react/basic.png
  packages/react-docs/src/generated/components/login-page/react/showhide-password.png
  packages/react-docs/src/generated/components/toolbar/react-demos/console-log-viewer-toolbar-demo.png
  packages/react-docs/src/generated/demos/card-view/react-demos/card-view.png
  packages/react-docs/src/generated/demos/primary-detail/react-demos/primary-detail-data-list-in-card.png
  packages/react-docs/src/generated/demos/primary-detail/react-demos/primary-detail-simple-list-in-card.png
Labels: ux review

#5656 feat(CodeBlock): add component
  packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
  packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md
  packages/react-core/src/components/ClipboardCopy/index.ts
  packages/react-core/src/components/CodeBlock/CodeBlock.tsx
  packages/react-core/src/components/CodeBlock/CodeBlockAction.tsx
  packages/react-core/src/components/CodeBlock/CodeBlockCode.tsx
  packages/react-core/src/components/CodeBlock/__tests__/CodeBlock.test.tsx
  packages/react-core/src/components/CodeBlock/__tests__/__snapshots__/CodeBlock.test.tsx.snap
  packages/react-core/src/components/CodeBlock/examples/CodeBlock.md
  packages/react-core/src/components/CodeBlock/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/codeblock.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/CodeBlockDemo/CodeBlockDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#5672 feat(Table): Add optional icons to tree table rows, add responsive view
  packages/react-catalog-view-extension/package.json
  packages/react-console/package.json
  packages/react-core/package.json
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-table/src/components/Table/TableTypes.ts
  packages/react-table/src/components/Table/TreeRowWrapper.tsx
  packages/react-table/src/components/Table/examples/Table.md
  packages/react-table/src/components/Table/utils/decorators/treeRow.tsx
  packages/react-table/src/components/TableComposable/TableComposable.tsx
  packages/react-table/src/components/TableComposable/Td.tsx
  packages/react-tokens/package.json
  yarn.lock
Labels: css review, ux review

#5669 fix, feat(Slider): Update Slider API to be more like the range input API
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/_tests_/Slider.test.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-core/src/components/Slider/examples/Slider.md
  packages/react-integration/cypress/integration/slider.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
Labels: bug :bug:, enhancement :rocket:, ux review

#5621 feat(Form): Add stacked variant and section title
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/FormSection.tsx
  packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
  packages/react-core/src/components/Form/__tests__/FormSection.test.tsx
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormSection.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/cypress/integration/formhorizontal.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormHorizontalDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#5675 feat(Select): Added invalid state to select
  packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsole.test.tsx.snap
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-integration/cypress/integration/selectvalidated.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectValidatedDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review

#5696 Release notes 2020 5
  packages/react-docs/RELEASE-NOTES.md
  packages/react-docs/src/generated/components/backdrop/react/with-spinner.png
  packages/react-docs/src/generated/components/login-page/react/basic.png
  packages/react-docs/src/generated/components/login-page/react/showhide-password.png
  packages/react-docs/src/generated/components/toolbar/react-demos/console-log-viewer-toolbar-demo.png
  packages/react-docs/src/generated/demos/primary-detail/react-demos/primary-detail-data-list-in-card.png
  packages/react-docs/src/generated/demos/primary-detail/react-demos/primary-detail-simple-list-in-card.png
Labels: chore :house:
