Repository patternfly/patternfly-react, pull requests merged in 2021-01, with the labels that each got.

#5255 chore(eslint): Add linting rule to disallow nested ternaries
  .eslintrc.json
  packages/react-charts/src/components/ChartBullet/ChartBullet.tsx
  packages/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx
  packages/react-charts/src/components/ChartBullet/utils/chart-bullet-size.ts
  packages/react-console/src/components/AccessConsoles/AccessConsoles.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Radio/Radio.tsx
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/TimePicker/TimePicker.tsx
  packages/react-core/src/components/TimePicker/TimePickerUtils.tsx
  packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableFavoritesDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultGroup.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/GroupHull.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/NodePath.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/NodePolygon.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/NodeRect.tsx
  packages/react-table/src/components/Table/Body.tsx
  packages/react-table/src/components/Table/utils/decorators/selectable.tsx
  packages/react-table/src/components/Table/utils/headerUtils.tsx
  packages/react-topology/src/behavior/useDndDrag.tsx
  packages/react-topology/src/behavior/useDndDrop.tsx
  packages/react-topology/src/components/DefaultRemoveConnector.tsx
  packages/react-topology/src/components/layers/Layer.tsx
Labels: chore :house:

#5318 Hides Popover when its trigger is scrolled out of view
  packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalContainer.test.tsx.snap
  packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
  packages/react-core/src/components/Popover/Popover.tsx
  packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/Popover.test.tsx.snap
  packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/helpers/FocusTrap/FocusTrap.tsx
  packages/react-core/src/helpers/Popper/Popper.tsx
  packages/react-docs/patternfly-docs.css.js
  packages/react-styles/.gitignore
  packages/react-styles/src/css/components/Popper/Popper.css
Labels: ux review

#5230 fix(SearchInput): hide clear button when onClear function is not set
  packages/react-core/src/components/SearchInput/SearchInput.tsx
  packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
Labels: ux review

#5338 (Number input): Renamed Touchspin to NumberInput
  packages/react-catalog-view-extension/package.json
  packages/react-charts/package.json
  packages/react-console/package.json
  packages/react-core/package.json
  packages/react-core/src/components/NumberInput/NumberInput.tsx
  packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
  packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
  packages/react-core/src/components/NumberInput/examples/NumberInput.md
  packages/react-core/src/components/NumberInput/index.ts
  packages/react-core/src/components/Touchspin/index.ts
  packages/react-core/src/components/index.ts
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/drawer.spec.ts
  packages/react-integration/cypress/integration/numberInput.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/NumberInputDemo/NumberInputDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/react-styles/package.json
  packages/react-table/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: bug :bug:, css review, ux review

#5312 fix(Nav): Make nav items keyboard and screen reader accessible
  packages/react-core/src/components/Nav/NavExpandable.tsx
  packages/react-core/src/components/Nav/NavItem.tsx
  packages/react-core/src/components/Nav/NavList.tsx
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  packages/react-core/src/components/Page/PageSidebar.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-core/src/demos/Nav.md
Labels: accessibility

#5328 feat(Drawer): improve cursor responsiveness
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
Labels: ux review

#5298 fix(table): empty state should be consistent across demos and examples
  packages/react-table/src/components/Table/examples/Table.md
  packages/react-table/src/demos/Table.md
Labels: ux review

#5325 fix(Wizard): add wizard demos to match core
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/demos/Wizard/WizardDemo.md
  packages/react-core/src/demos/Wizard/imgBrand.svg
Labels: css review, ux review

#5331 fix(drawer): fix dragging problem on iframe when resizing drawer
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-docs/patternfly-docs.css.js
  packages/react-styles/src/css/components/Drawer/DrawerIframe.css
Labels: css review

#5358 feat(Slider): Added new slider component
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/SliderStep.tsx
  packages/react-core/src/components/Slider/_tests_/Slider.test.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-core/src/components/Slider/examples/Slider.md
  packages/react-core/src/components/Slider/index.ts
  packages/react-core/src/components/index.ts
  packages/react-integration/cypress/integration/slider.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: accessibility, css review, ux review
