Repository patternfly/patternfly-react, pull requests merged in 2022-11, with the labels that each got.

#8310 feat(Popper, misc): allow components to customize popper z-index
  packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
  packages/react-core/src/components/ContextSelector/ContextSelector.tsx
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
  packages/react-core/src/components/Nav/NavItem.tsx
  packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx
  packages/react-core/src/components/SearchInput/SearchInput.tsx
  packages/react-core/src/components/Select/Select.tsx
  packages/react-core/src/components/Tabs/OverflowTab.tsx
  packages/react-core/src/components/TimePicker/TimePicker.tsx
  packages/react-core/src/next/components/Dropdown/Dropdown.tsx
  packages/react-core/src/next/components/Select/Select.tsx
Labels: css review

#8307 feat(Progress): added helper text
  packages/react-core/src/components/HelperText/__mocks__/HelperText.tsx
  packages/react-core/src/components/HelperText/__mocks__/HelperTextItem.tsx
  packages/react-core/src/components/HelperText/__mocks__/index.ts
  packages/react-core/src/components/Progress/Progress.tsx
  packages/react-core/src/components/Progress/ProgressContainer.tsx
  packages/react-core/src/components/Progress/ProgressHelperText.tsx
  packages/react-core/src/components/Progress/__tests__/Progress.test.tsx
  packages/react-core/src/components/Progress/__tests__/ProgressHelperText.test.tsx
  packages/react-core/src/components/Progress/__tests__/__snapshots__/ProgressHelperText.test.tsx.snap
  packages/react-core/src/components/Progress/examples/Progress.md
  packages/react-core/src/components/Progress/examples/ProgressHelperText.tsx
Labels: ux review, css review

#8344 feat(MultipleFileUpload): added support for helper text
  packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx
  packages/react-core/src/components/MultipleFileUpload/__tests__/MultipleFileUploadStatusItem.test.tsx
  packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md
  packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUploadBasic.tsx
Labels: ux review, css review

#8329 feat(MenuInput): use SearchInput instead of TextInput
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx
  packages/react-integration/cypress/integration/menu.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
Labels: ux review, css review

#8304 fix(NumberInput): allow user to back out number to type input
  packages/react-core/src/components/NumberInput/NumberInput.tsx
  packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInput.md
  packages/react-core/src/components/NumberInput/examples/NumberInputCustomStep.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputCustomStepAndThreshold.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputDefault.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputDisabled.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputUnit.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputUnitThreshold.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputVaryingSizes.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInputWithStatus.tsx
  packages/react-integration/cypress/integration/numberInput.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NumberInputDemo/NumberInputDemo.tsx
Labels: ux review

#8328 feat(spinner): added isInline, updated link button
  packages/react-core/src/components/Button/Button.tsx
  packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/react-core/src/components/Spinner/Spinner.tsx
  packages/react-core/src/components/Spinner/examples/Spinner.md
  packages/react-core/src/components/Spinner/examples/SpinnerInline.tsx
Labels: css review

#8286 chore(tabs): reworked tabs demos based on design/core updates
  packages/react-core/src/demos/Tabs.md
  packages/react-core/src/demos/examples/DashboardWrapper.js
  packages/react-core/src/demos/examples/Tabs/GrayTabs.tsx
  packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx
  packages/react-core/src/demos/examples/Tabs/NestedTabs.tsx
  packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
  packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
  packages/react-core/src/demos/examples/Tabs/TabsAndTablesAutoWidthTabs.tsx
Labels: css review, ux approved

#8348 feat(Tabs): add TabAction, update core ver
  packages/react-catalog-view-extension/package.json
  packages/react-console/package.json
  packages/react-core/package.json
  packages/react-core/src/components/Tabs/Tab.tsx
  packages/react-core/src/components/Tabs/TabAction.tsx
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/__tests__/Tab.test.tsx
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-core/src/components/Tabs/examples/TabsHelp.tsx
  packages/react-core/src/components/Tabs/examples/TabsHelpAndClose.tsx
  packages/react-core/src/components/Tabs/index.ts
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: ux review, css review
