Repository patternfly/patternfly-react, pull requests merged in 2022-08, with the labels that each got.

#7713 feat(DescriptionList): add Display and Card variants
  packages/react-core/src/components/DescriptionList/DescriptionList.tsx
  packages/react-core/src/components/DescriptionList/DescriptionListGroup.tsx
  packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
  packages/react-core/src/components/DescriptionList/examples/DescriptionListDisplaySizeAndCard.tsx
  packages/react-core/src/components/DescriptionList/examples/DescriptionListDisplaySizeAndCardHorizontalTermWidth.tsx
  packages/react-core/src/components/DescriptionList/examples/DescriptionListDisplaySizeAndCardThreeColumn.tsx
  packages/react-core/src/components/DescriptionList/examples/DescriptionListWithCard.tsx
  packages/react-core/src/components/DescriptionList/examples/DescriptionListWithDisplaySize.tsx
Labels: ux review, css review

#7764 feat(Page): add support for vertical breakpoints, add sticky breadcrumb demo
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Page/PageBreadcrumb.tsx
  packages/react-core/src/components/Page/PageGroup.tsx
  packages/react-core/src/components/Page/PageNavigation.tsx
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/Page.test.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-core/src/demos/Page/Page.md
  packages/react-core/src/helpers/constants.ts
  packages/react-core/src/helpers/util.ts
Labels: ux review, css review

#7748 feat(MenuToggle): add split button variants
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/MenuToggleAction.tsx
  packages/react-core/src/components/MenuToggle/MenuToggleCheckbox.tsx
  packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonAction.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonActionPrimary.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonActionSecondary.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckbox.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxPrimary.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxSecondary.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxWithText.tsx
  packages/react-core/src/components/MenuToggle/index.ts
Labels: ux review, css review

#7743 fix(Menu): can navigate via keyboard for checkbox variant
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx
Labels: accessibility

#7790 fix(Select): apply aria-describedby to correct element
  packages/react-core/src/components/Select/Select.tsx
Labels: accessibility

#7822 chore(Page): add aria label prop to page subcomponents explicitly
  packages/react-core/src/components/Page/PageBreadcrumb.tsx
  packages/react-core/src/components/Page/PageGroup.tsx
  packages/react-core/src/components/Page/PageNavigation.tsx
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/PageBreadcrumb.test.tsx
  packages/react-core/src/components/Page/__tests__/PageGroup.test.tsx
  packages/react-core/src/components/Page/__tests__/PageNavigation.test.tsx
  packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
  packages/react-core/src/demos/JumpLinks.md
  packages/react-core/src/demos/examples/BackToTop/BackToTopNameDemo.tsx
Labels: accessibility

#7828 feat(Label): adjust editable keyboard behavior
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/LabelGroup/LabelGroup.tsx
  packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
  packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAdd.tsx
  packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddDropdown.tsx
  packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddModal.tsx
Labels: accessibility

#7850 docs(Table): add sticky toolbar with table demo
  packages/react-table/src/demos/Table.md
  packages/react-table/src/demos/examples/ComposableTableStickyToolbar.tsx
Labels: ux review, css review

#7806 feat(NumberInput): add status validate icons
  packages/react-core/src/components/InputGroup/InputGroup.tsx
  packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx
  packages/react-core/src/components/NumberInput/NumberInput.tsx
  packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
  packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
  packages/react-core/src/components/NumberInput/examples/NumberInput.md
  packages/react-core/src/components/NumberInput/examples/WithStatus.tsx
Labels: enhancement :rocket:, ux review, css review, accessibility

#7852 feat(ExpandableSection): add truncated variant
  packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
  packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionTruncateExpansion.tsx
Labels: css review, ux approved

#7815 feat(Timestamp): create component
  packages/react-core/src/components/Timestamp/Timestamp.tsx
  packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx
  packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap
  packages/react-core/src/components/Timestamp/examples/Timestamp.md
  packages/react-core/src/components/Timestamp/examples/TimestampBasicFormats.tsx
  packages/react-core/src/components/Timestamp/examples/TimestampCustomContent.tsx
  packages/react-core/src/components/Timestamp/examples/TimestampCustomFormat.tsx
  packages/react-core/src/components/Timestamp/examples/TimestampCustomTooltip.tsx
  packages/react-core/src/components/Timestamp/examples/TimestampDefault.tsx
  packages/react-core/src/components/Timestamp/examples/TimestampDefaultTooltip.tsx
  packages/react-core/src/components/Timestamp/index.ts
  packages/react-core/src/components/index.ts
Labels: ux review, css review, accessibility

#7838 chore(table): update expandable table data
  packages/react-table/src/demos/table-demos/ExpandCollapseAll.jsx
  packages/react-table/src/docs/demos/Table.md
  packages/react-table/src/docs/demos/table-demos/Compact.jsx
  packages/react-table/src/docs/demos/table-demos/CompoundExpansion.jsx
  packages/react-table/src/docs/demos/table-demos/ExpandCollapseAll.jsx
  packages/react-table/src/docs/demos/table-demos/StickyFirstColumn.jsx
  packages/react-table/src/docs/examples/ComposableTableStickyToolbar.tsx
  packages/react-table/src/docs/examples/Data.jsx
Labels: ux review

#7725 Adds content to card react examples
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/demos/CardDemos.md
Labels: ux review, documentation :memo:

#7703 feat(WizardComposable): Created composable spinoff of wizard w/ enhancements
  packages/react-core/src/components/Wizard/examples/Wizard.md
  packages/react-core/src/next/components/Wizard/Wizard.tsx
  packages/react-core/src/next/components/Wizard/WizardBody.tsx
  packages/react-core/src/next/components/Wizard/WizardContext.tsx
  packages/react-core/src/next/components/Wizard/WizardFooter.tsx
  packages/react-core/src/next/components/Wizard/WizardHeader.tsx
  packages/react-core/src/next/components/Wizard/WizardNav.tsx
  packages/react-core/src/next/components/Wizard/WizardNavItem.tsx
  packages/react-core/src/next/components/Wizard/WizardStep.tsx
  packages/react-core/src/next/components/Wizard/WizardToggle.tsx
  packages/react-core/src/next/components/Wizard/__tests__/Wizard.test.tsx
  packages/react-core/src/next/components/Wizard/examples/Wizard.md
  packages/react-core/src/next/components/Wizard/examples/WizardBasic.tsx
  packages/react-core/src/next/components/Wizard/examples/WizardCustomNav.tsx
  packages/react-core/src/next/components/Wizard/examples/WizardKitchenSink.tsx
  packages/react-core/src/next/components/Wizard/hooks/index.ts
  packages/react-core/src/next/components/Wizard/hooks/useWizardFooter.tsx
  packages/react-core/src/next/components/Wizard/index.ts
  packages/react-core/src/next/components/Wizard/types.tsx
  packages/react-core/src/next/components/Wizard/utils.ts
  packages/react-core/src/next/components/index.ts
  packages/react-styles/README.md
Labels: ux review
