Repository patternfly/patternfly-react, pull requests merged in 2022-04, with the labels that each got.

#7082 chore(CalendarMonth): add date range example
  packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
  packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md
  packages/react-core/src/components/CalendarMonth/examples/CalendarMonthDateRange.tsx
Labels: ux review, css review

#7172 fix(a11y): various aria related updates
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
  packages/react-core/src/components/JumpLinks/JumpLinksItem.tsx
  packages/react-core/src/components/JumpLinks/__tests__/__snapshots__/JumpLinks.test.tsx.snap
  packages/react-core/src/components/ProgressStepper/ProgressStep.tsx
  packages/react-core/src/components/ProgressStepper/__tests__/__snapshots__/ProgressStepper.test.tsx.snap
  packages/react-core/src/components/ProgressStepper/examples/ProgressStepper.md
  packages/react-core/src/components/Tabs/Tab.tsx
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/examples/Tabs.md
Labels: accessibility

#7197 feat(Wizard): add description component type
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardHeader.tsx
  packages/react-core/src/components/Wizard/examples/Wizard.md
Labels: css review

#7183 docs(Tabs): add tables and tabs auto width tabs demo
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/demos/Tabs.md
  packages/react-core/src/demos/examples/Tabs/TabsAndTablesAutoWidthTabs.tsx
Labels: ux review, css review

#7176 feat(Brand): allow picture with child elements and breakpoints, add example/test
  packages/react-core/src/components/Brand/Brand.tsx
  packages/react-core/src/components/Brand/__tests__/Brand.test.tsx
  packages/react-core/src/components/Brand/__tests__/__snapshots__/Brand.test.tsx.snap
  packages/react-core/src/components/Brand/examples/Brand.md
  packages/react-core/src/components/Brand/examples/BrandResponsive.tsx
  packages/react-core/src/components/Brand/examples/pf-c-brand--logo-base.jpg
  packages/react-core/src/components/Brand/examples/pf-c-brand--logo-on-lg.svg
  packages/react-core/src/components/Brand/examples/pf-c-brand--logo-on-md.svg
  packages/react-core/src/components/Brand/examples/pf-c-brand--logo-on-sm.svg
  packages/react-core/src/components/Brand/examples/pf-c-brand--logo-on-xl.svg
  packages/react-core/src/components/Brand/examples/pf-c-brand--logo.svg
Labels: css review

#7192 fix(Pagination): make items per page text in toggle clickable
  packages/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/OptionsToggle.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/Pagination/examples/Pagination.md
  packages/react-integration/cypress/integration/paginationbuttonvariant.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationButtonVariantDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: ux review, css review

#7242 docs(Toolbar): Updated to use search input instead of input group in …
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
Labels: ux review, css review

#7229 Feat(Switch): Adds check + label functionality and demo
  packages/react-core/src/components/Switch/Switch.tsx
  packages/react-core/src/components/Switch/examples/Switch.md
Labels: ux review, css review

#7194 feat(Tabs): Add nested, unindented demo
  packages/react-core/src/demos/Tabs.md
  packages/react-core/src/demos/examples/DashboardWrapper.js
  packages/react-core/src/demos/examples/Tabs/GrayTabs.tsx
  packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx
  packages/react-core/src/demos/examples/Tabs/NestedTabs.tsx
  packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
  packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
Labels: ux review, css review

#7250 feat(HelperText): add react demos
  packages/react-core/src/components/HelperText/HelperText.tsx
  packages/react-core/src/components/HelperText/HelperTextItem.tsx
  packages/react-core/src/demos/HelperText.md
  packages/react-core/src/demos/examples/HelperText/HelperTextDynamicVariantStaticText.tsx
  packages/react-core/src/demos/examples/HelperText/HelperTextStaticVariantDynamicText.tsx
  packages/react-core/src/demos/examples/HelperText/HelperTextStaticVariantStaticText.tsx
Labels: ux review, css review, accessibility
