Repository patternfly/patternfly-react, pull requests merged in 2022-03, with the labels that each got.

#6955 feat(Toolbar): allow custom chip group content
  packages/react-core/src/components/Toolbar/Toolbar.tsx
  packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarExpandableContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarUtils.tsx
  packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-core/src/components/Toolbar/examples/ToolbarCustomChipGroupContent.tsx
Labels: ux review

#6932 refactor(demo-masthead): use QuestionCircleIcon instead of HelpIcon in Masthead
  packages/react-core/src/demos/Nav.md
  packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
  packages/react-core/src/demos/Page/Page.md
  packages/react-core/src/demos/examples/DashboardHeader.js
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
  packages/react-table/src/demos/Table.md
Labels: ux review

#6986 fix(Menu): screen reader correctly announces on view more
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
Labels: accessibility

#6979 docs(table): 6776 table example with overflow menu action
  packages/react-table/src/components/TableComposable/examples/ComposableTable.md
  packages/react-table/src/components/TableComposable/examples/ComposableTableActionsOverflow.tsx
Labels: documentation :memo:

#6963 fix(NotificationDrawer): Drawer receives focus after opening
  packages/react-core/src/components/NotificationDrawer/NotificationDrawer.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawer.test.tsx.snap
  packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
Labels: accessibility

#6940 fix(Tabs): make tooltips more accessible
  packages/react-core/src/components/Tabs/Tab.tsx
  packages/react-core/src/components/Tabs/TabButton.tsx
  packages/react-core/src/components/Tabs/examples/Tabs.md
Labels: accessibility

#6877 fix(Tile): add aria-selected to indicate selection state
  packages/react-core/src/components/Tile/Tile.tsx
  packages/react-core/src/components/Tile/__tests__/__snapshots__/Tile.test.tsx.snap
  packages/react-core/src/components/Tile/examples/Tile.md
  packages/react-core/src/demos/TileDemo.md
Labels: accessibility

#6962 demo: date select dropdown
  packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
  packages/react-core/src/demos/ComposableMenu/examples/ComposableDateSelect.tsx
Labels: ux review

#6953 Feat(AlertGroup): 6890 alert group overflow
  packages/react-core/src/components/AlertGroup/AlertGroup.tsx
  packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx
  packages/react-core/src/components/AlertGroup/__tests__/AlertGroup.test.tsx
  packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
  packages/react-core/src/components/AlertGroup/examples/AlertGroup.md
Labels: ux review, css review

#6989 feat(CodeEditor): 6663 - allow for keyboard shortcut menu, add example
  packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
  packages/react-code-editor/src/components/CodeEditor/examples/CodeEditor.md
Labels: ux review, feature

#6949 fix(NumberInput): better support for min/max
  packages/react-core/src/components/NumberInput/NumberInput.tsx
  packages/react-core/src/components/NumberInput/examples/NumberInput.md
Labels: ux review

#7047 feat(Avatar): add new size prop and demo
  packages/react-core/src/components/Avatar/Avatar.tsx
  packages/react-core/src/components/Avatar/examples/Avatar.md
Labels: ux review, css review

#7043 fix(TimePicker): re-add ability to append to document body
  packages/react-core/src/components/TimePicker/TimePicker.tsx
  packages/react-core/src/components/TimePicker/examples/TimePicker.md
Labels: accessibility

#7070 fix(Menu): remove rogue scrollbar from drilldown menus
  packages/react-core/src/components/Menu/MenuContent.tsx
Labels: css review

#7061 Feat(DescriptionList): 6866 set width of term column
  packages/react-core/src/components/DescriptionList/DescriptionList.tsx
  packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
  packages/react-core/src/components/Popover/Popover.tsx
Labels: css review, feature

#7068 fix/docs(Table): add zindex docs, fix old rowIndex callback
  packages/react-table/src/components/Table/base/types.tsx
  packages/react-table/src/components/TableComposable/Td.tsx
  packages/react-table/src/components/TableComposable/examples/ComposableTable.md
Labels: css review

#7089 docs(MenuToggle): update examples to match core
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.css
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
Labels: ux review, css review

#7095 chore(Dropdown): update examples to show different appends
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
Labels: accessibility

#7087 chore(Select): update examples to show different appends
  packages/react-core/src/components/Select/examples/Select.md
Labels: accessibility

#7118 fix(Drawer): Updated resizable drawer to make it more accessible
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/DrawerContent.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/DrawerContent.test.tsx
  packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerContent.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
Labels: accessibility
