Repository patternfly/patternfly-react, pull requests merged in 2022-12, with the labels that each got.

#8361 feat: add pf-screen-reader for screen reader text to Badge
  packages/react-core/src/components/Badge/Badge.tsx
  packages/react-core/src/components/Badge/__tests__/Badge.test.tsx
  packages/react-core/src/components/Badge/examples/BadgeUnread.tsx
Labels: accessibility

#8412 fix(Pagination): Added support for insets
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/Pagination/examples/Pagination.md
  packages/react-core/src/components/Pagination/examples/PaginationInset.tsx
Labels: css review

#8405 feat(Menu): add drilldown filter demo, add flag to support demo & fix some keyboard interaction
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/examples/MenuFilterDrilldown.tsx
Labels: ux review

#8391 feat(Table): add sticky modifiers to Td
  packages/react-table/src/components/Table/base/types.tsx
  packages/react-table/src/components/TableComposable/Td.tsx
  packages/react-table/src/components/TableComposable/Th.tsx
  packages/react-table/src/components/TableComposable/examples/ComposableTable.md
Labels: css review

#8319 feat(Pagination): refactored to use menu/menu toggle
  packages/react-core/src/components/Pagination/Navigation.tsx
  packages/react-core/src/components/Pagination/OptionsToggle.tsx
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/OptionsToggle.test.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/PaginationOptionsMenu.test.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/OptionsToggle.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/Pagination/examples/PaginationBottom.tsx
  packages/react-core/src/components/Pagination/examples/PaginationCompact.tsx
  packages/react-core/src/components/Pagination/examples/PaginationDisabled.tsx
  packages/react-core/src/components/Pagination/examples/PaginationIndeterminate.tsx
  packages/react-core/src/components/Pagination/examples/PaginationNoItems.tsx
  packages/react-core/src/components/Pagination/examples/PaginationOnePage.tsx
  packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx
  packages/react-core/src/components/Pagination/examples/PaginationTop.tsx
  packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx
  packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx
  packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx
  packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx
  packages/react-core/src/demos/Filters/examples/FilterSameSelectGroup.tsx
  packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx
  packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx
  packages/react-integration/cypress/integration/pagination.spec.ts
  packages/react-integration/cypress/integration/paginationbuttonvariant.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationButtonVariantDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
  packages/react-table/src/docs/demos/Table.md
  packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
  packages/react-table/src/docs/demos/table-demos/Compact.jsx
  packages/react-table/src/docs/demos/table-demos/CompoundExpansion.jsx
  packages/react-table/src/docs/demos/table-demos/SortableResponsive.jsx
  packages/react-table/src/docs/demos/table-demos/StaticBottomPagination.jsx
Labels: css review

#8375 chore(CalendarMonth): provided explicit guidance for labeling an inline calendar month
  packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
  packages/react-core/src/components/CalendarMonth/__tests__/CalendarMonth.test.tsx
  packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md
  packages/react-core/src/components/CalendarMonth/examples/CalendarMonthDateRange.tsx
  packages/react-core/src/components/CalendarMonth/examples/CalendarMonthSelectableDate.tsx
Labels: css review
