Repository patternfly/patternfly-react, pull requests merged in 2022-05, with the labels that each got.

#7269 chore(Page): update centered example to match Core
  packages/react-core/src/components/Page/examples/Page.md
Labels: css review

#7285 feat(divider): add support for switching orientation at various breakpoints
  packages/react-core/src/components/Divider/Divider.tsx
  packages/react-core/src/components/Divider/__tests__/Divider.test.tsx
  packages/react-core/src/components/Divider/examples/Divider.md
  packages/react-core/src/components/Divider/examples/DividerOrientationVariousBreakpoints.tsx
  packages/react-core/src/components/Divider/examples/DividerVerticalFlex.tsx
  packages/react-core/src/components/Divider/examples/DividerVerticalFlexInsetMedium.tsx
  packages/react-core/src/components/Divider/examples/DividerVerticalFlexInsetVariousBreakpoints.tsx
  packages/react-core/src/demos/CardDemos.md
Labels: ux review, css review

#7270 chore(docs):cleanup dead link
  ADVANCED-USAGE-README.md
  packages/react-core/README.md
Labels: chore :house:

#7264 Feat(Table): Adds full screen demo for basic/bulk select
  packages/react-table/src/demos/Table.md
Labels: ux review, css review

#7335 fix(ClipboardCopy): dynamic tooltip updates get announced
  packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
Labels: accessibility

#7334 fix: tree view menu keyboard handling
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Panel/Panel.tsx
  packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
  packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx
  packages/react-core/src/helpers/KeyboardHandler.tsx
Labels: accessibility

#7274 fix(Page): add tabindex to components with hasOverflowScroll
  packages/react-core/src/components/Page/PageBreadcrumb.tsx
  packages/react-core/src/components/Page/PageGroup.tsx
  packages/react-core/src/components/Page/PageNavigation.tsx
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageBreadcrumb.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageGroup.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageNavigation.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
Labels: accessibility

#7332 fix(Tooltip): make ref variant announced by assistive tech
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-core/src/components/Tooltip/Tooltip.tsx
  packages/react-core/src/components/Tooltip/examples/Tooltip.md
Labels: accessibility

#7293 docs(Modal): add example preserving a11y when content overflows
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-core/src/components/Modal/__tests__/Modal.test.tsx
  packages/react-core/src/components/Modal/examples/Modal.md
  packages/react-core/src/components/Modal/examples/ModalWithOverflowingContent.tsx
Labels: accessibility

#7297 feat(Tabs): allow dynamic close/add
  packages/react-core/src/components/Tabs/Tab.tsx
  packages/react-core/src/components/Tabs/Tabs.tsx
  packages/react-core/src/components/Tabs/TabsContext.ts
  packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
  packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-core/src/components/Tabs/examples/TabsDynamic.tsx
Labels: ux review, css review, accessibility

#7144 fix(Card): indicate card selectivity and status if using a screen reader
  packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/CardTitle.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/__tests__/CardTitle.test.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/components/Card/examples/CardLegacySelectable.tsx
  packages/react-core/src/components/Card/examples/CardSelectable.tsx
  packages/react-core/src/components/Card/examples/CardSelectableA11yHighlight.tsx
  packages/react-core/src/demos/Card/Card.md
  packages/react-core/src/demos/PrimaryDetail.md
  packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx
Labels: ux review

#7277 feat(table): expandable table demo
  packages/react-table/src/demos/Table.md
  packages/react-table/src/demos/table-demos/ExpandCollapseAll.jsx
Labels: css approved, ux approved

#7377 fix(Banner): add screen reader text
  packages/react-core/src/components/Banner/Banner.tsx
  packages/react-core/src/components/Banner/__tests__/Banner.test.tsx
  packages/react-core/src/components/Banner/__tests__/__snapshots__/Banner.test.tsx.snap
  packages/react-core/src/components/Banner/examples/BannerBasic.tsx
Labels: accessibility

#7333 fix(switch): isReversed variant now supports check icon
  packages/react-core/src/components/Switch/Switch.tsx
Labels: css approved

#7338 feat(table): Add fullscreen demo for compact variant
  packages/react-table/src/demos/Table.md
  packages/react-table/src/demos/table-demos/Compact.jsx
Labels: css review, ux approved

#7387 fix(Chip): add custom maxWidth prop
  packages/react-core/src/components/Chip/Chip.tsx
  packages/react-core/src/components/Chip/__tests__/Chip.test.tsx
  packages/react-core/src/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap
Labels: ux review, css review

#7366 feat(table): add compound expandable fullscreen demo
  packages/react-table/src/demos/Table.md
  packages/react-table/src/demos/table-demos/CompoundExpansion.jsx
Labels: css approved, ux approved

#7408 fix(Slider): add support for aria-labelledby ad aria-describedby
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/_tests_/Slider.test.tsx
Labels: accessibility

#7368 feat(Menu): Added support for checkbox menu
  packages/react-core/src/components/Checkbox/Checkbox.tsx
  packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/__tests__/Menu.test.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/examples/MenuWithCheckbox.tsx
  packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx
Labels: css review, ux approved

#7292 feat(table): update sortable demo to align with core
  packages/react-core/src/demos/examples/DashboardHeader.js
  packages/react-table/src/demos/Table.md
Labels: css approved, ux approved

#7426 feat(HelperText): add screenreader text for dynamic variant
  packages/react-core/src/components/HelperText/HelperTextItem.tsx
  packages/react-core/src/components/HelperText/__tests__/__snapshots__/HelperText.test.tsx.snap
Labels: accessibility

#7370 feat(table): add fullscreen loading state demo
  packages/react-table/src/demos/Table.md
Labels: css review, ux approved

#7434 fix(Select): popper menu flips correctly
  packages/react-core/src/components/ContextSelector/ContextSelector.tsx
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
  packages/react-core/src/components/Select/Select.tsx
Labels: css review

#7371 feat(table): add fullscreen empty state demo
  packages/react-table/src/demos/Table.md
Labels: css approved, ux approved

#7399 feat(Popper): add mouse events for popper content
  packages/react-core/src/components/Tooltip/Tooltip.tsx
  packages/react-core/src/helpers/Popper/Popper.tsx
Labels: accessibility

#7411 fix(Modal): tooltip visibility on modal open
  packages/react-core/src/components/Modal/ModalBoxTitle.tsx
Labels: ux review, accessibility

#7463 fix(Slider): use slider with no linear data
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/examples/Slider.md
  packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
Labels: ux review

#7417 fix(ComposableMenu): update appendTo in demos
  packages/react-core/src/demos/ComposableMenu/examples/ComposableActionsMenu.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableDateSelect.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableDrilldownMenu.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableDropdwnVariants.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableFlyout.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableOptionsMenuVariants.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleDropdown.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx
Labels: css review, accessibility

#7431 refactor(Search Input): use Panel instead Card in composable advanced…
  packages/react-core/src/demos/SearchInput/SearchInput.md
Labels: css review
