Repository patternfly/patternfly-react, pull requests merged in 2023-10, with the labels that each got.

#9583 docs(Text): add description
  packages/react-core/src/components/Text/examples/Text.md
Labels: css review, content review

#9730 feat(Wizard): Add prop for nav aria label
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardNavInternal.tsx
  packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
Labels: accessibility

#9671 [v4] fix(InputGroup): don't add aria-describedby automatically
  packages/react-core/src/components/InputGroup/InputGroup.tsx
  packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx
  packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
Labels: accessibility

#9670 fix(InputGroup): don't add aria-describedby automatically
  packages/react-core/src/components/InputGroup/InputGroup.tsx
  packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx
  packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
Labels: accessibility

#9740 feat(Nav): Updated to add wrapper for nav link text
  packages/react-core/src/components/Nav/NavExpandable.tsx
  packages/react-core/src/components/Nav/NavItem.tsx
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/components/Nav/examples/NavExpandableThirdLevel.tsx
  packages/react-core/src/components/Nav/examples/NavLinkText.tsx
  packages/react-core/src/components/Nav/examples/nav.css
Labels: css review
