Repository patternfly/patternfly-react, pull requests merged in 2023-01, with the labels that each got.

#8392 fix(Slider): updated input text styling
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
Labels: css review

#8480 fix(DualListSelector): added empty state to composable examples
  packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
  packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
  packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposable.tsx
  packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposableTree.tsx
Labels: ux review, css review

#8508 Topology documentation: add baseline and custom demo + docs
  packages/react-docs/patternfly-docs/patternfly-docs.css.js
  packages/react-docs/patternfly-docs/patternfly-docs.source.js
  packages/react-topology/README.md
  packages/react-topology/src/components/TopologyView/examples/Topology.md
  packages/react-topology/src/components/TopologyView/examples/TopologyBaselineDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/TopologyCustomNodeDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
  packages/react-topology/src/components/nodes/DefaultNode.tsx
  yarn.lock
Labels: documentation :memo:

#8560 fix(Tabs): Removed isHelpAction prop from TabsAction
  packages/react-console/package.json
  packages/react-core/package.json
  packages/react-core/src/components/Tabs/TabAction.tsx
  packages/react-core/src/components/Tabs/examples/Tabs.md
  packages/react-core/src/components/Tabs/examples/TabsHelp.tsx
  packages/react-core/src/components/Tabs/examples/TabsHelpAndClose.tsx
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review

#8378 Adds content to dropdown next component examples.
  packages/react-core/src/next/components/Dropdown/examples/Dropdown.md
Labels: Content

#8557 docs(topology): Add pan/zoom demo
  packages/react-topology/src/components/TopologyView/examples/Topology.md
  packages/react-topology/src/components/TopologyView/examples/TopologyPanZoomDemo.tsx
Labels: documentation :memo:

#8512 docs(topology): add selection demo
  packages/react-topology/src/components/TopologyView/examples/Topology.md
  packages/react-topology/src/components/TopologyView/examples/TopologySelectionDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
Labels: documentation :memo:

#8515 feat(Accordion): made scrollable content focusable
  packages/react-core/src/components/Accordion/AccordionContent.tsx
  packages/react-core/src/components/Accordion/__tests__/AccordionContent.test.tsx
  packages/react-core/src/components/Accordion/examples/AccordionFixedWithMultipleExpandBehavior.tsx
  packages/react-integration/cypress/integration/accordion.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/Accordion/AccordionDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, accessibility

#8018 Adds content to menu react examples
  packages/react-core/src/components/Menu/examples/Menu.md
Labels: ux review, documentation :memo:

#8570 fix(ExpandableSection): made toggle button conditional with truncate variant
  packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
  packages/react-integration/cypress/integration/expandablesectiontruncate.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionTruncateDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: ux review, css review

#8496 fix(Select-next,Dropdown-next): updated logic for keyboard interaction
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuContext.ts
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/MenuList.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/examples/MenuOptionMultiSelect.tsx
  packages/react-core/src/components/Menu/examples/MenuOptionSingleSelect.tsx
  packages/react-core/src/next/components/Dropdown/Dropdown.tsx
  packages/react-core/src/next/components/Select/Select.tsx
  packages/react-core/src/next/components/Select/SelectList.tsx
  packages/react-core/src/next/components/Select/examples/SelectCheckbox.tsx
  packages/react-core/src/next/components/Select/examples/SelectMultiTypeahead.tsx
Labels: accessibility

#8582 Revert "fix patternfly for function subtyping"
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorWithActionsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/FileUploadDemo/FileUploadDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDrilldownDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectFavoritesDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectTypeaheadFooterDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectValidatedDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreGroupedDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreTypeaheadGroupedDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableRowClickDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/Connectors.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPipelineDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/CustomCircleNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/CustomPathNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/CustomPolygonNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/CustomRectNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultEdge.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultGroup.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoDefaultNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoFinallyNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoTaskNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/GroupHull.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleEdge.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleGroup.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/actionsComponentFactory.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/defaultComponentFactory.ts
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/pipelineComponentFactory.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/shapesComponentFactory.ts
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/stylesComponentFactory.tsx
  packages/react-integration/demo-app-ts/tsconfig.json
  packages/react-topology/src/Visualization.ts
  packages/react-topology/src/behavior/dnd-types.ts
  packages/react-topology/src/behavior/useDndDrag.tsx
  packages/react-topology/src/behavior/useDndDrop.tsx
  packages/react-topology/src/behavior/usePanZoom.tsx
  packages/react-topology/src/behavior/useSelection.tsx
  packages/react-topology/src/behavior/withContextMenu.tsx
  packages/react-topology/src/behavior/withCreateConnector.tsx
  packages/react-topology/src/components/ElementWrapper.tsx
  packages/react-topology/src/components/GraphComponent.tsx
  packages/react-topology/src/components/factories/components/componentUtils.ts
  packages/react-topology/src/types.ts
Labels: Do Not Merge

#8518 chore(Alert): Allowed for non header elements to be set at the Alert title
  packages/react-core/src/components/Alert/Alert.tsx
  packages/react-core/src/components/Alert/examples/Alert.md
Labels: css review, accessibility
