Repository patternfly/patternfly-react, pull requests merged in 2023-05, with the labels that each got.

#9021 Victory package update
  packages/react-charts/package.json
  packages/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletGroupTitle.test.tsx.snap
  packages/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
  yarn.lock
Labels: 🔷 PatternFly 5

#8678 Adds content to tabs component examples.
  packages/react-core/src/components/Tabs/examples/Tabs.md
Labels: ux review

#8758 fix(Table) Table tooltips not triggered via keyboard
  packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  packages/react-table/src/components/Table/SortColumn.tsx
  packages/react-table/src/components/Table/TableText.tsx
  packages/react-table/src/components/Table/Td.tsx
  packages/react-table/src/components/Table/Th.tsx
  packages/react-table/src/components/Table/examples/Table.md
  packages/react-table/src/components/Table/examples/TableTextModifiers.tsx
  packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
Labels: accessibility

#9084 feat(misc): dark theme docs fixes
  packages/react-core/src/components/DataList/examples/DataListWidthModifiers.tsx
  packages/react-core/src/components/Divider/examples/DividerUsingLi.tsx
  packages/react-table/src/components/Table/examples/TableMisc.tsx
Labels: css review

#9005 feat(Dropdown): fix focusing, add popper props
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Dropdown/DropdownGroup.tsx
  packages/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/react-core/src/components/Dropdown/examples/DropdownBasic.tsx
  packages/react-core/src/components/Dropdown/examples/DropdownWithDescriptions.tsx
  packages/react-core/src/components/Dropdown/examples/DropdownWithGroups.tsx
  packages/react-core/src/components/Dropdown/examples/DropdownWithKebabToggle.tsx
Labels: accessibility

#9002 Combine Label and Label Group docs
  packages/react-core/src/components/Label/LabelGroup.tsx
  packages/react-core/src/components/Label/__tests__/LabelGroup.test.tsx
  packages/react-core/src/components/Label/__tests__/__snapshots__/LabelGroup.test.tsx.snap
  packages/react-core/src/components/Label/examples/Label.md
  packages/react-core/src/components/Label/examples/LabelGroupBasic.tsx
  packages/react-core/src/components/Label/examples/LabelGroupCategory.tsx
  packages/react-core/src/components/Label/examples/LabelGroupCategoryRemovable.tsx
  packages/react-core/src/components/Label/examples/LabelGroupEditableAdd.tsx
  packages/react-core/src/components/Label/examples/LabelGroupEditableAddDropdown.tsx
  packages/react-core/src/components/Label/examples/LabelGroupEditableAddModal.tsx
  packages/react-core/src/components/Label/examples/LabelGroupEditableLabels.tsx
  packages/react-core/src/components/Label/examples/LabelGroupOverflow.tsx
  packages/react-core/src/components/Label/examples/LabelGroupVerticalCategoryOverflowRemovable.tsx
  packages/react-core/src/components/Label/index.ts
  packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
  packages/react-core/src/components/LabelGroup/index.ts
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/LabelGroupDemos.md
Labels: content review

#9083 fix(DataList, Table): update hoverable reference to clickable
  packages/react-core/src/components/Badge/Badge.tsx
  packages/react-core/src/components/Badge/__tests__/Badge.test.tsx
  packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/DataList/DataListItem.tsx
  packages/react-core/src/components/DataList/examples/DataList.md
  packages/react-core/src/components/DataList/examples/DataListClickableRows.tsx
  packages/react-core/src/components/DataList/examples/DataListDraggable.tsx
  packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx
  packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatusItem.test.tsx.snap
  packages/react-core/src/demos/ProgressDemo.md
  packages/react-core/src/demos/ProgressStepperDemo.md
  packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDraggableDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableRowClickDemo.tsx
  packages/react-table/src/components/Table/RowWrapper.tsx
  packages/react-table/src/components/Table/Table.tsx
  packages/react-table/src/components/Table/TableTypes.tsx
  packages/react-table/src/components/Table/Tr.tsx
  packages/react-table/src/components/Table/examples/Table.md
  packages/react-table/src/components/Table/examples/TableClickable.tsx
  packages/react-table/src/deprecated/components/Table/examples/LegacyTableClickable.tsx
  packages/react-table/src/deprecated/components/Table/examples/Table.md
Labels: css review

#9093 fix(Tabs): fixed keyboard use and positioning of TabsAndTable dropdowns
  packages/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/react-core/src/demos/examples/DashboardWrapper.js
  packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
  packages/react-table/src/components/Table/ActionsColumn.tsx
Labels: accessibility

#9108 chore(deps): update pf core dep
  packages/react-core/package.json
  packages/react-core/src/components/AboutModal/AboutModal.tsx
  packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx
  packages/react-core/src/components/BackgroundImage/__tests__/__snapshots__/BackgroundImage.test.tsx.snap
  packages/react-core/src/components/Chip/ChipGroup.tsx
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/Label/LabelGroup.tsx
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginPage.test.tsx.snap
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-icons/scripts/icons/patternflyIcons.mjs
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review, dependencies

#9134 fix(About Modal): Update about modal to set background image pf5 var and updated examples
  packages/react-core/src/components/AboutModal/AboutModal.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModal.md
  packages/react-core/src/components/AboutModal/examples/AboutModalBasic.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalComplexUserPositionedContent.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalCustomBackgroundImage.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalWithoutProductName.tsx
Labels: css review

#9123 chore(Card): Add card data to fix card view demos
  packages/react-core/src/demos/Card/Card.md
  packages/react-core/src/demos/Card/CardData.jsx
  packages/react-core/src/demos/PrimaryDetail.md
Labels: ux review

#9122 feat(Flex): add gap support
  packages/react-core/src/layouts/Flex/Flex.tsx
  packages/react-core/src/layouts/Flex/__tests__/Flex.test.tsx
  packages/react-core/src/layouts/Flex/examples/Flex.md
Labels: css review

#9092 feat(Card) implement new selectable/clickable card design
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/CardHeader.tsx
  packages/react-core/src/components/Card/CardSelectableActions.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/__tests__/__snapshots__/CardHeader.test.tsx.snap
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/components/Card/examples/CardClickable.tsx
  packages/react-core/src/components/Card/examples/CardClickableSelectable.tsx
  packages/react-core/src/components/Card/examples/CardDeprecatedSelectable.tsx
  packages/react-core/src/components/Card/examples/CardDeprecatedSelectableA11yHighlight.tsx
  packages/react-core/src/components/Card/examples/CardSelectable.tsx
  packages/react-core/src/components/Card/examples/CardSingleSelectable.tsx
  packages/react-core/src/components/Checkbox/Checkbox.tsx
  packages/react-core/src/components/Radio/Radio.tsx
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: ux review, css review

#9132 feat(FormControls): updated logic for rendering icons
  packages/react-core/package.json
  packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
  packages/react-core/src/components/ClipboardCopy/__tests__/Generated/__snapshots__/ClipboardCopy.test.tsx.snap
  packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  packages/react-core/src/components/FileUpload/FileUploadField.tsx
  packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
  packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
  packages/react-core/src/components/FormControl/FormControlIcon.tsx
  packages/react-core/src/components/FormSelect/FormSelect.tsx
  packages/react-core/src/components/FormSelect/__tests__/FormSelect.test.tsx
  packages/react-core/src/components/FormSelect/__tests__/__snapshots__/FormSelect.test.tsx.snap
  packages/react-core/src/components/FormSelect/examples/FormSelect.md
  packages/react-core/src/components/FormSelect/examples/FormSelectIconSpriteVariant.tsx
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
  packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
  packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
  packages/react-core/src/components/Slider/Slider.tsx
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-core/src/components/TextArea/TextArea.tsx
  packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx
  packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
  packages/react-core/src/components/TextArea/examples/TextArea.md
  packages/react-core/src/components/TextArea/examples/TextAreaIconSprite.tsx
  packages/react-core/src/components/TextInput/TextInput.tsx
  packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx
  packages/react-core/src/components/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  packages/react-core/src/components/TextInput/examples/TextInput.md
  packages/react-core/src/components/TextInput/examples/TextInputCustomIcon.tsx
  packages/react-core/src/components/TextInput/examples/TextInputCustomIconInvalid.tsx
  packages/react-core/src/components/TextInput/examples/TextInputIcon.tsx
  packages/react-core/src/components/TextInput/examples/TextInputIconSprite.tsx
  packages/react-core/src/components/TimePicker/TimePicker.tsx
  packages/react-core/src/components/TreeView/TreeViewSearch.tsx
  packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
  packages/react-core/src/demos/examples/DateTimePicker/DateTimePicker.tsx
  packages/react-core/src/deprecated/components/Select/Select.tsx
  packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/clipboardcopy.spec.ts
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/cypress/integration/searchinput.spec.ts
  packages/react-integration/cypress/integration/tableeditable.spec.ts
  packages/react-integration/cypress/integration/textarea.spec.ts
  packages/react-integration/cypress/integration/textinputdemo.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/TextInputDemo/TextInputDemo.tsx
  packages/react-styles/package.json
  packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  packages/react-tokens/package.json
  yarn.lock
Labels: ux review, css review

#9014 feat(menus): custom menus updates
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuContainer.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/index.ts
  packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
  packages/react-core/src/demos/ComposableMenu/examples/ComposableMultipleTypeaheadSelect.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableOptionsMenuVariants.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleDropdown.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx
  packages/react-core/src/demos/CustomMenus/ApplicationLauncher.md
  packages/react-core/src/demos/CustomMenus/ContextSelector.md
  packages/react-core/src/demos/CustomMenus/CustomMenus.md
  packages/react-core/src/demos/CustomMenus/OptionsMenu.md
  packages/react-core/src/demos/CustomMenus/examples/ActionsMenuDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/ApplicationLauncherDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/ComposableDateSelect.tsx
  packages/react-core/src/demos/CustomMenus/examples/ComposableDropdwnVariants.tsx
  packages/react-core/src/demos/CustomMenus/examples/ContextSelectorDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/DateSelectDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/DrilldownMenuDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/FavoritesDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/FlyoutDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/OptionsMenuDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/TreeViewMenuDemo.tsx
  packages/react-core/src/demos/CustomMenus/examples/avatarImg.svg
  packages/react-core/src/demos/CustomMenus/examples/pf-logo-small.svg
Labels: content review

#9133 feat(Table): added class names for table elements
  packages/react-core/package.json
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-table/src/components/Table/Caption.tsx
  packages/react-table/src/components/Table/Tbody.tsx
  packages/react-table/src/components/Table/Td.tsx
  packages/react-table/src/components/Table/Th.tsx
  packages/react-table/src/components/Table/Thead.tsx
  packages/react-table/src/components/Table/Tr.tsx
  packages/react-table/src/components/Table/__tests__/__snapshots__/RowWrapper.test.tsx.snap
  packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  packages/react-tokens/package.json
  yarn.lock
Labels: css review

#9147 fix(Input group): Removed variant prop from input group text
  packages/react-core/src/components/InputGroup/InputGroupText.tsx
  packages/react-core/src/components/InputGroup/__tests__/InputGroupText.test.tsx
  packages/react-core/src/components/InputGroup/examples/InputGroupBasic.tsx
  packages/react-integration/demo-app-ts/src/components/demos/InputGroupDemo/InputGroupDemo.tsx
Labels: css review

#9143 feat(Flex): add plain gap spacing
  packages/react-core/package.json
  packages/react-core/src/layouts/Flex/Flex.tsx
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: css review

#9159 Charts: Update to use v5 prefix
  packages/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
  packages/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
  packages/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
  packages/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
  packages/react-charts/src/components/ChartBoxPlot/__snapshots__/ChartBoxPlot.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeErrorMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeWarningMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletGroupTitle.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimaryDotMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletPrimarySegmentedMeasure.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletQualitativeRange.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletTitle.test.tsx.snap
  packages/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
  packages/react-charts/src/components/ChartCursorContainer/__snapshots__/ChartCursorContainer.test.tsx.snap
  packages/react-charts/src/components/ChartCursorTooltip/__snapshots__/ChartCursorFlyout.test.tsx.snap
  packages/react-charts/src/components/ChartCursorTooltip/__snapshots__/ChartCursorTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
  packages/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
  packages/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
  packages/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
  packages/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
  packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
  packages/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
  packages/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
  packages/react-charts/src/components/ChartScatter/__snapshots__/ChartScatter.test.tsx.snap
  packages/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
  packages/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
  packages/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
  packages/react-charts/src/components/ChartUtils/chart-helpers.ts
  packages/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
Labels: 🔷 PatternFly 5

#9160 Pagination - accept only positive whole numbers
  packages/react-core/src/components/Pagination/Navigation.tsx
Labels: ux review

#9171 chore(DatePicker): updated controlled examples
  packages/react-core/src/components/DatePicker/DatePicker.tsx
  packages/react-core/src/components/DatePicker/examples/DatePickerControlled.tsx
  packages/react-core/src/components/DatePicker/examples/DatePickerControlledCalendar.tsx
  packages/react-integration/cypress/integration/datepicker.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DatePickerDemo/DatePickerDemo.tsx
Labels: ux review
