Repository patternfly/patternfly-react, pull requests merged in 2023-02, with the labels that each got.

#8617 fix(MenuItemAction): updated aria-label prop to be required
  packages/react-core/src/components/Menu/MenuItemAction.tsx
Labels: accessibility

#8601 fix(Card): set default component to "div" to match core
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
Labels: css approved

#8645 docs(topology): split up topology demos, run a11y tests
  packages/react-docs/patternfly-a11y.config.js
  packages/react-topology/src/components/TopologyView/examples/Topology.md
  packages/react-topology/src/components/TopologyView/examples/TopologyBaseline.md
  packages/react-topology/src/components/TopologyView/examples/TopologyCustomEdges.md
  packages/react-topology/src/components/TopologyView/examples/TopologyCustomEdgesDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/TopologyCustomNodes.md
  packages/react-topology/src/components/TopologyView/examples/TopologyCustomNodesDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/TopologyPanZoom.md
  packages/react-topology/src/components/TopologyView/examples/TopologyPanZoomDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/TopologySelectable.md
  packages/react-topology/src/components/TopologyView/examples/TopologySelectableDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
Labels: documentation :memo:

#8616 feat(Spinner): remove legacy variant and svg prop
  packages/react-core/src/components/Icon/Icon.tsx
  packages/react-core/src/components/Icon/examples/IconCustomProgress.tsx
  packages/react-core/src/components/Spinner/Spinner.tsx
  packages/react-core/src/components/Spinner/__tests__/Spinner.test.tsx
  packages/react-core/src/components/Spinner/__tests__/__snapshots__/Spinner.test.tsx.snap
  packages/react-core/src/components/Spinner/examples/SpinnerBasic.tsx
  packages/react-core/src/components/Spinner/examples/SpinnerCustomSize.tsx
  packages/react-core/src/components/Spinner/examples/SpinnerInline.tsx
  packages/react-core/src/components/Spinner/examples/SpinnerSizeVariations.tsx
Labels: css review

#8624 chore(CodeEditorControl): remove deprecated props
  packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx
  packages/react-integration/demo-app-ts/src/components/demos/CodeEditorDemo/CodeEditorDemo.tsx
Labels: breaking change :boom:, 🔷 PatternFly 5

#8622 fix(Code block): Fixed to only render the header when actions are defined
  packages/react-core/src/components/CodeBlock/CodeBlock.tsx
  packages/react-core/src/components/CodeBlock/__tests__/__snapshots__/CodeBlock.test.tsx.snap
Labels: css review

#8652 docs(topology): add sidebar demo and documentation
  packages/react-topology/src/components/TopologyView/examples/TopologySidebar.md
  packages/react-topology/src/components/TopologyView/examples/TopologySidebarDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
Labels: documentation :memo:

#8644 docs(Topology): added control bar demo and documentation
  packages/react-topology/src/components/TopologyView/examples/TopologyControlBar.md
  packages/react-topology/src/components/TopologyView/examples/TopologyControlBarDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
Labels: documentation :memo:

#8626 chore(NotificationBadge): remove deprecated isread prop
  packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
  packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx
  packages/react-core/src/components/NotificationBadge/__tests__/NotificationBadge.test.tsx
  packages/react-core/src/components/NotificationBadge/__tests__/__snapshots__/NotificationBadge.test.tsx.snap
Labels: ux review, css review

#8633 fix(composable typeahead select): updated accessibility
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableMultipleTypeaheadSelect.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx
  packages/react-core/src/next/components/Select/examples/SelectMultiTypeahead.tsx
  packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx
  packages/react-integration/cypress/integration/menu.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
Labels: accessibility

#8592 Charts - fix broken tooltip examples for v5
  packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
  packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
Labels: 🔷 PatternFly 5

#8563 feat(Toolbar): support for vertical alignments
  packages/react-core/src/components/Toolbar/ToolbarContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
  packages/react-core/src/components/Toolbar/examples/ToolbarStacked.tsx
  packages/react-core/src/demos/Card/Card.md
  packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
  packages/react-core/src/demos/Toolbar.md
  packages/react-core/src/demos/examples/DashboardHeader.js
  packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx
  packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx
Labels: css review, 🔷 PatternFly 5

#8683 docs(topology): add context menu demo and documentation
  packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/ContextMenus.tsx
  packages/react-topology/src/components/TopologyView/examples/TopologyContextMenu.md
  packages/react-topology/src/components/TopologyView/examples/TopologyContextMenuDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/TopologySelectable.md
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
Labels: documentation :memo:

#8679 docs(topology): add anchors demo and documentation
  packages/react-topology/src/components/TopologyView/examples/TopologyAnchors.md
  packages/react-topology/src/components/TopologyView/examples/TopologyAnchorsDemo.tsx
  packages/react-topology/src/components/TopologyView/examples/topology-example.css
Labels: documentation :memo:

#8649 chore(multiple components): updated arialabel on unsupported divs
  packages/react-core/src/components/Accordion/Accordion.tsx
  packages/react-core/src/components/Alert/Alert.tsx
  packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/MenuList.tsx
  packages/react-core/src/components/Page/PageGroup.tsx
  packages/react-core/src/components/Page/PageNavigation.tsx
  packages/react-core/src/components/Page/__tests__/Page.test.tsx
  packages/react-core/src/components/Page/__tests__/PageGroup.test.tsx
  packages/react-core/src/components/Page/__tests__/PageNavigation.test.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageGroup.test.tsx.snap
  packages/react-core/src/components/Page/__tests__/__snapshots__/PageNavigation.test.tsx.snap
  packages/react-core/src/components/ProgressStepper/ProgressStep.tsx
  packages/react-core/src/components/ProgressStepper/__tests__/ProgressStep.test.tsx
  packages/react-core/src/components/Wizard/Wizard.tsx
  packages/react-core/src/components/Wizard/WizardBody.tsx
  packages/react-core/src/components/Wizard/WizardToggle.tsx
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardBody.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardToggle.test.tsx.snap
  packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
  packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
  packages/react-core/src/components/Wizard/examples/WizardBasic.tsx
  packages/react-core/src/next/components/Wizard/WizardBody.tsx
  packages/react-core/src/next/components/Wizard/__tests__/WizardBody.test.tsx
  packages/react-core/src/next/components/Wizard/examples/Wizard.md
  packages/react-core/src/next/components/Wizard/examples/WizardBasic.tsx
  packages/react-core/src/next/components/Wizard/examples/WizardKitchenSink.tsx
  packages/react-integration/cypress/integration/wizard.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
Labels: accessibility

#8732 Charts - add unique IDs to labels
  packages/react-charts/src/components/Chart/Chart.tsx
  packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
  packages/react-charts/src/components/ChartBullet/ChartBullet.tsx
  packages/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx
  packages/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx
  packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
  packages/react-charts/src/components/ChartLegend/ChartLegend.tsx
  packages/react-charts/src/components/ChartPie/ChartPie.tsx
Labels: 🔷 PatternFly 5

#8707 Charts - fix broken tooltip examples
  packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
  packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
Labels: 🔷 PatternFly 5

#8674 fix(About modal): Refactor about modal to reuse the modal component
  packages/react-core/src/components/AboutModal/AboutModal.tsx
  packages/react-core/src/components/AboutModal/AboutModalBox.tsx
  packages/react-core/src/components/AboutModal/AboutModalBoxBrand.tsx
  packages/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx
  packages/react-core/src/components/AboutModal/AboutModalBoxContent.tsx
  packages/react-core/src/components/AboutModal/AboutModalBoxHeader.tsx
  packages/react-core/src/components/AboutModal/AboutModalBoxHero.tsx
  packages/react-core/src/components/AboutModal/AboutModalContainer.tsx
  packages/react-core/src/components/AboutModal/__tests__/AboutModal.test.tsx
  packages/react-core/src/components/AboutModal/__tests__/AboutModalBox.test.tsx
  packages/react-core/src/components/AboutModal/__tests__/AboutModalContainer.test.tsx
  packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalBox.test.tsx.snap
  packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalContainer.test.tsx.snap
  packages/react-core/src/components/AboutModal/examples/AboutModalComplexUserPositionedContent.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalCustomBackgroundImage.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalWithoutProductName.tsx
Labels: ux review, css review
