Repository patternfly/patternfly-react, pull requests merged in 2023-06, with the labels that each got.

#9214 fix(TimePicker): resolved border styling on open menu
  packages/react-core/src/components/TimePicker/TimePicker.tsx
Labels: css review

#9173 fix(react-styles): updated class names to include versions
  packages/react-styles/src/css/components/Consoles/AccessConsoles.css
  packages/react-styles/src/css/components/Consoles/DesktopViewer.css
  packages/react-styles/src/css/components/Consoles/SerialConsole.css
  packages/react-styles/src/css/components/Consoles/VncConsole.css
  packages/react-styles/src/css/components/Table/inline-edit.css
Labels: css review

#9219 fix(Pagination): remove spin buttons
  packages/react-core/src/components/Pagination/Navigation.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-integration/cypress/integration/pagination.spec.ts
Labels: ux review, css review

#9223 chore(docs): Updated the Navigation demos to use the masthead instead of the page header
  packages/react-core/src/components/Page/examples/Page.md
  packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
  packages/react-core/src/components/Toolbar/__tests__/ToolbarGroup.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/ToolbarItem.test.tsx
  packages/react-core/src/demos/Nav.md
Labels: ux review, css review

#9276 feat(charts): Update Victory packages to latest version
  packages/react-charts/package.json
  yarn.lock
Labels: PF5

#9323 Bug - v5 preview testing - chart legend tooltip spacing
  packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
  packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
  packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
Labels: PF5
