Repository patternfly/patternfly-react, pull requests merged in 2023-04, with the labels that each got.

#8854 feat(Page): Deprecate PageHeader component
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/components/Nav/examples/NavHorizontalPageHeader.tsx
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Page/__tests__/Page.test.tsx
  packages/react-core/src/components/Page/examples/Page.md
  packages/react-core/src/components/Page/index.ts
  packages/react-core/src/demos/Nav.md
  packages/react-core/src/demos/Page.md
  packages/react-core/src/demos/examples/Page/PageStickySectionGroupUsingPageHeader.tsx
  packages/react-core/src/deprecated/components/PageHeader/PageHeader.tsx
  packages/react-core/src/deprecated/components/PageHeader/PageHeaderTools.tsx
  packages/react-core/src/deprecated/components/PageHeader/PageHeaderToolsGroup.tsx
  packages/react-core/src/deprecated/components/PageHeader/PageHeaderToolsItem.tsx
  packages/react-core/src/deprecated/components/PageHeader/examples/PageHeader.md
  packages/react-core/src/deprecated/components/PageHeader/examples/PageVerticalNavUsingPageHeaderComponent.tsx
  packages/react-core/src/deprecated/components/PageHeader/index.ts
  packages/react-core/src/deprecated/components/PageHeader/tests/PageHeader.test.tsx
  packages/react-core/src/deprecated/components/PageHeader/tests/PageHeaderTools.test.tsx
  packages/react-core/src/deprecated/components/PageHeader/tests/PageHeaderToolsGroup.test.tsx
  packages/react-core/src/deprecated/components/PageHeader/tests/PageHeaderToolsItem.test.tsx
  packages/react-core/src/deprecated/components/PageHeader/tests/__snapshots__/PageHeader.test.tsx.snap
  packages/react-core/src/deprecated/components/PageHeader/tests/__snapshots__/PageHeaderTools.test.tsx.snap
  packages/react-core/src/deprecated/components/PageHeader/tests/__snapshots__/PageHeaderToolsGroup.test.tsx.snap
  packages/react-core/src/deprecated/components/PageHeader/tests/__snapshots__/PageHeaderToolsItem.test.tsx.snap
  packages/react-core/src/deprecated/components/index.ts
  packages/react-integration/demo-app-ts/src/App.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageManagedSidebarClosedDemo.tsx
Labels: ux review

#8810 feat(FormGroup): use HelperText
  packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/FormHelperText.tsx
  packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
  packages/react-core/src/components/Form/__tests__/FormHelperText.test.tsx
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormHelperText.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-core/src/components/Form/examples/FormBasic.tsx
  packages/react-core/src/components/Form/examples/FormGrid.tsx
  packages/react-core/src/components/Form/examples/FormGroupLabelInfo.tsx
  packages/react-core/src/components/Form/examples/FormHorizontal.tsx
  packages/react-core/src/components/Form/examples/FormHorizontalHelper.tsx
  packages/react-core/src/components/Form/examples/FormInvalid.tsx
  packages/react-core/src/components/Form/examples/FormInvalidWithFormAlert.tsx
  packages/react-core/src/components/Form/examples/FormLimitWidth.tsx
  packages/react-core/src/components/Form/examples/FormValidated.tsx
  packages/react-core/src/components/FormSelect/examples/FormSelectIconSpriteVariant.tsx
  packages/react-core/src/components/FormSelect/examples/FormSelectValidated.tsx
  packages/react-core/src/components/LoginPage/LoginForm.tsx
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
  packages/react-core/src/components/TextArea/examples/TextAreaValidated.tsx
  packages/react-core/src/components/Wizard/examples/WizardEnabledOnFormValidation.tsx
  packages/react-core/src/components/Wizard/examples/WizardValidateOnButtonPress.tsx
  packages/react-core/src/demos/examples/HelperText/HelperTextDynamicVariantStaticText.tsx
  packages/react-core/src/demos/examples/HelperText/HelperTextStaticVariantDynamicText.tsx
  packages/react-core/src/demos/examples/HelperText/HelperTextStaticVariantStaticText.tsx
  packages/react-core/src/next/components/Wizard/examples/WizardEnabledOnFormValidation.tsx
  packages/react-core/src/next/components/Wizard/examples/WizardValidateOnButtonPress.tsx
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/cypress/integration/login-page.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: css review

#8879 fix(Menu/Dropdown): updated external link and focus management
  packages/react-core/src/components/Dropdown/Dropdown.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
Labels: accessibility

#8833 feat(Datepicker, Timepicker): use HelperText
  packages/react-core/src/components/DatePicker/DatePicker.tsx
  packages/react-core/src/components/DatePicker/examples/DatePickerHelperText.tsx
  packages/react-core/src/components/TimePicker/TimePicker.tsx
Labels: css review

#8820 feat(Menu): match css structure
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuSearch.tsx
  packages/react-core/src/components/Menu/MenuSearchInput.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/examples/MenuFilterDrilldown.tsx
  packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx
  packages/react-core/src/components/Menu/index.ts
  packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableDropdwnVariants.tsx
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
Labels: css review, css approved

#8900 Charts: box plot
  packages/react-charts/package.json
  packages/react-charts/src/components/ChartBoxPlot/ChartBoxPlot.test.tsx
  packages/react-charts/src/components/ChartBoxPlot/ChartBoxPlot.tsx
  packages/react-charts/src/components/ChartBoxPlot/__snapshots__/ChartBoxPlot.test.tsx.snap
  packages/react-charts/src/components/ChartBoxPlot/examples/ChartBoxPlot.md
  packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
  packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
  packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipLabel.tsx
  packages/react-charts/src/components/ChartTheme/ChartStyles.ts
  packages/react-charts/src/components/ChartTheme/examples/ChartTheme.md
  packages/react-charts/src/components/ChartTheme/styles/box-plot-tooltip-styles.ts
  packages/react-charts/src/components/ChartTheme/themes/color-theme.ts
  packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
  packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
  packages/react-charts/src/components/index.ts
  yarn.lock
Labels: ux review, 🔷 PatternFly 5

#8918 feat(Sidebar): add border and padding
  packages/react-core/src/components/Sidebar/Sidebar.tsx
  packages/react-core/src/components/Sidebar/SidebarContent.tsx
  packages/react-core/src/components/Sidebar/SidebarPanel.tsx
  packages/react-core/src/components/Sidebar/__tests__/Sidebar.test.tsx
  packages/react-core/src/components/Sidebar/__tests__/SidebarContent.test.tsx
  packages/react-core/src/components/Sidebar/__tests__/SidebarPanel.test.tsx
  packages/react-core/src/components/Sidebar/examples/Sidebar.md
  packages/react-core/src/components/Sidebar/examples/SidebarBorder.tsx
  packages/react-core/src/components/Sidebar/examples/SidebarPaddingContent.tsx
  packages/react-core/src/components/Sidebar/examples/SidebarPaddingPanel.tsx
Labels: ux review, css review

#8832 feat(infrastructure): Added ability import components directly to support fed modules tree-shaking of shared packages.
  package.json
  packages/react-charts/package.json
  packages/react-charts/single-packages.config.json
  packages/react-core/package.json
  packages/react-core/single-packages.config.json
  packages/react-table/package.json
  packages/react-table/single-packages.config.json
  scripts/build-single-packages.js
Labels: infrastructure, feature request

#8931 chore(BackgroundImage/AboutModal): updated usage of bg image
  packages/react-core/src/components/AboutModal/AboutModal.tsx
  packages/react-core/src/components/AboutModal/AboutModalBoxHero.tsx
  packages/react-core/src/components/AboutModal/__tests__/AboutModalBoxHero.test.tsx
  packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalBoxHero.test.tsx.snap
  packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx
  packages/react-core/src/components/BackgroundImage/__tests__/__snapshots__/BackgroundImage.test.tsx.snap
  packages/react-core/src/components/BackgroundImage/examples/BackgroundImageBasic.tsx
  packages/react-core/src/components/LoginPage/LoginPage.tsx
  packages/react-core/src/components/LoginPage/__tests__/LoginPage.test.tsx
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginPage.test.tsx.snap
  packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx
  packages/react-core/src/components/LoginPage/examples/LoginPageLanguageSelect.tsx
  packages/react-core/src/components/LoginPage/examples/LoginPageShowHidePassword.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/images/pfbg-icon.svg
Labels: ux review, css review

#8957 chore(SearchInput): remove type attribute, use default text type
  packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
  packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
  packages/react-core/src/components/Menu/examples/MenuFilterDrilldown.tsx
  packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx
  packages/react-core/src/components/SearchInput/SearchInput.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx
  packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx
  packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
  packages/react-core/src/deprecated/components/ContextSelector/ContextSelector.tsx
  packages/react-core/src/deprecated/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
  packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
Labels: css review

#8928 fix(Table): update sticky css props
  packages/react-table/src/components/Table/Td.tsx
  packages/react-table/src/components/Table/Th.tsx
  packages/react-table/src/components/Table/examples/Table.md
Labels: css approved

#8949 fix(CardTitle): apply pf-c-card__title-text class
  packages/react-core/src/components/Card/CardTitle.tsx
  packages/react-core/src/components/Card/__tests__/__snapshots__/CardTitle.test.tsx.snap
Labels: css review

#8924 feat(Alert, Icon, Modal, NotificationDrawer): use custom CSS for default
  packages/react-core/src/components/Alert/Alert.tsx
  packages/react-core/src/components/Alert/AlertIcon.tsx
  packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
  packages/react-core/src/components/Alert/__tests__/AlertIcon.test.tsx
  packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  packages/react-core/src/components/Alert/examples/Alert.md
  packages/react-core/src/components/Icon/__tests__/Icon.test.tsx
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalBoxTitle.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-core/src/components/Modal/__tests__/ModalBoxTitle.test.tsx
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxTitle.test.tsx.snap
  packages/react-core/src/components/Modal/examples/Modal.md
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx
  packages/react-core/src/components/Popover/Popover.tsx
  packages/react-core/src/components/Popover/PopoverHeader.tsx
  packages/react-core/src/components/Popover/examples/PopoverAlert.tsx
Labels: css approved

#8954 fix(createIcon): Spread className to svg to fix broken images
  package.json
  packages/react-core/src/components/EmptyState/__tests__/Generated/__snapshots__/EmptyStateIcon.test.tsx.snap
  packages/react-core/src/components/EmptyState/__tests__/__snapshots__/EmptyState.test.tsx.snap
  packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-icons/src/createIcon.tsx
  yarn.lock
Labels: ux review, css review
