Repository patternfly/patternfly-react, pull requests merged in 2023-11, with the labels that each got.

#9694 fix(RTL): added right-to-left page demo
  packages/react-core/src/demos/RTL/RTL.md
  packages/react-core/src/demos/RTL/examples/PaginatedTable.css
  packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx
  packages/react-core/src/demos/RTL/examples/translations.en.json
  packages/react-core/src/demos/RTL/examples/translations.he.json
Labels: ux review

#9705 fix(Text input): Added aria-expanded
  packages/react-core/src/components/TextInput/TextInput.tsx
  packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx
  packages/react-core/src/components/TextInput/examples/TextInput.md
Labels: accessibility

#9569 fix(Notification Drawer): Added screen reader text for notification drawer item read state
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx
  packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItem.test.tsx
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerHeader.test.tsx.snap
  packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItem.test.tsx.snap
Labels: accessibility

#9087 feat(Datalist): implement full page Basic demo to match HTML #9048
  packages/react-core/src/demos/DataList/examples/DataListBasic.tsx
  packages/react-core/src/demos/DataListDemo.md
Labels: ux review, css review

#9484 fix Search Input - composable advanced search demo
  packages/react-core/src/components/DatePicker/DatePicker.tsx
  packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  packages/react-core/src/demos/SearchInput/SearchInput.md
Labels: css review

#9687 docs(custom menu): add example with search input inline filtering
  packages/react-core/src/demos/CustomMenus/CustomMenus.md
  packages/react-core/src/demos/CustomMenus/examples/InlineSearchFilterMenuDemo.tsx
Labels: ux review

#9536 docs(select): Adds documentation to React examples.
  packages/react-core/src/components/Select/examples/Select.md
Labels: ux review, Content
