Repository patternfly/patternfly-react, pull requests merged in 2023-08, with the labels that each got.

#9372 feat(Drawer): add noBackground to colorVariant
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/DrawerContent.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/DrawerSection.tsx
  packages/react-core/src/demos/PrimaryDetail.md
  packages/react-core/src/demos/examples/PrimaryDetail/PrimaryDetailContentPadding.tsx
Labels: css review

#9302 feat(SimpleList): add ul/li classes
  packages/react-core/src/components/SimpleList/SimpleList.tsx
  packages/react-core/src/components/SimpleList/SimpleListGroup.tsx
  packages/react-core/src/components/SimpleList/SimpleListItem.tsx
  packages/react-core/src/components/SimpleList/__tests__/Generated/__snapshots__/SimpleListGroup.test.tsx.snap
  packages/react-core/src/components/SimpleList/__tests__/Generated/__snapshots__/SimpleListItem.test.tsx.snap
  packages/react-core/src/components/SimpleList/__tests__/__snapshots__/SimpleList.test.tsx.snap
Labels: css review

#9300 feat(Modal): use css vars to set width, add maxWidth
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-integration/cypress/integration/wizarddeprecated.spec.ts
Labels: css review

#9232 feat(Pagination): add offset example
  packages/react-core/src/components/Pagination/Pagination.tsx
  packages/react-core/src/components/Pagination/examples/Pagination.md
  packages/react-core/src/components/Pagination/examples/PaginationOffset.tsx
Labels: ux review

#9453 feat(Modal): added ability to customize initial focus
  packages/react-core/src/components/Modal/Modal.tsx
  packages/react-core/src/components/Modal/ModalContent.tsx
  packages/react-core/src/components/Modal/examples/Modal.md
  packages/react-core/src/components/Modal/examples/ModalCustomFocus.tsx
  packages/react-integration/cypress/integration/modal.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
Labels: accessibility

#9408 fix(Menu): focused items should scrollintoview when overflowed
  packages/react-core/src/components/Menu/MenuItem.tsx
Labels: ux review

#9493 fix(Chip): Added prop to render a badge in the chip after the text
  packages/react-core/src/components/Chip/Chip.tsx
  packages/react-core/src/components/Chip/examples/ChipDefault.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDemo.tsx
Labels: css review

#9500 fix(Button): Fixed incorrect styles when plain variant and isLoading is false
  packages/react-core/src/components/Button/Button.tsx
Labels: css review

#9427 feat(Table): Added isNoInset prop for flat tree tables
  packages/react-table/src/components/Table/Table.tsx
  packages/react-table/src/components/Table/examples/Table.md
  packages/react-table/src/components/Table/examples/TableTreeNoInset.tsx
Labels: css review

#9322 chore(card view demos): update to new selectable card variant
  packages/react-core/src/demos/Card/Card.md
  packages/react-core/src/demos/PrimaryDetail.md
Labels: css approved, ux approved

#9401 fix(DatePicker): resolved page scrolling bug
  packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
  packages/react-core/src/components/DatePicker/DatePicker.tsx
  packages/react-core/src/components/Popover/Popover.tsx
  packages/react-core/src/components/Popover/examples/Popover.md
  packages/react-core/src/components/Popover/examples/PopoverCustomFocus.tsx
Labels: accessibility
