Repository patternfly/patternfly-react, pull requests merged in 2023-07, with the labels that each got.

#9317 fix(SelectDeprecated): use textinput component for typeahead
  packages/react-core/src/deprecated/components/Select/Select.tsx
  packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
Labels: css review

#9338 fix(charts): export getThemeColors
  packages/react-charts/src/components/ChartUtils/chart-theme.ts
  packages/react-charts/src/components/index.ts
Labels: PF5

#9334 fix(TextInput,TextArea, FormSelect): changed form control div to a span
  packages/react-core/src/components/ClipboardCopy/__tests__/Generated/__snapshots__/ClipboardCopy.test.tsx.snap
  packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
  packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
  packages/react-core/src/components/FormControl/FormControlIcon.tsx
  packages/react-core/src/components/FormSelect/FormSelect.tsx
  packages/react-core/src/components/FormSelect/__tests__/__snapshots__/FormSelect.test.tsx.snap
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
  packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
  packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
  packages/react-core/src/components/TextArea/TextArea.tsx
  packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
  packages/react-core/src/components/TextInput/TextInput.tsx
  packages/react-core/src/components/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
Labels: css review

#9325 feat(Toolbar): update/add alignItems + alignSelf
  packages/react-core/src/components/Toolbar/ToolbarContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
Labels: css review

#9298 fix(build): transform icons and react core dependencies imports
  package.json
  packages/transformer-cjs-imports/index.js
  packages/transformer-dynamic-imports/CHANGELOG.md
  packages/transformer-dynamic-imports/index.ts
  packages/transformer-dynamic-imports/package.json
  packages/tsconfig.base.json
  yarn.lock
Labels: enhancement :rocket:

#9303 fix(ExpandableSection): added ARIA attributes
  packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
  packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx
  packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionDetached.tsx
  packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatus.tsx
  packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatus.test.tsx.snap
  packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md
Labels: accessibility

#9379 fix(toolbar): added chip container class to toolbar content
  packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx
  packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/ToolbarChipGroupContent.test.tsx.snap
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap
Labels: css review

#9382 feat(Menu): Added support for tooltips to menu
  packages/react-core/src/components/Dropdown/DropdownItem.tsx
  packages/react-core/src/components/Dropdown/examples/Dropdown.md
  packages/react-core/src/components/Dropdown/examples/DropdownBasic.tsx
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/examples/Menu.md
  packages/react-core/src/components/Menu/examples/MenuBasic.tsx
  packages/react-table/src/components/Table/ActionsColumn.tsx
  packages/react-table/src/components/Table/TableTypes.tsx
  packages/react-table/src/components/Table/examples/Table.md
Labels: css review

#9296 fix(Page) allow change of main tag
  packages/react-core/src/components/Page/Page.tsx
Labels: css review
