Repository patternfly/patternfly-react, pull requests merged in 2024-06, with the labels that each got.

#10268 docs(menu-toggle): Adds docs for split button examples.
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
Labels: Content

#10488 feat(hint): added hasNoOffset prop
  packages/react-core/src/components/Hint/Hint.tsx
  packages/react-core/src/components/Hint/__tests__/Hint.test.tsx
  packages/react-core/src/components/Hint/__tests__/__snapshots__/Hint.test.tsx.snap
  packages/react-core/src/components/Hint/examples/Hint.md
  packages/react-core/src/components/Hint/examples/HintActionsWithNoOffset.tsx
Labels: css review

#10184 Add description list basic demo
  packages/react-core/src/demos/DescriptionList/DescriptionList.md
  packages/react-core/src/demos/DescriptionList/examples/DescriptionListBasic.tsx
Labels: ux review, css review

#10445 feat(badge): add disabled badge variant
  packages/react-core/src/components/Badge/Badge.tsx
  packages/react-core/src/components/Badge/__tests__/Badge.test.tsx
  packages/react-core/src/components/Badge/examples/Badge.md
  packages/react-core/src/components/Badge/examples/BadgeDisabled.tsx
  packages/react-core/src/components/Button/Button.tsx
Labels: ux review, css approved

#10241 Masthead: add demo that includes horizontal nav
  packages/react-core/src/demos/Masthead.md
  packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
Labels: ux review, css review

#10586 feat(Modal Next): Added status variant styling to title
  packages/react-core/src/next/components/Modal/ModalBoxTitle.tsx
  packages/react-core/src/next/components/Modal/ModalHeader.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBoxTitle.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBoxTitle.test.tsx.snap
Labels: css review

#10592 feat(Modal): Added status variant styling to title V6
  package.json
  packages/react-core/src/components/Modal/ModalBoxTitle.tsx
  packages/react-core/src/components/Modal/ModalHeader.tsx
  packages/react-core/src/components/Modal/__tests__/ModalBoxTitle.test.tsx
  packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxTitle.test.tsx.snap
Labels: css review
