Repository patternfly/patternfly-react, pull requests merged in 2024-05, with the labels that each got.

#10255 feat(Button): change behaviour of isDisabled prop
  packages/react-core/src/components/Button/Button.tsx
  packages/react-core/src/components/Button/__tests__/Button.test.tsx
  packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
  packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
  packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  packages/react-core/src/deprecated/components/Wizard/__tests__/Generated/__snapshots__/WizardFooterInternal.test.tsx.snap
  packages/react-core/src/deprecated/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
Labels: css approved

#10309 docs(toggle-group): Adds example documentation.
  packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
Labels: Content

#10248 feat(FormGroupLabelHelp): update markup to match core
  packages/react-core/src/components/Button/examples/ButtonInlineSpanLink.tsx
  packages/react-core/src/components/Form/FormGroupLabelHelp.tsx
  packages/react-core/src/components/Form/examples/FormBasic.tsx
  packages/react-core/src/components/Form/examples/FormGroupLabelInfo.tsx
  packages/react-core/src/components/Form/examples/FormLimitWidth.tsx
  packages/react-core/src/components/Modal/examples/ModalWithForm.tsx
  packages/react-core/src/demos/SearchInput/SearchInput.md
  packages/react-core/src/demos/examples/PasswordStrength/PasswordStrengthDemo.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithForm.tsx
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
  packages/react-table/src/components/Table/Table.tsx
Labels: css approved

#10418 feat(Toolbar): updated spacer props to gap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap
  packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletQualitativeRange.test.tsx.snap
  packages/react-core/package.json
  packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
  packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-core/src/components/Toolbar/examples/ToolbarSpacers.tsx
  packages/react-core/src/demos/DashboardHeader.tsx
  packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerBasic.tsx
  packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerGrouped.tsx
  packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx
  packages/react-core/src/demos/RTL/examples/PaginatedTable.tsx
  packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
  packages/react-core/src/demos/examples/Nav/NavFlyout.tsx
  packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx
  packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx
  packages/react-core/src/demos/examples/Nav/NavManual.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx
  packages/react-core/src/helpers/util.ts
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-styles/package.json
  packages/react-table/src/demos/DashboardHeader.tsx
  packages/react-tokens/package.json
  yarn.lock
Labels: require codemod
