Repository patternfly/patternfly-react, pull requests merged in 2024-03, with the labels that each got.

#10097 feat(MenuToggle): consumed Penta updates
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx
  packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
  packages/react-core/src/demos/DataList/examples/DataListBasic.tsx
  packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorWithActionsDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
  packages/react-table/src/components/Table/ActionsColumn.tsx
  packages/react-table/src/components/Table/examples/TableActionsOverflow.tsx
  packages/react-table/src/components/Table/examples/TableSortableCustom.tsx
  packages/react-table/src/demos/examples/TableColumnManagement.tsx
  packages/react-table/src/demos/examples/TableColumnManagementWithDraggable.tsx
  packages/react-table/src/demos/examples/TableCompact.tsx
  packages/react-table/src/demos/examples/TableCompoundExpansion.tsx
  packages/react-table/src/demos/examples/TableSortableResponsive.tsx
  packages/react-table/src/demos/examples/TableStaticBottomPagination.tsx
  packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  packages/react-table/src/deprecated/components/Table/examples/LegacyTableSortableCustom.tsx
Labels: ux review, css review

#10107 feat(Login): use children for loginmainfooterlinksitem
  packages/react-core/src/components/LoginPage/LoginMainFooterLinksItem.tsx
  packages/react-core/src/components/LoginPage/__tests__/LoginMainFooterLinksItem.test.tsx
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginMainFooterLinksItem.test.tsx.snap
  packages/react-core/src/components/LoginPage/examples/LoginPage.md
  packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx
  packages/react-core/src/components/LoginPage/examples/LoginPageLanguageSelect.tsx
  packages/react-core/src/components/LoginPage/examples/LoginPageShowHidePassword.tsx
Labels: css review

#10016 Consume core Penta updates: Form controls, checkbox, radio
  packages/react-core/src/components/Checkbox/Checkbox.tsx
  packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx
  packages/react-core/src/components/Form/FormFieldGroupHeader.tsx
  packages/react-core/src/components/Form/FormGroup.tsx
  packages/react-core/src/components/Form/FormGroupLabelHelp.tsx
  packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
  packages/react-core/src/components/Form/examples/Form.md
  packages/react-core/src/components/Form/examples/FormBasic.tsx
  packages/react-core/src/components/Form/examples/FormGroupLabelInfo.tsx
  packages/react-core/src/components/Form/examples/FormLimitWidth.tsx
  packages/react-core/src/components/Form/index.ts
  packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
  packages/react-core/src/components/Modal/examples/ModalWithForm.tsx
  packages/react-core/src/components/Radio/Radio.tsx
  packages/react-core/src/components/Radio/__tests__/Radio.test.tsx
  packages/react-core/src/components/Radio/__tests__/__snapshots__/Radio.test.tsx.snap
  packages/react-core/src/components/Radio/examples/RadioReversed.tsx
  packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
  packages/react-core/src/demos/examples/PasswordStrength/PasswordStrengthDemo.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithForm.tsx
  packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
Labels: ux review, css review, breaking change :boom:

#10152 fix(Table): updated a11y for empty/nontext Th components
  packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx
  packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx
  packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx
  packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx
  packages/react-core/src/demos/Filters/examples/FilterSameSelectGroup.tsx
  packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx
  packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx
  packages/react-core/src/demos/examples/Card/CardStatus.tsx
  packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
  packages/react-integration/cypress/integration/tableselectable.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx
  packages/react-table/src/components/Table/Th.tsx
  packages/react-table/src/components/Table/__tests__/Th.test.tsx
  packages/react-table/src/components/Table/examples/TableActions.tsx
  packages/react-table/src/components/Table/examples/TableActionsOverflow.tsx
  packages/react-table/src/components/Table/examples/TableCompoundExpandable.tsx
  packages/react-table/src/components/Table/examples/TableDraggable.tsx
  packages/react-table/src/components/Table/examples/TableExpandable.tsx
  packages/react-table/src/components/Table/examples/TableNestedExpandable.tsx
  packages/react-table/src/components/Table/examples/TableNestedStickyHeader.tsx
  packages/react-table/src/components/Table/examples/TableNestedTableExpandable.tsx
  packages/react-table/src/components/Table/examples/TableSelectableRadio.tsx
  packages/react-table/src/components/Table/examples/TableStripedExpandable.tsx
  packages/react-table/src/components/Table/utils/decorators/selectable.tsx
  packages/react-table/src/demos/examples/TableBulkSelect.tsx
  packages/react-table/src/demos/examples/TableCompoundExpansion.tsx
  packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
Labels: css review, accessibility

#10172 chore(Badge/MenuToggle): updated implementation of badge toggle
  packages/react-core/src/components/Badge/Badge.tsx
  packages/react-core/src/components/Badge/__tests__/Badge.test.tsx
  packages/react-core/src/components/Badge/examples/Badge.md
  packages/react-core/src/components/Badge/examples/BadgeToggle.tsx
  packages/react-core/src/components/Breadcrumb/examples/BreadcrumbDropdown.tsx
  packages/react-core/src/components/Menu/examples/MenuWithDrilldownBreadcrumbs.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
  packages/react-core/src/demos/CustomMenus/examples/ComposableDropdwnVariants.tsx
Labels: ux review, css review

#10209 feat(MenuToggle/Select): add status
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
  packages/react-core/src/components/MenuToggle/examples/MenuToggleStatus.tsx
  packages/react-core/src/components/Select/examples/Select.md
  packages/react-core/src/components/Select/examples/SelectValidated.tsx
Labels: css review

#10202 fix(Card): updated v5 logic to prevent unclickable cards
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/CardHeader.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/components/Card/examples/CardClickableSelectable.tsx
  packages/react-core/src/components/Card/examples/CardSelectable.tsx
  packages/react-core/src/components/Card/examples/CardSingleSelectable.tsx
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: accessibility

#10199 feat(Label): allow clickable labels to be disabled
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/Label/examples/LabelCompact.tsx
  packages/react-core/src/components/Label/examples/LabelFilled.tsx
  packages/react-core/src/components/Label/examples/LabelOutline.tsx
Labels: css review
