Repository patternfly/patternfly-react, pull requests merged in 2024-01, with the labels that each got.

#9871 Chore: add primary button with icon to button docs
  packages/react-core/src/components/Button/examples/ButtonVariations.tsx
Labels: ux review

#9876 feat(Accordion): pulled in Penta updates
  packages/react-core/src/components/Accordion/AccordionContent.tsx
  packages/react-core/src/components/Accordion/AccordionContext.ts
  packages/react-core/src/components/Accordion/AccordionItem.tsx
  packages/react-core/src/components/Accordion/AccordionToggle.tsx
  packages/react-core/src/components/Accordion/__tests__/AccordionContent.test.tsx
  packages/react-core/src/components/Accordion/__tests__/AccordionItem.test.tsx
  packages/react-core/src/components/Accordion/__tests__/AccordionToggle.test.tsx
  packages/react-core/src/components/Accordion/__tests__/Generated/AccordionContent.test.tsx
  packages/react-core/src/components/Accordion/__tests__/Generated/AccordionItem.test.tsx
  packages/react-core/src/components/Accordion/__tests__/Generated/AccordionToggle.test.tsx
  packages/react-core/src/components/Accordion/__tests__/Generated/__snapshots__/AccordionContent.test.tsx.snap
  packages/react-core/src/components/Accordion/__tests__/Generated/__snapshots__/AccordionItem.test.tsx.snap
  packages/react-core/src/components/Accordion/__tests__/Generated/__snapshots__/AccordionToggle.test.tsx.snap
  packages/react-core/src/components/Accordion/__tests__/__snapshots__/AccordionContent.test.tsx.snap
  packages/react-core/src/components/Accordion/__tests__/__snapshots__/AccordionItem.test.tsx.snap
  packages/react-core/src/components/Accordion/examples/AccordionBordered.tsx
  packages/react-core/src/components/Accordion/examples/AccordionDefinitionList.tsx
  packages/react-core/src/components/Accordion/examples/AccordionFixedWithMultipleExpandBehavior.tsx
  packages/react-core/src/components/Accordion/examples/AccordionSingleExpandBehavior.tsx
  packages/react-core/src/demos/examples/Card/CardWithAccordion.tsx
  packages/react-integration/demo-app-ts/src/components/demos/Accordion/AccordionDemo.tsx
Labels: ux review, css review

#9887 chore(expandablesection): Added a demo to show how to use expandable section to create an expandable text component.
  packages/react-core/src/demos/ExpandableSection/ExpandableSection.md
  packages/react-core/src/demos/ExpandableSection/examples/ExpandableTextDemo.tsx
Labels: ux review, css review, content review, Tech debt

#9842 feat(CodeEditor): use new monaco package
  packages/react-code-editor/package.json
  packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
  packages/react-code-editor/src/components/CodeEditor/__test__/CodeEditor.test.tsx
  packages/react-code-editor/src/components/CodeEditor/__test__/CodeEditorControl.test.tsx
  packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap
  packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditorControl.test.tsx.snap
  packages/react-integration/cypress/integration/codeeditor.spec.ts
  packages/react-integration/package.json
  yarn.lock
Labels: ux review, css review

#9852 feat(Modal next): Introduce a next composable Modal
  packages/react-core/src/next/components/Modal/Modal.tsx
  packages/react-core/src/next/components/Modal/ModalBody.tsx
  packages/react-core/src/next/components/Modal/ModalBox.tsx
  packages/react-core/src/next/components/Modal/ModalBoxCloseButton.tsx
  packages/react-core/src/next/components/Modal/ModalBoxDescription.tsx
  packages/react-core/src/next/components/Modal/ModalBoxTitle.tsx
  packages/react-core/src/next/components/Modal/ModalContent.tsx
  packages/react-core/src/next/components/Modal/ModalFooter.tsx
  packages/react-core/src/next/components/Modal/ModalHeader.tsx
  packages/react-core/src/next/components/Modal/__tests__/Modal.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBody.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBox.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBoxCloseButton.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBoxDescription.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBoxHeader.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalBoxTitle.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalContent.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/ModalFooter.test.tsx
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBody.test.tsx.snap
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBox.test.tsx.snap
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBoxDescription.test.tsx.snap
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBoxHeader.test.tsx.snap
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBoxTitle.test.tsx.snap
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
  packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalFooter.test.tsx.snap
  packages/react-core/src/next/components/Modal/examples/Modal.md
  packages/react-core/src/next/components/Modal/examples/ModalBasic.tsx
  packages/react-core/src/next/components/Modal/examples/ModalCustomFocus.tsx
  packages/react-core/src/next/components/Modal/examples/ModalCustomHeader.tsx
  packages/react-core/src/next/components/Modal/examples/ModalCustomTitleIcon.tsx
  packages/react-core/src/next/components/Modal/examples/ModalCustomWidth.tsx
  packages/react-core/src/next/components/Modal/examples/ModalNoHeaderFooter.tsx
  packages/react-core/src/next/components/Modal/examples/ModalSize.tsx
  packages/react-core/src/next/components/Modal/examples/ModalTitleIcon.tsx
  packages/react-core/src/next/components/Modal/examples/ModalTopAligned.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithDescription.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithDropdown.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithForm.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithHelp.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithOverflowingContent.tsx
  packages/react-core/src/next/components/Modal/examples/ModalWithWizard.tsx
  packages/react-core/src/next/components/Modal/index.ts
  packages/react-core/src/next/components/index.ts
  packages/react-integration/cypress/integration/modalnext.spec.ts
  packages/react-integration/demo-app-ts/src/Demos.ts
  packages/react-integration/demo-app-ts/src/components/demos/ModalNextDemo/ModalNextDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/index.ts
Labels: css review, accessibility, Content

#9784 feat(DragDrop): new drag drop styling fixes
  packages/react-core/src/components/DataList/examples/DataList.md
  packages/react-core/src/components/DragDrop/examples/DragDrop.md
  packages/react-core/src/components/DragDrop/examples/DragDropBasic.tsx
  packages/react-core/src/components/DragDrop/examples/DragDropMultipleLists.tsx
  packages/react-core/src/components/DragDrop/index.ts
  packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
  packages/react-core/src/components/DualListSelector/index.ts
  packages/react-core/src/components/index.ts
  packages/react-docs/package.json
  packages/react-docs/patternfly-docs/patternfly-docs.source.js
  packages/react-drag-drop/package.json
  packages/react-drag-drop/src/index.ts
  packages/react-drag-drop/src/next/components/DragDrop/DragButton.tsx
  packages/react-drag-drop/src/next/components/DragDrop/DragDropSort.tsx
  packages/react-drag-drop/src/next/components/DragDrop/DragDropUtil.tsx
  packages/react-drag-drop/src/next/components/DragDrop/Draggable.tsx
  packages/react-drag-drop/src/next/components/DragDrop/DraggableDataListItem.tsx
  packages/react-drag-drop/src/next/components/DragDrop/DraggableDualListSelectorListItem.tsx
  packages/react-drag-drop/src/next/components/DragDrop/Droppable.tsx
  packages/react-drag-drop/src/next/components/DragDrop/DroppableContext.ts
  packages/react-drag-drop/src/next/components/DragDrop/__tests__/DragDrop.test.tsx
  packages/react-drag-drop/src/next/components/DragDrop/__tests__/__snapshots__/DragDrop.test.tsx.snap
  packages/react-drag-drop/src/next/components/DragDrop/examples/BasicSorting.tsx
  packages/react-drag-drop/src/next/components/DragDrop/examples/BasicSortingWithDragButton.tsx
  packages/react-drag-drop/src/next/components/DragDrop/examples/DataListDraggable.tsx
  packages/react-drag-drop/src/next/components/DragDrop/examples/DragDrop.md
  packages/react-drag-drop/src/next/components/DragDrop/examples/DragDropDemos.md
  packages/react-drag-drop/src/next/components/DragDrop/examples/DualListSelectorDraggable.tsx
  packages/react-drag-drop/src/next/components/DragDrop/index.ts
  packages/react-drag-drop/src/next/components/index.ts
  packages/react-drag-drop/src/next/index.ts
  packages/react-drag-drop/tsconfig.cjs.json
  packages/react-drag-drop/tsconfig.json
  packages/tsconfig.cjs.json
  packages/tsconfig.json
  scripts/promote.sh
  yarn.lock
Labels: ux review, css review

#9830 Add support for isLabelWrapped and component in Checkbox / Radio
  packages/react-core/src/components/Checkbox/Checkbox.tsx
  packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx
  packages/react-core/src/components/Radio/Radio.tsx
  packages/react-core/src/components/Radio/__tests__/Radio.test.tsx
Labels: css review

#9948 feat(Navigation): Penta updates for nav
  packages/react-core/package.json
  packages/react-core/src/components/Nav/Nav.tsx
  packages/react-core/src/components/Nav/NavExpandable.tsx
  packages/react-core/src/components/Nav/NavItem.tsx
  packages/react-core/src/components/Nav/NavList.tsx
  packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavExpandable.test.tsx.snap
  packages/react-core/src/components/Nav/__tests__/Nav.test.tsx
  packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  packages/react-core/src/components/Nav/examples/Nav.md
  packages/react-core/src/components/Nav/examples/NavExpandable.tsx
  packages/react-core/src/components/Nav/examples/NavLegacyTertiary.tsx
  packages/react-core/src/components/Nav/examples/nav.css
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Page/__tests__/Page.test.tsx
  packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
  packages/react-core/src/components/Page/examples/Page.md
  packages/react-core/src/components/Page/examples/PageGroupSection.tsx
  packages/react-core/src/components/Page/examples/PageTertiaryNav.tsx
  packages/react-core/src/demos/Nav.md
  packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
  packages/react-core/src/demos/examples/Nav/deprecated/NavLight.tsx
  packages/react-core/src/demos/examples/Nav/deprecated/NavTertiary.tsx
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/nav.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: ux review, css review

#9934 feat(Button): consume Penta tokens and update examples
  packages/react-core/src/components/Button/Button.tsx
  packages/react-core/src/components/Button/__tests__/Button.test.tsx
  packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/react-core/src/components/Button/examples/Button.md
  packages/react-core/src/components/Button/examples/ButtonAriaDisabled.tsx
  packages/react-core/src/components/Button/examples/ButtonCallToAction.tsx
  packages/react-core/src/components/Button/examples/ButtonDisabled.tsx
  packages/react-core/src/components/Button/examples/ButtonLinks.tsx
  packages/react-core/src/components/Button/examples/ButtonPlainHasNoPadding.tsx
  packages/react-core/src/components/Button/examples/ButtonProgress.tsx
  packages/react-core/src/components/Button/examples/ButtonSmall.tsx
  packages/react-core/src/components/Button/examples/ButtonStateful.tsx
  packages/react-core/src/components/Button/examples/ButtonTypes.tsx
  packages/react-core/src/components/Button/examples/ButtonVariations.tsx
  packages/react-core/src/components/Button/examples/ButtonWithCount.tsx
Labels: ux review, css review, breaking change :boom:, Penta

#9894 chore(ExpandableSection): updated indented example for Penta disclosure variation
  packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
  packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
  packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionIndented.tsx
Labels: ux review, css review

#9946 feat(Panel): consumed Penta updates
  packages/react-core/src/components/Panel/Panel.tsx
  packages/react-core/src/components/Panel/__tests__/Panel.test.tsx
  packages/react-core/src/components/Panel/examples/Panel.md
Labels: ux review, css review

#9954 feat(Avatar): Penta updates
  packages/react-core/src/components/Avatar/Avatar.tsx
  packages/react-core/src/components/Avatar/__tests__/Avatar.test.tsx
  packages/react-core/src/components/Avatar/examples/Avatar.md
  packages/react-core/src/components/Avatar/examples/AvatarBasic.tsx
  packages/react-core/src/components/Avatar/examples/AvatarBordered.tsx
  packages/react-core/src/components/Avatar/examples/AvatarSizeVariations.tsx
  packages/react-core/src/components/Avatar/examples/example.css
Labels: ux review, css review

#9957 chore(About modal): Update logos in about modal examples
  packages/react-core/src/components/AboutModal/examples/AboutModal.md
  packages/react-core/src/components/AboutModal/examples/AboutModalBasic.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalComplexUserPositionedContent.tsx
  packages/react-core/src/components/AboutModal/examples/AboutModalWithoutProductName.tsx
  packages/react-core/src/components/assets/PF-IconLogo.svg
  packages/react-core/src/components/assets/pf-background.svg
Labels: ux review, css review

#9953 feat(SimpleList): penta updates
  packages/react-core/src/components/SimpleList/SimpleListItem.tsx
  packages/react-core/src/components/SimpleList/examples/SimpleList.md
  packages/react-core/src/components/SimpleList/examples/SimpleListBasic.tsx
  packages/react-core/src/components/SimpleList/examples/SimpleListLinks.tsx
Labels: ux review, css review

#10020 feat(NotificationBadge): refactor to use status buttons for penta
  packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx
  packages/react-core/src/components/NotificationBadge/__tests__/NotificationBadge.test.tsx
  packages/react-core/src/components/NotificationBadge/__tests__/__snapshots__/NotificationBadge.test.tsx.snap
  packages/react-core/src/components/NotificationBadge/examples/NotificationBadge.md
  packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeBasic.tsx
  packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeWithCount.tsx
  packages/react-core/src/components/NotificationBadge/examples/notificationBadge.css
  packages/react-integration/cypress/integration/notificationbadge.spec.ts
Labels: css approved

#10031 feat(MultipleFileUpload): update for penta
  packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatus.tsx
  packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx
  packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatus.test.tsx.snap
  packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatusItem.test.tsx.snap
Labels: css approved
