Repository patternfly/patternfly-react, pull requests merged in 2024-07, with the labels that each got.

#10646 fix(Switch): updated a11y by removing dynamic labeling
  packages/react-charts/src/components/Skeletons/examples/skeletons.md
  packages/react-core/src/components/Switch/Switch.tsx
  packages/react-core/src/components/Switch/__tests__/Switch.test.tsx
  packages/react-core/src/components/Switch/__tests__/__snapshots__/Switch.test.tsx.snap
  packages/react-core/src/components/Switch/examples/Switch.md
  packages/react-core/src/components/Switch/examples/SwitchBasic.tsx
  packages/react-core/src/components/Switch/examples/SwitchCheckedWithLabel.tsx
  packages/react-core/src/components/Switch/examples/SwitchDisabled.tsx
  packages/react-core/src/components/Switch/examples/SwitchReversed.tsx
  packages/react-core/src/components/Switch/examples/SwitchUncontrolled.tsx
  packages/react-core/src/components/Switch/examples/SwitchWithoutLabel.tsx
  packages/react-core/src/demos/JumpLinks.md
  packages/react-integration/demo-app-ts/src/components/demos/SwitchDemo/SwitchDemo.tsx
  yarn.lock
Labels: accessibility, require codemod

#10649 chore(Toolbar): replaced chip instances with label
  packages/react-core/src/components/Toolbar/Toolbar.tsx
  packages/react-core/src/components/Toolbar/ToolbarContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarExpandableContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarFilter.tsx
  packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
  packages/react-core/src/components/Toolbar/ToolbarItem.tsx
  packages/react-core/src/components/Toolbar/ToolbarLabelGroupContent.tsx
  packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
  packages/react-core/src/components/Toolbar/ToolbarUtils.tsx
  packages/react-core/src/components/Toolbar/__tests__/Generated/ToolbarChipGroupContent.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/Generated/ToolbarExpandableContent.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/ToolbarChipGroupContent.test.tsx.snap
  packages/react-core/src/components/Toolbar/__tests__/Toolbar.test.tsx
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap
  packages/react-core/src/components/Toolbar/examples/Toolbar.md
  packages/react-core/src/components/Toolbar/examples/ToolbarCustomLabelGroupContent.tsx
  packages/react-core/src/components/Toolbar/examples/ToolbarWithFilters.tsx
  packages/react-core/src/demos/CardView/examples/CardView.tsx
  packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx
  packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx
  packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx
  packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx
  packages/react-core/src/demos/examples/PrimaryDetail/PrimaryDetailCardView.tsx
  packages/react-integration/cypress/integration/toolbar.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
  packages/react-table/src/demos/examples/TableFilterable.tsx
  yarn.lock
Labels: require codemod

#10602 fix(Table): compound expansion table row styles
  packages/react-table/src/components/Table/Tr.tsx
  packages/react-table/src/components/Table/examples/TableCompoundExpandable.tsx
Labels: css review

#10662 feat(Pagination): Added wrapper around menu toggle
  packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
  packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap
  packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
Labels: css approved

#10775 feat(MenuToggle): replace custom styles with text modifier
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
Labels: css review

#10603 fix(Table): compound expansion table row styles (V6)
  packages/react-table/src/components/Table/Tr.tsx
  packages/react-table/src/components/Table/examples/TableCompoundExpandable.tsx
Labels: css approved

#10760 feat(Page): support page fill
  packages/react-core/package.json
  packages/react-core/src/components/Page/Page.tsx
  packages/react-core/src/components/Page/PageGroup.tsx
  packages/react-core/src/components/Page/PageSection.tsx
  packages/react-core/src/components/Page/__tests__/Page.test.tsx
  packages/react-core/src/components/Page/__tests__/PageGroup.test.tsx
  packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
  packages/react-core/src/components/Page/examples/Page.md
  packages/react-core/src/components/Page/examples/PageWithOrWithoutFill.tsx
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/labelgroupeditable.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupEditableDemo.tsx
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: Content

#10809 feat(Masthead): Updates for new masthead structure in Penta
  packages/react-core/package.json
  packages/react-core/src/components/Masthead/MastheadBrand.tsx
  packages/react-core/src/components/Masthead/MastheadLogo.tsx
  packages/react-core/src/components/Masthead/__tests__/Masthead.test.tsx
  packages/react-core/src/components/Masthead/__tests__/__snapshots__/Masthead.test.tsx.snap
  packages/react-core/src/components/Masthead/examples/Masthead.md
  packages/react-core/src/components/Masthead/examples/MastheadBasic.tsx
  packages/react-core/src/components/Masthead/examples/MastheadBasicMixedContent.tsx
  packages/react-core/src/components/Masthead/examples/MastheadDisplayInline.tsx
  packages/react-core/src/components/Masthead/examples/MastheadDisplayStack.tsx
  packages/react-core/src/components/Masthead/examples/MastheadDisplayStackInlineResponsive.tsx
  packages/react-core/src/components/Masthead/examples/MastheadIconRouterLink.tsx
  packages/react-core/src/components/Masthead/examples/MastheadInsets.tsx
  packages/react-core/src/components/Masthead/index.ts
  packages/react-core/src/components/Page/examples/Page.md
  packages/react-core/src/components/Page/examples/PageCenteredSection.tsx
  packages/react-core/src/components/Page/examples/PageGroupSection.tsx
  packages/react-core/src/components/Page/examples/PageHorizontalNav.tsx
  packages/react-core/src/components/Page/examples/PageMainSectionPadding.tsx
  packages/react-core/src/components/Page/examples/PageMainSectionVariations.tsx
  packages/react-core/src/components/Page/examples/PageMultipleSidebarBody.tsx
  packages/react-core/src/components/Page/examples/PageUncontrolledNav.tsx
  packages/react-core/src/components/Page/examples/PageVerticalNav.tsx
  packages/react-core/src/components/Page/examples/PageWithOrWithoutFill.tsx
  packages/react-core/src/demos/DashboardHeader.tsx
  packages/react-core/src/demos/Masthead.md
  packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerBasic.tsx
  packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerGrouped.tsx
  packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx
  packages/react-core/src/demos/RTL/examples/PaginatedTable.tsx
  packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
  packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
  packages/react-core/src/demos/examples/Nav/NavFlyout.tsx
  packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx
  packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx
  packages/react-core/src/demos/examples/Nav/NavManual.tsx
  packages/react-core/src/demos/examples/Page/PageContextSelector.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx
  packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx
  packages/react-core/src/demos/examples/Wizard/InPageWithDrawer.tsx
  packages/react-core/src/demos/examples/Wizard/InPageWithDrawerInformationalStep.tsx
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/demo-app-ts/src/App.tsx
  packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageManagedSidebarClosedDemo.tsx
  packages/react-styles/package.json
  packages/react-table/src/demos/DashboardHeader.tsx
  packages/react-table/src/demos/Table.md
  packages/react-tokens/package.json
  yarn.lock
Labels: css review, content review
