Repository patternfly/patternfly-react, pull requests merged in 2024-02, with the labels that each got.

#10036 feat(Drawer): consumed Penta updates
  packages/react-core/src/components/Drawer/Drawer.tsx
  packages/react-core/src/components/Drawer/DrawerContent.tsx
  packages/react-core/src/components/Drawer/DrawerHead.tsx
  packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
  packages/react-core/src/components/Drawer/DrawerPanelDescription.tsx
  packages/react-core/src/components/Drawer/DrawerSection.tsx
  packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
  packages/react-core/src/components/Drawer/__tests__/DrawerPanelContent.test.tsx
  packages/react-core/src/components/Drawer/__tests__/DrawerPanelDescription.tsx
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  packages/react-core/src/components/Drawer/__tests__/__snapshots__/DrawerPanelDescription.tsx.snap
  packages/react-core/src/components/Drawer/examples/Drawer.md
  packages/react-core/src/components/Drawer/examples/DrawerBasic.tsx
  packages/react-core/src/components/Drawer/examples/DrawerBasicInline.tsx
  packages/react-core/src/components/Drawer/examples/DrawerBreakpoint.tsx
  packages/react-core/src/components/Drawer/examples/DrawerFocusTrap.tsx
  packages/react-core/src/components/Drawer/examples/DrawerInlinePanelEnd.tsx
  packages/react-core/src/components/Drawer/examples/DrawerInlinePanelStart.tsx
  packages/react-core/src/components/Drawer/examples/DrawerModifiedContentPadding.tsx
  packages/react-core/src/components/Drawer/examples/DrawerModifiedPanelPadding.tsx
  packages/react-core/src/components/Drawer/examples/DrawerPanelBottom.tsx
  packages/react-core/src/components/Drawer/examples/DrawerPanelEnd.tsx
  packages/react-core/src/components/Drawer/examples/DrawerPanelStart.tsx
  packages/react-core/src/components/Drawer/examples/DrawerResizableAtEnd.tsx
  packages/react-core/src/components/Drawer/examples/DrawerResizableAtStart.tsx
  packages/react-core/src/components/Drawer/examples/DrawerResizableOnBottom.tsx
  packages/react-core/src/components/Drawer/examples/DrawerResizableOnInline.tsx
  packages/react-core/src/components/Drawer/examples/DrawerSecondaryBackground.tsx
  packages/react-core/src/components/Drawer/examples/DrawerStackedContentBodyElements.tsx
  packages/react-core/src/components/Drawer/examples/DrawerStatic.tsx
  packages/react-core/src/components/Drawer/index.ts
  packages/react-core/src/components/Wizard/examples/WizardStepDrawerContent.tsx
  packages/react-core/src/demos/examples/Wizard/InModalWithDrawer.tsx
  packages/react-core/src/demos/examples/Wizard/InModalWithDrawerInformationalStep.tsx
  packages/react-core/src/demos/examples/Wizard/InPageWithDrawer.tsx
  packages/react-core/src/demos/examples/Wizard/InPageWithDrawerInformationalStep.tsx
  packages/react-core/src/deprecated/components/Wizard/__tests__/Wizard.test.tsx
  packages/react-core/src/deprecated/components/Wizard/examples/WizardWithDrawer.tsx
  packages/react-integration/cypress/integration/drawer.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
Labels: ux review, css review

#10019 refactor(ToggleGroup)
  packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
  packages/react-core/src/components/ToggleGroup/examples/ToggleGroupDefaultMultiple.tsx
Labels: css approved

#10040 chore(Tile): add spacing between tile examples/demos
  packages/react-core/src/components/Tile/examples/Tile.css
  packages/react-core/src/components/Tile/examples/Tile.md
Labels: css review

#10056 feat(Card): Consume penta tokens
  packages/react-core/src/components/Card/Card.tsx
  packages/react-core/src/components/Card/CardHeader.tsx
  packages/react-core/src/components/Card/CardTitle.tsx
  packages/react-core/src/components/Card/__tests__/Card.test.tsx
  packages/react-core/src/components/Card/__tests__/CardTitle.test.tsx
  packages/react-core/src/components/Card/examples/Card.md
  packages/react-core/src/components/Card/examples/CardClickable.tsx
  packages/react-core/src/components/Card/examples/CardClickableSelectable.tsx
  packages/react-core/src/components/Card/examples/CardDeprecatedSelectable.tsx
  packages/react-core/src/components/Card/examples/CardDeprecatedSelectableA11yHighlight.tsx
  packages/react-core/src/components/Card/examples/CardExpandableWithIcon.tsx
  packages/react-core/src/components/Card/examples/CardSecondary.tsx
  packages/react-core/src/components/Card/examples/CardSelectable.tsx
  packages/react-core/src/components/Card/examples/CardSingleSelectable.tsx
  packages/react-core/src/components/Card/examples/CardWithDividers.tsx
  packages/react-core/src/components/Card/examples/CardWithImageAndActions.tsx
  packages/react-core/src/components/Card/examples/CardWithModifiers.tsx
  packages/react-core/src/demos/examples/Card/CardHorizontalSplit.tsx
  packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
  packages/react-integration/cypress/integration/card.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
Labels: ux review, css review, doc review

#10041 feat(ActionList): consumed Penta updates
  packages/react-core/src/components/ActionList/ActionList.tsx
  packages/react-core/src/components/ActionList/ActionListGroup.tsx
  packages/react-core/src/components/ActionList/ActionListItem.tsx
  packages/react-core/src/components/ActionList/__tests__/ActionListGroup.test.tsx
  packages/react-core/src/components/ActionList/examples/ActionListSingleGroup.tsx
  packages/react-core/src/components/ActionList/examples/ActionListWithCancelButton.tsx
  packages/react-core/src/components/ActionList/examples/ActionListWithIcons.tsx
Labels: ux review, css review

#10081 feat(CodeEditor,Divider): consume penta & update core version
  packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
  packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx
  packages/react-code-editor/src/components/CodeEditor/__test__/CodeEditor.test.tsx
  packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap
  packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditorControl.test.tsx.snap
  packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorCustomControl.tsx
  packages/react-core/package.json
  packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
  packages/react-core/src/components/Divider/examples/Divider.md
  packages/react-core/src/components/Divider/examples/DividerVerticalFlexInsetSmall.tsx
  packages/react-core/src/components/Menu/Menu.tsx
  packages/react-core/src/components/Menu/MenuItem.tsx
  packages/react-core/src/components/Menu/MenuItemAction.tsx
  packages/react-core/src/components/Menu/__tests__/Menu.test.tsx
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/TreeView/TreeViewListItem.tsx
  packages/react-core/src/components/TreeView/__tests__/TreeViewListItem.test.tsx
  packages/react-docs/package.json
  packages/react-icons/package.json
  packages/react-integration/cypress/integration/menu.spec.ts
  packages/react-styles/package.json
  packages/react-tokens/package.json
  yarn.lock
Labels: ux review, css review

#10084 fix(Menu toggle): Passed aria label prop value to typeahead variant
  packages/react-core/src/components/MenuToggle/MenuToggle.tsx
  packages/react-core/src/components/MenuToggle/examples/MenuToggleTypeahead.tsx
  packages/react-core/src/components/Select/examples/SelectMultiTypeahead.tsx
  packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCheckbox.tsx
  packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCreatable.tsx
  packages/react-core/src/components/Select/examples/SelectTypeahead.tsx
  packages/react-core/src/components/Select/examples/SelectTypeaheadCreatable.tsx
Labels: accessibility

#10049 feat(Chip): use Label internally, deprecate Chip
  packages/react-code-editor/src/components/CodeEditor/examples/CodeEditor.md
  packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorShortcutMainHeader.tsx
  packages/react-core/src/components/Chip/Chip.tsx
  packages/react-core/src/components/Chip/ChipGroup.tsx
  packages/react-core/src/components/Label/Label.tsx
  packages/react-core/src/components/Select/examples/SelectMultiTypeahead.tsx
  packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCreatable.tsx
  packages/react-core/src/components/TextInputGroup/examples/TextInputGroupFilters.tsx
  packages/react-core/src/components/Toolbar/ToolbarFilter.tsx
  packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap
  packages/react-core/src/components/index.ts
  packages/react-core/src/demos/examples/TextInputGroup/AttributeValueFiltering.tsx
  packages/react-core/src/demos/examples/TextInputGroup/AutoCompleteSearch.tsx
  packages/react-core/src/deprecated/components/Chip/Chip.tsx
  packages/react-core/src/deprecated/components/Chip/ChipGroup.tsx
  packages/react-core/src/deprecated/components/Chip/__tests__/Chip.test.tsx
  packages/react-core/src/deprecated/components/Chip/__tests__/ChipGroup.test.tsx
  packages/react-core/src/deprecated/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap
  packages/react-core/src/deprecated/components/Chip/__tests__/__snapshots__/ChipGroup.test.tsx.snap
  packages/react-core/src/deprecated/components/Chip/examples/Chip.md
  packages/react-core/src/deprecated/components/Chip/examples/ChipDefault.tsx
  packages/react-core/src/deprecated/components/Chip/examples/ChipGroupInline.tsx
  packages/react-core/src/deprecated/components/Chip/examples/ChipGroupRemovableCategories.tsx
  packages/react-core/src/deprecated/components/Chip/examples/ChipGroupWithCategories.tsx
  packages/react-core/src/deprecated/components/Chip/index.ts
  packages/react-core/src/deprecated/components/Select/Select.tsx
  packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  packages/react-core/src/deprecated/components/Select/examples/Select.md
  packages/react-core/src/deprecated/components/index.ts
  packages/react-integration/cypress/integration/chip.spec.ts
  packages/react-integration/cypress/integration/chipgroup.spec.ts
  packages/react-integration/cypress/integration/chipgroupdefaultisopen.spec.ts
  packages/react-integration/cypress/integration/chipgroupwithcategory.spec.ts
  packages/react-integration/cypress/integration/chipgroupwithoverflowchipeventhandler.spec.ts
  packages/react-integration/cypress/integration/form.spec.ts
  packages/react-integration/cypress/integration/select.spec.ts
  packages/react-integration/cypress/integration/selectfavorites.spec.ts
  packages/react-integration/cypress/integration/toolbar.spec.ts
  packages/react-integration/demo-app-ts/src/components/demos/ChipDemo/ChipDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupWithCategoryDemo.tsx
  packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupWithOverflowChipEventHandler.tsx
Labels: ux review, css review

#9901 feat(DualListSelector next): Add next composable Dual List Selector
  packages/react-core/src/next/components/DualListSelector/DualListSelector.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorContext.ts
  packages/react-core/src/next/components/DualListSelector/DualListSelectorControl.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorControlsWrapper.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorList.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorListItem.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorListWrapper.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorPane.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorTree.tsx
  packages/react-core/src/next/components/DualListSelector/DualListSelectorTreeItem.tsx
  packages/react-core/src/next/components/DualListSelector/__tests__/DualListSelector.test.tsx
  packages/react-core/src/next/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelector.md
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelectorBasic.tsx
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelectorBasicSearch.tsx
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelectorBasicTooltips.tsx
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelectorComplexOptionsActions.tsx
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelectorDragDrop.tsx
  packages/react-core/src/next/components/DualListSelector/examples/DualListSelectorTree.tsx
  packages/react-core/src/next/components/DualListSelector/index.ts
  packages/react-core/src/next/components/DualListSelector/treeUtils.ts
  packages/react-core/src/next/components/index.ts
Labels: css review
